### ISSUE TITLE
Can't enter milestones for feature deprecation

### ISSUE THREAD

**Issue by clelland** [GoogleChrome/chromium-dashboard#1008]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
The "Prepare to Ship" stage for a feature deprecation and removal has a progress checkmark for "Updated target milestone". However, it doesn't seem to be possible to enter that information in that stage, or any of the others.

**To Reproduce**
1. Edit a feature whose type is deprecation/removal (I'm using https://www.chromestatus.com/guide/edit/5740835259809792)
2. See that "Updated target milestone" is not checked
3. Click "start" or "preview" for all stages. Try to find a place to enter the deprecation or removal milestones.

**Expected behavior**
The form for each stage should have edit fields that clearly map to the progress checkmarks for that stage. Specifically, I should be able to enter a milestone for when the feature becomes deprecated, and for the milestone when it will be removed.

**Comment by jpmedley** [comment]
Thank you for opening this. Your timing is interesting because we've been working on fixing this for the lat two days. I'll keep you updated on our progress.

**Comment by jpmedley** [comment]
Here's the tracking bug: #1009

**Comment by jpmedley** [comment]
Marking this as duplicate and closing.

**Comment by clelland** [comment]
Thanks!
