### ISSUE TITLE
Create a subdashboard specifically for deprecated and removed features

### ISSUE THREAD

**Issue by maxh** [GoogleChrome/chromium-dashboard#101]
Goal is to have an easy, focused place for developers to get information about what features are going to be removed from Chrome.

Context: https://groups.google.com/a/chromium.org/d/msg/blink-dev/nNsZDn_utUc/clT3aVUGZaAJ

**Comment by addyosmani** [comment]
Short term, https://www.chromestatus.com/features#deprecated doesn't seem like something bad to link to. A dedicated deprecations feed would be super useful too.

**Comment by jeffposnick** [comment]
The problem with https://www.chromestatus.com/features#deprecated is that it picks up features with `"impl_status_chrome": "Deprecated"` but not `"impl_status_chrome": "Removed"`

A saved search + a new feed that reflected the union of https://www.chromestatus.com/features#removed + https://www.chromestatus.com/features#deprecated would probably be the most useful.

CC: @beaufortfrancois

**Comment by beaufortfrancois** [comment]
For info, https://www.chromestatus.com/features#deprecated|removed works the way you expect it to be.
I've just noticed that the count is wrong though. I will fix it.

**Comment by beaufortfrancois** [comment]
Here's a PR to that fix count number by the way: https://github.com/GoogleChrome/chromium-dashboard/pull/194
cc @ebidel

**Comment by dglazkov** [comment]
would love for this to happen soon. Explicitly surfacing deprecation data FTW :rocket: :100: :trophy: 

@PaulKinlan

**Comment by ebidel** [comment]
@dglazkov @PaulKinlan https://www.chromestatus.com/features#deprecated or https://www.chromestatus.com/features#deprecated|remove seems sufficient to me. Do we need something more?

FWIW, you can deep link into any search in chromestatus :) We foresaw your needs years ago :)

**Comment by PaulKinlan** [comment]
You need a browser to automate the parsing of the data want to read it with
a tool (because of the fragment syntax). There should ideally be a feed or
server side generated content.

**Comment by jeffposnick** [comment]
Since there seems to be demand for an RSS feed (to supplement the https://www.chromestatus.com/features#deprecated|remove UI), https://github.com/GoogleChrome/chromium-dashboard/pull/198 is one approach that might work.

**Comment by jeffposnick** [comment]
https://www.chromestatus.com/features.xml?status=Deprecated,Removed now works. It'll return an RSS feed of features that were marked as either deprecated or removed.
