### ISSUE TITLE
LGTMs field doesn't validate multiple email addresses

### ISSUE THREAD

**Issue by clelland** [GoogleChrome/chromium-dashboard#1010]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
The "Intent to Ship LGTMs" field requests a comma-separated list of email addresses, but flags the field with a message when multiple addresses are used.

**To Reproduce**
1. Go to "Prepare to ship" stage on a feature
2. Enter a comma-separated list of email addresses, as requested, in the "Intent to Ship LGTMs" field.
3. Submit the changes and go back to the edit screen.
4. See the error message: "Enter a valid email address." on that field

<img width="711" alt="Screen Shot 2020-09-11 at 11 53 52 AM" src="https://user-images.githubusercontent.com/45853/92947175-a3f60c80-f425-11ea-8316-41bb5fa9ba8e.png">

**Expected behavior**
The field should be seen as valid.

**Comment by jpmedley** [comment]
This was fixed, but I can't find the PR.
