### ISSUE TITLE
Percentage values order is not changed on the page "usage > all features > stack rank" when clicking on "Percentage" column title

### ISSUE THREAD

**Issue by d-01** [GoogleChrome/chromium-dashboard#1013]
**Describe the bug**
The percentage values order is not changed on the page *usage > all features > stack rank* (<https://www.chromestatus.com/metrics/feature/popularity>) when clicking on the *Percentage* column title.

**To Reproduce**
1. Go to <https://www.chromestatus.com/metrics/feature/popularity>
   1. Notice the default sort order is "by *Percentage* descending".
2. Click on the *Percentage* column title.
   1. Notice the sort order has changed from descending to ascending.
   1. Feature names order has changed properly.
   1. Bars order has changed properly.
   1. Percentage values order remains unchanged, thus not in sync with feature names.
3. Screenshots.

   Descending sort order (default) by *Percentage*:

   ![1_desc_order_](https://user-images.githubusercontent.com/45796739/93007510-4f13dc80-f572-11ea-9261-88098567fd26.png)

   Ascending order by *Percentage*:

   ![2_asc_order_](https://user-images.githubusercontent.com/45796739/93007554-ab76fc00-f572-11ea-8191-f4119681bce3.png)

**Expected behavior**
When clicking on the *Percentage* column title, the percentage values order should get changed accordingly.

**Additional context**
This behavior reproduced with:
1. Firefox 80.0 (64-bit), Windows 7 x64
2. Chromium 72.0.3626.121 (32-bit), Windows 7 x64

**Comment by CrypticWizard** [comment]
@jrobbins This issue seems resolved now.

**Comment by d-01** [comment]
The issue resolved. Confirmed just now in:
- [x] Firefox 88.0
- [x] Chromium 84.0.4147.135
