### ISSUE TITLE
Metrics data is stale

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1015]
**Describe the bug**
The feeds that populate the metrics charts are missing some days of data, or not updating at all on recent days.
For example, this feed
https://chromestatus.com/data/timeline/featurepopularity?bucket_id=3137
Has scattered data up to Sept 5, and then nothing from the 6th to the 14th.

Logs show that the cron job was running out of RAM.  But, even on a successful run, this particular data feed still has no recent data points.

**Comment by mikewest** [comment]
It looks like this is still dead. Any updates? cc @jpchase

**Comment by mikewest** [comment]
Good news: some of the data updated on the 19th!

Bad news: it was mostly zero'd out.

**Comment by mikewest** [comment]
Perhaps things were propagating when I looked this morning? https://chromestatus.com/data/timeline/featurepopularity?bucket_id=3137 seems to have data!

**Comment by mikewest** [comment]
Seems to have flakily succeeded on the 19th. No updates since.

**Comment by justinfagnani** [comment]
I noticed this too. The data for is bucket 1689very sparsely filled out for September: https://chromestatus.com/data/timeline/featurepopularity?bucket_id=1689

There are missing days for other recent months too, but September is particularly bad.

**Comment by jrobbins** [comment]
This code was reworked in 9cbc5345de68f825b82f653daf73ab42441eb8b9 and some subsequent changes.
The metrics pages seem much more reliable since mid-Dec 2020.
