### ISSUE TITLE
measurement field

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1017]
**Describe the solution you'd like**
Chris Harrelson added a "Measurement" section to the old doc template for intent emails.
We should support that in the chromestatus tool by adding a string field for measurement strategy to the Feature objects.
And, add it to the intent email template so that it shows up there.

**Additional context**
https://docs.google.com/document/d/1vlTlsQKThwaX0-lj_iZbVTzyqY7LioqERU8DK3u3XjI/edit?ts=5f5bcaf7

**Comment by jrobbins** [comment]
@cwilso Do you think that a "measurement" field is a good idea, and if so, how should it fit into the launch process?  Specifically, which stage should prompt for it, and what guidance should the help text offer?

**Comment by cwilso** [comment]
Yes, good idea.  Should show up during "Evaluate Readiness for Shipping", text field with instructions: "It's important to measure the adoption and success of web-exposed features. Note here what measurements you have added to track the success of this feature, such as UseCounters."

**Comment by mrego** [comment]
As an idea maybe we could also add an optional field that could link to the UseCounter if it exists. So when someone browse the feature in chromestatus they get a link to the UseCounter directly.

**Comment by cwilso** [comment]
How often is this something OTHER than a usecounter?  Maybe we should say ""It's important to measure the adoption and success of web-exposed features. Note here what measurements you have added to track the success of this feature, such as a link to the UseCounter(s) you have set up."

**Comment by chrishtr** [comment]
new text sounds fine to me.

Some features (JS ones in particular) don't use the UseCounter machinery and may have an alternative. Same for networking features I would imagine.

**Comment by jrobbins** [comment]
LaForge raise the question as to whether this needs to be a field in ChromeStatus or if it could be a section of the design doc.  What's the pragmatic difference between this field and other details that are OK as design doc sections?

**Comment by jrobbins** [comment]
Ping.  Before I implement this, can we state a reason why having this text in a chromestatus field would be better than having it in the templates that developers use for design docs?

I see that there is already a section named "Metrics" in  go/chrome-design-doc-template.  It doesn't ask for UseCounters, but maybe it should.

**Comment by mrego** [comment]
Honestly I don't know which are those templates for design docs (e.g. they're not linked from https://www.chromium.org/blink/launching-features), and I've seen very different formats on design docs; even sometimes design docs are skipped for some features.

In any case just sharing my opinion, I think it has a value to be able to go directly to the use counter of a feature from the chromestatus entry, it'd be very easy and straight forward to check adoption or a given feature after a few releases and things like that.

**Comment by jrobbins** [comment]
This was added and it is live now.

**Comment by mrego** [comment]
I cannot find this filed in chromestatus yet, could you point it to me where is this in the UI?

For example, if I go to https://www.chromestatus.com/guide/stage/5738050678161408/5 I don't see it (this is in stage *Prepare to ship*).

Thanks.

**Comment by mrego** [comment]
I found this now, it's in the *Prepare to ship* stage but only for features marked as *New feature incubation*.  

I think we want to have this in the other cases too.
At least it's clear we want it in *Existing feature implementation* (if there's a standard property that we want to implement, we want to be sure we're measuring this).
For "Web developer facing change to existing code" we might want this too, I guess it depends on the case.
And for "Feature deprecation" we should have a counter somewhere, so linking to it sounds like a good idea too, or explaining why we don't have it.

WDYT about adding this field in all the feature types?

Apart from that I see this field is not included in the generated intent-to-ship mail, while it's in the *deprecated* template: https://docs.google.com/document/d/1vlTlsQKThwaX0-lj_iZbVTzyqY7LioqERU8DK3u3XjI/edit#bookmark=id.w8j30a6lypz0
Shouldn't we add it there too?
