### ISSUE TITLE
"Issues addessed" mispelling

### ISSUE THREAD

**Issue by domenic** [GoogleChrome/chromium-dashboard#1029]
**Describe the bug**

In generated intent emails, the "TAG review status" is generated as "Issues addessed", instead of "Issues addressed" with an "r".

**To Reproduce**
1. Go to https://chromestatus.com/admin/features/launch/5683766104162304/3?intent
2. See the misspelling

**Expected behavior**
Correct spelling

**Comment by jrobbins** [comment]
Fixed.
