### ISSUE TITLE
Newlines are not preserved in the generated intent emails "Interoperability and Compatibility" section

### ISSUE THREAD

**Issue by domenic** [GoogleChrome/chromium-dashboard#1030]
**Describe the bug**
Generated intent emails collapse newlines in the "Interoperability and Compatibility Risks:" field into spaces.

**To Reproduce**
1. Go to https://chromestatus.com/guide/editall/5683766104162304. Notice how the "Interoperability and Compatibility Risks:" section contains several paragraphs, separated by newlines.

2. Go to https://chromestatus.com/admin/features/launch/5683766104162304/3?intent. Notice how the generated section for "Interoperability and Compatibility" removes all the newlines.

**Expected behavior**
Newlines should be preserved. Interop and compat risks are complicated and explaining them often requires several paragraphs.

**Comment by jpmedley** [comment]
@jrobbins This happens in the summary field too. Eric did this intentionally. I don't know why. We should consider removing this from all text fields.

**Comment by jrobbins** [comment]
This was deployed,
