### ISSUE TITLE
Consider Leading default page with something other than "No active development"

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#1035]
**Is your feature request related to a problem? Please describe.**
Currently, the default view for Chrome Status opens with "No active development", as shown below. The reason this is at the top is lost in the mists of time. The moment has arrive to discuss what we want viewers to see when they arrive at the site.

![image](https://user-images.githubusercontent.com/8204171/94040153-72facd80-fd7d-11ea-8328-8ca5ff686c6a.png)

**Describe the solution you'd like**
I would personally put "In development" at the top. That's just a personal preference. I'll accept the group consensus.

**Comment by jrobbins** [comment]
Anthony also asked about this.

I am thinking of moving "No active development" to be after the numeric milestones, just before "No longer pursuing".  I'll leave the other implantation statuses in the order that they have now, so Proposed features would be at the top of the page.

This has the side effect that newly created features will appear near the bottom of the list until someone edits them to set their implementation status.  Being at the bottom of the list puts them out of sight, so a user who created a feature might think that their form submission did not work.  That only affects users who create features, and it's probably a good idea for them to set the implementation status, but we need be sure that we encourage that in a clear way.

**Comment by shivamag00** [comment]
@jpmedley @jrobbins, this issue seems to be solved. Please close this issue if it is so.
