### ISSUE TITLE
Clarify signals in intent-to-ship

### ISSUE THREAD

**Issue by chrishtr** [GoogleChrome/chromium-dashboard#1051]
I think the intent-to-ship form does not currently link to [this document](https://docs.google.com/document/d/1xkHRXnFS8GDqZi7E0SSbR3a7CZsGScdxPUWBsNgo-oo/edit) when specifying how to collect signals from Gecko and WebKit. That should be added.

Bonus points for adding some javascript that warns the developer if their signals don't look like a link to mozilla standards positions or webkit-dev?

**Comment by mrego** [comment]
Also Edge shouldn't be on the form anymore, and I guess neither on the summary view of a chromestatus entry.

**Comment by mrego** [comment]
The form doesn't link to https://bit.ly/blink-signals, also the list of options differs from the one on the document. Edge is still present and the possible signals are different.

**Comment by tomayac** [comment]
…And we also agreed on formalizing developer signals at [goo.gle/developer-signals](http://goo.gle/developer-signals). When you add the [bit.ly/blink-signals](https://bit.ly/blink-signals), please also add the developer signals. Thank you!

**Comment by cwilso** [comment]
To be clear:

1. Web developer signals should be required
2. the Safari/Mozilla fields should point to  https://bit.ly/blink-signals for guidance
3. the web developer signals should point to goo.gle/developer-signals

**Comment by chrishtr** [comment]
Those 3 items LGTM!

**Comment by tomayac** [comment]
> 3. the web developer signals should point to goo.gle/developer-signals

We can make it `https://goo.gle/developer-signals` (not `http:`) to save everyone a roundtrip.
