### ISSUE TITLE
Some Chrome reports and chromium source code contain links to "/features/:id" which does not work

### ISSUE THREAD

**Issue by xPaw** [GoogleChrome/chromium-dashboard#1055]
Using reporting api, I get reports like this:
```
{
  "anticipatedRemoval": 1559620800000,
  "id": "CustomCursorIntersectsViewport",
  "message": "Custom cursors with size greater than 32x32 DIP intersecting native UI is deprecated and will be removed in M75, around June 2019. See https://www.chromestatus.com/features/5825971391299584 for more details."
}
```

The `/features/` url does not load, as it needs to be `/feature/`, I am unsure if this is a mistake in Chrome's code or chromestatus.com changed and does not support that route anymore.

There's plenty of references to it in Chromium source code as well: https://source.chromium.org/search?q=chromestatus.com%2Ffeatures%2F&ss=chromium&start=1

**Comment by jpmedley** [comment]
Thank you for submitting this issue.

This is a known issue. It's a byproduct of a change to make the features/ page load faster. We have it on our list to fix, but have not gotten to it yet.

**Comment by jrobbins** [comment]
This change went live yesterday.
For example, the URL in the original problem report now brings up a feature detail page
https://www.chromestatus.com/features/5825971391299584
