### ISSUE TITLE
Existing /features/:id URLs don't work

### ISSUE THREAD

**Issue by foolip** [GoogleChrome/chromium-dashboard#1066]
**Describe the bug**
https://www.chromestatus.com/features/5699616519487488 doesn't show the "CSSKeyframesRule.insertRule() (removed)" entry but rather a list of all entries

**To Reproduce**
1. Browse blink-dev from 2015: https://groups.google.com/a/chromium.org/g/blink-dev/c/wW7w8Hro78s/m/JDULF2oM9iIJ
2. Click the https://www.chromestatus.com/features/5699616519487488 link
3. Wait for ChromeStatus to load. It will be a list of all features:

![image](https://user-images.githubusercontent.com/498917/95954934-5ee64100-0dfc-11eb-94e9-6d102478d65a.png)

**Expected behavior**
I'm not sure what originally happened, but am quite sure the link worked. https://www.chromestatus.com/feature/5699616519487488 still works, and is the single feature. Perhaps we should redirect /features/:id to /feature/:id?

**Comment by jrobbins** [comment]
Going forward, we should use the feature detail page for these links.  I'll make sure that that is the case.

For existing links in the mailing list archive, I think the problem might be that we only display a limited number of features and this feature is not one of the ones displayed.  I like the idea of a redirect.  We could even add some JS code that uses an API to check that such a feature exists before doing the redirect.

**Comment by jpmedley** [comment]
@foolip,

Thank you for bringing this up. This is a known issue and a duplicate #1055. I hope you'll forgive that we need to close your version of the ticket.

Joe
