### ISSUE TITLE
Convert from using app identity library to env. vars

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1073]

**Comment by vishwjeet-singh** [comment]
hi @jrobbins, I would like to work on this issue can you please explain how to start on this issue.

**Comment by MissMwendwa** [comment]
hi @jrobbins, in this particular problem, is there a bug or it is being developed from scratch?

**Comment by MissMwendwa** [comment]
Though in my line of thought, I am thinking that this can be implemented using javascript.

**Comment by MissMwendwa** [comment]
can this be done using the python programming language?

**Comment by shivamag00** [comment]
@jrobbins Please close this issue also as it is solved by CL #1207 (Merged)
