### ISSUE TITLE
Convert from using urlfetch to native python library

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1074]

**Comment by piyushjasaiwal** [comment]
i would like to contribute to this

**Comment by Naman-12911** [comment]
I want solve this issue please assign me

**Comment by shivamag00** [comment]
@jrobbins I have raised the PR - #1205 which should fix this issue. As I understand, solving issue was important so that the repository could be migrated to Python 3 from Python 2
