### ISSUE TITLE
Setting "Will this feature be supported on all six Blink platforms" for intent prototype

### ISSUE THREAD

**Issue by wanderview** [GoogleChrome/chromium-dashboard#1081]
Hello, I recently created a new chromestatus entry:

https://www.chromestatus.com/feature/5731920199548928

When generating the intent to prototype the email seemed to always include "no" for "Will this feature be supported on all six Blink platforms?"

I couldn't figure out how to get chromestatus to understand that I plan to ship this on all platforms.  For now I just changed the email I actually sent.

**Comment by jrobbins** [comment]
Sorry if that is unclear.   The checkbox for that is in the form for the Dev Trails stage:
https://www.chromestatus.com/guide/stage/5731920199548928/2

I realize that your feature is still on the "Start prototyping" stage.  So, naturally you have not filled that out yet.  In fact, that field should not appear in the I2P email.  I'll change that.
