### ISSUE TITLE
Broken link to "interoperability risk

### ISSUE THREAD

**Issue by jyasskin** [GoogleChrome/chromium-dashboard#1082]
https://chromestatus.com/guide/stage/5710618575241216/2 has a "Describe the degree of interoperability risk." link that goes to https://sites.google.com/a/chromium.org/dev/blink?pli=1#TOC-Policy-for-shipping-and-removing-web-platform-API-features, which has been refactored away.

The right new target *might* be https://www.chromium.org/blink/guidelines/web-platform-changes-guidelines#TOC-Finding-balance, but I'm not confident of that.

**Comment by jyasskin** [comment]
To be clear, this is about the interface of that page (and probably other pages with similar links into chromium.org), and not the content of that particular feature.

**Comment by jstenback** [comment]
https://docs.google.com/document/d/1LdqUfUILyzM5WEcOgeAWGupQILKrZHidEXrUxevyi_Y/edit might be the best thing to link at here, with a change to the exact text as well. @cwilso do you agree, or is there a better thing we can link to in the new process docs?

**Comment by jrobbins** [comment]
Hmm, that doc is titled "Deprecation Guidelines".  But, interoperability risk applies to both deprecation and new features (the more common case).

There is already a second link in that help text that points to "Blink principles of web compatibility"
https://docs.google.com/document/d/1RC-pBBvsazYfCNNUSkPqAVpSpNJ96U8trhNkfV0v9fk/edit#heading=h.83o2xr8ayal6
That second doc looks pretty comprehensive to me.

What it we just removed the first link and point users to only "Blink principles of web compatibility"?

Could the content of the "Deprecation Guidelines" doc be merged into "Blink principles of web compatibility"?  Having two docs allows them to disagree with each other, or for a developer to read only one and mistakenly think that they have the complete picture.

**Comment by jrobbins** [comment]
Oh, actually, the first link has a section "Launching and Removing Features" that lists three other docs and a video.  

Maybe the first link should be kept and adjusted to a new anchor
https://sites.google.com/a/chromium.org/dev/blink#TOC-Launching-and-Removing-Features
