### ISSUE TITLE
Typo in "Launch bug URL" field description

### ISSUE THREAD

**Issue by clelland** [GoogleChrome/chromium-dashboard#1107]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
There is a typo in the "Launch bug URL" field description. "aprpovals" should be "approvals".

**To Reproduce**
1. Edit a feature
2. Click on the "Edit" link in the box at the top of the page with the 
3. Scroll down to the bottom of the form
4. See error:

<img width="653" alt="Screen Shot 2020-12-08 at 3 22 20 PM" src="https://user-images.githubusercontent.com/45853/101537585-bd95ea00-3969-11eb-8228-9b8d7d961dbd.png">

**Comment by jpmedley** [comment]
I don't have a deployment ETA, but I believe we update regularly. I'm closing the issue.
