### ISSUE TITLE
No "Add new feature" button

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/chromium-dashboard#1112]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
[Launching Features](https://www.chromium.org/blink/launching-features)  includes this language

> The Chromium process to launch a new feature
> Step 0: Create a ChromeStatus entry, and choose your feature type.
> For all types of features, the first step is to create a ChromeStatus entry.  Go to https://www.chromestatus.com/features, ensure you are logged in (see the bottom line on the screen), and click “Add new feature”.  Follow the directions to name your feature and give a short summary, and select the appropriate feature type.

**To Reproduce**
1. There is no "Add new feature button"

**Expected behavior**
1. A conspicuous "Add new feature" button on the site

**Additional context**
https://bugs.chromium.org/p/chromium/issues/detail?id=1143761#c7

**Comment by shivamag00** [comment]
@guest271314, You need to have access to create a feature. The [Launching Features](https://www.chromium.org/blink/launching-features) page has been updated with this info and says:-

> If you do no have access to create a new feature, please send an email to webstatus-request@google.com to request access. Follow the directions to name your feature and give a short summary, and select the appropriate feature type.

**Comment by shivamag00** [comment]
@guest271314 @jrobbins, I hope this issue can be closed now
