### ISSUE TITLE
Edge views not included in intent emails

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1114]
**Describe the bug**
The intent email templates include FF and safari views, but leave out the views for Edge.

**Expected behavior**
When we have data for a UA signal, we should display it.

**Additional context**
Edge signals was removed in
https://github.com/GoogleChrome/chromium-dashboard/commit/6af1b1366623a28bd65e9a9863a9824f7b9b82c2#diff-ec8cd8ecec9f640e8a0209f66301563e8a00d7941ddfe23d364fa858257b2b6e
based on following https://bit.ly/blink-signals very literally, but I think that it makes sense to include Edge signals if there is a value for them.

**Comment by mrego** [comment]
I believe the idea was not to have Edge signals in the form directly, that would mean they could only be present in old features; for the new ones they won't have Edge signals, and then they won't appear on the intent mails (see #1051).

**Comment by jrobbins** [comment]
This change was reverted.
