### ISSUE TITLE
Can not edit some specific existing entry in the renewed edit page

### ISSUE THREAD

**Issue by toyoshim** [GoogleChrome/chromium-dashboard#1118]
https://www.chromestatus.com/feature/6247959677108224

When I try updating this entry by clicking the edit icon, the server returns 500.

**Comment by toyoshim** [comment]
@jrobbins can you take a look?
it seems you are actively working on the dashboard as long as I can see in the commit log.

**Comment by jrobbins** [comment]
The problem was smart quotes that cannot be converted to ASCII.  I worked around it by changing them to plain single quotes.  The edit page should load now.

This is a defect in the way that the app handles unicode content.  I will look into the location of the defect and try to fix it.

**Comment by toyoshim** [comment]
Thanks for a quick treatment, now it works to me too!
