### ISSUE TITLE
HTTP/2 connection coalescing for two domains with completely different resolved IP addresses

### ISSUE THREAD

**Issue by tmpdat** [GoogleChrome/chromium-dashboard#1123]
**Describe the bug**
During my HTTP/2 server monitoring, sometimes, I realized that  Chrome/86-87 is requesting a.example.com but using the HTTP/2 connection of the b.example.com, even though these two domains are completely different from the ip address. Therefore, the status code 404 is responded for the request with the wrong address.

**To Reproduce**
a.example.com     1xx.2.3.4
a.example.com     1xx.2.3.5

b.example.com     4x.5.6.7
b.example.com     4x.5.6.8

**Expected behavior**
Only reuse the HTTP/2 connection when two domains have the same ip address.

**Additional context**
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Location request: US

**Comment by jpmedley** [comment]
@tmpdat, sorry for the late response. We've all been on vacation around here. 

We appreciate you letting us know. Unfortunately, this list is for issues with [chromestatus.com](https://www.chromestatus.com/), not with Chrome. Can you please open this on http://crbug.com/

Thank you.
