### ISSUE TITLE
KR: API owner review happens primarily through ChromeStatus (including on-thread email notifications)

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/chromium-dashboard#1130]

**Comment by carolrivero** [comment]
1. Confirm with API owners (through a survey) that the new functionality meets their needs 
2. Address any blocking issues that prevent API owners from phasing out their spreadsheet (issues will be captured as dependencies for this epic)
3. Observe intent email  threads on blink-dev are being resolved through the tool

**Comment by jrobbins** [comment]
This has been happening for the past 2 years.
