### ISSUE TITLE
Create a PRD for implementation for API owners workflow

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/chromium-dashboard#1139]

**Comment by jrobbins** [comment]
Doc: https://docs.google.com/document/d/1SnwZZiWm9cmgnaaSL_8yusG2JMdYUpN5MP3Wtd-znL0/edit#heading=h.e320gm2emnd3

**Comment by jrobbins** [comment]
This doc is done, but I think that I need to revise the UI to avoid repeated navigation in and out of the feature editing page.
