### ISSUE TITLE
Edit feature complains about multiple contact emails

### ISSUE THREAD

**Issue by mkruisselbrink** [GoogleChrome/chromium-dashboard#1148]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
On a feature with more than one (comma separated) contact email, the edit form gives a "Enter a valid email address." error.

**To Reproduce**
1. Go to https://www.chromestatus.com/guide/edit/6013006146174976
2. Click on 'Edit' to edit the feature details
3. Scroll down to Contact emails.
4. See that there is a "Enter a valid email address." error.

**Expected behavior**
The field contains a comma separated list of full email addresses as it is supposed to, so there shouldn't an error displayed.

**Comment by jrobbins** [comment]
I think we need to extend the django email form field class to get it to do the right thing here.

Later versions of Django might handle multiple-emails better.  We'll find out at the time that we are able to upgrade to a newer django, but for now we are stuck on a version that supports Py2.

**Comment by MayankVir** [comment]
Hi @jrobbins I tried to reproduce the bug bit it says Error 403, Access Forbidden. Below is the attached screenshot. Please let me know how to approach it in any other way. This is my first issue in open source community.

![image](https://user-images.githubusercontent.com/41983025/111127826-40969400-859a-11eb-97c3-7416cbc91c61.png)

**Comment by MayankVir** [comment]
I think we can use the Django's Multi Email field form to manage list of emails on one form. Below is the documentation of the library. If sounds good, then I want to work on this issue

https://pypi.org/project/django-multi-email-field/

**Comment by khubaibalam2000** [comment]
Hi @jrobbins, I wanted to reproduce the bug, but it is showing me an error.
![1](https://user-images.githubusercontent.com/74249716/112519378-22137280-8dbc-11eb-989c-16432b60956c.PNG)

**Comment by hemcharan22** [comment]
hai @jrobbins , I looked at the website it asked me to sign in with one of my google account 
![image](https://user-images.githubusercontent.com/77770865/112777220-493d9e80-905f-11eb-8a6f-a4531a84a18e.png)
i proceded to sign in with one of my accounts then its says you dont have permission to enter this site
 
![image](https://user-images.githubusercontent.com/77770865/112777321-8d30a380-905f-11eb-8231-064e39e2eb25.png)

**Comment by shivamag00** [comment]
@jrobbins, I have submitted a CL #1248 which should close this issue.

**Comment by shivamag00** [comment]
@MayankVir @hemcharan22 @khubaibalam2000, you need to host the repo on local machine and use local database to reproduce the error.
