### ISSUE TITLE
"about" link links to very outdated doc

### ISSUE THREAD

**Issue by mkruisselbrink** [GoogleChrome/chromium-dashboard#1152]
**Describe the bug**
The "about" link at the bottom of chromestatus.com seems to link to a very outdated FAQ, that describes some version of chromestatus.com that was based on a spreadsheet. We should probably get rid of the about link or at least link to something that describes the current state?

**To Reproduce**
1. Go to 'https://www.chromestatus.com/'
2. Scroll all the way to the bottom
3. Click on 'About'
4. End up on https://docs.google.com/document/d/1jrSlM4Yhae7XCJ8BuasWx71CvDEMMbSKbXwx7hoh1Co/edit?pli=1

**Expected behavior**
Something describing the current chromestatus.com, rather than what it was 7 years ago.

**Comment by jrobbins** [comment]
I'm thinking that I should redo this as a link to a markdown file on GitHub.  That will make it easy to edit and keep it with the source code so that it is less likely to get so far out-of-date.

**Comment by scheib** [comment]
The old 'about' document is no longer even functioning:

![image](https://user-images.githubusercontent.com/386971/116454502-e897b200-a814-11eb-8c4e-b139ddf42b52.png)

**Comment by jrobbins** [comment]
We'll remove the link for now.  We can always add it back if there is a reason.
