### ISSUE TITLE
Replace or Remove References to WebFundamentals

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#1153]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
The [hack_wf_components.py](https://github.com/GoogleChrome/chromium-dashboard/blob/main/hack_wf_components.py) ffile contains hundreds or references to the GitHub repo for [WebFundamentals](https://developers.google.com/web/). Chrome management has ordered DevRel to shut down WebFundamentals by the end of the year since its replacements are now live. This will break all the links in that file.

**Expected behavior**
These links need to be replaced, or alternatively evaluate whether they're still needed and possibly remove them.

**Comment by MayankVir** [comment]
Hey @jpmedley Can I work on this issue if it is still open ?

**Comment by jpmedley** [comment]
We haven't made any progress and would appreciate the help. Thanks.

**Comment by jpmedley** [comment]
I can't find any occurrences in the repo. Closing.
