### ISSUE TITLE
"additional fields by process phase" widget is not keyboard-accessible

### ISSUE THREAD

**Issue by sersorrel** [GoogleChrome/chromium-dashboard#1155]
**Describe the bug**
The "additional fields by process phase" widget:

![image](https://user-images.githubusercontent.com/9433472/106319724-c8824200-6269-11eb-846e-457fae53d559.png)

is not keyboard-accessible.

**To Reproduce**
1. Go to e.g. https://www.chromestatus.com/feature/6730096436051968#
2. Scroll to the bottom of the page
3. Try to expand "additional fields by process phase" with the keyboard

**Expected behavior**
As a minimum, the clickable element [should have](https://web.dev/focusable-controls/) a `tabindex=0`. It should also have [the correct ARIA roles](https://web.dev/custom-control-roles/).

Ideally, a custom element wouldn't be used at all – `<details>` seems like it would do the job just fine.

**Comment by codeit13** [comment]
I would like to work on this issue.
I will make the element appear in the correct tab structure and set the correct ARIA labels as well in order to make it accessible from keyboard keys like "Enter/Space".
@sersorrel @jrobbins  Can you please assign this issue to me?

**Comment by shivamag00** [comment]
@sersorrel @jrobbins, I have submitted the CL #1244 for solving this bug. As suggested by @sersorrel, custom element was not required to make the widget keyboard accessible. Adding a button element did the job.
