### ISSUE TITLE
Edit page for deprecating a feature has "Link to existing feature" checkbox but no way to make the link.

### ISSUE THREAD

**Issue by jyasskin** [GoogleChrome/chromium-dashboard#1156]
When editing a Deprecate-and-Remove feature, for example https://chromestatus.com/guide/edit/5717324021628928, there's a checkbox for "Link to existing feature":

!["Link to existing feature" checkbox](https://user-images.githubusercontent.com/83420/106937541-bcb3d700-66d2-11eb-8ae3-e6fa2c47b86f.png)

However, when you click "Update", which goes to https://chromestatus.com/guide/stage/5717324021628928/7 in this case, there's no "existing feature" field.

**Comment by jpmedley** [comment]
@jyasskin ,

Thank you for the nudge. This is one of several pieces of additional functionality we have yet to address. This duplicates #1045, which covers the issue more broadly.
