### ISSUE TITLE
Draft emails don't include relevant timelines

### ISSUE THREAD

**Issue by mrego** [GoogleChrome/chromium-dashboard#1162]
For example the following feature has *OT desktop/android start/end* fields set:
https://chromestatus.com/guide/stage/5280634094223360/3

But that info doesn't show up in the draft mail:
https://chromestatus.com/admin/features/launch/5280634094223360/3?intent

The timeline should be included in the intent to experiment template.

**Comment by jpmedley** [comment]
@jrobbins On Friday, we discussed reworking how stages with relevant Chrome versions are handled in various stages of Web Status. It seems logical that intent emails should match. I've revised the title of @mrego's bug to reflect that.

**Comment by chrishtr** [comment]
Also, the "any risks when the experiment finishes" part is missing.

**Comment by mikewest** [comment]
It would be ideal if this could be addressed. It's causing additional round-trips in practically all the OT intent threads that could be easily avoided.

cc @cwilso @jstenback

**Comment by jstenback** [comment]
Thanks for raising the awareness of this one, Mike. @jrobbins, is this something you or others can get to quickly?

**Comment by jrobbins** [comment]
I'll work on it today.

**Comment by jpmedley** [comment]
This appears to be fixed.
