### ISSUE TITLE
Security and User Friendliness of Chrome OS, Chromium OS, etc

### ISSUE THREAD

**Issue by demansanaallan** [GoogleChrome/chromium-dashboard#1178]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**

**To Reproduce**
4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behavior**

**Additional context**

**Comment by demansanaallan** [comment]
How secure really is Chromium OS and the rest...It was said that Chromium OS and it's successful child (Google Chrome OS) benefitted from the inherent Security plus it's own engineered security (boxes [chromebook and the like]) of the rest of the browsers and tools that connect to the WWW?

I tried Wind00wz and i can dissapointlly say, no that one is purely property and security blah blah that eats up it's own future in the business industry...

**Comment by jstenback** [comment]
It's not entirely clear what issue you're talking about here, but it doesn't sound like this is not about something being broken in chromestatus.com. Unfortunately this issue tracker is for the https://chromestatus.com website, not Chrome the browser or Chrome OS. Please file issues with Chrome itself at https://crbug.com/new

**Comment by demansanaallan** [comment]
I don't know if I'm just imagining things, but crashes and frequent and weird behavior of Chromebook (either configured as purely Chrome browser and Chrome OS alone--Chrome Dev Developer Acct-or Chrome Enterprise-Chrome OS and Corel Apollo--Chromium OS and/or Linux with Chrome Beta Browser blue logo or the red and orange one)...Alll are behaving erratically and configuring a satisfactory environement for a mixed virtual and on-premise computing seems far fetched and too complicated...
