### ISSUE TITLE
Going "back" from Edit blanks out the left-hand nav

### ISSUE THREAD

**Issue by sethladd** [GoogleChrome/chromium-dashboard#120]
ChromeOS, Version 36.0.1941.2 dev

Go to chromestatus.com
Redirects to http://www.chromestatus.com/features

I see:

![screenshot 2014-04-25 at 1 57 09 pm](https://cloud.githubusercontent.com/assets/5479/2805635/2dc9caca-ccbc-11e3-8e54-8886388cc9e7.png)

Then click "edit" for picture element. See this:

![screenshot 2014-04-25 at 1 57 38 pm](https://cloud.githubusercontent.com/assets/5479/2805642/43872ea2-ccbc-11e3-96ed-a2f865ab55a6.png)

Then click back. I see this:

![screenshot 2014-04-25 at 1 58 02 pm](https://cloud.githubusercontent.com/assets/5479/2805646/5029af54-ccbc-11e3-8364-7e71f83d584e.png)

Notice the left-hand nav is empty.

**Comment by RByers** [comment]
Can't reproduce this, assuming it's been fixed.  @sethladd please re-open if you can.
