### ISSUE TITLE
Use Google Sign-In for authentication

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1201]
**Describe the solution you'd like**
Rather than continue to use the GAE 'users' library that is only available for python2, we need to use some form of oauth for python3.   Google Sign-In seems like a good choice that is available for both.
https://developers.google.com/identity/sign-in/web

**Additional context**
We have a bunch of handlers that use web 1.0 style web forms and we have a multi-page app that loads complete HTML pages when the user navigates.  While that may change in the long term, for the short term we need some way to know the user who is making a request for an HTML page.  

The Google Sign-In library gives an id_token that can be used with XHR requests, but it does not set a cookie, so we would not get anything on page navigation.   To generate personalized (or even permission-checked) pages, we would need a cookie set.  Flask has cookie-based sessions, so maybe we could store the id_token there after it was provided in an XHR request.

As a prerequisite to switching to Google Sign-In, we need to do all permission checking in python code rather than the "login: required" or "login: admin" lines in app.yaml.  Those lines are not available for py3, but even in py2 they will fail to work if we do not use GAE 'users' library cookie-based sessions.

**Comment by MayankVir** [comment]
Can I start working on this issue? @jrobbins

**Comment by Naman-12911** [comment]
Hello sir I want to fix this issue please assign me.

**Comment by jrobbins** [comment]
@Naman-12911 and @MayankVir, I don't want to assign the issue to either of you just yet.
You are welcome to start experimenting on how Google Sign-In could be used and send some PRs to show your initial progress.

I feel that I need to do the "As a prerequisite to switching ..." part myself.  I will start working on that today and I hope to have it committed in a few days.

Also, if you have any comments or questions about what I suggested about the id_token and cookie, you can post them here.

**Comment by Naman-12911** [comment]
Ohk @jrobbins I will start working on today

**Comment by MayankVir** [comment]
Okay sure, Thanks

**Comment by shivamag00** [comment]
UPDATE: @jrobbins has implemented 'As a prerequisite to switching...' part in #1238

**Comment by shivamag00** [comment]
@jrobbins May you please explain how flask is being used with django ?

**Comment by shivamag00** [comment]
@jrobbins, I have raised CL #1275 containing my initial progress. I hope my approach is correct.
