### ISSUE TITLE
ebidel/lighthouse-ci does not exist

### ISSUE THREAD

**Issue by aavishkarmishra** [GoogleChrome/chromium-dashboard#1221]
**Describe the bug**
For setting up dev env when use `npm ci` id shows error, because` ebidel/lighthouse-ci `has be renamed to` ebidel/lighthousebot `

**To Reproduce**
1. Go to 'chromium-dashboard'
2. Run command `npm ci'
4. See error. 
![Screenshot from 2021-03-19 19-06-08](https://user-images.githubusercontent.com/58372823/111788647-5384cd80-88e6-11eb-9c8e-e7ea88bcb395.png)

**Comment by shivamag00** [comment]
@aavishkarmishra Have you configured SSH key on github??

**Comment by jrobbins** [comment]
lighthouse-ci is no longer being used.  I will remove that dependency.
