### ISSUE TITLE
"Intent to Experiment" email does not include experiment timeline

### ISSUE THREAD

**Issue by mkruisselbrink** [GoogleChrome/chromium-dashboard#1225]
**Describe the bug**
Intent to Experiment emails are supposed to include a timeline for the proposed origin trial, as well as a section on "any risks when the experiment finishes". Neither of these sections seem to be part of the email generated by chromestatus.com.

**Comment by mrego** [comment]
This is similar to #1162.

**Comment by chrishtr** [comment]
Closing in favor of #1162
