### ISSUE TITLE
chrome remote debug no longer works for android devices

### ISSUE THREAD

**Issue by KMasaitis** [GoogleChrome/chromium-dashboard#1228]
**Description:**
Remote inspection for android apps and webview is not working and displaying a blank dev tools window.

Tested on v89 and v91(canary)

**Steps to reproduce:**
Open chrome://inspect
Select Android device to inspect
Debug window opened, but no debug informationio displayed for selected device

**Comment by jrobbins** [comment]
This sounds like you are trying to report a defect in the chrome browser rather than the chromestatus feature tracking tool.  Please report your issue at https://crbug.com/new.
