### ISSUE TITLE
Milestone page list without scrollable sidebar

### ISSUE THREAD

**Issue by khubaibalam2000** [GoogleChrome/chromium-dashboard#1240]
**Is your feature request related to a problem? Please describe.**
While opening milestone pages on chromestatus.com, if you open web page of milestones below 50 or 60, then you have to again scroll to the top of the page. Sometimes, it is annoying, as you are continuously opening multiple milestone pages and again and again scroll to the top to see features list.

**Describe the solution you'd like**
If we just put the milestone pages in a scrollable sidebar, then this problem will resolve, and web page will also look more better.

**Additional context**
https://user-images.githubusercontent.com/74249716/112718842-6e26fa00-8f17-11eb-988e-56f37a02f599.mp4

**Comment by khubaibalam2000** [comment]
I am willing to work on this issue.

**Comment by jrobbins** [comment]
I'm planning on eventually removing the side nav altogether and instead using a set of filter widgets located above the list.  But, I am not ready to spec out that design yet.

**Comment by khubaibalam2000** [comment]
I worked on UIs and designs in my some of my past university projects. I have a design in my mind. Can I share that design with you?

**Comment by shivamag00** [comment]
Just For the record, #1113 contains a proposal for replacing left hand navigation.
