### ISSUE TITLE
Rollup Error : Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by akgupta0777** [GoogleChrome/chromium-dashboard#1241]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
I am installing and setting chromium dashboard repo on my local system and after installation starting the build fails with rollup error : Cannot read property 'add' of undefined.

**To Reproduce**
1. Run npm run start command after installation from README file.

**Expected behavior**
It should start the server and build chromium dashboard without any error.

**Additional context**
Operating System : Windows 10 Home

**Log Screenshot :** 

![image](https://user-images.githubusercontent.com/51379307/112721339-5193bd80-8f29-11eb-8e96-393b9afb00e5.png)

**Comment by shivamag00** [comment]
@akgupta0777, I did a fresh installation of the repo on my local system today. I did not encounter any errors. Please try to install again by carefully following all the instructions from README.md. Also, verify that the you have installed GAE SDK for Python 2 as it no longer the default version

**Comment by akgupta0777** [comment]
I have installed GC SDK as mentioned in the repo readme

**Comment by akgupta0777** [comment]
I think this is caused by rollup or i think i need a rollup.config which I don't have

**Comment by akgupta0777** [comment]
@shivamag00 did everything but didn't fixed the problem Help please

**Comment by shivamag00** [comment]
Seems to be a problem with specific versions of [babel](https://github.com/babel/minify/issues/556). Which command did you use to install npm dependencies ?

**Comment by akgupta0777** [comment]
Just npm ci

**Comment by shivamag00** [comment]
I tried to install the repo again on another Windows PC. I still cannot reproduce this error. 

However, I would recommend you to install the repo in a Linux Distro or in a Linux VM on Windows (I am using WSL2). There may be some additional changes that you may need to do if you run it on Windows. For example, `npm start` command will try to execute a bash script after building the project files (You are facing error in the build process). For running a bash script on windows, you will have to make some changes.

**Comment by akgupta0777** [comment]
I will try to install this on WSL 2 i have on my windows machine.

And the terminal which I am using on windows for running bash script is a bash terminal itself. I already worked a lot with Hyper terminal with bash scripts never encountered any error.

Thanks for commenting I will try on WSL 2

**Comment by akgupta0777** [comment]
I have the Latest versions of node and npm.

**Comment by jrobbins** [comment]
I think that we are unlikely to be able to help you resolve this.  If you are able to resolve it on your own, please note it here.
