### ISSUE TITLE
Pin Tabs to the Right, (L/R tab management)

### ISSUE THREAD

**Issue by BennEntterprise** [GoogleChrome/chromium-dashboard#1245]
**Is your feature request related to a problem? Please describe.**
I hate getting derailed by a coworker. Whatever happens I need to open up a separate set of tabs, help solve the problem, then employ some "tab management" to metaphorically clean my workspace back to the state I had it when I was still working on my stuff. 

**Describe the solution you'd like**
I would love the ability to Pin Tabs to the left AND Right. 

This way my work can always stay on the left.
Any "spontaneous work can go to the right. 
When I'm done with the spontaneous stuff I can just close everything on the right, thus returning me to my productivity. 

(I would argue this is the digital equivalent of closing a manila folder and handing back to your coworker.) 

**Additional context**
 There is already a 'Close Tabs To Right' option in the right click context menu. It might be worth it to develop a 'Close Tabs to Left'

**Comment by jrobbins** [comment]
This sounds like a feature request for the chrome browser rather than anything related to the chromestatus.com feature tracking tool.  Please file your feature request at https://crbug.com/new.
