### ISSUE TITLE
Site and JSON data need to support that origin trials are now supported in WebView

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#1247]
The following needs to be done:

* The JSON needs to be updated with origin trial start and origin trial end fields for WebView.
* Cards need to be updated to display this information.

Support for WebView origin trials [is finished](https://bugs.chromium.org/p/chromium/issues/detail?id=1099836). The first WebView origin trial will likely star in 91 with [Trust Token API](https://www.chromestatus.com/feature/5078049450098688).

**Comment by jpmedley** [comment]
@jrobbins Did origin trials not end up being on WebView? I thought this was a done deal, but fields for this haven't shown up in the wizard.

**Comment by jrobbins** [comment]
Not yet.  But, we can certainly add it.

**Comment by jpmedley** [comment]
I think we should. Judging by the history of these things, there's no guarantee that Android and WebView OTs will happen at the same time.

**Comment by jrobbins** [comment]
The fields were added.  That change is live now.
