### ISSUE TITLE
How can I delete a ChromeStatus entry?

### ISSUE THREAD

**Issue by mfreed7** [GoogleChrome/chromium-dashboard#1251]
This is either not possible or not obvious. I need to delete this entry, as it is no longer being launched and has been cancelled:

https://www.chromestatus.com/feature/5741884322349056

Is this possible?

**Comment by jpmedley** [comment]
@mfreed7 Changing the Chromium status to "No Longer Pursuing" is the recommended approach. @cwilso Is there any heuristic regarding when to delete versus when to change the status?

Regarding deleting, do you see this when you're logged in?

![image](https://user-images.githubusercontent.com/8204171/114583529-88aae400-9c36-11eb-835b-9ae8512aec2f.png)

**Comment by cwilso** [comment]
I would just change to no longer pursuing.  (I think the ACLs for deleting are different from creating and modifying; only some of us have access to delete, iirc.)

**Comment by jrobbins** [comment]
@mfreed7, the "Delete" link that jmedley mentioned is for site admins only.  So, cwilso's comment is your best answer, and in fact, it looks like the feature status was already set to "No longer pursuing".

**Comment by mfreed7** [comment]
Thanks!

**Comment by mfreed7** [comment]
Actually, I'd like to re-open this issue. I "revived" the chromestatus entry, with a slightly different approach. I set the feature status to "Enabled by Default", as that's the approval I'm seeking. However, [the entry](https://chromestatus.com/feature/5741884322349056) still says this:

> This feature is only shown in the feature list to users with edit access.

Any way to bring this entry back from the invisible state?

**Comment by jstenback** [comment]
Yes, if you go edit the entry you'll see a checkbox that says it's an "Unlisted" entry. Uncheck that and save and it should be back to "normal".

**Comment by mfreed7** [comment]
Ahh, the hidden-in-plain-sight "unlisted" checkbox. Thanks! That did the trick.
