### ISSUE TITLE
Filtering issue on mobile view

### ISSUE THREAD

**Issue by khubaibalam2000** [GoogleChrome/chromium-dashboard#1261]
**Describe the bug**
In desktop view of website chromestatus.com, we have a direct filter method as shown below:
![chromium filter bug](https://user-images.githubusercontent.com/74249716/114404929-9a04d980-9bbf-11eb-9ea3-429197995569.PNG)

But in mobile view, there is not such type of filtering method.
![chromium filter bug mob view](https://user-images.githubusercontent.com/74249716/114407863-4b0c7380-9bc2-11eb-83c4-08ef0a1a308e.jpeg)

**To Reproduce**
On Mobile:

1. Go to https://chromestatus.com/features
2. Try to find the filter button on the features block.

**Expected behavior**
A filtering should be appear as it is appearing on desktop view of website. Then, it will be easy for developers to filter out the features category wise.

**Comment by jrobbins** [comment]
I'm planning on redoing the entire UI for filtering.  We won't use the category links.  Instead we will have some filtering widgets displayed at the top of the list.

I'm going to close this issue now, but I will keep in mind that the new filtering widgets need to work on mobile.
