### ISSUE TITLE
Chrome 90 removed #intensive-wake-up-throttling Flag

### ISSUE THREAD

**Issue by muadDweeb** [GoogleChrome/chromium-dashboard#1268]
I noticed with the newest release of Chrome 90 that the flag for intensive-wake-up-throttling has been removed.

the registry settings to disable the setting are not working in Windows 10-
Software\Policies\Google\Chrome\IntensiveWakeUpThrottlingEnabled
key value of 0x00000000

Just curious if anyone knows what happened to the flag/setting in this new version of Chrome? I've searched the release notes as well as the deprecated/removed and dev/beta forums for any mention.

Any help would be much appreciated!

**Comment by jrobbins** [comment]
Some of our feature entires have flag_name, but that field was recently added so we have not tracked it for all features.  I am not able to answer your question with any information on chromestatus.com.

You might try asking on https://groups.google.com/a/chromium.org/g/chromium-dev
