### ISSUE TITLE
Unclear where the explainer is populated from (for the Intent to Ship)

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/chromium-dashboard#1273]
**Describe the bug**
I created the Intent to Ship on https://www.chromestatus.com/guide/edit/5665918254317568 and it said "Explainer" "None". It would be great if it was a bit clearer where this field comes from. Is it from "Doc links" field or?

**Expected behavior**
I would like the field that populates the Explainer to be labelled as such. This is helpful when I'd like to do an inline explainer, so I can just type it into Chromestatus from the start instead of having modify the intent template and then figure out where it would go in Chromestatus.

**Comment by jrobbins** [comment]
For a new feature incubation, the explainer comes from the "explainer links" field in the "Start prototyping" stage.

However, your feature entry type is just "web developer facing change to existing code".  According to the process doc, an explainer is not required:
https://www.chromium.org/blink/launching-features#:~:text=Web-developer-facing%20change%20to%20existing%20code%20(PSA)

I'll change the intent generation template so that that section is not shown in that case.

**Comment by jrobbins** [comment]
Note that for that feature type, there is a "Spec link" field in the first stage.  I think that an existing feature is assumed to have an existing spec rather than an explainer.  I realize that is not what you asked, I'm just noting why I think that an explainer is not required.

**Comment by npm1** [comment]
Thanks for that clarification. I think explainer should always be required (even if inline, like I ended up doing in my intent). It is crucial to enable evaluating the change proposed. Looping in API OWNER @yoavweiss

**Comment by yoavweiss** [comment]
A short explainer of what the web-facing change is required for an intent to ship.


> However, your feature entry type is just "web developer facing change to existing code". According to the process doc, an explainer is not required:
> https://www.chromium.org/blink/launching-features#:~:text=Web-developer-facing%20change%20to%20existing%20code%20(PSA)

That's for a PSA, which is significantly lighter weight, and destined at smaller changes which require no approval.

**Comment by jyasskin** [comment]
I believe this is a specific case of https://github.com/GoogleChrome/chromium-dashboard/issues/3363, "Make it easier to recover from picking the "wrong" feature type". Feel free to reopen it if I got that wrong.
