### ISSUE TITLE
Hard to see what stage a feature is at

### ISSUE THREAD

**Issue by jyasskin** [GoogleChrome/chromium-dashboard#1276]
**Describe the bug**

In https://chromestatus.com/feature/5702310124584960, it's hard to tell that the feature is entering origin trial in M91.

**Expected behavior**

The "Status in Chromium" section should probably mention this.

**Comment by cwilso** [comment]
Probably, this should be two things - show the stage in the abbreviated feature page, and show the OT start/end milestones if it's in OT.

**Comment by jpmedley** [comment]
#1083 covers the latter.

**Comment by jyasskin** [comment]
This is fixed. The active stage is now marked as active in the main feature page, and milestones are also visible.
