### ISSUE TITLE
Middle-clicking links to timeline views doesn't work

### ISSUE THREAD

**Issue by davidben** [GoogleChrome/chromium-dashboard#1294]
**Describe the bug**
Middle-clicking the progress bar links on https://chromestatus.com/metrics/feature/popularity doesn't work.

**To Reproduce**
1. Go to https://chromestatus.com/metrics/feature/popularity
2. Middle-click on a progress bar

**Expected behavior**
The timeline page opens in a new tab.

**Additional context**
If I need to look at a collection of features, I usually first get to https://chromestatus.com/metrics/feature/popularity, because that's where the 'Stats' button in the header takes me. There are enough entries that the dropdown in the timeline view is inconvenient to search through (find in page works on the first link), so I'll usually just middle-click them into new tabs.

As an aside, it also usually throws me off that clicking the name actually takes me to a fragment on the same page. The progress bars are not as obviously clickable. Maybe the name should also go to the timeline view? Jumping to a particular row in the popularity page seems not useful to me, but maybe there's some other workflow I'm missing.

**Comment by jrobbins** [comment]
The middle click problem was resolved by [this commit](https://github.com/GoogleChrome/chromium-dashboard/pull/1850).  And that change is live.

**Comment by jrobbins** [comment]
Regarding the clicking on the name vs. the bar, I agree with that.  I am thinking that maybe they could both go to the use counter timer line.  And, there could be a separate UI element like a paragraph-symbol that appears as the user hovers to be the self-link.
