### ISSUE TITLE
GOOGLE_SIGN_IN_CLIENT_ID

### ISSUE THREAD

**Issue by shivamag00** [GoogleChrome/chromium-dashboard#1312]
**Is your feature request related to a problem? Please describe.**
Currently, the `GOOGLE_SIGN_IN_CLIENT_ID` is defined as a variable in `settings.py`. Since `http://localhost:8080` is not added as _Authorized JavaScript origins_ in GCP for the existing OAuth 2.0 Client ID, developers will have to change it everytime they test some functionality and change it back to the original one before they commit changes. This may be a source of errors in the future.  

**Describe the solution you'd like**

- We can initialize GOOGLE_SIGN_IN_CLIENT_ID as an environment variable. Then, developers will only have to replace it once with the OAuth 2.0 Client ID which they would issue themselves from GCP.

OR

-  I don't know if this will be a good practice. Add `http://localhost:8080` to Authorized JavaScript origins for the existing OAuth 2.0 Client ID.

Request for Comments: @jrobbins

**Comment by jrobbins** [comment]
Leaving out localhost:8080 was my mistake since I use :8888.
I have added :8080.
Please try the default client_id now.

**Comment by shivamag00** [comment]
Thank You @jrobbins. It am able to use the default client_id now.
