### ISSUE TITLE
Intent to experiment email does not include the milestone ranges for the experiment

### ISSUE THREAD

**Issue by chrishtr** [GoogleChrome/chromium-dashboard#1321]
Most of the fields are copied into the generated email, but it seems the milestones are not. Compare:

https://groups.google.com/a/chromium.org/g/blink-dev/c/UgZAAElUWzU

with

https://www.chromestatus.com/feature/5193009714954240#details

**Comment by jpmedley** [comment]
+1

**Comment by mrego** [comment]
This has been reported in #1162.

**Comment by yoavweiss** [comment]
^^ @cwilso @jrobbins
