### ISSUE TITLE
Titles for edit pages should include the name of the feature

### ISSUE THREAD

**Issue by davidben** [GoogleChrome/chromium-dashboard#1336]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
Edit pages for features do not include the feature name.

**To Reproduce**
1. Go to https://www.chromestatus.com/guide/edit/6678134168485888 and various other similar pages
2. Try to find the tab again

**Expected behavior**
The titles include the feature name, so bookmarks, tab search, etc., easily picks this up. Right now the titles all say "Chrome Platform Status", which isn't very useful.

**Additional context**

**Comment by shivamag00** [comment]
> **Describe the bug**
> Edit pages for features do not include the feature name.
> 
>
> **Expected behavior**
> The titles include the feature name, so bookmarks, tab search, etc., easily picks this up. Right now the titles all say "Chrome Platform Status", which isn't very useful

Just to confirm that I understood the bug properly, do you mean to say that _**'Edit pages for features do not include the feature name'**_ in the web page title which is displayed on the chrome tab ?
