### ISSUE TITLE
Add a boolean field to indicate a feature affects //chrome

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1338]
**Is your feature request related to a problem? Please describe.**
Some features don't just affect the content area of a web browser.  When such features are adopted by other browsers, they may need to make changes to the corresponding aspects of their product UI.  ChromeStatus should have a field to identify such features.

**Describe the solution you'd like**
A boolean field in the chrome implementation status part of the Start Prototyping phase.

**Additional context**
The help text will explain the field and ask the feature owner to follow a link to a spreadsheet to fill in additional details.  In the future, those details themselves would in edited in chromestatus.

**Comment by jyasskin** [comment]
I think #1373 fixed this.
