### ISSUE TITLE
Use datalist instead

### ISSUE THREAD

**Issue by jimmywarting** [GoogleChrome/chromium-dashboard#1342]
On https://chromestatus.com/metrics/feature/timeline/popularity you have a very long list of select options
It's not so search friendly...

![Skärmavbild 2021-06-01 kl  01 09 46](https://user-images.githubusercontent.com/1148376/120248207-7fbdb280-c276-11eb-94e6-c240f1631f5c.png)

Change it to:
```html
<input type="search" list="features">
<datalist id="features">
  <option>
  ...
```
and you will get a input with both a drop down and a search field combo
![Skärmavbild 2021-06-01 kl  01 11 32](https://user-images.githubusercontent.com/1148376/120248262-b85d8c00-c276-11eb-910d-cb26e518df16.png)

(There is no need for a fancy/complicated select2 dropdown with lots of javascript complexity - native is the king!)

**Comment by jrobbins** [comment]
I think to make the change we would need to change the <option value="..."> attribute to be the name of the UseCounter.  That would avoid displaying the UseCounter (bucket) numbers.   And, the JS and/or python code would need to be changed to accommodate that.   We would still need to support existing URLs that contain the bucket ID number.

**Comment by jimmywarting** [comment]
dose number in the screenshots just poped up cuz i just simply switched the `<select>` to be a `<datalist>` in devtool
a unnecessary byproduct if you will. don't remember where they came from or what they stands for

**Comment by Subhradeep10** [comment]
Can I work on it?

**Comment by Subhradeep10** [comment]
@jimmywarting Can I work on it?

**Comment by jimmywarting** [comment]
@Subhradeep10 ofc! Go ahead.

I just submitted a idea, I have no knowledge/experiences in this repo

**Comment by GouravSingal-code** [comment]
can i work on it

**Comment by rushikeshadhav** [comment]
Is this issue open. I am beginner to this project. Can you assign me ?

**Comment by ankit-dot** [comment]
can i work on it \

**Comment by kevinshen56714** [comment]
Hi, I have created PR #1824 for this.
