### ISSUE TITLE
Research and upgrade to a new email sending service

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1358]
Currently we send emails using google.appengine.api.mail and detect bounces using an app.yaml setting and a handler in internals/notifier.py. These dependencies are available in Py2 on GAE, but not Py3.

The recommended upgrade path is to use an external provider:
https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/migrating-services#mail

We will need to research these options, sign up / provision them, and change our code to use them.

See g/cr-status-staging-emails for examples of email messages sent from our staging server. We don't do anything fancy with emails, we just need to be able to send a HTML email and have it arrive in the recipients' inboxes (which can potentially be tricky because of spam detection, SPF, and DKIM).

We don't do much with inbound emails, but we do detect bounces to (1) stop sending emails to the bouncing address, and (2) notify an escalation address.

**Comment by jrobbins** [comment]
Currently we send emails using `google.appengine.api.mail` and detect bounces using an app.yaml setting and a handler in internals/notifier.py.  These dependencies are available in Py2 on GAE, but not Py3.

The recommended upgrade path is to use an external provider:
https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/migrating-services#mail

We will need to research these options, sign up / provision them, and change our code to use them.

See g/cr-status-staging-emails for examples of email messages sent from our staging server.  We don't do anything fancy with emails, we just need to be able to send a HTML email and have it arrive in the recipients' inboxes (which can potentially be tricky because of spam detection, SPF, and DKIM).

We don't do much with inbound emails, but we do detect bounces to (1) stop sending emails to the bouncing address, and (2) notify an escalation address.

**Comment by KyleJu** [comment]
After some quick search amongst [three services](https://cloud.google.com/appengine/docs/flexible/python/sending-messages),  Mailjet and Sengrid seem to have better integration with Python, as [Mailgun](https://github.com/mailgun) doesn't have a python library. 

Pricing wise, Sendgrid gives you $300 credits while Mailjet allows you to send [6000 emails for free](https://www.mailjet.com/integration/google/).

Both sendgrid and Mailjet have great dev documentation. I am going ahead with Mailjet because it seems to have better integration with [Google Cloud](https://www.mailjet.com/integration/google/)

**Comment by jrobbins** [comment]
I had not thought about billing.   6000 emails per month is not enough.  I suppose that we have budget, but over the long run there will periodically be occasions where something billing-related needs to be updated otherwise there will be an outage.  It's another potential point of failure, especially for a project that has no dedicated SREs.  So, let's weigh alternatives again before committing.

I have been thinking that if we didn't have time to upgrade mail sending to use a service, then we could keep our `notifier` service in py2.  notifier.py and notifier_test.py total about 1000 lines of code.  I had thought that the advantage of doing that would be just to be able to upgrade the main app to py3 before getting into mail sending.  The disadvantage is that when we lose py2 on our workstations, we would need to test each email change on the staging server which is tedious.

However, your research into mail sending services highlights another advantage of keeping part of our app in py2.  That is that GAE py2 email sending would avoid new points of failure for the technical integration with the mail service and the billing setup.  To mitigate the disadvantage, we could split notifier.py into two files for our app-specific logic vs. a very simple task handler that only sends emails (and handles bounce notifications).   So, we might have under 200 lines of py2 code.  We could mitigate the debugging hassle by keeping the existing condition that decides to either send email or log it to the terminal, and making sure that that stays on the py3 side of the split.  Architecturally it would be like:
`Web UI in py3` -> `existing task` -> `notifier.py in py3` -> `new email sending task` -> `sendemail.py in py2`

Someday GAE py2 support will be shut down, and we will need to integrate with some email sending service anyway.  However, by that time, we should be in a better position to cope with that dependency.  E.g., have monitoring in place.  E.g., have our app fully tested in py3.

**Comment by jrobbins** [comment]
We resolved this by using the GAE bundled legacy library.
