### ISSUE TITLE
Upgrade to cloud logging

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1359]
Apparently, we need to make some changes to allow logging to work in Py3 under appengine.
https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/migrate-to-cloud-logging

**Comment by jrobbins** [comment]
Testing this change sounds tricky because the docs say that only way to test is to run as a Py3 app.  Our app (as a whole) does not yet run under Py3, so  that can't happen.  But, maybe we could just get the requirements.txt and logging client setup calls in place for now with testing to come later.   Or, we could try to temporarily make a small subset of the app run under Py3 just to test logging, but that might not be worth it at this point.

**Comment by KyleJu** [comment]
The doc also mentions `With Cloud Logging, the Log Viewer does not assign a severity level to request logs. When you expand a request entry, you'll see app entries nested within the request entry, and those app entries will show a severity icon. But the request entry itself does not show a severity icon and cannot be filtered by severity level.`

It means before running as a Py3 app, we will lose severity icons and and the ability to filter, but the log should still be nested.

**Comment by jrobbins** [comment]
No worries about losing request severity icons and filtering.  I usually look at HTTP response codes only, and then expand out the log lines for requests that responded with 500.

**Comment by KyleJu** [comment]
Fixed by  #1449

**Comment by KyleJu** [comment]
Retry #1438 in python3 because #1449 didn't retain structured logging on appengine
