### ISSUE TITLE
Get our continuous integration (CI) system working again

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1360]
The old Travis-CI setup that we inherited has stopped working.

Research the options available today (e.g., GitHub Actions, Google Cloud Build, Travis, Circle, etc.)  choose one and get it working.

Right now we only use CI to run unit tests for github PRs.    In the future, we will also want to run javascript unit tests for PRs.   And, of course, we need Py2 for now and Py3 later, ideally with the possibility of running tests in both during the final stages of our upgrade to py3..

**Comment by shivamag00** [comment]
FIY, the CI will require running DataStore Emulator for running the tests.
