### ISSUE TITLE
No dropdown for standardization status

### ISSUE THREAD

**Issue by TimothyGu** [GoogleChrome/chromium-dashboard#1366]
**Describe the bug**
When editing a feature, one cannot change the standardization status of the spec.

**To Reproduce**
1. Go to https://chromestatus.com/feature/5658622220566528. Under "Specification" is "Editor's draft".
2. Now go to https://chromestatus.com/guide/editall/5658622220566528 as a Chromium contributor. There is no way to change the status of the specification to be "Established standard" or anything else.

**Expected behavior**
One should be able to change the standardization status.

**Comment by jyasskin** [comment]
I think this is fixed. At least, I can't find "Editor's draft" on https://chromestatus.com/feature/5658622220566528 anymore.

**Comment by past** [comment]
Seems fixed by #1428 and #1514.
