### ISSUE TITLE
Play Store will not Update  phone to newest release

### ISSUE THREAD

**Issue by GrisGrisMan86** [GoogleChrome/chromium-dashboard#1368]
My browser says that there a newer version available, the 6/16 release. I go to Google Play Store to update, and when I hit update, it says pending for a split second and then instead of downloading or installing, it goes back to button saying update. I have the space, so what gives. It's a Samsung Galaxy A11 if that makes a difference. Updated fine on my laptop.

**Comment by jpmedley** [comment]
I apologize that this escaped our notice before now. This is not the correct place to report this. [Please go here](https://support.google.com/googleplay/community).
