### ISSUE TITLE
Duplicate chrome status entry: VirtualKeyboard API

### ISSUE THREAD

**Issue by keithlee96** [GoogleChrome/chromium-dashboard#1396]
https://chromestatus.com/guide/edit/5717448231747584

is a dupe of

https://chromestatus.com/guide/edit/5680057076940800

Could I get https://chromestatus.com/guide/edit/5717448231747584 deleted? 

There doesn't seem to be an easy way to delete chrome-status entries.

**Comment by jrobbins** [comment]
Done.

Only site admins can delete features for now.
