### ISSUE TITLE
P3: Better aggregate "citizenship" view of feature colors

### ISSUE THREAD

**Issue by maxh** [GoogleChrome/chromium-dashboard#14]
The spreadsheet is a cluttered mess, but the one thing it has over this replacement is that it's easy to visualize the citizenship of the whole project at a glance, because you can see so many green/red cells and if you squint you get a good overall feel--kind of like how a sparkline can help you understand general trends even if the specific data points are too small to understand.

We should figure out how to add an aggregate view to the new dashboard.

**Comment by jpmedley** [comment]
This is so old it is no longer possible to determine what is being asked for.
