### ISSUE TITLE
Add new subcomponent Blink>Storage>SharedStorage to Chrome Platform Status Dashboard

### ISSUE THREAD

**Issue by pythagoraskitty** [GoogleChrome/chromium-dashboard#1402]
Blink>Storage>SharedStorage has been added to Monorail.  Could you please add it to Chrome Platform Status so that the [Shared Storage API](https://chromestatus.com/feature/6256348582903808) can be listed under this new subcomponent?  Thank you.

**Comment by jpmedley** [comment]
Just confirmed this was fixed, but don't know when.
