### ISSUE TITLE
chromedash-featurelist on-scroll listener slows down initial load

### ISSUE THREAD

**Issue by ajklein** [GoogleChrome/chromium-dashboard#141]
When the features list first comes in, `scrollToMilestone` is called by chromedash-featurelist. Looking at a profile of the page load, this call takes ~100ms on my Z620. I suspect this is because of the `on-scroll` listener, which repeatedly tries to calculate which milestone to highlight in the left nav.

This could probably be avoided by waiting to add the on-scroll listener until after page load is finished.

**Comment by beaufortfrancois** [comment]
I just had a look at the `on-scroll` listener doesn't seem to be called multiple times on page load.
![screenshot 2015-01-21 at 5 23 13 pm](https://cloud.githubusercontent.com/assets/634478/5839946/3dea85ba-a192-11e4-8a1d-795484fadfbe.png)
Please feel free to comment to reopen the issue.
