### ISSUE TITLE
Allow /features/ID URL to be an alias of /feature/ID

### ISSUE THREAD

**Issue by mrego** [GoogleChrome/chromium-dashboard#1435]
In Chromium source code there are many pointers to https://www.chromestatus.com/features/ID URLs that no longer work as they're now https://www.chromestatus.com/feature/ID

You can get a link to /features/ in the JavaScript console, but when you click it you don't reach the feature.

If possible it'd be nice to allow using those URLs or configure some kind of redirect.

**Comment by jpmedley** [comment]
Thank you for submitting this. This is actually a bug in the display of the features/ page. You can find the bug for that at #1055
