### ISSUE TITLE
CSS Properties like background, color, cursor, border properties have been removed in Chrome 92. This has made the UI screens look like disabled screens

### ISSUE THREAD

**Issue by NayanaShekar** [GoogleChrome/chromium-dashboard#1441]
![image](https://user-images.githubusercontent.com/88086153/127305412-532e81cd-2625-4b94-8265-9007b1b316c9.png)
![image](https://user-images.githubusercontent.com/88086153/127305455-268ae1c8-5fac-46cc-b3ba-d1f6bd1b0bae.png)

**Comment by Pravenn18** [comment]
hey i wanna work on this issue

**Comment by jrobbins** [comment]
Thanks for filing this report! Unfortunately this is the wrong tracker for the Chrome browser (this tracker is for the website chromestatus.com). Please file the Chrome issue at https://crbug.com/new
