### ISSUE TITLE
Chrome Releases Page has wrong link for downloading dev version of the browser

### ISSUE THREAD

**Issue by shivamag00** [GoogleChrome/chromium-dashboard#1444]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
The current releases page shows information about stable, beta and dev channels. It also contains the link to download the corresponding versions of the browser. However, for the dev channel, the link points to Canary version instead of dev version.

**To Reproduce**
1. Go to 'https://chromestatus.com/features/schedule'
2. Click on 'Chrome 93 in the DEV Channel'

**Expected behavior**
The link should point to the download link of dev version of the browser.

**Comment by saan5** [comment]
@ @jrobbins
