### ISSUE TITLE
Convert Tab Group to Bookmark Folder

### ISSUE THREAD

**Issue by abaldenko** [GoogleChrome/chromium-dashboard#1448]
As a chrome user I'd like to be able to convert a tab group into a bookmark folder. This will provide me the psychological safety to close tab groups that i'm not using today, but that i know i will need soon. 😅

**Comment by jstenback** [comment]
Thanks for filing this report! Unfortunately this is the wrong tracker for the Chrome browser (this tracker is for the website chromestatus.com). Please file the Chrome issue at https://crbug.com/new

**Comment by abaldenko** [comment]
Thanks and sorry for the confusion!
