### ISSUE TITLE
Drag and Drop bug with Lenovo gaming mouse

### ISSUE THREAD

**Issue by kam2yar** [GoogleChrome/chromium-dashboard#1459]
Hi
I have a problem with drag and drop tabs in google chrome and chromium, it's not working at all but it's normally works with a touch pad.
my mouse works fine in firefox tabs.

Lenovo gaming mouse, (attached with Lenovo y700)

**Comment by jrobbins** [comment]
Thanks for filing this report! Unfortunately this is the wrong tracker for the Chrome browser (this tracker is for the website chromestatus.com). Please file the Chrome issue at https://crbug.com/new
