### ISSUE TITLE
Should "Edge Views" should be removed from vendor signals?

### ISSUE THREAD

**Issue by phoglenix** [GoogleChrome/chromium-dashboard#1483]
Now that Edge is using Chromium engine it doesn't count as a separate implementation and therefore vendor signals from Edge are not requested anymore, right?

https://bit.ly/blink-signals also doesn't mention Edge as part of the official process.

If that's correct, it is a bit confusing to have a Vendor Signals field for Edge in Chromestatus.
Could the field be removed, or (if it needs to stay for historical reasons) a note be added to explain that it's not needed for new features?

**Comment by chrishtr** [comment]
I agree that this field should be removed since it causes confusion in intents. See also #1379, which is related.

**Comment by cwilso** [comment]
OK, how about this: 

I want to keep some measure of input on "other browser" signals.  However, this is a different category, should not be confused with "implementation signals" and definitely not required.

We should have required signals:
webkit
gecko
web developer

and then an optional text entry box - not a dropdown - for "other signals (e.g. other browsers)".

@jrobbins WDYT?

**Comment by chrishtr** [comment]
Sounds good to me.

**Comment by chrishtr** [comment]
Can this issue be closed now?
