### ISSUE TITLE
URL fields should handle extraneous information

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#1484]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
The form fields that require URLs allow other text that breaks links. The image below shows this for a feature that's about to ship. The feature owner was allowed to enter '(merged)', which the rendered card makes part of the URL. Following this "link" returns a 404.

![image](https://user-images.githubusercontent.com/8204171/130465356-bb63a479-f504-44d0-86f7-d77519e75659.png)

**To Reproduce**
1. In the staged test version of the site, open any feature.
2. Enter text like the following in any field intended to hold a URL: "`https://github.com/whatwg/html/pull/6562 (merged)`".
3. Save the entry.
4. On the rendered card attempt to follow the link.

**Expected behavior**
Here are a couple of options. 
* disallow non-URL text in URL fields.
* Extract URLs from text fields and render them before concatenating additional text.

**Comment by kevinshen56714** [comment]
Hi, I created PR #1847 for this.

**Comment by jpmedley** [comment]
👏
