### ISSUE TITLE
Linked spreadsheet for `requires_embedder_support` appears to be private

### ISSUE THREAD

**Issue by stephenmcgruer** [GoogleChrome/chromium-dashboard#1497]
For `requires_embedder_support`, aka `Requires embedder support:`, in the incubating phase, the help text links to the following spreadsheet. When I click on that link, it doesn't appear to be either world-readable, shared with my @chromium, or with my @google. 

This isn't really a problem with ChromeStatus itself of course, but I'm hoping you might know who to ping :). I've requested access myself, so if its approved I'll figure out the sheet owner and tell them directly too.

The spreadsheet: https://docs.google.com/spreadsheets/d/1QV4SW4JBG3IyLzaonohUhim7nzncwK4ioop2cgUYevw/edit#gid=0

**Comment by jpmedley** [comment]
I would send an email to the feature owners.
