### ISSUE TITLE
chrome preserved console log can not be expaned

### ISSUE THREAD

**Issue by FanFanFantastic** [GoogleChrome/chromium-dashboard#1500]
**Describe the bug**
chrome preserved console log can not be expanded

**To Reproduce**
1. log something on the console and proceed/redirect to a second page
2. preserved console logs can not be expanded and observed 
![image](https://user-images.githubusercontent.com/13370622/131251639-8649a045-c381-4702-a76b-8a5906676635.png)

**Expected behavior**
should be able to expand and checkout the object that's been logged

Version 92.0.4515.159 (Official Build) (x86_64) Mac

**Comment by jrobbins** [comment]
Thanks for filing this report! Unfortunately this is the wrong tracker for the Chrome browser (this tracker is for the website chromestatus.com). Please file the Chrome issue at https://crbug.com/new
