### ISSUE TITLE
Specification "Unknown status" is overly vague when explainer and specifications exist.

### ISSUE THREAD

**Issue by scheib** [GoogleChrome/chromium-dashboard#1504]
When entering explainer and or specification links the resulting published section for 'Specification' can remain "Unknown status".  This is an overly vague status when more concrete details are known.

That is, If an explainer link is provided, it should create a link on the status page labeled "explainer".  If a specification link is provided, it should not hide the explainer, and have its own link including the word "specification".

E.g. [Idle Detection](https://chromestatus.com/feature/4590256452009984) at this moment has an [explainer](https://github.com/WICG/idle-detection/blob/main/README.md) and [Spec link](https://wicg.github.io/idle-detection/) == [Draft API spec](https://github.com/WICG/idle-detection/blob/main/README.md) links.  However, the result is simply a confusing:

![image](https://user-images.githubusercontent.com/386971/131413486-0f6a3461-c347-49f9-8bdb-8f030b8ecfef.png)

**Comment by jrobbins** [comment]
I tweaked the UI to show a bit more information and make it more clear.  That change went live yesterday.

**Comment by scheib** [comment]
Thank you.  Good improvement.  Can I ask for more?  If an explainer and specification are provided please show links to both.
