### ISSUE TITLE
Incorrect links to Mozilla's standards position for intents.

### ISSUE THREAD

**Issue by mikewest** [GoogleChrome/chromium-dashboard#1512]
In intent emails sent over the last few days, I've seen the link to Mozilla's standards position incorrectly generated. For example, https://groups.google.com/a/chromium.org/g/blink-dev/c/U5K69fbA6SU/m/6Ipi3Q4zAgAJ displays `Gecko: No signal (https://github.com/mozilla/standards-positions/issues/570)`, but the link points to `https://chromestatus.com/admin/features/launch/5702310124584960/5?intent=1`.

**Comment by jrobbins** [comment]
This change went live yesterday.
