### ISSUE TITLE
Grammar failure

### ISSUE THREAD

**Issue by singleDeveloper63** [GoogleChrome/chromium-dashboard#1516]
![image](https://user-images.githubusercontent.com/63005771/132351625-72a5394d-6508-476e-b538-49c2ec8c3c21.png)
This is not right. **Focus debugge** - _Focus debugger_

**Comment by jrobbins** [comment]
Thanks for filing this report! Unfortunately this is the wrong tracker for the Chrome browser (this tracker is for the website chromestatus.com). Please file the Chrome issue at https://crbug.com/new

**Comment by singleDeveloper63** [comment]
> Thanks for filing this report! Unfortunately this is the wrong tracker for the Chrome browser (this tracker is for the website chromestatus.com). Please file the Chrome issue at https://crbug.com/new

OMG, I'm sorry )
