### ISSUE TITLE
Gantt Chart Should Show End of OT When no Shipping Milestone is Present

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#1524]
**Is your feature request related to a problem? Please describe.**
When a shipping milestone is present, I don't really need the end milestone for an origin trial. I can assume that the origin trial ended before shipping.

When an origin trial is in progress, I might want to know when it is ending.

**Describe the solution you'd like**
A range is show for origin trials, at least when there is no shipping milestone. 

**Additional context**
The origin trial dashboard already does this. If the long-term plan is to integrate the dashboard's functionality into Chrome Status, we will eventually need to show this too.

![image](https://user-images.githubusercontent.com/8204171/132883614-a726ac3c-da4d-45f5-a8b0-081990b8ab83.png)

**Comment by jpmedley** [comment]
**_Additional_ additional context:**

The Digital Goods API folks requested an origin trial extension. Extensions happen occasionally, and there is currently no consistent way to show this on the dashboard.

**Comment by IamK51** [comment]
> **Is your feature request related to a problem? Please describe.**
> When a shipping milestone is present, I don't really need the end milestone for an origin trial. I can assume that the origin trial ended before shipping.
> 
> When an origin trial is in progress, I might want to know when it is ending.
> 
> **Describe the solution you'd like**
> A range is show for origin trials, at least when there is no shipping milestone.
> 
> **Additional context**
> The origin trial dashboard already does this. If the long-term plan is to integrate the dashboard's functionality into Chrome Status, we will eventually need to show this too.
> 
> ![image](https://user-images.githubusercontent.com/8204171/132883614-a726ac3c-da4d-45f5-a8b0-081990b8ab83.png)

Only Me,You Trust no one

**Comment by jpmedley** [comment]
@IamK51 Is there a point you're trying to make?

**Comment by jpmedley** [comment]
Duplicate of #1494
