### ISSUE TITLE
Releases Page Shows Shipping Milestone as an Origin Trial

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#1535]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
The features/schedule/ page shows features in a release milestone as being in an origin trial. This is indicated by a puzzle-piece icon as shown in the image below.

![image](https://user-images.githubusercontent.com/8204171/133659417-d0bd1d1c-aed6-4590-a637-9e0b2c502e08.png)

A look at the underlying feature shows that it is not in an origin trial for the column that it's in.

![image](https://user-images.githubusercontent.com/8204171/133660688-6c5106e8-1a4b-4e55-b42d-1c3c207b6608.png)

Since the feature on which this problem was found is likely to change, I've [recreated the problem in staging](https://cr-status-staging.appspot.com/feature/5667616219725824) ([same feature on the release page](https://cr-status-staging.appspot.com/features/schedule)).

**To Reproduce**
1. On any feature add values to the origin trial milestones.
2. Add a shipping milestone that is past the origin trial end milestone.
3. Change the 'Process stage' field to 'Origin Trial'.

**Expected behavior**
The item as listed on the Releases page should *not* show an origin trial icon.

**Comment by jrobbins** [comment]
I think the way to fix this should be to launch the /upcoming page.  It uses headings to indicate what kind of launch is happening for each feature in each milestone.   If you visit https://cr-status-staging.appspot.com/upcoming, you will see your test feature in m95 without the puzzle piece icon, and if you scroll back to m91 it is there with the icon.

**Comment by jpmedley** [comment]
Makes sense. When is that launching?

**Comment by jrobbins** [comment]
I have one change in mind that I will work on today.  After that, I think it could be ready to launch.

**Comment by jpmedley** [comment]
Fixed by redesign.
