### ISSUE TITLE
chromedash-x-meter doesn't produce valid links

### ISSUE THREAD

**Issue by martinthomson** [GoogleChrome/chromium-dashboard#1543]
**Describe the bug**
From [metrics](https://www.chromestatus.com/metrics/feature/popularity) you can access a page that shows more detail on each metric.  You can only do that by a simple click because the chart, which uses a custom `chromedash-x-meter` element, does not render the link in a way that is visible to browsers.

**To Reproduce**
1. Go to https://www.chromestatus.com/metrics/feature/popularity
2. Right click on any of the graph parts.
3. [BUG] The browser does not recognize these as links.  There is no option to copy a link or open it in a new tab/window.
4. Left click on the graph parts, outside of the box where the text percentage is rendered.
5. [BUG] The browser does not navigate, though it shows a cursor of style 'pointer'.

**Expected behavior**
The intent is that these act as links to pages with more detail.  A cursor style of 'pointer' is set and a left click will result in an onclick handler being invoked with the browser navigating to the page identified in the href attribute of the element, if the percentage is clicked on.

If these were truly links then browser functions like "open in new tab" would be able to function.

**Additional context**
This is a very heavy page (Firefox reports this as taking almost 5 times more memory than an active GMail tab).  Being able to open detail pages in a new tab is a useful part of managing the costs associated with navigation to and from this page, even with a bfcache.

**Comment by jrobbins** [comment]
I think the solution will be to add an `<a href="...">` tag that contains the bar-graph elements.
