### ISSUE TITLE
Can't fill in a field if debuggability was empty

### ISSUE THREAD

**Issue by jyasskin** [GoogleChrome/chromium-dashboard#1544]
I tried to fill in the "Firefox views" link in https://www.chromestatus.com/guide/editall/5638148514119680, but it refused my attempt to save because the Debuggability field is empty. Maybe the required fields could be enforced when the feature developer tries to generate an Intent email, but not when another person tries to fill in a different empty field?

**Comment by jrobbins** [comment]
Yep, that's exactly my plan.  It is just taking a while to get around to working on that.

**Comment by jpmedley** [comment]
Jeffrey,

In the meantime, there's an easy hack. Just put a space in the box.

Joe
Joe Medley | Technical Writer, Chrome DevRel | ***@***.*** |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by jyasskin** [comment]
This was fixed by #2460.
