### ISSUE TITLE
Chrome flag "#screentime" is not working

### ISSUE THREAD

**Issue by benniamann** [GoogleChrome/chromium-dashboard#1566]
When i want to activate the https://chrome:flags #screentime to activate to function of apple for my chrome browser, it does not work.

After the relaunch i am still able to type a webadress oder click on my favorite bar but the content site is no more clickable.
When i open a inkognito app its working again and i have to deactivate the flag again and after the relaunch everything works again.

Would be awesome if this function will get fixed soon

**Comment by jrobbins** [comment]
Thanks for filing this report! Unfortunately this is the wrong tracker for the Chrome browser (this tracker is for the website chromestatus.com). Please file the Chrome issue at https://crbug.com/new
