### ISSUE TITLE
"Intent to implement" option not available in some cases

### ISSUE THREAD

**Issue by yoavweiss** [GoogleChrome/chromium-dashboard#1569]
An [intent](https://groups.google.com/a/chromium.org/d/msgid/blink-dev/CAH7Q68VwZB4o%3DHb774HUzGHeYa8H%3DiY6YZbmkpvTxEB_i763aA%40mail.gmail.com) was sent as a "ready for trial" email, even though it's not something the intent owner expect would be trialed with.

Such cases should have a more reasonable option.

**Comment by jpmedley** [comment]
Thank you for the feedback. 

I'm not sure what you're asking for. Can you please provide more information.

**Comment by yoavweiss** [comment]
Essentially, the option to send an "intent to prototype/implement" should be available even when changing existing code in a web-facing way. To quote the intent: 'I wanted to submit an intent-to-implement instead, but it wasn't proposed in the interface, when filling out a "Web developer facing change to existing code".'

**Comment by jrobbins** [comment]
@cwilso, does launching-features need to be revised?  E.g., add something to "Step 1: Write up motivation and implement code" to say that an intent-to-prototype thread is required or optional, or just to send a non-intent heads-up to blink-dev?

**Comment by jpmedley** [comment]
We have a similar problem across the board. The underlying problem is that all four feature types use the same development flow. I changed the title of #700 to cover this.

**Comment by jyasskin** [comment]
I believe this is a specific case of #3363, "Make it easier to recover from picking the "wrong" feature type", in that the Feature Type should really have been "New feature incubation". Feel free to reopen it if I got that wrong.
