### ISSUE TITLE
Staging instance clean up

### ISSUE THREAD

**Issue by KyleJu** [GoogleChrome/chromium-dashboard#1572]
I am running `npm run staging` and the error message indicates that we need to clean up outdated staging instances:

```
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Your app may not have more than 210 versions. Please delete one of the existing versions before trying to create a new version.
```

**Comment by KyleJu** [comment]
I deleted all instances as of May 2021 on all three services

**Comment by jrobbins** [comment]
OK good.  I was meaning to get around to that.  I'll clean up old prod instances so that we don't hit the same problem there.
