### ISSUE TITLE
Chromestatus.com is rather user hostile if credentials expire

### ISSUE THREAD

**Issue by mfreed7** [GoogleChrome/chromium-dashboard#1589]
So I logged in to chromestatus, and started a new feature. I spent the 20+ minutes it takes to fill out the entire questionnaire for the new feature. I then clicked the "Save" button. I was greeted by a 401 Unauthorized error page, because apparently (somehow?) my credentials expired between starting and finishing things. Clicking Back took me back to the beginning. All of that content is completely gone.

It seems that we should at **minimum** figure out some way to make sure you can get back to the form with your content still there, so you can copy paste it to somewhere while you re-enter your credentials. At best, it should check the credentials before submitting the page, and allow you to re-authenticate, without losing any of the content you've entered.

In case it helps at all, the feature I was working on is here: https://chromestatus.com/feature/5654547184746496#details

**Comment by mfreed7** [comment]
Thanks for the replies. So I think I got half way through filling it out, went to get some external information, likely got side-tracked, and came back after an hour.

I don’t think the token needs to be kept alive, it just needs to be more resilient if the token expires before you click “Done”. Like checking and offering an option to renew the login. Rather than just abandoning ship to a 401 page with no ability to click Back.

**Comment by jrobbins** [comment]
This was initially resolved using the Google Sign-In library last year (#1649).
Then, we upgraded to Sign In With Google this year and also implemented session refresh (#1804).

**Comment by mfreed7** [comment]
Thank you!
