### ISSUE TITLE
Sample URLs lists shows the same result for all features

### ISSUE THREAD

**Issue by mrego** [GoogleChrome/chromium-dashboard#1612]
**Describe the bug**
Independently of the feature the list of "Sample URLs" is showing the same list, which is not right.

**To Reproduce**
1. Go to the following pages and check that the list of "Sample URLs" is exactly the same:
  * https://chromestatus.com/metrics/feature/timeline/popularity/95
  * https://chromestatus.com/metrics/feature/timeline/popularity/1692
  * https://chromestatus.com/metrics/feature/timeline/popularity/3987

**Expected behavior**
Each feature should have its own list.

**Additional context**
Not sure if this is the same issue than #1290 or a different one.

**Comment by rviscomi** [comment]
Thanks @yoavweiss. I think I have a fix in #1613.

**Comment by jrobbins** [comment]
#1613 is live now, however I am not sure that it is working correctly.
Some pages give "No data" with this change, whereas they did not show that before.
Is that a problem, or are they correctly showing "No data" for features that really have no data?

E.g., compare the current live version:
https://chromestatus.com/metrics/feature/timeline/popularity/95
vs. the same page with the previous version of the cr-status app:
https://f896c59-dot-app-py3-dot-cr-status.appspot.com/metrics/feature/timeline/popularity/95

**Comment by rviscomi** [comment]
That sounds WAI as not all features are detectable in HTTP Archive, for example those that depend on user interaction or authentication. In this case it seems like the feature itself is not very popular.

**Comment by mrego** [comment]
Getting "no data" was usually common, when the feature has low usage. So I guess this is working fine, at least working the same than in the past.

Thanks for the quick fix!
