### ISSUE TITLE
Missing feedback when setting an item to approved

### ISSUE THREAD

**Issue by dbratell** [GoogleChrome/chromium-dashboard#1642]
**Describe the bug**

In the new "My Features" section, an item can have different statuses. When changing the status to approved, there was no visual status that the update registered.

**To Reproduce**
I've only one item set to approved and I do not want to "approve" anything just to test so I will go from memory here.

I performed the following steps. many of them are probably unnecessary.

1. Opened an item by clicking the stamp icon.
2. Set the dropdown to approved.
3. Clicked the enabled save button, though nothing seemed to happen.
4. Wrote a few words in case the save button needed that to work. 
5. Clicked the save button. Nothing seemed to happen.
6. Closed the item.
7. Opened the item by clicking the stamp icon.
8. Noticed that the item was set to approved.

**Expected behavior**
I expected there to be some kind of visual sign that the button performed an action. Just making the save button disabled again would be enough to show that something happened.

**Comment by jrobbins** [comment]
Have you hit this problem again recently?

I think that this may have been caused by the old 1-hour session expiration bug that we had back in December.  That should have been resolved by https://github.com/GoogleChrome/chromium-dashboard/pull/1649 which went live in mid-December.

**Comment by dbratell** [comment]
I have not seen this happen lately so your theory is probably correct!
