### ISSUE TITLE
My features -> Feature -> left arrow goes to All Features instead of My features.

### ISSUE THREAD

**Issue by dbratell** [GoogleChrome/chromium-dashboard#1645]
**Describe the bug**
Clicking the back arrow (left arrow in the upper left corner) of a feature goes to the All features page even if you came from "My features".

**To Reproduce**

1. Go to "My features"
2. Click on a feature.
3. See the my features page being replaced by the clicked feature.
4. Click the left arrow in the upper left corner of the page.
5. Note that you are now at "All Features" instead of "My Features".

**Expected behavior**
The button/link looks like a "return to where I came from" button so I expected to get back to "My Features".

**Comment by jrobbins** [comment]
This was also mentioned by Chris last week
I believe it this was fixed by #1640.
I only deployed that change today, a few minutes before the API Owners meeting this morning.
So, if you encountered it earlier and entered this issue from memory, please try again now.

**Comment by dbratell** [comment]
Yes, this seems fixed. I encountered it just as the meeting started yesterday so I must have had the old code still running.

Closing as fixed by #1640.
