### ISSUE TITLE
CORS access to featurepopularity endpoint no longer possible?

### ISSUE THREAD

**Issue by fippo** [GoogleChrome/chromium-dashboard#1646]
**Describe the bug**
I've been accessing the [featurepopularity endpoint](https://www.chromestatus.com/data/timeline/featurepopularity?bucket_id=2254) (for feature # 2254) which returns the raw data that is visualized e.g on https://www.chromestatus.com/metrics/feature/timeline/popularity/2254
This is running into `Access to fetch at ... has been blocked by CORS policy`

**To Reproduce**
1. Go to [https://webrtchacks.github.io/chromestatus/](https://webrtchacks.github.io/chromestatus/)
2. check the JS console for CORS related errors.

**Expected behavior**
This used to work a couple of hours ago even. I prefer my visualization since one can work a bit better with the data.

**Additional context**
Apologies if I ended up putting too much load on that endpoint (I wouldn't expect it to be excessive, so far I am the only user)

**Comment by jrobbins** [comment]
We recently added a redirect for all GETs on www.chromestatus.com to just plan chromestatus.com.
So, maybe you need to change your line 119 to remove the "www."?

**Comment by fippo** [comment]
:bow: that fixes it, thank you!

**Comment by fippo** [comment]
seems this broke again? :sob:
@henbos wanted it for nicer comparison of two stats

**Comment by henbos** [comment]
Yeah https://webrtchacks.github.io/chromestatus/ is pretty neat when you want public dashboards (unlike UMA)

**Comment by fippo** [comment]
looks like it is working again? Thank you!

**Comment by KyleJu** [comment]
> looks like it is working again? Thank you!

Perfect! Closing this issue
