### ISSUE TITLE
Features sometimes show up twice in a box on the MyFeatures page

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1647]
**Describe the bug**
Entries in the myfeatures boxes are sometimes duplicated.  This is an intermittent error.      

**To Reproduce**
1. Repeatedly reload the myfeatures page.
2. Within a few tries you will notice that one of the features toward the end of the list shows up twice.
3. Reload again and the list is (probably) back to normal. 

The length of the list is unchanged, meaning that the duplicate row is shown instead of some other row.

**Expected behavior**
Each feature should only be listed once.  And, reloading the page without anyone editing the features should produce the same feature list each time.

**Additional context**
The intermittent nature indicates some kind of race condition.  However, the code for populating those boxes is pretty simple.

**Comment by jrobbins** [comment]
The bug was that the local variable KEY had the wrong value.  So, cached features were being written to the wrong location in the ramcache.  Looking at the source code with that in mind, it becomes easy to spot the problem:
* KEY is being set in the first for-loop, and has a final value that is appropriate for the last feature ID in the list on the last iteration of that first for-loop.
* KEY is then used in the second for-loop, but it is never recalculated.  So, every retrieved feature is stored at the KEY location that was intended for the final feature in the list.

Our existing unit tests don't catch this defect because the code actually produces the correct result so long as it is run a single thread and the list feature ID in the list was a cache miss.   The promises may overlap in time, but we resolve them in order.  That means that if there are N iterations of the second for-loop, N-1 of them write incorrect features to the same entry in ramcache and then the final iteration actually overwrites those with the correct feature.

However, in the case where there are two requests being served concurrently:
* Processing of request A can be on one of the non-final iterations, meaning that the cache has the wrong feature written to it.
* Processing of request B can try to read that feature from the cache and actually get the wrong feature.

**Comment by KyleJu** [comment]
> Our existing unit tests don't catch this defect because the code actually produces the correct result so long as it is run a single thread and the list feature ID in the list was a cache miss. The promises may overlap in time, but we resolve them in order. That means that if there are N iterations of the second for-loop, N-1 of them write incorrect features to the same entry in ramcache and then the final iteration actually overwrites those with the correct feature.

Great analysis!

**Comment by jrobbins** [comment]
This fix was deployed on Thursday (4 days ago).
