### ISSUE TITLE
Process change: question regarding non-open-source-code or APIs

### ISSUE THREAD

**Issue by chrishtr** [GoogleChrome/chromium-dashboard#1659]
Please add the following bolded text to the intent-to-ship required questions list:

**Does the feature depend on any code or APIs outside the Chromium open source repository and its open-source dependencies to function? (e.g. server-side APIs, operating system APIs or closed-source code bundles)
Yes or no. If yes, explain why this is necessary.**

Proposal/approval evidence here:

https://groups.google.com/a/chromium.org/g/blink-api-owners-discuss/c/fbAyrB6fT-g/m/ZMLZ_JveEAAJ

**Comment by past** [comment]
I wonder how likely it is that engineers encountering this question will take "operating system APIs" literally. I suspect the API owners don't care if the feature is using malloc, mmap or the like, but rather the more exotic operating system APIs that don't have equivalents elsewhere?

**Comment by chrishtr** [comment]
Maybe we could rephrase as "operating system APIs tailored to this feature"?

**Comment by past** [comment]
Yes, that seems clearer.

**Comment by jrobbins** [comment]
This change was displayed back in January.
