### ISSUE TITLE
Chrome Platform Status - Upcoming Versions (UI Issue).

### ISSUE THREAD

**Issue by Temp212345433-3** [GoogleChrome/chromium-dashboard#1673]
The 'Bug' is within the Chrome Platform Status webpages e.g. Roadmap & All Features.

As currently under 'Roadmap' it contains:
Stable, (Chrome 97), Beta was Nov 18 - Dec 2, Stable 8 days ago (Jan 4);
Next Up, (Chrome 98), Beta between Jan 6 - Jan 13, Stable in 20 days (Feb 1);
Dev, (Chrome 98), Beta between Jan 6 - Jan 13, Stable in 20 days (Feb 1);

Whereas, under the All Features it contains:
table, (Chrome 97), Beta was Nov 18 - Dec 2, Stable 8 days ago (Jan 4);
Next Up, (Chrome 98), Beta between Jan 6 - Jan 13, Stable in 20 days (Feb 1);
Dev, (Chrome 99), Beta Feb 3 - Feb 10, Stable in 48 days ( Mar 1);

The above issues have been attached in 2 screenshots, and the outcome expected should be that it syncs.

![image](https://user-images.githubusercontent.com/91842479/149225662-1ae8fca6-55f6-4ab8-8161-dd287e330468.png)
![image](https://user-images.githubusercontent.com/91842479/149225720-e25131c5-1b0c-4a6d-aa39-72a65382d5a1.png)

Thank You!

Happy New Year!

**Comment by jrobbins** [comment]
Thanks for pointing this out.
I think this was a temporary problem because a change to the chrome release process that happened around that time.
The problem does not appear now.
