### ISSUE TITLE
should use 301 for http to https redirect

### ISSUE THREAD

**Issue by ghost** [GoogleChrome/chromium-dashboard#169]
It's better to use 301 status code for http to https redirect, but it's now 302.

**Comment by beaufortfrancois** [comment]
According to https://code.google.com/p/googleappengine/issues/detail?id=2081#c1, this is a Google App Engine philosophy issue. 
If we enable HSTS for www.chromestatus.com as discussed at https://github.com/GoogleChrome/chromium-dashboard/issues/170#issuecomment-70835837, this should be solved.

**Comment by jpmedley** [comment]
It appears that the site redirects from http to https.
