### ISSUE TITLE
Send HTTP Strict Transport Security header

### ISSUE THREAD

**Issue by ghost** [GoogleChrome/chromium-dashboard#170]
www.chromestatus.com is already https only, but of course there are many websites that still link to http://www.chromestatus.com. By enabling HSTS, it saves the time to make the first http connection.

**Comment by beaufortfrancois** [comment]
Hey @ebidel, why don't we simply submit "www.chromestatus.com" for inclusion in Chrome's HTTP Strict Transport Security (HSTS) preload list at https://hstspreload.appspot.com?

To see how it would look like in Chrome, you can simply go to `chrome://net-internals/#hsts` and enter "www.chromestatus.com" as Domain name and click the "Add" button. Then, check out `chrome://net-internals/#events` and notice there are no HTTP connections.

**Comment by jpmedley** [comment]
@jrobbins Do you know if this has been done?

**Comment by jrobbins** [comment]
It has not been done.  It seems like a good idea, and probably not too difficult.  I think we need to add a response header before we can submit the site to https://hstspreload.appspot.com.

**Comment by jrobbins** [comment]
There's a little more work to do here.  I need to deploy this change and then submit our site to https://hstspreload.appspot.com.

**Comment by jpmedley** [comment]
Sorry about that.

**Comment by jrobbins** [comment]
No worries.

I have deployed and submitted the site now. 

IIUC, it might be be awhile before chrome starts automatically using https.  When it does take effect, It is supposed to be transparent, so we might not notice unless we test it out.
