### ISSUE TITLE
Don't flag i2p intents for review

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1702]
The API owners prefer to review i2p intents on the mailing list rather than in the tool.  They only require an Ack rather than an actual LGTM.  So, just don't create a review request for i2p.

**Comment by jpmedley** [comment]
@jrobbins This morning, I forwarded you an email where an i2p was combined with an i2s. Does that throw a wrench into what you did?

**Comment by jrobbins** [comment]
The subject line "Intent to prototype & ship: ..." should be detected as an I2S because we convert `&` to `and`, and we recognize `intent to \w+ and ship`.
