### ISSUE TITLE
Sign-in button not updating to reflect signed-in state

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#1705]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
After I log in, the "Sign in with Google" button is still visible. I have to refresh the page to see my email address, it's settings menu, and the icons for notifications, LGTMs, and editing.

**To Reproduce**
1. Sign out of Chrome Status if you are not already.
2. Click "Sign in with Google". Notice that the UI does not change.
3. Refresh the page. Now the UI changes.

**Expected behavior**
The UI changes immediately after sign in.

**Comment by jpmedley** [comment]
cc: @jrobbins FYI

**Comment by jrobbins** [comment]
I have also noticed this once or twice.   We are planning on doing an upgrade to Google Identity Service this quarter, so we'll see if we can repro the problem with that library or not.

**Comment by jpmedley** [comment]
I was just looking for a PR, because this seems to be working today.

**Comment by KyleJu** [comment]
This should be fixed after the migration.
