### ISSUE TITLE
Tapping feature on Chrome mobile doesn't open it

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#171]
It quickly open and closes it.

**Comment by beaufortfrancois** [comment]
@ebidel I cannot reproduce the issue with Chrome for Android 39.0.2171.59 and Chrome for iOS 40.0.2214.61.

**Comment by ebidel** [comment]
Nor can I. Likely a Polymer bug that got fixed (or Chrome :))
