### ISSUE TITLE
"Intent to Ship LGTMs by" field shows validation error for multiple emails

### ISSUE THREAD

**Issue by scheib** [GoogleChrome/chromium-dashboard#1716]
When entering Intent to Ship LGTM details there is a field which requests "Comma separated list of full email addresses of API owners who LGTM'd the Intent to Ship email thread."  However, when multiple emails are entered an error is shown "Enter a valid email address."

Screenshot:

> ![image](https://user-images.githubusercontent.com/386971/152840827-ac9f6136-12a0-4ec9-b3fe-fc31d7e54e98.png)

**To Reproduce**
1. Enter a single email address into the "Intent to Ship LGTMs by" field.
2. Save, and go back to edit, notice that the email is accepted.
3. Complete entering the multiple LGTM emails, comma separated.
4. Save, and go back to edit, notice the error message, "Enter a valid email address."

**Expected behavior**
Comma separated emails are accepted without error.

**Comment by past** [comment]
Fixed by #1870 and also this field is deprecated now.
