### ISSUE TITLE
Stage Table Lacks Affordance for Extending an Origin Trial

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#1727]
**Is your feature request related to a problem? Please describe.**
I sometimes see [manually-drafted emails on blink-dev@](https://groups.google.com/a/chromium.org/g/blink-dev/c/wIYqo3F_Vmo/m/R6XjY4aBBgAJ) asking for the extension of an origin trial. There are fields for this in Chrome Status, but nothing that tells you this. You. need to click update on the origin trial row to see this fields. If you notice them when you requested the first origin trial, that was weeks or months ago, and you probably don't remember.

![image](https://user-images.githubusercontent.com/8204171/153052717-31d650a6-780a-4216-84bd-d1332dfbe802.png)

**Describe the solution you'd like**
Off the top of my head, I can think of two ways to do this. 

*Add a second draft link to the origin trial row*
This is probably the simplest to implement, but will not allow force or encourage users to update the appropriate fields.

*Add a new row titled 'Extended Origin Trial'*
This is harder to implement, but will probably produce more complete and reliable results.

**Additional context**
Not addressed is the issue of whether the extension of an origin trial should be reflected on the rendered feature card. It seems like this might require additional milestone fields.

**Comment by jpmedley** [comment]
The result of this is that old approval information is being overwritten. [Conditional Focus](https://chromestatus.com/feature/5646614535340032) shows an Intent to Experiment for an Intent to Extend Experiment. It renders this as the first experiment which was requested and approved within the last nine days.

![image](https://user-images.githubusercontent.com/8204171/153619511-71677553-bf9d-4c4b-90ed-3334b21857df.png)

However, this is not the original origin trial for this as the Origin Trial Dashboard shows.

![image](https://user-images.githubusercontent.com/8204171/153619686-dbe7d5bc-50c4-448b-a54a-8c36a3997985.png)

 cc: @jpchase

**Comment by DanielRyanSmith** [comment]
This issue can be closed now that the older feature detail table has been removed, and the OT process has been updated to allow for multiple stages. there is now a "Request trial extension" button next to all origin trials that have been created.
