### ISSUE TITLE
Features fail to load with IE's new UA string

### ISSUE THREAD

**Issue by jacobrossi** [GoogleChrome/chromium-dashboard#174]
For context, see our recent announcement about IE's new "living" Edge mode.  In this mode (currently available to a randomly selected set of Windows 10 Tech Preview users, or by opting in through about:flags "Enable Experimental Web Platform Features"), IE uses a new UA String that no longer includes the Trident token.

ChromeStatus.com is currently broken in edge (features fail to load). Changing the UA back to IE11's (but staying in edge mode) resolves the issue. The issue looks like its in Polymer. I've opened up a corresponding [issue](https://github.com/Polymer/webcomponentsjs/issues/51) on that repo, but wanted to file this here too for awareness.

**Comment by jacobrossi** [comment]
Any luck?

**Comment by ebidel** [comment]
Updated to latest polymer/wc. Can you give it a check?

**Comment by jacobrossi** [comment]
Looks like everything's working now. Thanks @ebidel!

**Comment by jacobrossi** [comment]
This seems to have regressed. :-/  Not sure what's up yet, I'll follow up with technical details.

**Comment by RByers** [comment]
Spent a bit of time on chromestatus.com from my Windows phone - everything seems to be behaving the same as Chrome to me.  @jacobrossi please re-open if you still see any issues.

**Comment by jacobrossi** [comment]
Ah yeah it's working now, meant to close this down. Thanks!
