### ISSUE TITLE
Missing I2S on chromestatus.com/myfeatures

### ISSUE THREAD

**Issue by miketaylr** [GoogleChrome/chromium-dashboard#1744]
https://groups.google.com/a/chromium.org/g/blink-dev/c/RY9leYMu5hI

Expected: it shows up
Actual: it doesn't

cc @jrobbins

**Comment by jrobbins** [comment]
Unfortunately I didn't look at the logs soon enough and now I can't get specific evidence of what happened.  But, I think that I have good guesses.

For the first one:
* It included a 486KB animated gif, but we skip processing any inbound email over 100KB.
* We should have some limit to protect against crashing in the case of a huge input.  But I think that we could increase it to say, 20MB.  That should be enough for this use case.

For the second one:
* It looks like the user used an older form of the intent template that had a different way of writing the heading for the link to the chromestatus entry.
* We can add another regex case to match that format.
