### ISSUE TITLE
Wrong HSTS support status for Safari

### ISSUE THREAD

**Issue by nextPrime** [GoogleChrome/chromium-dashboard#176]
According to Wikipedia and some other websites [1][2], Safari supports HTTP Strict Transport Security as of OS X Mavericks, so https://www.chromestatus.com/features/4941480133132288 needs to update.

[1] https://www.eff.org/deeplinks/2014/02/websites-hsts: "we noticed that Apple quietly added HSTS support to Safari in OS X 10.9."
 [2] https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security#Browser_compatibility

**Comment by beaufortfrancois** [comment]
Hey, you're absolutely right! 
https://hstspreload.appspot.com/ says `Firefox and Safari also have HSTS preload lists which include the Chrome list.`
And I can confirm the presence of `~/Libary/Cookies/HSTS.plist` file as well.

I've updated the HSTS feature at https://www.chromestatus.com/features#hsts.
![screenshot 2015-01-21 at 2 39 31 pm - display 2](https://cloud.githubusercontent.com/assets/634478/5837000/89e07d10-a17b-11e4-90c0-59296e8cd74a.png)
