### ISSUE TITLE
Input doubleclick selection. Symbol ":" is not a separator.

### ISSUE THREAD

**Issue by JVPhase** [GoogleChrome/chromium-dashboard#1767]
In Firefox I can select in string "foo:bar" only "foo" by doubleclick on it. But in Chrome it selects whole string.

 Chrome version 98.0.4758.102

**Comment by jpmedley** [comment]
Thank you for your submission. Unfortunately, this is not where you report Chrome bugs. This is where you report bugs with [Chrome Status](https://chromestatus.com). To report a Chrome bug got to [https://bugs.chromium.org](https://bugs.chromium.org).

Thank you

**Comment by art-frela** [comment]
done: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4047
