### ISSUE TITLE
Lists on /roadmap view should use case-insensitive sort

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#1774]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
Sometimes a feature entry has a title that begins with a language keyword (JS, CSS, etc.). Such words cannot be capitalized as required by the English rules for titles. The current title sorting on the [/roadmap view](https://chromestatus.com/roadmap) does not take this into account. Any feature with an uncapitalized title appears after features with capitalized titles. (Sorting appears to be by unicode value, rather than English letter value.)

**To Reproduce**
There is an example of this on the [/roadmap view](https://chromestatus.com/roadmap) at the time of writing. If an example is no longer visible, see the image below.

![image](https://user-images.githubusercontent.com/8204171/156825001-49370d49-63b5-40ca-b1ae-e42829574814.png)

**Expected behavior**
All features will be sorted by English letter regardless of whether that letter is upper case or lower case.

**Comment by Spectre-ak** [comment]
Hi, I've created a PR for this issue https://github.com/GoogleChrome/chromium-dashboard/pull/1809

**Comment by jrobbins** [comment]
Thanks again.  This has been live for a while.
