### ISSUE TITLE
[Process improvement]

### ISSUE THREAD

**Issue by chrishtr** [GoogleChrome/chromium-dashboard#1775]
Per API owners [resolution](https://groups.google.com/a/chromium.org/g/blink-api-owners-discuss/c/isF7o9q23IQ/m/aWAjcrO3BAAJ), please add the following question to the Intent to Ship required questions:

Does this intent deprecate or change behavior of existing APIs, such that it has potentially high risk for Android WebView-based applications? (See [here](https://new.chromium.org/developers/webview-changes/) for more a definition of "potentially high risk", information on why changes to this platform carry higher risk, and general rules of thumb for which changes have higher or lower risk) If so:
* Please use a base::Feature killswitch (examples [here](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/common/features.h)) that can be flipped off in case of compat issues
* Consider reaching out to [android-webview-dev@chromium.org](mailto:android-webview-dev@chromium.org) for advice
* If you're not sure, just put "not sure" as the answer here and the API owners can help during the intent-to-ship

**Comment by chrishtr** [comment]
Can this issue be closed now?

**Comment by jrobbins** [comment]
Yep, this is live.
