### ISSUE TITLE
Not able to screen share 

### ISSUE THREAD

**Issue by Daniella24** [GoogleChrome/chromium-dashboard#1776]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
The issue happens randomly. I have noticed it happens on Mac, not sure if it is a PC bug as well. After leaving my browser open for a day or so, I tried to share my screen on google meets and got the error "Can't share your screen" "An error has occurred". Permissions are on, everything is good.. The only way I can make it work is by quitting completely google chrome and restart it again every time I get the error. Happens on google meets and in other web platforms. 

**To Reproduce**
1. Leave your browser open for a day or so. Sometimes works, sometimes it doesn't.
2. Try to share your screen on google meets and you will get the error. 
Attaching the console errors screenshot.
 
![image (10)](https://user-images.githubusercontent.com/39418035/157067287-a437f21e-0614-4ec5-a383-ef9273599f19.png)

**Expected behavior**
I expect that when I click "Share screen" it doesn't give me any error and can screen-share without needing to quit/close my browser. 

**Additional context**

Seems the issue only happens when trying to screen-share "Entire screen".

**Comment by jrobbins** [comment]
Thanks for your report.  However, this sounds like a bug in the chrome browser rather than anything related to the chromestatus.com feature tracking tool.  Please file your issue at https://crbug.com/new.
