### ISSUE TITLE
403 for PushAPI Launch Bug

### ISSUE THREAD

**Issue by lholmquist** [GoogleChrome/chromium-dashboard#179]
clicking on the "launch bug" for the PushAPI, https://www.chromestatus.com/feature/5416033485586432, returns this,  Your client does not have permission to get URL /p/chromium/issues/detail?id=349474 from this server.

**Comment by ebidel** [comment]
@gauntface what's a better bug for the push api?

**Comment by gauntface** [comment]
Looks like this might be the better bug: https://code.google.com/p/chromium/issues/detail?id=350378

**Comment by ebidel** [comment]
Thanks. Fixed.

**Comment by lholmquist** [comment]
awesome, thanks
