### ISSUE TITLE
Running into out of memory issue when opening large pdf in Google Chrome browser(99.0.4844.51)

### ISSUE THREAD

**Issue by ThalapaneniSushma** [GoogleChrome/chromium-dashboard#1794]
Hi,

Actually in our web application we are using mozilla pdf.js plugin to view the pdf files and very recently we are facing an issue i.e. when we are trying to load a pdf which contains more than 25k pages with a size of 130MB (Note: We are streaming the pdf files), the browser is throwing out of memory issue in the Chrome browser, but in the Firefox browser its working fine i.e. able to load the 25k pages pdf file

**Note: In the month of January 2022, even in chrome browser it worked fine without any issues**

Please find the below screenshots for reference
![pdf-failed](https://user-images.githubusercontent.com/91343957/158455783-0edab5d5-e170-4d3b-bb33-d42bd4a1130e.PNG)
![pdf-failed-1](https://user-images.githubusercontent.com/91343957/158455789-6f091dd9-cc21-412c-9edf-140fda6a4810.PNG)

Please any suggestions/help would be appreciated as its the heart of our application.

Thank you.

**Comment by jrobbins** [comment]
Thank you for your submission. Unfortunately, this is not where you report Chrome bugs. This is where you report bugs with [Chrome Status](https://chromestatus.com/). To report a Chrome bug go to https://bugs.chromium.org/.

Thank you

**Comment by Sai2024-oss** [comment]
Hi all,

Is the above-mentioned "Not enough memory to open this page" & "Aw snap"  resolved? Can anyone please help me in resolving this issue? @ThalapaneniSushma @jrobbins 

Please suggest/help!
