### ISSUE TITLE
Icons not visible in some views

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#1802]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
In views smaller than desktop, I cannot see the action icons. 

![image](https://user-images.githubusercontent.com/8204171/159739487-9203e6f0-84ee-4e06-9e1c-f94918a9d6e3.png)

**To Reproduce**
1. Open the site.
2. Shrink the window. Eventually, the icons will cease to be visible.

![image](https://user-images.githubusercontent.com/8204171/159739921-f58b1990-2f3a-4e15-bdb2-b782f3fbc0ac.png)

**Expected behavior**
Icons should be visible at all times.

**Comment by Kunal0220** [comment]
Hey @jrobbins , I successfully managed to reproduced the bug and I think I can fix it , Can I give it a try ?

**Comment by jrobbins** [comment]
Go for it.

**Comment by Kunal0220** [comment]
👍🏻

**Comment by kevinshen56714** [comment]
Hi, I have created PR #1823 for this issue.
