### ISSUE TITLE
The old logo must be updated

### ISSUE THREAD

**Issue by ghost** [GoogleChrome/chromium-dashboard#1812]
**Describe the bug**
Starting at version 100 the Chrome browser had the logo changed to a new version with better colors. But the website "Chrome Platform Status" still displays the old logo.

**URL of the logo that should be updated to the new version:**
https://chromestatus.com/static/img/chrome_logo.svg

**Comment by kneerightful** [comment]
I just forked it, updated it to the new logo, the SVG file size has been greatly reduced as well.

**New logo url:**
https://github.com/kneerightful/chromium-dashboard/blob/main/static/img/chrome_logo.svg

**Comment by kneerightful** [comment]
Hey, @jpmedley

I updated it to the new logo, the SVG file size has also been greatly reduced.
Just replace the old logo with the new one in the /static/img/ folder.

**New logo url:**
https://raw.githubusercontent.com/kneerightful/files/main/chrome_logo.svg

**Comment by Kunal0220** [comment]
Hi @kneerightful ,I guess there is a small issue with running the project on the local system , Once it gets sorted , I will change the Old Logo with the New one and fix this issue.
Thank You :)

**Comment by jrobbins** [comment]
@Kunal0220, still interested in making this change?

**Comment by Kunal0220** [comment]
Would love to , can I go ahead?

**Comment by jrobbins** [comment]
Sure, this is still needed.
We should be using the logo that currently shows up on chrome.com:
https://www.google.com/chrome/static/images/chrome-logo-m100.svg

**Comment by KUNDAN1334** [comment]
i am intrested in this and want to change the  logo but  can you guide me in which file i have to make changes

**Comment by Prasun60** [comment]
Hi, I see this issue isn't closed yet. I am interested to solve this issue, can you tell me which file should I replace ( location of the old SVG), as I checked that the old svg (/statict/img/chrome_logo.svg) and the one you have provided here are the same.

**Comment by awanishyadav967** [comment]
> Sure, this is still needed. We should be using the logo that currently shows up on chrome.com: https://www.google.com/chrome/static/images/chrome-logo-m100.svg

Review my PR ,i added one

**Comment by Rishabh-mikku** [comment]
Hi, I have understood this issue completely and I am interested in this.

**Comment by Rishabh-mikku** [comment]
Can you please guide me in which file I have to make changes.

**Comment by zelfroster** [comment]
Hey @jrobbins, sorry to ping you.
I wanted to ask if this is issue is still open, and Can I work on it?

**Comment by aarishshahmohsin** [comment]
Is the issue still open, Can I work on it?

**Comment by Abhi-y2003** [comment]
Hey, If the issue is still not fixed, I would like to work on this.

**Comment by jrobbins** [comment]
This is done now.
