### ISSUE TITLE
Error when running npm run deps

### ISSUE THREAD

**Issue by MfenaKaase** [GoogleChrome/chromium-dashboard#1820]
### Description
i get this error ''source' is not recognized as an internal or external command, operable program or batch file.' when i run the command `npm run deps`

### See Error
![Screenshot (82)](https://user-images.githubusercontent.com/68476762/162326594-a9630eae-5905-4ef7-8a6b-090f75d56718.png)
 
### Other Info
I recently applied for the Google Summer of Code program. I would like to contribute to this project, how do I go about it any pointers as i write my proposal

**Comment by jrobbins** [comment]
We don't do any development on Windows, we use Unix instead.  `source` is a build-in command for the unix shell `bash`.

If you use Powershell, I think you could run cs-env/bin/activate.ps1, but that is just a guess.  If you are able to activate the virtual environment manually, then as long as you keep that shell window open, you could simply delete the `source` commands for each target in package.json.

However, given that we don't do development on Windows and have not tested anything on windows, you are likely to hit other  problems.  You might do better by installing a unix partition or using a cloud-based unix shell.
