### ISSUE TITLE
Update Intent email template

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#184]
Latest: https://docs.google.com/a/chromium.org/document/d/1vlTlsQKThwaX0-lj_iZbVTzyqY7LioqERU8DK3u3XjI/edit

**Comment by ebidel** [comment]
@beaufortfrancois do you want to take this one?

**Comment by beaufortfrancois** [comment]
Just submitted a PR https://github.com/GoogleChrome/chromium-dashboard/pull/189
