### ISSUE TITLE
Update "Blink components" list

### ISSUE THREAD

**Issue by michaelwasserman** [GoogleChrome/chromium-dashboard#1872]
**Describe the bug**
I'm trying to assign a chromestatus feature to a Blink component that was recently-added in crbug, but it's not listed.

**To Reproduce**
1. Go to https://chromestatus.com/guide/editall/5252960583942144
2. Click on the 'Blink component' dropdown
3. Look for 'Blink>Screen' or 'Blink>Screen>MultiScreen'
4. Observe that no such components are listed, but it is on https://bugs.chromium.org/p/chromium/adminComponents

**Expected behavior**
Expect chromestatus component list to match that of crbug.com

**Additional context**
These components were created recently (~1-2 months ago?)

**Comment by jrobbins** [comment]
This is live now.
