### ISSUE TITLE
run google-chrome --no-sandbox , black page

### ISSUE THREAD

**Issue by bobwatcherx** [GoogleChrome/chromium-dashboard#1876]
i using arch linux , but ubuntu also have problme like this

in root , i using command  = **google-chrome --no-sandbox**  or **chromium --no-sandbox**
and window is open but black screen like this

![tolol](https://user-images.githubusercontent.com/52072811/167262211-7c79dcba-cc63-4b00-8637-822780c2c1df.png)

wtahs the solutions,
i want to run flutter using chrome , but not work
 thanks ,

**Comment by jrobbins** [comment]
Thanks for your report. However, this sounds like a bug in the chrome browser rather than anything related to the chromestatus.com feature tracking tool. Please file your issue at https://crbug.com/new.
