### ISSUE TITLE
Disable the side limit of flotating media player (like Youtube)

### ISSUE THREAD

**Issue by jefer94** [GoogleChrome/chromium-dashboard#1882]
![image](https://user-images.githubusercontent.com/3018142/167747181-12eb453c-7cbb-4cd2-bde7-fb30479d8624.png)

**Comment by jrobbins** [comment]
Thanks for your report. However, this sounds like a bug in the chrome browser rather than anything related to the chromestatus.com feature tracking tool. Please file your issue at https://crbug.com/new.

**Comment by jefer94** [comment]
🤷‍♂️
![image](https://user-images.githubusercontent.com/3018142/167748596-a0cc6ee2-1a56-4af4-96bc-1eac1582a19c.png)
