### ISSUE TITLE
Error 500 when posting an issue

### ISSUE THREAD

**Issue by zetafunction** [GoogleChrome/chromium-dashboard#190]
I've been trying to create a new intent, and I always get a HTTP 500 when clicking "Submit".

I've been told that having a newline in the description will do this, but as far as I can tell, I don't? Maybe we could make the error messages a little better?

**Comment by ebidel** [comment]
Server says "Property comments is 511 characters long; it must be 500 or less.". We need some error handling :)

@beaufortfrancois interested?
