### ISSUE TITLE
Re-establish access to feature popularity endpoint

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/chromium-dashboard#1912]
A recent [commit](https://github.com/GoogleChrome/chromium-dashboard/commit/c570bfbe474de37d501b3033ce772f09894810ff) by @KyleJu removed CORS. I'm aware of several folks who consume feature popularity JSON from URLs like [this](https://chromestatus.com/data/timeline/featurepopularity?bucket_id=990). Could you consider reestablishing CORS? This was also noted by a couple of folks on https://github.com/GoogleChrome/chromium-dashboard/issues/1646.

**Comment by KyleJu** [comment]
We have a plan to re-establish for the following endpoints /features.json, /features_v2.json, /data/timeline/*, /data/csspopularity/*,  /data/csspopularity/*, and /data/featurepopularity/*, features.xml path.

**Comment by tomayac** [comment]
@KyleJu, an app of mine would need access to `https://chromestatus.com/metrics/feature/timeline/popularity/*`. Could you enable this path, too?

**Comment by tomayac** [comment]
Oh, sorry, it turns out I don't need `/metrics/*`, but URLs like `https://chromestatus.com/data/timeline/featurepopularity?bucket_id=1501`. Unfortunately it still fails:

<img width="634" alt="Screen Shot 2022-06-15 at 21 12 34" src="https://user-images.githubusercontent.com/145676/173918412-4ba6d493-0857-4fae-9bd6-38bf0dc67d7a.png">

**Comment by KyleJu** [comment]
> Oh, sorry, it turns out I don't need `/metrics/*`, but URLs like `https://chromestatus.com/data/timeline/featurepopularity?bucket_id=1501`. Unfortunately it still fails:
> 
> <img alt="Screen Shot 2022-06-15 at 21 12 34" width="634" src="https://user-images.githubusercontent.com/145676/173918412-4ba6d493-0857-4fae-9bd6-38bf0dc67d7a.png">

CORS should be enabled in the next prod push!

**Comment by tomayac** [comment]
And double-sorry, just re-read https://github.com/GoogleChrome/chromium-dashboard/issues/1912#issuecomment-1143975097 and opened https://github.com/GoogleChrome/chromium-dashboard/issues/1938.

**Comment by tomayac** [comment]
Wait, so it will be allowed for `*`, not individual origins as outlined in https://github.com/GoogleChrome/chromium-dashboard/issues/1912#issuecomment-1143975097? In this case, consider https://github.com/GoogleChrome/chromium-dashboard/issues/1938 done.

**Comment by jrobbins** [comment]
Our deployment is blocked on an unrelated problem, but I hope to get a fix for that one in the works today so that we can deploy tomorrow or Friday.

**Comment by jrobbins** [comment]
> Wait, so it will be allowed for `*`, not individual origins as outlined in [#1912 (comment)](https://github.com/GoogleChrome/chromium-dashboard/issues/1912#issuecomment-1143975097)? In this case, consider #1938 done.

My understanding of the security concern for using `Access-Control-Allow-Origin: '*'` is that it can leak personal info whenever it is used on requests that give a personalized response, e.g., showing the list of features that the current user has starred or the results of a query like `owner:me`.   The metrics data that is located at the `/data/...` URLs is never personalized and we have no plans to make it personalized, so it seems safe to use `*` there.

**Comment by tomayac** [comment]
Correct! @jakearchibald has wonderfully summarized this in a [blog post](https://jakearchibald.com/2021/cors/#is-it-safe-to-expose-resources-via-cors).

**Comment by jrobbins** [comment]
https://github.com/GoogleChrome/chromium-dashboard/pull/1922 was deployed today.  Please give it a try.

**Comment by tomayac** [comment]
Confirmed to be working again. Thanks a lot!
