### ISSUE TITLE
Very important feature suggestion that will make google chrome better for everyone.

### ISSUE THREAD

**Issue by FrancoFrancis** [GoogleChrome/chromium-dashboard#1935]
I am a web developer I get really pissed when I end up with too many open **tabs** in my browser.

It would be amazing to be able to mark several open **tabs** and close them at once, instead of having to click and close tabs one at a time.

**Comment by FrancoFrancis** [comment]
hello everyone

**Comment by jrobbins** [comment]
This is the same as
https://github.com/GoogleChrome/chromium-dashboard/issues/1946
