### ISSUE TITLE
Build failed on Mac osx 

### ISSUE THREAD

**Issue by sajadgoudarzi** [GoogleChrome/chromium-dashboard#1947]
Hello There, 

I have updated my OSX to Monterey (12.4), but I cannot build the Chromium Source code. 
I get this error  

`../../content/browser/media/capture/screen_capture_kit_device_mac.mm:7:9: fatal error: 'ScreenCaptureKit/ScreenCaptureKit.h' file not found
#import <ScreenCaptureKit/ScreenCaptureKit.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[2151/19403] CXX obj/content/browser/browser/pepper_player_delegate.o
ninja: build stopped: subcommand failed.
`

I was wondering if any one could let help me. 

Bests

**Comment by jrobbins** [comment]
Thanks for raising this issue.  However, this is the wrong place for it.  This issue tracker is only for problems with the chromestatus.com website.

Your issue would probably be better discussed on the chromium-dev mailing list, or one of the other mailing lists listed on this page: https://www.chromium.org/developers/technical-discussion-groups/
