### ISSUE TITLE
Overflow issues on iOS Safari/Chrome for iOS

### ISSUE THREAD

**Issue by beriberikix** [GoogleChrome/chromium-dashboard#199]
iOS 8.3/Cr41.0.2272.58

![2015-04-10](https://cloud.githubusercontent.com/assets/178376/7100039/b1bceefa-dfbe-11e4-8cf9-43ecd02baf31.jpg)

**Comment by tagawa** [comment]
Same in Firefox 38 on Android and stock browser (Android 4.4.4).

**Comment by simevidas** [comment]
Use `word-wrap: break-word`?

**Comment by tagawa** [comment]
Maybe @paulirish knows who we should alert about this?

**Comment by PaulKinlan** [comment]
@ebidel is the man. I suspect america has been ooo this past weekend.
