### ISSUE TITLE
Spec link should not be an I2P email prerequisite

### ISSUE THREAD

**Issue by miketaylr** [GoogleChrome/chromium-dashboard#2000]
This report is pulled from some feedback on https://groups.google.com/a/chromium.org/g/blink-api-owners-discuss/c/08cT0FTh6yY/m/9Rr9tfBwBAAJ

https://www.chromium.org/blink/launching-features/#step-2-prototyping states:

> During this stage, you should expand on the explainer with a full design doc (this may also have implementation-specific details), and consider creating a specification (or writing up a pull request with changes to an existing spec).

This work will happen _after_ sending the I2P email; we shouldn't consider it a prerequisite.

![6YAwtVvYnaQcTmw](https://user-images.githubusercontent.com/67283/177605015-e8539cec-aa7b-46a2-856c-9ce907b01b7c.png)

**Comment by jpmedley** [comment]
@dlaliberte I consulted the launch process and found that it's actually the [the explainer that's a prerequisite](https://www.chromium.org/blink/launching-features/#:~:text=Start%20sketching%20out%20a%20proposed%20solution%20in%20your%20(public)%20explainer%2C%20detailing%20API%20design%20(IDL)%20in%20your%20incubation.) to sending the I2P email.

**Comment by dlaliberte** [comment]
From what I can see in processes.py, the 'Draft Intent to Prototype email' action seems to be a copy of the same list as for 'Draft Ready for Trial email', which includes both the Explainer and Spec link.  I'll make a change to remove the Spec link for the Prototype email.
