### ISSUE TITLE
Rendering of help text has no styling

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#2013]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
Help text contains HTML elements that are not styled. The HTML sent down the client looks like this:

![image](https://user-images.githubusercontent.com/8204171/178351520-1bed159f-6700-4b00-9984-2a7a3057fbcb.png)

But renders like this: 

![image](https://user-images.githubusercontent.com/8204171/178351707-d34d576c-0d2d-4e32-acc0-3e8e5fee82a6.png)

Looking at the styles pane in DevTools, I see that `list-style` has been set to `none` globally, with no override for `.helptext`.

![image](https://user-images.githubusercontent.com/8204171/178351982-93ca74e3-aafb-458b-8668-917883ff08b0.png)

**Comment by jpmedley** [comment]
I haven't figured out yet if this is particular to lists or general to styling.

**Comment by jrobbins** [comment]
`list-style:none` is set in shared-css.js, so it applies to the whole app currently.

I can see it making sense to have list bullets in help text, however the width available for the initial part of the help is pretty narrow, so the bullets would need to be fairly condensed.  And, we'd need to check to make sure that line wraps look good.

**Comment by jpmedley** [comment]
I'm aware of those concerns. I don't need formatting for many things, but sometimes I do.

**Comment by jrobbins** [comment]
This problem got resolved.  I see the bullet items in the help for that form field now.
