### ISSUE TITLE
In feature change notifications, set reply-to to the user who made the change

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2020]
**Describe the solution you'd like**
In feature change notifications, set reply-to to the user who made the change.
This will make it easier for interested parties to follow up with the person who made the change.

Only do this for users who could can comment, because other people on the internet who star a feature might not have the same expectations about when it is appropriate to contact the person who made the edit.  They can certainly still do that since that address is in the body of the email.  We just don't want them sending "unsubscribe", vacation, or other off-topic replies to the person who made the change.

**Comment by jpmedley** [comment]
Can the reply show the replier's show the repliers access level. Maybe do something like: "Site editor jmedley@google.com replied to your update."

I'm not in love with that language or what it implies about how this would work. I'm trying to convey that the response should give the feature owner some context about the reply. If I request a change and the recipient of my request knows I'm a site editor, they automatically know that I'm empowered to make requests like that.

**Comment by jrobbins** [comment]
Well, the reply is just a regular email message that you compose yourself.  You could identify yourself as a "site editor" in the body of the message.  There is no email header that the app can set that would control the attribution in a reply that you write.

**Comment by jrobbins** [comment]
This is live now.
