### ISSUE TITLE
Replace django templates for email with jinja2 templates

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2030]
We currently use two python web app frameworks (django and flask) and we are trying to use just flask.   We'd like to phase out our use of django, including where it is used to generate the body of email messages.

While it would be tempting to get really simple by using python formatted string literals like `f'Hello {name}'`, we must follow a security guideline of automatically escaping all user-controlled values.

Flask includes jinja2 templates, which are similar to django templates.  So, maybe what we could do is convert the existing django template to jinja2 templates and change from django's `render_to_string(path, data)` to `flask.render_template(path, **data)`.

We would need to upgrade the email templates from the django template syntax to the jinja2 syntax: `templates/*-email.html` and `templates/estimated-milestones-table.html`.

There should be no user-visible impact of this change.  It is a project health issue to reduce our excessive library dependencies.

**Comment by Rbcoder1** [comment]
**i would like to solve this issue. please give me the task**

**Comment by Rbcoder1** [comment]
> We currently use two python web app frameworks (django and flask) and we are trying to use just flask. We'd like to phase out our use of django, including where it is used to generate the body of email messages.
> 
> While it would be tempting to get really simple by using python formatted string literals like `f'Hello {name}'`, we must follow a security guideline of automatically escaping all user-controlled values.
> 
> Flask includes jinja2 templates, which are similar to django templates. So, maybe what we could do is convert the existing django template to jinja2 templates and change from django's `render_to_string(path, data)` to `flask.render_template(path, **data)`.
> 
> We would need to upgrade the email templates from the django template syntax to the jinja2 syntax: `templates/*-email.html` and `templates/estimated-milestones-table.html`.
> 
> There should be no user-visible impact of this change. It is a project health issue to reduce our excessive library dependencies.

**I would like to solved this problem. please assign it to me**

**Comment by jrobbins** [comment]
OK Rohit, go for it. 
I look forward to your pull request.
Let me know if you have any questions.

**Comment by jrobbins** [comment]
@Rbcoder1 any progress on this?
