### ISSUE TITLE
Add a MDN reference link to each feature with a MDN doc that exist

### ISSUE THREAD

**Issue by eorroe** [GoogleChrome/chromium-dashboard#204]
Title says it all.

**Comment by ebidel** [comment]
If you have a list of specific features with relevant links, that would be very helpful.

**Comment by jeffposnick** [comment]
My understanding is that the docs team on the Chrome side of things is currently prioritizing adding docs to MDN if they don't already exist when a new web platform features is implemented in Chrome.

So, in practice, the docs links for new features moving forward will tend to be MDN links. That's not backfilled, though.

CC: @jpmedley

**Comment by eorroe** [comment]
### CHROME 44

Document.scrollingElement: https://developer.mozilla.org/en-US/docs/Web/API/document/scrollingElement

### CHROME 43

Cache API (global scope): https://developer.mozilla.org/en-US/docs/Web/API/Cache

Permissions API: https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API

### CHROME 42

Classes (ES6): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

Fetch API: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

Push API: https://developer.mozilla.org/en-US/docs/Web/API/Simple_Push_API

### CHROME 41

'any-pointer' and 'any-hover' Media Queries: [https://developer.mozilla.org/en-US/docs/Web/CSS/@media/any-pointer, https://developer.mozilla.org/en-US/docs/Web/CSS/@media/any-hover]

Blending of HTML and SVG elements: https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode

Template Strings (ES6): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings

WebAudio: StereoPannerNode: https://developer.mozilla.org/en-US/docs/Web/API/StereoPannerNode

image-rendering: pixelated: https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering

### CHROME 40

Service Worker: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker_API/Using_Service_Workers

minlength attribute: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-minlength, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attr-minlength]

reportValidity() for form controls: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reportValidity

### CHROME 39

Beacon: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon

Generators (ES6): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator

Web Application Manifest: https://developer.mozilla.org/en-US/Apps/Build/Manifest

### CHROME 38

<picture> Element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

Battery Status API: https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API

Encoding API: https://developer.mozilla.org/en-US/docs/Web/API/Encoding_API

File Constructor: https://developer.mozilla.org/en-US/docs/Web/API/File

JS iterators (i.e. the for-of feature) (ES6): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

Map (ES6): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

Math functions (ES6): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math#Methods

Screen Orientation API: https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation

Set (ES6): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

Symbols (ES6): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

### CHROME 37

"all" CSS shorthand: https://developer.mozilla.org/en-US/docs/Web/CSS/all

<dialog> Element: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement

CSS Shapes Module Level 1: https://developer.mozilla.org/en-US/docs/Web/CSS/shape

NavigatorLanguage: navigator.languages and languagechange event: https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages

Web Crypto API: https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API

### CHROME 36

CSS touch-action: https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

CSS will-change: https://developer.mozilla.org/en-US/docs/Web/CSS/will-change

HTML Imports: https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports

Object.observe(): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe

Unprefixed CSS Transforms: https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Using_CSS_transforms

WeakMap (ES6): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

WeakSet (ES6): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet

### CHROME 35

Blending of background images: https://developer.mozilla.org/en-US/docs/Web/CSS/background-blend-mode

Shadow DOM: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM

Unprefixed Web Audio API: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_Web_Audio_API

### CHROME 34

<img srcset>: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset

font-variant-ligatures: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures

### CHROME 33

Custom Elements: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements

Page Visibility API: https://developer.mozilla.org/en-US/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API

font-kerning: https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning

### CHROME 32

Promises (ES6): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

URL: https://developer.mozilla.org/en-US/docs/Web/API/URL

Vibration API: https://developer.mozilla.org/en-US/docs/Web/Guide/API/Vibration

### CHROME 31

Canvas Focus Ring: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Hit_regions_and_accessibility#Focus_rings

DOM3 Wheel Events: https://developer.mozilla.org/en-US/docs/Web/Events/wheel

Device Motion: https://developer.mozilla.org/en-US/docs/Web/API/Detecting_device_orientation

devicePixelRatio on zoom: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

object-fit and object-position: [https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit, https://developer.mozilla.org/en-US/docs/Web/CSS/object-position]

### CHROME 30

DOM3 mouseenter & mouseleave Events: [https://developer.mozilla.org/en-US/docs/Web/Events/mouseenter, https://developer.mozilla.org/en-US/docs/Web/Events/mouseleave]

### CHROME 29

Media Queries: resolution feature: https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Media_queries#resolution

### CHROME 28

Conditional Rules: https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports

### CHROME 26

<template> element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

### CHROME 25

Gradients: https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Using_CSS_gradients

### CHROME 24

performance.now(): https://developer.mozilla.org/en-US/docs/Web/API/Performance/now

requestAnimationFrame(): https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

### CHROME 23

Media Source Extensions: https://developer.mozilla.org/en-US/docs/Web/API/MediaSource

Pointer Lock(Mouse Lock): https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API

Track Element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track

WebRTC: https://developer.mozilla.org/en-US/docs/Web/Guide/API/WebRTC

Position Sticky: https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning

### CHROME 21

Flexbox: https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Flexible_boxes

getUserMedia: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia

### CHROME 20

<datalist> element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

Blob: https://developer.mozilla.org/en-US/docs/Web/API/Blob

iframe[seamless] attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-seamless

iframe[srcdoc] attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-srcdoc

### CHROME 19

CSS calc(): https://developer.mozilla.org/en-US/docs/Web/CSS/calc

Filters: https://developer.mozilla.org/en-US/docs/Web/CSS/filter

iframe[sandbox] attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox

### CHROME 18

Block Bindings: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function]

GamePad API: https://developer.mozilla.org/en-US/docs/Web/Guide/API/Gamepad

Mutation Observers: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

Proxies (ES6): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

Touch Events: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events

### CHROME 15

Fullscreen API: https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Using_full_screen_mode

### CHROME 14

a[download] attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download

### CHROME 13

File System API (Chromium): https://developer.mozilla.org/en-US/docs/Web/API/FileSystem

Navigation Timing API: https://developer.mozilla.org/en-US/docs/Navigation_timing

Typed Arrays: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays

### CHROME 12

<details>/<summary>: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary]

### CHROME 11

IndexedDB: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB

### CHROME 10

Form Validation: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms/Data_form_validation

### CHROME 9

WebGL: https://developer.mozilla.org/en-US/docs/Web/WebGL

matchMedia: https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Testing_media_queries

### CHROME 7

Device Orientation: https://developer.mozilla.org/en-US/docs/Web/API/Detecting_device_orientation

FileReader: https://developer.mozilla.org/en-US/docs/Web/API/FileReader

### CHROME 6

Application Cache: https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

EventSource: https://developer.mozilla.org/en-US/docs/Web/API/EventSource

### CHROME 5

Geolocation: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

Web Notifications: https://developer.mozilla.org/en-US/docs/Web/API/Notification/Using_Web_Notifications

Web Storage: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

### CHROME 4

WebSocket: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

### CHROME 2

Message Channel: https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel

### CHROME 1

Canvas: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial

Masks: https://developer.mozilla.org/en-US/docs/Web/CSS/mask

postMessage: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

Compositing and Blending in Canvas 2D: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Compositing

ImageData: https://developer.mozilla.org/en-US/docs/Web/API/ImageData

font-size-adjust: https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust

**Comment by ebidel** [comment]
Solid. Thank you for looking this up!

**Comment by eorroe** [comment]
I just realized I miss the features that are not out, like under development, proposed, and no active development. But I guess by the time the chrome team implements them you'll be able to add them. If anything let me know I'll finish it off, but it's night night for me.

**Comment by jeffposnick** [comment]
That was super-helpful, @eorroe. Thanks again for looking those up!

I and @jpmedley have backfilled the corresponding chromestatus.com entries going back to Chrome 1.

**Comment by eorroe** [comment]
@jeffposnick You're welcome, tweet me at: **16JSDev** if you need any other favor. (don't worry you won't be bothered with crap, it's a programming only twitter)

**Comment by eorroe** [comment]
Default Parameters: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

Destructuring: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

Reflect: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect

**Change**
ES6 Array methods: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype#Methods

**Comment by myakura** [comment]
@eorroe thanks! updated.
FYI, if you cannot wait someone to update, you can request edit access via the link at the bottom of https://www.chromestatus.com/features ;-)

**Comment by eorroe** [comment]
@myakura cool thanks just did.
