### ISSUE TITLE
Create a date range filter.

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/chromium-dashboard#205]
Developers are reporting that it is hard to workout what is new between two dates, i,e what landed in the last 6 months.  We let developers see what landed in a version of Chrome, but it doesn't make it clear when that was launched.

**Comment by ebidel** [comment]
This one gets a bit tricky b/c the dashboard shows more than just landed. It shows deprecated, in dev, propsed, etc. We'd have to be clear what this filter was for or figure out the UX to make it work across impl status types.

**Comment by jrobbins** [comment]
Closing as done.  I think this need is well-addressed by the roadmap page that is the site's current home page.  Also, our current search box allows for inequalities on fields like the shipping milestone.
