### ISSUE TITLE
Hard to deeplink into a Chrome version, also it is not discoverable via search

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/chromium-dashboard#206]
It is very hard to quickly get to what was in a version of Chrome.  You can create a filter for a version https://www.chromestatus.com/features#=43, however it is not discoverable.

Developers would like a single URL that they could visit that tells them what was in a version of Chrome and this URL would also be used for search engine discovery (i.e, when a user types 'what is in Chrome 42').

We could ideally also have an XML feed per version of Chrome stable, beta, dev.

**Comment by RByers** [comment]
Agreed.  Perhaps it should also be easy to link into "what's new in Chrome 43" separately from "what's removed in Chrome 43"?

**Comment by RByers** [comment]
@ebidel says the search syntax is pretty rich but non-discoverable.  He suggests adding some UI elements to pre-populate the search, eg. "new in Chrome <verison>".  I'm not sure what exactly we'd want the UX to look like here, maybe similar to https://status.modern.ie?  @drufball thoughts?

**Comment by jpchase** [comment]
In investigating #299, I noticed that the current deep link doesn't work properly for versions without any features (e.g. https://www.chromestatus.com/features#=17). In that case, the page just shows "loading" permanently. If you manually filter on the page (enter "=17" in the search box), the page more expectedly shows no results.

Whatever changes happen here, should make sure to better handle the case of a version with no features.

**Comment by ebidel** [comment]
Here are examples of the query language (they're under the "?" icon):

![screen shot 2016-07-13 at 10 40 04 am](https://cloud.githubusercontent.com/assets/238208/16813442/545c727a-48e6-11e6-800f-ff786b3f0282.png)

**Comment by NavidZ** [comment]
ebidel@ but it doesn't seem that we can merge these conditions as far as I found for the regex checks in the code. Right?

**Comment by ebidel** [comment]
Yea, fairly trivial atm but gets answers to most of the interesting questions they will have.

**Comment by NavidZ** [comment]
So basically with the current way there is no query to answer this question "what's new in Chrome 43" separately from "what's removed in Chrome 43"?
Maybe I can start with what Jason reported about the versions (or any criteria) that don't have any feature. Do you want me to file another issue particularly for that or just send a PR for it?

**Comment by ebidel** [comment]
Right. "= 43" would give you "changes in chrome 43", but there's no way to go finer grained than that. A bug doesn't hurt to document the work and let others know you're working on it :)
