### ISSUE TITLE
Add a user preference to opt out of notifications when marked as editor

### ISSUE THREAD

**Issue by DanielRyanSmith** [GoogleChrome/chromium-dashboard#2070]
from @jrobbins:
> We should consider adding a user preference notify_as_editor that users could uncheck if they don't want notifications for that reason.

This would allow users to opt out of receiving notification emails whenever a feature is changed, even if they are listed as a feature editor.

**Comment by jpmedley** [comment]
Do we think feature updates are going to be spammy? Edits would have to come from a feature owner or a site editor. I wouldn't think we'd want anyone opting out of those notifications.

**Comment by jrobbins** [comment]
I was speculating that this setting would be useful for people who are listed as feature editors on a whole lot of different features.  However, there might not be any such users.  So, let's defer this.  I'll close this issue for now.  If there is a demonstrated user need, we can always reopen it.
