### ISSUE TITLE
Filtering problem (picture says it all)

### ISSUE THREAD

**Issue by eorroe** [GoogleChrome/chromium-dashboard#208]
![pic](https://cloud.githubusercontent.com/assets/6982605/7735148/4dd9efd6-ff09-11e4-8cae-41b5dd85d7cf.png)

**Comment by jpmedley** [comment]
This has been fixed:

![image](https://user-images.githubusercontent.com/8204171/108294137-1fcd5100-714a-11eb-86a4-3b6cb80c7774.png)
