### ISSUE TITLE
framework/ramcache.py has not worked well, replace it with GAE legacy bundle memcache

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2085]
**Describe the bug**
User-visible latency on chromestatus.com is inconsistent with some fast response and other slow responses for the same page.   The reason is that our ramcache.py implements a cache that is too often empty and too frequently completely invalidated.  These cache misses cause slow page loads.  

Cache misses happen when new GAE instances spun up, or after any user with write access updates any feature.  
* When a new GAE instance is started, it starts with an empty cache, so it is slow to respond to its first request.  That is a problem because GAE auto-scaling will automatically add more instances when responses are slow, but those new instances are also slow, potentially causing GAE to add even more instances. 
* Our cache invalidation is too simple.  Whenever anyone writes anything to datastore, we invalidate the entire distributed ramcache.  Since the site is more actively used now, the slow-downs from these heavy-handed invalidations happen frequently enough that they give a bad impression to users.

I implemented ramcache.py because it did not look like we had memcache available to us in python 3.  However, it is now available as part of the GAE legacy bundled services (which we already use for email).  
https://cloud.google.com/appengine/docs/legacy/standard/python/refdocs/google.appengine.api.memcache 

**Additional context**
One concern about using any caching service is cache schema evolution:  If we change the expected format of data in the cache, and then deploy that new version of our app, there could be existing data in the cache that would cause an error.  A simple way to avoid this is to include the app version string in our cache keys.  

Also, one of our main uses of caching is to have faster access to entities that we retrieve from NDB.  But, NDB has some kind of global cache that can be configured, including an implementation that uses memcache. 
https://googleapis.dev/python/python-ndb/latest/global_cache.html
Please check if this can be set to work automatically, allowing us to eliminate some cache checking and setting code.

If this all works as expected, we should see a decrease in our 90th and 99th percentiles on our latency graph.  And, users should field that the app is more consistently fast rather than sometimes fast and sometimes slow.

**Comment by KyleJu** [comment]
Had an offline discussion with [jcscottiii](https://github.com/jcscottiii). Memcache is a legacy bundled service that is supported in python3 runtime.  While it is supported, `legacy` might imply that GCP might retire it at some point in the future. 

Also, NDB's global cache also includes an implementation of Redis cache, https://googleapis.dev/python/python-ndb/latest/global_cache.html#google.cloud.ndb.global_cache.RedisCache. From the maintenance standpoint, we would like to keep the tech stack consistent across products in this team. wpt.fyi has already migrated to Redis and it would make more sense to adopt Redis in webstatus as well.

Let me try the Redis setup and see if I can get it to work
