### ISSUE TITLE
Add MDN source to DOM3 KeyboardEvent |code| attribute

### ISSUE THREAD

**Issue by eorroe** [GoogleChrome/chromium-dashboard#210]
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

**Comment by myakura** [comment]
updated. https://www.chromestatus.com/feature/5228092293382144

**Comment by ebidel** [comment]
Thanks!

**Comment by eorroe** [comment]
My bad @ebidel I should probably should of added it to the list I made before, if anything MDN link wise comes up I'll just comment on there.
