### ISSUE TITLE
CORS doesn't show why it fails

### ISSUE THREAD

**Issue by Rashad-j** [GoogleChrome/chromium-dashboard#2109]
**Describe the bug**
Chrome reports there is a CORS problem even though the OPTIONS request return the correct origin. After debugging we found that some headers were sent with a typo, we have special headers sent. It could be helpful for developers that chrome shows the CORS occurred because the headers are not allowed.

**To Reproduce**
1. Make a request that needs OPTIONS preflight request
2. Make sure you send some random headers with typos
3. You will see just a CORS error on console without a hint that it lies in headers

**Expected behavior**
At least show in console the reason why CORS failed

**Comment by jrobbins** [comment]
Thank you for your submission. Unfortunately, this is not where you report Chrome bugs. This is where you report bugs with [Chrome Status](https://chromestatus.com/). To report a Chrome bug go to https://bugs.chromium.org/.

Thank you
