### ISSUE TITLE
Credential Management spec has moved

### ISSUE THREAD

**Issue by tbroyer** [GoogleChrome/chromium-dashboard#211]
The dashboard links to http://projects.mikewest.org/credentialmanagement/spec/ which normally redirects to https://mikewest.github.io/credentialmanagement/spec/ except if you previously went to https://mikewest.org in which case you'd have a TLS error: mikewest.org sets up HSTS with `includeSubDomains`, and https://projects.mikewest.org does not have a valid certificate.

/cc @mikewest

**Comment by ebidel** [comment]
Feature link?

**Comment by tbroyer** [comment]
Oops, sorry! Here it is: https://www.chromestatus.com/feature/5026422640869376

**Comment by ebidel** [comment]
Fixed!

**Comment by mikewest** [comment]
Thanks! Sorry about the breakage. :(
