### ISSUE TITLE
Timeline data is empty and shows a range of 1970 to 1970

### ISSUE THREAD

**Issue by progers** [GoogleChrome/chromium-dashboard#2122]
**Describe the bug**
Timeline data is empty and shows a range of 1970 to 1970.

**To Reproduce**
1. Go to https://chromestatus.com/metrics/feature/timeline/popularity/3867
2. Notice the timeline graph is empty and shows a range of 1970 to 1970

**Comment by jrobbins** [comment]
I believe the problem was caused by a recent change that I made that indirectly changed the date format used in our JSON API.
I have a fix and I am deploying it now.

**Comment by jrobbins** [comment]
The fix is live.  The timeline charts are showing again.

I am keeping this issue open while I work on a better fix.

**Comment by jrobbins** [comment]
This went live back in August.
