### ISSUE TITLE
Phase out core_enums.STANDARD_MATURITY_BACKFILL

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2135]
**Describe the bug**
When we added the `standard_maturity` field, we did not migrate values from the old `standardization` field.  That work still needs to be done so that we can phase out some python code and drop the `standardization` field when we migrate to using the new feature models.

**Plan**
* Write a cron task to copy data from the `standardization` field to the `standard_maturity` field using `core_enums.STANDARD_MATURITY_BACKFILL` as the value mapping.
* Deploy and run that task on staging and prod
* Delete `STANDARD_MATURITY_BACKFILL` and the logic that references it from `format_for_template()`
* Delete the copying code

**Comment by DanielRyanSmith** [comment]
All existing features have had their `standard_maturity` fields backfilled 👍
