### ISSUE TITLE
Deleting a feature raises 404

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/chromium-dashboard#214]
Will investigate more...

**Comment by beaufortfrancois** [comment]
@ebidel Let me know if that's ok with you.

**Comment by beaufortfrancois** [comment]
This is addressed in #215. @ebidel Can we push it to live server?

**Comment by ebidel** [comment]
Meant to do that yesterday! Should be deployed now.

**Comment by beaufortfrancois** [comment]
Perfect. Thanks!
