### ISSUE TITLE
Create /samples page

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/chromium-dashboard#216]
Forked off from https://github.com/GoogleChrome/samples/issues/37

It would give developers a browsable/searchable page that provides links to all the samples associated with features, and ways of aggregating them based on the existing tags/Chrome milestone metadata already stored in the backend.

It might also be a chance to start using Polymer 1.0 on the site, since it would theoretically be new development rather than reusing the existing templates.

CC: @gauntface @beaufortfrancois @PaulKinlan

**Comment by beaufortfrancois** [comment]
I'm looking forward for this. Please feel free to cc me for review there.

**Comment by jeffposnick** [comment]
@ebidel released https://www.chromestatus.com/samples
