### ISSUE TITLE
canvas.captureStream() is capturing blank stream on certain canvas size when changing canvas size dynamically.(windows 10))

### ISSUE THREAD

**Issue by AnujRathore-Mint** [GoogleChrome/chromium-dashboard#2162]
i am making a whiteboard using canvas and capturing its stream and sending it to remote user using webRtc.
everything works fine in mac.
but after latest update of chrome which is 104  it is behaving weirdly. in latest chrome in window 10 when then canvas size is changed then its capturing blank stream only and on resizing canvas to certain other size it started capturing the stream.
and this is happening on window 10 chrome 104 only.
when i downgraded the chrome version it started working fine.
i gave gone through the update release doc of google chrome but i can't see any changes that could effect my code still i am facing this issue.

**Comment by jpmedley** [comment]
Thank you for submitting. Unfortunately, this repo is for opening tickets against problems with ChromeStatus.com, not against Chrome. Please file your issue at [crbug.com](https://bugs.chromium.org/p/chromium/issues/list).

Thank you.
