### ISSUE TITLE
Capture changes as Amendments

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2168]
**Describe the solution you'd like**

Right now the Feature class implements `__notify_feature_subscribers_of_changes()` that computes a diff and enqueues a notification task with that diff as one of the parameters.

Instead of treating the diff as a temporary object, we should create a ReviewComment with the diff items as Amendment's.  Then, an equivalent notification task could be enqueued with the ReviewComment ID as the parameter rather than the diff itself.  That part of this issue would result in no user-visible change.

The user-visible part will come later: we would be able to add a section to the feature detail page to display all such comments that are associated with the current feature.

**Comment by jpmedley** [comment]
🎉

**Comment by DanielRyanSmith** [comment]
This is now live under the hood in production 👍
