### ISSUE TITLE
rename "IE views" to "Edge/IE views"

### ISSUE THREAD

**Issue by myakura** [GoogleChrome/chromium-dashboard#217]
while updating entries I realized what I'd entered for "IE views" wasn't actually impl status of IE but Edge.

**Comment by myakura** [comment]
or perhaps to create a new "Edge views" as Edge is removing features or changing behaviours.

**Comment by ebidel** [comment]
Yea we can update that. I see the vendor views as the different browser companies, but I can understand MS wanting to ditch the name IE as quickly as possible :)

**Comment by myakura** [comment]
@jacobrossi wdyt?

**Comment by jacobrossi** [comment]
LGTM
