### ISSUE TITLE
Move off of the Files API

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/chromium-dashboard#219]
The current code is affected by the [Files API service turndown](https://cloud.google.com/appengine/docs/deprecations/files_api) which will go into effect on July 28.

It looks like the code in question is https://github.com/GoogleChrome/chromium-dashboard/blob/9edb14efdc4202ca2b01ab3fedd602f438269a76/admin.py#L171

CC: @ebidel @beaufortfrancois

**Comment by ebidel** [comment]
Good catch Jeff. Looks straightforward to migrate: https://cloud.google.com/appengine/docs/python/googlecloudstorageclient/migrate
