### ISSUE TITLE
Selected item in JS/HTML metrics pages is often wrong on load

### ISSUE THREAD

**Issue by foolip** [GoogleChrome/chromium-dashboard#220]
https://www.chromestatus.com/metrics/feature/timeline/popularity/845

On this and every other such page, the dropdown is usually showing the first `AddEventListenerNoArguments` option on load.

It looks like the trick to reproduce this is to open it in a background tab, let it finish loading, and then switching to the loaded tab. Switching quickly or pasting the URL into a foreground tab doesn't reproduce the problem.

**Comment by foolip** [comment]
@annevk also noticed this

**Comment by RByers** [comment]
Yep I can reproduce this by opening into a background tab.

**Comment by jpmedley** [comment]
I can't duplicate this and given its age probably won't be able to.

**Comment by foolip** [comment]
I can confirm this no longer reproduces.
