### ISSUE TITLE
Going back in Roadmap leads to useless dates

### ISSUE THREAD

**Issue by gsnedders** [GoogleChrome/chromium-dashboard#2205]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**

**To Reproduce**
1. Go to https://chromestatus.com/roadmap
2. Click on "Previous" repeatedly
3. Read "Stable 594 days ago (Jan 19)"

**Expected behavior**
I would expect something more understandable; I presume 594 days ago is early 2021, but I shouldn't have to do that maths myself. Something like, "Stable 2 years ago (Jan 19 2021)" would be more helpful.

**Comment by jrobbins** [comment]
This seems like a place where we could use sl-relative-date again.  And, maybe phase out some existing relative date logic.

**Comment by DanielRyanSmith** [comment]
This is now fixed in production 👍
