### ISSUE TITLE
Blink components sl-select takes 20 to 30 seconds to open

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2207]
**Describe the bug**
In HEAD, the blink_components sl-select element is populated by an API call now.   The API call returns JSON in only 200ms, but the sl-select makes the user wait 20 to 30 seconds after a click until the items are shown.  This latency is not new: it happened before the switch to being API-driven.

**To Reproduce**
1. Go to your local server
2. Sign in
3. Edit some feature's metadata or use the feature creation form
4. Click the blink component widget.

**Expected behavior**
The menu should open almost instantly, certainly in less than a second.

**Additional context**
Maybe we can find a way to make sl-select render the menu faster.
Or, maybe this should be a button that opens a dialog that lists out the choices... kind of like a home-made menu.
Or, maybe it should be a regular text field with a datalist of choices (like we choose metrics buckets)

**Comment by jrobbins** [comment]
I asked for advice on the shoelace discussion board:
https://github.com/shoelace-style/shoelace/discussions/902

**Comment by kevinshen56714** [comment]
This doesn't happen to me though at my local version. See my screen record:


https://user-images.githubusercontent.com/11501902/188702647-b55b45a7-72f9-436a-b7dd-9f665fb8da5b.mov

**Comment by kevinshen56714** [comment]
Ok, I see this behavior on the staging server. I will see if I can improve it, but I think switching to datalist is not a bad idea.
