### ISSUE TITLE
Some stats are recorded and visible when you know the URL but not in the drop down

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/chromium-dashboard#223]
https://www.chromestatus.com/metrics/feature/timeline/popularity/882 for example is not in the select box (user timing) but works when you know the url.

cc @jeffposnick @ebidel

**Comment by ebidel** [comment]
Is this fixed @PaulKinlan I see `AddEventListenerNoArguments` in the dropdown. Brand new values are added by a cron job. It could take them 24hrs+ to show up.

**Comment by jpmedley** [comment]
This looks like it was fixed.
