### ISSUE TITLE
chrome.loadTimes()

### ISSUE THREAD

**Issue by mchtakdmn96** [GoogleChrome/chromium-dashboard#2247]
First of all, hello everyone, I'm new here. 
My name is Mücahit Akduman. I am getting 1 warning and in the Chrome web store, 
I would really appreciate if you could help me how to solve them. and I don't know much about coding right now, 
I would be more happy if you could help me by  the codes directly :) The warning and I got are as follows. Best regards, Mucahit Akduman.
![Screenshot_2](https://user-images.githubusercontent.com/101957740/190826557-d6a2f81e-d0a2-4e34-8e31-f428067840da.png)
Geliştirici Araçları kaynak eşlemesini yükleyemedi: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map için içerik yüklenemedi: Sistem hatası: net::ERR_FILE_NOT_FOUND
m=consumer:620 [Violation] 'setTimeout' handler took 151ms
[Violation] Forced reflow while executing JavaScript took 30ms
![Screenshot_3](https://user-images.githubusercontent.com/101957740/190826645-29a4309e-6f2d-43b6-a8ce-9ef594e2ad6c.png)

**Comment by jrobbins** [comment]
Sorry, I don't know anything about that error or that extension.
