### ISSUE TITLE
When viewing a non-existent feature, the UI just hangs

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2257]
**Describe the bug**
If the user tries to visit a non-existent feature (e.g., a deleted one or a random number for the ID), then the page just shows a shimmering skeleton forever.  It should say "404" or "Feature not found".

**To Reproduce**
1. Go to https://cr-status-staging.appspot.com/feature/12345

**Additional context**
There might be something shown in the toast, but the toast is not being displayed due to a different error that I have a pending PR for.

The message that the toast is set to show is "Some errors occurred.  Please refresh the page or try again later."  But, that is not helpful in the case of a 404.

**Comment by jrobbins** [comment]
@kevinshen56714 FYI.

**Comment by aaryan-verma** [comment]
I want to work on this issue. Pls assign it to me.
