### ISSUE TITLE
Keep "Intent to *" templates in sync with http://www.chromium.org/blink#launch-process

### ISSUE THREAD

**Issue by foolip** [GoogleChrome/chromium-dashboard#230]
From https://groups.google.com/a/chromium.org/d/msg/blink-dev/Bu9EQO-Tjtk/way3F2mFBAAJ it sounds like there are templates on chromestatus.com that are not in sync with the templates in http://www.chromium.org/blink#launch-process

If that's true, let's figure out a way to keep them in sync, e.g. by linking one from the other.

**Comment by ebidel** [comment]
Doc is https://docs.google.com/document/d/1vlTlsQKThwaX0-lj_iZbVTzyqY7LioqERU8DK3u3XjI/edit#.

Unfortunately, we really can't link from crstatus.com to this doc b/c the template is generated and populated for users after they setup a new feature. We'll just need to manually update it if the doc changes. I'm not sure of a better way.

**Comment by jpmedley** [comment]
Chrome Status is becoming a wizard to the launch process itself. The problem now is keeping the launch process instructions in sync with Chrome Status.
