### ISSUE TITLE
Upgrade us to use the latest versions of NodeJS and Babel

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2304]
**Is your feature request related to a problem? Please describe.**
Our current README.md says to use 12, whereas the current version is 16.   This makes it more difficult for potential developers to set up a development environment.

Also, we have been declining PRs suggested by dependbot because they cause JS compilation errors.   They depend on newer versions of Node, Babel, or other JS libraries.  These PRs are often triggered by reported security vulnerabilities, so by declining them our app is left vulnerable.

Also, we don't seem to be able to use recent JS language features, for example the questionmark-dot operator.

**Describe the solution you'd like**
Get our app working on the latest version of Node, Babel, and do any needed JS library upgrades.  Update README.md to tell potential developers that they can use the latest version of Node, or name a specific Node version that it current now.

**Comment by jcscottiii** [comment]
Taking notes for myself:

Going to node 18.
It will be going into [LTS](https://github.com/nodejs/Release) on October 25.

---
Migrating from node-sass to sass.
node-sass uses libsass. both are [deprecated](https://sass-lang.com/blog/libsass-is-deprecated#:~:text=If%20you're%20a%20user,switch%20to%20Dart%20Sass's%20CLI.) [[2](https://www.npmjs.com/package/node-sass)] 
Why migrate? When using node-sass with gulp-sass, I get this message now with the new node version: https://stackoverflow.com/questions/66173984/unable-to-install-gulp-sass-on-npm-version-7-5-1

Upgrading gulp-sass to 5.1.0 fixes the problem without having to change node-sass. But npm install takes a lot longer.

---
Getting conflicting dependency [warnings](https://stackoverflow.com/questions/67185714/how-do-i-read-npm-conflicting-peer-dependency-error-messages)
https://github.com/npm/cli/issues/3083#issuecomment-820387637
Had to delete package-lock.json and node_modules and do a raw npm install
^ This is going to cause the bulk of the "changes" in the PR

**Comment by jrobbins** [comment]
I'd also like to phase out our use of SASS, because we don't use much of it.  We've already converted almost all of it to lit-css.
I'll leave it up to you if you want to upgrade SASS as part of this work or phase it out to avoid the need to upgrade.
