### ISSUE TITLE
New timeline view has insufficient precision

### ISSUE THREAD

**Issue by foolip** [GoogleChrome/chromium-dashboard#232]
Example: https://www.chromestatus.com/metrics/feature/timeline/popularity/774

When hovering, percentages are only shown in 0.01% steps and the gradations of the scale to the right is also in this scale. Previously one could see data to a precision of 0.0001%, and differences at this level have often been part of the decision making. For example, it doesn't make sense to try to remove an old API that's easy to maintain if it's used on 0.01% of page views, but if it's 0.0001% and it's no already interoperably implemented, it could make sense.

**Comment by ebidel** [comment]
Drats. We may have to go back to the non material design charts api if there's not a way to control this. I'll dig into it.

**Comment by ebidel** [comment]
Fixed this. Rolled back to the old charting lib.

**Comment by foolip** [comment]
Thanks!
