### ISSUE TITLE
Button to insert a new stage (or clone one)

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2338]
**Is your feature request related to a problem? Please describe.**
Features sometimes have multiple origin trials or launch in phases.  These are not represented well in our old schema where we had specific milestone fields that allowed only one stage of each type. 

**Describe the solution you'd like**
Implement a button to allow the user to create a new stage.  

They could choose from a set of stage types that are appropriate to the type of feature.  Some stage types such as ROLLOUT could be added to any feature type.  Or, the user could choose to clone an existing stage.  

The new stage could be appended to the end of the list of stages, or inserted before or after a selected stage.

**Comment by DanielRyanSmith** [comment]
Addressed in #2611
