### ISSUE TITLE
Sidebar issues when Stable == Beta

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/chromium-dashboard#236]
During the magical period we're currently in, where both the Stable and Beta release are at 45, the sidebar is unhappy. It looks like

![image](https://cloud.githubusercontent.com/assets/1749548/9635518/d7b64436-5164-11e5-9829-8270953cc643.png)

with no mention of 46, and features that are tagged for 46 show up in the "No Active Development" section.

**Comment by ebidel** [comment]
BTW, this is fixed today. It really on effects the day of a new stable release.

**Comment by ebidel** [comment]
I'm actually going to close this b/c it's showing the correct behavior and it's showing the right info. 
It's happening again today, b/c there was just a stable update and beta/stable are the same.

![screen shot 2015-10-13 at 3 31 40 pm](https://cloud.githubusercontent.com/assets/238208/10470137/96a70284-71bf-11e5-916e-099ad8771e1d.png)

**Comment by jeffposnick** [comment]
The difference is that today, 47 is dev and 48 is canary, so they both showed up in the list. Back when I initially reported this, dev and canary were the same milestone, so an entire release dropped off the list.

It's not a big deal, but it is something that could cause confusion every 6 weeks. It might get triggered tomorrow if 48 makes dev before 47 makes beta...

**Comment by ebidel** [comment]
Right, I guess there are a few edge cases in this mix.
