### ISSUE TITLE
Standardization status of living standards

### ISSUE THREAD

**Issue by beverloo** [GoogleChrome/chromium-dashboard#237]
The standardization status of certain features Chrome implements doesn't really fit any of the existing options. For example, Web Notifications is a Living Standard:

https://notifications.spec.whatwg.org/

What standardization status should we use for newly recorded additions? It's not really an established or de-facto standard, it's not published or officially condoned by a working group (WD or similar) and editorially it's closest to an Editor's draft, but we consider it as something more mature.

_Working draft or equivalent_ covers the status most accurately, but not completely. Are we satisfied with that, or would it make sense to introduce a _Living standard_ option?

+@johnmellor

**Comment by ebidel** [comment]
I think this was the intention with working draft or equivalent. I'm not
sure another dropdown option offers much.
