### ISSUE TITLE
Add "js-decorators" proposal in the list

### ISSUE THREAD

**Issue by jogibear9988** [GoogleChrome/chromium-dashboard#2378]
as it is in stage 3, this should be added.

**Comment by jogibear9988** [comment]
chromebug: https://bugs.chromium.org/p/v8/issues/detail?id=12763&q=decorators&can=2

**Comment by jogibear9988** [comment]
possitions: 
ff: https://github.com/mozilla/standards-positions/issues/700
webkit: https://github.com/WebKit/standards-positions/issues/76

ts impl: https://github.com/microsoft/TypeScript/pull/50820

**Comment by jstenback** [comment]
Thanks for raising this. However, this repository is for tracking the implementation of the chromestatus.com site, not the data in it. If you'd like to get js-decorators added, you should do so directly in the tool, or ask those who are likely to be working on it.

Closing this issue.

**Comment by trusktr** [comment]
GitHub issue tracking all implementations: 

- https://github.com/tc39/proposal-decorators/issues/476
