### ISSUE TITLE
Bad signal/noise ratio in "About this Page" Google Doc

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/chromium-dashboard#240]
The "About this Page" link in the site's footer points to [this Google Doc](https://docs.google.com/document/d/1jrSlM4Yhae7XCJ8BuasWx71CvDEMMbSKbXwx7hoh1Co/edit?pli=1), which apparently has open edit access. Not surprisingly, there's a lot of noise on the page with very little actual information.

Is there a canonical version anywhere that it can be restored to? And maybe just put the same info in a `FAQ.md` file that's stored inline in the repo? That way we wouldn't have to manage Google Doc edit permissions.

**Comment by ebidel** [comment]
@maxh can you help?

**Comment by ebidel** [comment]
This house is CLLEEEEYAAA.
