### ISSUE TITLE
Font size for feature search in dropdown menus

### ISSUE THREAD

**Issue by KyleJu** [GoogleChrome/chromium-dashboard#2412]
We could reduce the font size to display the search fields better. Currently the texts in dropdown menus are cut off. Or we can increase the width of the field names

<img width="1371" alt="Screen Shot 2022-10-28 at 4 13 44 PM" src="https://user-images.githubusercontent.com/8611520/198749349-415b1fff-b929-4973-ab9e-61e2cb7e2558.png">

**Comment by punithnayak** [comment]
Can I please work on this
