### ISSUE TITLE
why /metrics/feature contains only a subset of features?

### ISSUE THREAD

**Issue by kdzwinel** [GoogleChrome/chromium-dashboard#242]
`/metrics/css` displays **all** CSS properties, `/metrics/feature` displays a **subset** of HTML features & DOM APIs. This isn't obvious at first + there is no explanation why it is a subset. I think it's worth mentioning.

I've talked with Paul Kinlan about this on slack and he explained it to me as follows:

> everything has to be manually instrumented so not everthing is tracked
deprecated features are tracked to see when they can be safely removed
I believe they have a process at build time for all the CSS features.

**Comment by ebidel** [comment]
Paul's assessment is right. All features in CSS are tracked through a single codepath, whereas html/js features need to be plumbed individual. I'm not sure there's much we can do about it. If you see a missing feature, file a Blink bug: crbug.com

**Comment by kdzwinel** [comment]
Thanks for a quick response. This explanation is absolutely clear, it's not obvious though for someone who stumbles on that page for the first time. If I haven't asked Paul about it, I'd probably still be confused about purpose of that page. Maybe it just me though.

**Comment by ebidel** [comment]
It does say "occurrences of certain HTML and JavaScript features in the wild"

**Comment by kdzwinel** [comment]
"occurrences of certain HTML and JavaScript features in the wild" is rather cryptic and easy to miss, but you are right, lets wait and see if anyone else will (ever) report it :)
