### ISSUE TITLE
Make it clear what is the order in samples/

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/chromium-dashboard#243]
Steps to reproduce:
1. Go to https://www.chromestatus.com/samples
2. Click on "Device" in the left pane
3. Browse through samples

It's not clear why Geolocation Chrome 5 is above NotificationOptions Chrome 47.
Maybe add some titles at the top of each section could help to understand this order.

@ebidel 

![screenshot 2015-10-07 at 10 13 24 am](https://cloud.githubusercontent.com/assets/634478/10332206/1421456e-6cdc-11e5-81b5-46fe1043ac18.png)

**Comment by ebidel** [comment]
How about a description at the top? To answer your question, it's enabled
by default features first, ordered by release, then features that are
behind a flag or are in the works (but have a sample). Within each of those
groups, they're alphabetized.

**Comment by beaufortfrancois** [comment]
Thank you @ebidel!
