### ISSUE TITLE
Implementation Status Shows Wrong Label on Standalone page view

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#244]
The following ticket shows the feature as being behind a flag in Chrome 47 for both desktop and Android when I view it on the dashboard:

https://www.chromestatus.com/features/5857463882481664

If I view the same ticket in standalone view, it makes it seem as if the feature is available in Chrome 47:

https://www.chromestatus.com/features/5857463882481664

I've confirmed with the feature owner that said feature is behind a flag on both platforms. The request is to change the label on the standalone page to accurately reflect the status of feature. In this case the Implementation status would say "behind a flag" for both desktop and Android.

**Comment by RByers** [comment]
I agree this is really confusing.  This could be a tiny tweak to wording, eg (for the case of [PointerEvents](https://www.chromestatus.com/feature/4504699138998272)) change:
```
Behind a flag in desktop Chrome 52 (launch bug)
Available in Chrome for Android release 52.
Available in Android WebView release 52.
```
To
```
Behind a flag (launch bug):
  - Chrome desktop: release 52
  - Chrome for Android: release 52.
  - Android WebView: release 52.
```

**Comment by NavidZ** [comment]
@RByers I wonder if we have feature.meta.needsflag set (which I assume it mean it is behind flag) does it include all the platforms or not? I mean cannot we have flag for one platform and not for the other or released on another platform? In that case what you are suggesting doesn't quite work. Right?

**Comment by ebidel** [comment]
Right, unfortunately there's only one "Status in chrome" dropdown instead of a separate one for each platform. The original idea was that the major of features launch/are removed/get a flag across all platforms at the same time. But that clearly doesn't work for 100% of features. Historically, we've asked folks to use the comments field to distinguish any deviations from this.

**Comment by RByers** [comment]
Yeah I think that's fine.  Really the status should be the same for desktop, Android and WebView too.  Maybe those should only be customized / displayed as exceptions somehow?
