### ISSUE TITLE
V8SVGFEConvolveMatrixElement_PreserveAlpha_AttributeGetter missing from stack rank

### ISSUE THREAD

**Issue by foolip** [GoogleChrome/chromium-dashboard#248]
https://www.chromestatus.com/metrics/feature/popularity

The V8SVGFEConvolveMatrixElement_PreserveAlpha_AttributeGetter counter isn't included here, although it is in the dropdown and the counter is working:
https://www.chromestatus.com/metrics/feature/timeline/popularity/791

Perhaps there are others missing for the same reason.

Noticed by @doomdavve

**Comment by ebidel** [comment]
Hmm, data collection looks spotty for these `V8*` properties as well. Last collection was in Oct for this one, although it's still listed in https://chromium.googlesource.com/chromium/blink/+/master/Source/core/frame/UseCounter.h. 

Do you know if the actual account was removed?

**Comment by foolip** [comment]
I have double-checked that the use counter is fact in place and working, it's just that this code path is hit very, very rarely. Is there some kind of filtering in place intended to exclude things that have already been removed, perhaps?

**Comment by toyoshim** [comment]
CssAtRule* are also dropped recently. Now the stack rank only shows 109 items out of ~1000.

**Comment by ebidel** [comment]
All should be back!

Example:
https://www.chromestatus.com/metrics/feature/popularity#V8SVGFEConvolveMatrixElement_PreserveAlpha_AttributeGetter
