### ISSUE TITLE
Action requested email has incorrect link

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/chromium-dashboard#2492]
**Describe the bug**
I received an email with title "[Action requested] Review FedCM iframe" which has an "Edit your feature" link pointing to https://chromestatus.com//guide/edit/5162418615877632. The correct link should be https://chromestatus.com/guide/edit/5162418615877632 (see the double vs single slash before 'guide'). I'm not sure who produces these email but I figured I'd file a bug here.

**Comment by jrobbins** [comment]
This fix is live now.
