### ISSUE TITLE
Toast is briefly displayed on page load

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2512]
On several of our pages, the chromedash-toast element briefly appears in the bottom left corner if the page is initially loaded or reloaded (not on a SPA navigation).   The fact that the toast flashed by looks like a mistake or error, even though it does not prevent the user from accomplishing any use case.  We should prevent it because it is not intended to be initially displayed.

**Comment by jrobbins** [comment]
Several pages: roadmap, myfeatures, newfeatures, and probably others.

**Comment by DanielRyanSmith** [comment]
https://github.com/GoogleChrome/chromium-dashboard/assets/56164590/63db554a-dc29-4089-9871-3562f59a12b6

Here is an example of the behavior you can see on the bottom left on page refresh.

**Comment by r3yc0n1c** [comment]
Hi, I'd like to work on this.

**Comment by DanielRyanSmith** [comment]
Hey @r3yc0n1c, feel free to open a PR for this work, and you can pose any questions you have here as well!

**Comment by r3yc0n1c** [comment]
Sure, there was some setup issues but now I got the dev-env ready, working on it... will drop a PR soon!

**Comment by impact-maker** [comment]
@r3yc0n1c  Hi I have
 already made a pull request on this issue and closing it.

**Comment by r3yc0n1c** [comment]
> @r3yc0n1c Hi I have already made a pull request on this issue and closing it.

Oh, I thought this is open to work, Daniel assigned it to me.
