### ISSUE TITLE
Implement editing for feature metadata from the feature detail page like other stage forms

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2520]
**Is your feature request related to a problem? Please describe.**
One of our goals is to allow editing starting from the feature detail page rather than having the user click through to the /guide/edit page (the process overview page).  So far, we display feature details in accordion sections and offer "Edit fields" buttons for each stage.   However, there is also a "Metadata" accordion section that does not have an "Edit fields" button yet.

**Describe the solution you'd like**
Add an "Edit fields" button to the "Metadata" accordion section.  That button should be like the other "Edit fields" buttons: a link to an editing form.

**Additional context**
Ideally the editing form would be exactly the same as any of the stage editing forms.  We currently use stage type zero when submitting changes to the metadata, so that could probably be used in the URL of the stage editing form page.

The existing code to generate the metadata editing form is in chromedash-guide-metadata.js.  We should make that code unused, but don't delete it yet because we are not ready to turn off the /guide/edit page yet.

**Comment by KyleJu** [comment]
This is fixed by #2619
