### ISSUE TITLE
/features broken on browsers without native Promises

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/chromium-dashboard#253]
The `Promise` polyfill seems to be provided in `features-imports.vulcanize.js`, but that's not loaded by the time the `/features.json` request promise is created, leading to the following error on browsers that lack native `Promise` support. (IE 11 in this case.)

![image](https://cloud.githubusercontent.com/assets/1749548/11816607/3b43a460-a31f-11e5-9274-7f894d71a99f.png)

**Comment by ebidel** [comment]
I have https://github.com/GoogleChrome/chromium-dashboard/blob/master/templates/features.html#L75 but I've purposefully tried to avoid loading a polyfill for older browsers. IE is 1% of users. IE 11 is 0.75% users.

**Comment by jeffposnick** [comment]
Oh, I thought the polyfill was being pulled in via `features-imports.vulcanize.js`, but I guess I read the minimized code incorrectly.

What about wrapping the `<script>` tag in an `if (typeof(Promise) === 'undefined')`? Seems lightweight enough.

**Comment by ebidel** [comment]
Yea we could. You'd have to coordinate the loading of that polyfill with the async xhr promise.

**Comment by jeffposnick** [comment]
Bah, I was mixing up my Django templating and Polymer templating and forgot that you couldn't use `typeof(Promise)` to trigger the (blocking) `<script>` tag.

I'm willing to let it go.
