### ISSUE TITLE
Layout horribly broken on mobile Safari

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#256]
Maybe the same root cause as #199, but a lot worse than what's shown there.  Makes the site mostly unusable on an iPhone - so seems pretty serious.  @ebidel WDYT?

![image](https://cloud.githubusercontent.com/assets/1280419/12150986/bb8c6082-b47a-11e5-93e9-aa9ef779f084.png)

**Comment by ebidel** [comment]
What safari version?

**Comment by RByers** [comment]
This is the latest version of iOS (9.2) on an iPhone 6s.
