### ISSUE TITLE
Changes on features_v2.json

### ISSUE THREAD

**Issue by ninware** [GoogleChrome/chromium-dashboard#2581]
Due to the short release cycle of Google Chrome Browser, we periodically check the public sources for hints regarding relevant changes with new Chrome (stable, dev, beta) versions.

We are polling chromium status updates from your endpoint https://chromestatus.com/features_v2.json

Why do we do this?
We are analyzing the chromium tickets to determine breaking and important changes very early. This is very important to guarantee the functionality of our software.
We can react very directly to upcoming changes or new features and adept them.

We dont want to review every ticket every time we spend the time to analyse it.
So we store that data together with additional useful information like 'discarded', 'to be reviewed again' and so on. These information helps us, if the bug/feature is still relevant and if it needs to be re-validated, if the 'update time' has changed.

You provide the content still as features_v2.json but not as features_v3.json, although the 'created.when' and 'updated.when' has been removed in the json api.

Do we have a chance that you bring back the old format, or at least add the update and created properties?

**Comment by m-jung** [comment]
We, do monitor periodically the platform status by scanning the feature list for updates.
Therefor the _https://chromestatus.com/features_v2.json_ -> `[n].updated.when` is of special interest for us to filter for updated entries since the last time the feature list was observed.
The missing updated-property forces us to query every single entry separately to check if it's been updated.

**Comment by DanielRyanSmith** [comment]
The `created` and `updated` fields will be returned to the structure in the next deployment.

**Comment by DanielRyanSmith** [comment]
These fields should now be available. Please let us know if you have further issues!
