### ISSUE TITLE
P4: Interface should provide more show/hide options

### ISSUE THREAD

**Issue by maxh** [GoogleChrome/chromium-dashboard#26]
This could include:

- [ ] "Esc" should collapse all open features
- [ ] Show/hide all panel toggle

Showing all may not be practical, but hide certainly is.

**Comment by jpmedley** [comment]
@jrobbins This would be useful. How hard is this to do?

**Comment by jrobbins** [comment]
I don't think this one is important enough to keep tracking.
I'm not planning on make small improvements to the existing feature list page because I have a KR to completely replace it.  I doubt that I will keep the inline expansion behavior in the new design, so this will be moot.
