### ISSUE TITLE
I can't edit motivation section

### ISSUE THREAD

**Issue by shhnjk** [GoogleChrome/chromium-dashboard#2659]
**Describe the bug**
Clicking the following edit link results in error in next navigation.

<img width="880" alt="image" src="https://user-images.githubusercontent.com/6134073/211943096-2b9c04d2-8771-41ac-bc24-b1cf78f0a228.png">

**To Reproduce**
1. Go to https://chromestatus.com/guide/edit/5128825141198848
2. Click on Edit link of the motivation
4. See error. 
<img width="692" alt="image" src="https://user-images.githubusercontent.com/6134073/211942825-0f181062-f36b-4676-bc7f-6797c5a0fc62.png">

**Expected behavior**
Motivation can be edited.

**Comment by jrobbins** [comment]
@DanielRyanSmith the "Update" button leads to a form with no fields on it.  So, I am guessing that the lookup of the set of fields for this process and stage is failing.

**Comment by jrobbins** [comment]
This should be working now.    Please give it a try.

**Comment by shhnjk** [comment]
Yup, it works now! Thanks!
