### ISSUE TITLE
Some metrics missing from list but present in raw UMA data

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#266]
AddEventListenerThirdArgumentIsObject (967) isn't listed in the stackrank, but shows up on the internal UMA dashboard with a non-trivial amount of usage.  Is it being filtered from the list for some reason?

**Comment by ebidel** [comment]
Any idea when this was added. It takes 24hrs+ for us to pick up new ids.

**Comment by ebidel** [comment]
`MediaStreamConstraintsConformant 1152` looks like the last one we collected. That was back in Jan 28:

<img width="1029" alt="screen shot 2016-02-24 at 5 37 27 pm" src="https://cloud.githubusercontent.com/assets/238208/13307032/51d71ffa-db1d-11e5-9f14-80f98add97e9.png">

@beaufortfrancois any interest in taking a look?

**Comment by ebidel** [comment]
I ran: 

import models

```
query = models.FeatureObserver.all()
#query.filter('bucket_id =', 967)
#query.filter('property_name =', 'AddEventListenerThirdArgumentIsObject')
query.order('-bucket_id')
data = query.fetch(20000)

for f in data:
  print f.property_name, f.bucket_id
```

**Comment by RByers** [comment]
> Any idea when this was added. It takes 24hrs+ for us to pick up new ids.

Both the `Add` (missing) and `Remove` (present) varients were [added back in October](https://chromium.googlesource.com/chromium/src/+/bd5f09eed76868c8aa00a9ab4fa66a9c72ccc6dc).

**Comment by ebidel** [comment]
Something happened around that time. We recorded https://www.chromestatus.com/metrics/feature/timeline/popularity/967 as `CastOverlayShown` and there's  a `CastOverlayClicked 966` that i no longer see in ttps://chromium.googlesource.com/chromium/src/+/master/tools/metrics/histograms/histograms.xml

**Comment by ebidel** [comment]
@RByers I've fixed up the two you care about. Working on some other data issues. People are changing strings on us so we're creating names that use the same bucket_id.

**Comment by beaufortfrancois** [comment]
@ebidel Do you think it's an issue with how works https://github.com/GoogleChrome/chromium-dashboard/blob/6b267c054dbddbcae740b504a2f6d182995f86c7/admin.py#L73 ?

**Comment by RByers** [comment]
> People are changing strings on us so we're creating names that use the same bucket_id.

Oh yeah, I see for example [this commit](https://chromium.googlesource.com/chromium/src/+/c50b98bea4c7bd611fefe7ade6d9bd52fa9af101%5E%21/#F16) which violates the rule (in UseCounter.h) that says not to rename entries.  I didn't see a change that messed explicitly with 967, but maybe I missed it.  If this is a pervasive problem we could probably add a presubmit rule that prevents this.

**Comment by ebidel** [comment]
Yea, I think that would be great. Seeing at least 24 name changes so far.

**Comment by ebidel** [comment]
Dupes are no gone. Now investigating why some properties haven't seen data updates from our cron job since 2/1

**Comment by ebidel** [comment]
Got to the bottom of the missing data. I suspect UMA changes on how the data is stored. The endpoint is returning 404 for us. We haven't successfully collected data since 2016-02-01.

**Comment by dstockwell** [comment]
@RByers

> Oh yeah, I see for example this commit which violates the rule (in UseCounter.h) that says not to rename entries. I didn't see a change that messed explicitly with 967, but maybe I missed it. If this is a pervasive problem we could probably add a presubmit rule that prevents this.

What rule? The tools should depend on the IDs, not names. We should have the flexibility to rename what we are counting.

**Comment by RByers** [comment]
> What rule? The tools should depend on the IDs, not names. We should have the flexibility to rename what we are counting.

We should definitely clarify this.  I know we shouldn't be changing the semantics of an existing UMA stat (eg. the UMA dashboard knows only about the ToT histograms.xml definition of the semantics).  But is a semantic-preserving name change OK elsewhere?  I don't why it wouldn't be but don't know for sure.  Perhaps @tdresser does?

The existing code comment in UseCounter.h should probably be clarified in this regard:
 >  Don't change assigned numbers of any item, and don't reuse removed slots.

**Comment by tdresser** [comment]
As far as I know, semantic preserving name changes are fine.

**Comment by RByers** [comment]
Thanks, that makes sense.  @ebidel is it reasonable for your pipeline to be able to handle semantic-preserving name changes?

**Comment by ebidel** [comment]
We store the numerical ids from histogram.xml and can update the names every night based on their snapshot. That will require some code changes. I'll file a bug.

**Comment by ebidel** [comment]
One example is `V8Element_Animate_Method`, which is in https://www.chromestatus.com/metrics/feature/timeline/popularity/773, but not in the list.

**Comment by ebidel** [comment]
Should be back now.
