### ISSUE TITLE
LGTM fields do not work on the page

### ISSUE THREAD

**Issue by DanielRyanSmith** [GoogleChrome/chromium-dashboard#2665]
**Describe the bug**
The feature fields to denote LGTM approvals for intents are displayed as empty and cannot be added to. The field can be filled in and submitted, but no changes will be saved and the field remains empty. This is because the LGTM fields were not moved over to the FeatureEntry field when handling the schema migration. A number of things are reliant on the fields, including the process overview field which is tracking the fields to determine if aspects of the process have been completed.

**Expected behavior**
These fields need to either be deprecated, or a script needs to be created to migrate them back from Feature entities to FeatureEntry entities. Additionally, another metric or approach will need to be created for determining process completeness.

**Comment by jrobbins** [comment]
We have already disabled editing of LGTM fields.
Next, we need existing LGTM email fields to be migrated to Vote entities on the appropriate stages and gates.

**Comment by DanielRyanSmith** [comment]
Here is a rough overview on how to approach this:
Create a new script similar to the changes in [this PR](https://github.com/GoogleChrome/chromium-dashboard/pull/2772), except no new fields should need to be added. Only the script in `schema_migration.py` and add a new Route in `main.py`.

As for the script, it should:
1. Query for each Feature and iterate through them.
2. Check if any of the LGTM email fields are filled on the Feature entity. If none are filled, continue to the next Feature entity.
3. For each LGTM email field with values, iterate through the emails.
4. Query for an existing Vote entity where `set_by=={{email}}` and gate_type matches the LGTM field type.
For example, if `feature.i2s_lgtm==["user@example.com"]`, then 
```py
existing_vote = Vote.query(Vote.set_by == "user@example.com", Vote.gate_type == GATE_SHIP).get()
```
5. If the Vote entity exists, make no changes (don't rewrite someone's vote!). If the query is null, create a new Vote entity with the set_by value equal to the email and the state equal to Vote.APPROVED.
6. If a new Vote entity was created, add it to a list to submit to the DB all at once later.
7. After all Feature entities have been checked, save all of the new Vote entities using `Vote.put_multi(votes_list)`

**Comment by KyleJu** [comment]
> ```python
> existing_vote = Vote.query(Vote.set_by == "user@example.com", Vote.gate_type == GATE_SHIP).get()
> ```

Probably needs feature_id there as well. The same person can set multiple votes across features

**Comment by KyleJu** [comment]
The migration is complete on prod
