### ISSUE TITLE
Removed in Chrome is shown as shipped in Opera

### ISSUE THREAD

**Issue by foolip** [GoogleChrome/chromium-dashboard#267]
Here's how the entry for SVGElement.offset* removal is shown:
![Rendering of SVGElement.offset* entry](http://i.imgur.com/0CjDhqe.png)
And these are the settings:
![Settings of SVGElement.offset* entry](http://i.imgur.com/QfQjyO0.png)

I was contacted by a web developer asking if this means that Opera will retain support even when it's removed from Chrome, which isn't what's going to happen.

**Comment by ebidel** [comment]
Yea, we don't have a precedence for this. Would it be ok just to remove opera 37 from those boxes?

**Comment by foolip** [comment]
Do you mean leaving the Opera fields empty in the settings for this specific entry, or changing the code to omit Opera under "Consensus & Standardization" in this kind of situation? The latter sounds like an acceptable workaround for now if doing something better would take more time. I assume there are more cases like this, so the former doesn't sound great.

**Comment by ebidel** [comment]
I was actually thinking of "leaving the Opera fields empty in the settings for this specific entry", because it requires no code changes. Unfortunately, the intention of chromestatus.com is not a tracking board for Opera features. If/when features start to diverge more in the future, we'll need to reconsider the linkage of Blink and Opera.

**Comment by foolip** [comment]
The trouble with changing only this entry is that the problem is bound to exist elsewhere, as the Opera version is automatically filled in and there are plenty of removed features. Here are just a few at random:
https://www.chromestatus.com/feature/6596598008119296
https://www.chromestatus.com/feature/4997403308457984
https://www.chromestatus.com/feature/5758434351775744

It's a more general issue that it's not possible to show a feature as being removed in other browsers, so perhaps a quickfix would be to omit any Opera information in cases of deprecation/removal? Naturally, since Opera information is under "Status in Chrome" in editing, it would be more natural to use the same status as Chrome, whatever it is.

**Comment by ebidel** [comment]
Yea, I think it's best to probably continue to make them match (e.g. if Chrome removes/deprecates, we'll show Opera as removed/deprecated as well).

**Comment by RByers** [comment]
Ok, I'll move Opera up into the implementation status section.  Blocked on #244.

**Comment by RByers** [comment]
As part of this, I'll change the "status in Chrome" text to "status in chromium" (to reflect that it's about the codebase, not any particular browser built on that codebase).
