### ISSUE TITLE
Samples field does not support commas inside URLs

### ISSUE THREAD

**Issue by cbiesinger** [GoogleChrome/chromium-dashboard#269]
https://www.chromestatus.com/feature/5670760496496640

In the samples field of that feature, I have a jsbin link. Those links come with commas:
http://jsbin.com/zefuxiviso/2/edit?html,output

The dashboard splits it at the comma :(

**Comment by cbiesinger** [comment]
Note that for that specific feature I've edited it the link to not have a comma, but nonetheless this is someting that would be good to have

**Comment by ebidel** [comment]
Ah, good one!

@beaufortfrancois can you take this?

**Comment by beaufortfrancois** [comment]
I will

**Comment by beaufortfrancois** [comment]
I just sent a PR for this.

**Comment by beaufortfrancois** [comment]
@cbiesinger I've changed https://www.chromestatus.com/feature/5670760496496640 to include http://jsbin.com/zefuxiviso/2/edit?html,output

**Comment by cbiesinger** [comment]
Thank you!
