### ISSUE TITLE
Add the field for intent subject line to the new schema

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2693]
**Describe the bug**
Intent email threads can a several different variations on the subject line.  We can detect many of these variations and recognize the thread as an intent thread.   However, unless we store the subject line, we cannot post replies that will appear as part of the thread.

The old schema Feature class has fields for those subject lines:
https://github.com/GoogleChrome/chromium-dashboard/blob/main/internals/core_models.py#L190

We should:
* [x] Add a single field for intent subject line to the Stage class
* [ ] Update the detect_intent code to set that field
* [x] Migrate old subject line values to the new field

**Comment by KyleJu** [comment]
@DanielRyanSmith I am happy to take on this issue if you haven't gotten to it!

**Comment by DanielRyanSmith** [comment]
@KyleJu I've actually gotten a good portion of this done. I'll try and submit a PR in the next 24 hours for it. I'll let you know when it's ready!

**Comment by KyleJu** [comment]
> @KyleJu I've actually gotten a good portion of this done. I'll try and submit a PR in the next 24 hours for it. I'll let you know when it's ready!

Perfect!
