### ISSUE TITLE
Upload progress percentage indicator feature is missing

### ISSUE THREAD

**Issue by boxcleverliam** [GoogleChrome/chromium-dashboard#2697]
Several versions back, Chrome displayed an upload progress indicator at the bottom left of the window.
![Screenshot 2022-11-02 at 10 09 05 AM](https://user-images.githubusercontent.com/23364154/215162596-eb616cc7-ca4a-493d-806d-fc4e635871fc.png)
This would display whenever I submitted a form with a file input (unless the request was very fast).
This feature seems to have been removed.
I cannot find any reference to the removal of this feature anywhere.

**Comment by awanishyadav967** [comment]
Hi ! I want to work on this .Can you assigmed it me.

**Comment by boxcleverliam** [comment]
> Hi @boxcleverliam , I want to work on this .Can you assigned it me.

Sorry, I don't have that option.

**Comment by jrobbins** [comment]
Thank you for submitting. Unfortunately, this repo is for opening tickets against problems with ChromeStatus.com, not against Chrome. Please file your issue at [crbug.com](https://bugs.chromium.org/p/chromium/issues/list).

**Comment by jrobbins** [comment]
Here is an issue that does not answer your question, but it might help you reach out to one of the issue participants who might know:
https://bugs.chromium.org/p/chromium/issues/detail?id=1214091

**Comment by boxcleverliam** [comment]
> Here is an issue that does not answer your question, but it might help you reach out to one of the issue participants who might know: https://bugs.chromium.org/p/chromium/issues/detail?id=1214091

Thank you!
