### ISSUE TITLE
Implementation Status for Webview Shows 'Available' When it should say 'Removed'

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#272]
Here's the ticket where you can see it: https://www.chromestatus.com/feature/5349061406228480

I've confirmed with avi@chromium.org that this should say 'removed' for all three flavors.

**Comment by avidrissman** [comment]
Yes; thank you for opening this.

**Comment by ebidel** [comment]
@jeffposnick want to look at this?

**Comment by avidrissman** [comment]
I have a patch if I can figure out how to make a pull request from it.

**Comment by avidrissman** [comment]
https://github.com/GoogleChrome/chromium-dashboard/pull/273 ?
