### ISSUE TITLE
Add Safari bug to async function entry

### ISSUE THREAD

**Issue by jkrems** [GoogleChrome/chromium-dashboard#274]
Looks like there's work being done on JSC side for "Async Functions": https://bugs.webkit.org/show_bug.cgi?id=156147

Chrome Status lists "No public signals" for Safari.

**Comment by myakura** [comment]
thanks. great to see it happen!
updated https://www.chromestatus.com/feature/5644533144485888

**Comment by mdittmer** [comment]
This appears to be fixed. https://www.chromestatus.com/features/5643236399906816 links to https://bugs.webkit.org/show_bug.cgi?id=156147.
