### ISSUE TITLE
Link to missing webkit feature: "Media Queries: resolution feature"

### ISSUE THREAD

**Issue by scheinercc** [GoogleChrome/chromium-dashboard#276]
This is the webkit tracker for the feature:
https://bugs.webkit.org/show_bug.cgi?id=78087

I came from:
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/mediaqueriesresolutionfeature?filter=f01000081

Chrome status:
https://www.chromestatus.com/features/5944509615570944

**Comment by ebidel** [comment]
Added.
