### ISSUE TITLE
Some webkit prefixed properties are listed twice in CSS stack rank

### ISSUE THREAD

**Issue by mikelawther** [GoogleChrome/chromium-dashboard#277]
For example, webkit-transform, and webkit-border-radius

<img width="761" alt="screen shot 2016-04-09 at 08 22 15" src="https://cloud.githubusercontent.com/assets/4713872/14399001/3bfd68c4-fe2c-11e5-913a-730ecc0674af.png">

**Comment by ebidel** [comment]
@beaufortfrancois do you want to investigate while Im OOO?

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by blitzy80** [comment]
Identity Mapping File for Host

version="1.0" encoding="utf-8" ?>
<Data>
  
  <Information InfoType="Antivirus" RootElement="Loop" Identity="displayName"></Information>
  <Information InfoType="Printer" RootElement="Loop" Identity="DriverName"></Information>
  
  <Information InfoType="Device_WMI" RootElement="Loop" Identity="PNPDeviceID,DeviceID"></Information>
  
  
  <Information InfoType="HotFix" RootElement="Loop" Identity="HotFixID"></Information>
  
  
  <Information InfoType="NetworkServices" RootElement="Loop" Identity="Name"></Information>
  
  <Information InfoType="Environment" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="Service_WMI" RootElement="Loop" Identity="DisplayName"></Information>
  <Information InfoType="RegistrySoftware" RootElement="Loop" Identity="Name"></Information>
  <Information InfoType="SystemRestore" RootElement="Loop" Identity="CreationTime"></Information>
  
  <Information InfoType="RecycleBin" RootElement="RecycleBinInfo" Identity="Name"></Information>
  <Information InfoType="SMARTData" RootElement="SMARTInfo" Identity="Code"></Information>
  <Information InfoType="SoftwareInstall" RootElement="SoftwareInstallInfo" Identity="DisplayName"></Information>
  <Information InfoType="MissingPatch" RootElement="MissingPatchInfo" Identity="Title"></Information>
  <Information InfoType="NetworkDevices" RootElement="NetworkDevice" Identity="Componentvalue"></Information>
</Data>

**Comment by ebidel** [comment]
There appears some has renamed prefixed property names as `alias-THING` :(

**Comment by ebidel** [comment]
Fixed up the data where property names had changed.

**Comment by phistuck** [comment]
-epub properties also have -alias prefixes - can you clean that as well?
(Or do you want a new issue?)

**Comment by ebidel** [comment]
New issue would be great :)
