### ISSUE TITLE
Mark Behind-A-Flag Features As Such More Prominently

### ISSUE THREAD

**Issue by phistuck** [GoogleChrome/chromium-dashboard#278]
It would probably make it easier if ChromeStatus.com had an icon next to features that are not enabled by default (without opening every feature) as this can be confusing to web developers as well as to the authors of the Chromium beta blog posts.

See https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/9ZNt7sRUEl0 for context.

Open question - what if a feature is behind a flag on, for example, desktop but not on Android?
(I originally wrote "on Windows but not on Linux", but, unfortunately, ChromeStatus.com does not have such granularity anyway)

**Comment by ebidel** [comment]
It already does. The puzzle icon is experimental/behind a flag:

<img width="815" alt="screen shot 2016-04-29 at 2 27 42 pm" src="https://cloud.githubusercontent.com/assets/238208/14930157/987639c4-0e16-11e6-9b97-2e7bf14923b6.png">

Regarding the 2nd question we dont have a good way to differentiate atm. We've been asking folks to use the comments to make finer grain remarks on when flags and other things switch.

**Comment by phistuck** [comment]
I missed that, sorry.
