### ISSUE TITLE
Timelines should show data for only the dominant version

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#279]
@foolip mentioned it would be really nice to see milestone markers on the timeline graphs.  On a related note, I've seen people confused before about an apparent huge spike in usage which was really just showing the metric making it to stable channel (before then I assume the timeline shows the beta/dev usage as a function of the total page view on all channels).

To avoid confusion, I suggest that we restrict the timeline to showing only stable channel (we can use the Google-internal uma dashboard when we need to drill further).  If we do that, then also adding stable-release-date milestone markers should be pretty easy / useful too.

@ebidel don't worry, I'm not asking you to do this - as we discussed, I'm working on finding an engineer (and/or some of my own time) to help with the dashboard.

**Comment by ebidel** [comment]
Is there a way to query UMA to return just stable channel results? I'm not sure if it's currently possible with our current setup.

**Comment by RByers** [comment]
It's definitely possible on the internal dashboard (just have a "Channel" filter), but I don't know how that's exposed down in the data.  Maybe we can just show only data for whatever major version is dominant on any given day (it's conflating data across versions that's the fundamental problem)?

**Comment by ebidel** [comment]
I need to look at stuff again, but IIRC, the json data we get from the GCS buckets is across all channels. It's not separated out.

**Comment by RByers** [comment]
Re-titling to describe the issue: people get confused about what the data means when the UseCounter in question hasn't actually been in stable for awhile.  I think the simplest fix is probably to have the UMA pipeline include only stable data, but I don't know the details of how that works and there are other options (eg. ideally you'd be able to see a separate line for dev channel or something).

I keep seeing people get confused by this, let's mark it high priority for whenever predictability team decides to return to doing a bunch of chromestatus work...

**Comment by ebidel** [comment]
@RByers have you raised these questions with the UMA team? If we decide what we need, I'm sure they can craft a dremel query for it. 

I'm a little worried about storing data for multiple channels. Do you think we can return only stable chrome for now? Worry about the other channel lines later?

**Comment by RByers** [comment]
> @RByers have you raised these questions with the UMA team? If we decide what we need, I'm sure they can craft a dremel query for it.

No.  IIRC the only context I have is that thread you drove back from when things broke.

> I'm a little worried about storing data for multiple channels. Do you think we can return only stable chrome for now? Worry about the other channel lines later?

Yes, showing only stable for now to keep it simple and unconfusing was my suggestion.

**Comment by ebidel** [comment]
I'll start a thread!

**Comment by RByers** [comment]
It's also [really easy to miss](https://groups.google.com/a/chromium.org/d/msg/blink-dev/fsDaKFqvU20/YK0cM9GKAQAJ) when a UseCounter has been deleted from the code (it looks just like declining usage in the graph).

I think the solution, if it's not too hard, is to do the query with a "version tag contains dominant" condition like we would from the internal UMA dashboard (rather than specifically requesting the stable version).  Then on the day the dominant version changes to one with/without the counter in question there will be a jump from/to exactly 0.

**Comment by RByers** [comment]
I think it might not be too hard to also show beta or dev channel data when a new counter hasn't yet hit stable.  Eg. when the value for a given counter is 0, we could show the beta value (as a fraction of beta PageVisits of course) in a semi-transparent line (indicating it's tentative).  In practice we've often seen beta and even dev data correlate fairly closely with stable (at least at the level of order-of-magnitude that we care about for UserCounters).

**Comment by RByers** [comment]
Conceptually, any single data point on the graph should represent data for the dominant version which has any data at all for that bucket on that day.  We can't mix versions since we can't guarantee that a given bucket will be consistently present/absent in the code across different Chrome versions.  The "dominant version" for a bucket will always be the currently deployed stable channel, except during the rollout of a release where the bucket is new.

**Comment by RByers** [comment]
I've landed the server component for this.  I think what's left on the client is:

- [ ] Update to the new endpoint API (#521)
- [ ] Store the new `milestone` and `low_volume` data.
- [ ] Update the timeline UI to show this data somehow, eg. augment the hover tooltip to add the dominant milestone for that date, and use a lighter color for lines/points with `low_volume` data.
- [ ] Update the timeline text from "Percentage of page views that use this feature" to include "(on it's dominant milestone)" or something shorter to similar effect.
- [ ] Possibly add the milestone / low_volume data to the stack rank view as well somehow. I'm mainly worried about people being confused about a feature that exists only in an old (but not entirely unused) version of Chrome.
- [ ] Update the text on the stack rank page to replace "(across all channels and platforms)" with "(for the milestone with the most usage of that feature, and across all platforms)".

**Comment by ebidel** [comment]
Couple of questoins:
- Is `low_volume` a boolean?
- Is `milestone ` (`day_milestone`) in your PR the "dominant version" of the day (the day the data was collected)? Or it's the  "dominant version" where that feature is showing up?
- "dominant version" is a synonym for "stable channel"?

**Comment by RByers** [comment]
For the record, there's a bunch of details available internally at go/chromestatus-usecounter

> Is low_volume a boolean?

Yes.  Really low volume stuff (eg. canary only, old releases that still have a few users on them) gets filtered out entirely.  This boolean should be false whenever the feature has reached at least Window or Android stable channel.  I.e. when it's true, the data is probably fairly representative but not totally conclusive yet.

> Is milestone (day_milestone) in your PR the "dominant version" of the day (the day the data was collected)? Or it's the "dominant version" where that feature is showing up?

It's the latter - feature specific.

The idea here is that when a new feature gets added, it's useful to see metrics from dev and beta channel, but it's important that the PageVisits denominator being used is just for those versions that have the metric (otherwise the data is totally misleading).  So for a new feature the dominant version will likely be whatever release is currently 'dev', while for existing features it's the current 'stable' channel.  Then when a feature gets removed (or code changed such that it's never hit anymore), the dominant version will correspond to some old release (until the volume for that release drops low enough that the feature gets filtered out entirely).

> "dominant version" is a synonym for "stable channel"?

No, it's the milestone above.

**Comment by RByers** [comment]
Details on how exactly this is implemented on the back end and the constraints we're under are available inside Google at go/chromestatus-usecounter.

**Comment by ebidel** [comment]
This should be fixed with our switch in UMA data. Please reopen if there's still something left to do.
