### ISSUE TITLE
Create links to change default sort/ordering of list

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#28]
non-intrusive links at the top of the list to select an alternate ordering e.g. 
- [ ] last updated
- [ ] category
- [ ] alphabetical
- [ ] overall color

Other may be added.

**Comment by jrobbins** [comment]
This issue is obsolete.  We have a new feature list now.  It also needs sorting, but we will track a new issue for that when we are ready to plan that work.
