### ISSUE TITLE
Webkit support CSS Custom Properties (AKA CSS Variables)

### ISSUE THREAD

**Issue by Nevraeka** [GoogleChrome/chromium-dashboard#281]
Webkit added CSS Variable support as of [version 9.1](https://webkit.org/status/#specification-css-variables) . The `features.json` returns 'Mixed Signals' . If there is a way for me to do a PR on this, I am happy to. Currently I am not sure how so please let me know or update it if you can ASAP (this project is where MS gets their status information as well) Thank you

**Comment by jeffposnick** [comment]
Thanks for the heads-up; I've updated the entry.

**Comment by Nevraeka** [comment]
thanks @jeffposnick
