### ISSUE TITLE
Push API & Service Workers - support changes

### ISSUE THREAD

**Issue by PascalReintjens** [GoogleChrome/chromium-dashboard#285]
Hello,

I think there are some updates for: https://www.chromestatus.com/feature/5416033485586432

The site lists the Push API still "In Development" by Firefox although the linked https://bugzilla.mozilla.org/show_bug.cgi?id=1038811 is resolved fixed. Mozillas own platform lists the Push API as supported since Firefox 44: https://platform-status.mozilla.org/#push - See as well: http://caniuse.com/#search=push and Browser compatibility table:  https://developer.mozilla.org/de/docs/Web/API/Push_API

In the description it's marked as "Opera for Android: in development" - Opera for Android supports this since Opera 37 (https://www.opera.com/blogs/mobile/2016/06/ad-blocking-push-notifications-opera-android/)

Edge: The "No public signals" is outdated, the feature is now in development: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/pushapi

-----

As for Service Workers (https://www.chromestatus.com/feature/6561526227927040) although it's not completely finished, there seems to be partial (nearly full) support since Firefox 44, they even consider it "landed" themselves: https://platform-status.mozilla.org/#service-worker. I am therefore not sure, whether "In development" is the right status (for more comparison see also https://jakearchibald.github.io/isserviceworkerready/)

**Comment by PascalReintjens** [comment]
Updated the issue, because Microsoft Edge changed their status from "_Development is intended to begin soon, priority high_" to "_In Development_"

**Comment by ebidel** [comment]
Thanks for the detailed updates. I've gone ahead and made the updates the data for the Push API and Service Worker.

**Comment by PascalReintjens** [comment]
Hallo @ebidel,

I think you missed the note on the Push API site
> Note: Standard has been drastically changed; it’s now based on Service Workers. **Status in Opera for Android: in development.**

Shouldn't this be changed to "Shipped" too?

Thanks for updating :)

**Comment by ebidel** [comment]
Got it
