### ISSUE TITLE
Better link for status of Safari/Webkit on Web Animation

### ISSUE THREAD

**Issue by scheinercc** [GoogleChrome/chromium-dashboard#287]
page:
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webanimationsjavascriptapi?filter=f0800003f
... afaik inheriting from ...
https://www.chromestatus.com/feature/5663463749713920

Current Safari (in Development) reference:
https://lists.webkit.org/pipermail/webkit-dev/2015-November/027771.html

Suggested Safari (in Development) reference:
https://bugs.webkit.org/show_bug.cgi?id=122912

**Comment by myakura** [comment]
yeah, the master bug seems better to link. updated.

**Comment by scheinercc** [comment]
Thanks

**Comment by scheinercc** [comment]
Thanks
