### ISSUE TITLE
"Intent to Ship: JSON.parse source text access" got 2 LGTMs, but counting as 3

### ISSUE THREAD

**Issue by miketaylr** [GoogleChrome/chromium-dashboard#2873]
Not sure how this happened, but when I went to approve in the tool (after emailing an LGTM2), I saw that Yoav had approved twice apparently - and it appears to accept this as 3 LGTMs.

<img width="427" alt="Screenshot 2023-03-28 at 9 25 29 AM" src="https://user-images.githubusercontent.com/67283/228251970-ab9f0ad1-c663-496d-97aa-88a440f2d181.png">

**Comment by miketaylr** [comment]
@jrobbins is it possible for you to remove one of Yoav's approvals, so this I2S shows up in our approval queue? Thanks!

**Comment by jrobbins** [comment]
I deleted that duplicate vote and I will look for other instances like that.
I have deployed a temporary version with a fix so it should not happen again.
I'll leave this issue open until the fix goes through review and our regular release cycle.

**Comment by miketaylr** [comment]
Thank you!
