### ISSUE TITLE
Metrics: Migrate to supported UMA pipeline

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#291]
Apparently we're relying on a deprecated data pipeline.  Need to work with uma-team to figure out the right path for sucking data out of UMA for the chromestatus dashboard.

**Comment by ebidel** [comment]
Somewhat related: https://github.com/GoogleChrome/chromium-dashboard/issues/98 (label the timeline with stable milestones).

**Comment by ebidel** [comment]
This is been fixed for a while. The new task is to switch to the new Blink.UserCounter: https://github.com/GoogleChrome/chromium-dashboard/issues/414
