### ISSUE TITLE
Missing Origin Trials stage

### ISSUE THREAD

**Issue by anaskim** [GoogleChrome/chromium-dashboard#2916]
**Guide UX Feedback**
I don't see the Origin Trials field in the feature [Align clipboard async API read/write HTML format with DataTransfer API](https://chromestatus.com/feature/5716132676763648).

![image](https://user-images.githubusercontent.com/77755715/232099990-4b62f568-9d3e-4bc9-ab81-2565f2bc59dd.png)

and I can't add the Origin Trials stage either

![image](https://user-images.githubusercontent.com/77755715/232100900-774289ec-edcc-47bb-9026-c61a0bf49157.png)

Is there a way to add it to the feature?

**Comment by jrobbins** [comment]
The process does not require an origin trial if you are just making a web-facing change to existing code.
https://www.chromium.org/blink/launching-features/#psa-process
You could generate your own intent-to-experiment email and send it to blink-dev and still do an origin trial.

Or, if you are doing more than a code-only change, you could create a different feature entry with feature type "Existing feature implementation".  Unfortunately, chromestatus does not allow changing of the feature type.

**Comment by jyasskin** [comment]
I believe this is a specific case of #3363, "Make it easier to recover from picking the "wrong" feature type". Feel free to reopen it if I got that wrong.
