### ISSUE TITLE
Clean install doesn't install bower

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#295]
Should `bower` be added to the dependencies somehow so that `npm install` knows to add it?

```
npm install
...
> chromestatus-dashboard@ deps /usr/local/google/home/rbyers/code/chromium-dashboard
> rm -rf static/bower_components; bower install

sh: bower: command not found
```

Installing it manually (`npm install -g bower`) got past the problem for me.

**Comment by ebidel** [comment]
Yep, it should.

**Comment by ebidel** [comment]
Actually, just going to add this to the README. It's recommended `bower` is installed globally and `npm install` will install it locally.
