### ISSUE TITLE
Integrate stars from feature bugs on Chromestatus

### ISSUE THREAD

**Issue by drufball** [GoogleChrome/chromium-dashboard#296]
Chromestatus entries have a link to their corresponding owp-launch bug. We should add UI directly in Chromestatus that allows developers to star the bug directly on Chromestatus [P1] and shows the number of stars for the bug [P2]

**Comment by RByers** [comment]
Note that [status.modern.ie](https://status.modern.ie) has nice treatment here - listed as "votes".

**Comment by robnyman** [comment]
Showing stars is a good idea, and voting to gauge interest and popularity is also one of the parts in the feedback initiative. Let's discuss more in that context, and to see the possible overlap!

**Comment by clelland** [comment]
Starring a crbug issue from chromestatus.com would require the user to be signed in to crbug; showing the number of stars may be easier -- these should probably be separate issues.
