### ISSUE TITLE
Offer better bug filing affordances from chromestatus entries

### ISSUE THREAD

**Issue by drufball** [GoogleChrome/chromium-dashboard#297]
Before a feature is launched, provide a link that goes to a new bug prepopulated with blocking:<feature bug>

After a feature is launched, provide a link that goes to a new bug prepopulated with the right component.

**Comment by RByers** [comment]
I guess we'll have to augment the form / data model to include the monorail component corresponding to the feature.  This is probably a good idea anyway.  Is it worth trying to guess the component for all the existing entries, or should this just be optional (defaulting, perhaps, to Cr-Blink)?

Filed bugs should also automatically cc the feature owners.

**Comment by clelland** [comment]
We can do some of the obvious ones, but it would probably be better to let the individual owners set up their own -- I'd send out a PSA to blink-dev asking folks to do it, and follow up in a couple of weeks to catch any features without components.

> Filed bugs should also automatically cc the feature owners.

Shouldn't monorail handle cc'ing feature owners? I'd be worried about naming individuals in chromestatus.com, as ownership changes all the time. Each component *should* have someone triaging it, though.

**Comment by RByers** [comment]
> We can do some of the obvious ones, but it would probably be better to let the individual owners set up their own -- I'd send out a PSA to blink-dev asking folks to do it, and follow up in a couple of weeks to catch any features without components.

Wait a second - maybe asking people to supply the component is silly - we should already have it from the components assigned to the launch bug!  Perhaps we should just try to read those and copy them rather than store this in the database?  Sorry I didn't think of this sooner.  I don't know what the monorail API is like though to know if this is easy to do, but it's almost certainly better then asking devs to update all their feature entries (seems unlikely that many would do so to be honest).

> Shouldn't monorail handle cc'ing feature owners? I'd be worried about naming individuals in chromestatus.com, as ownership changes all the time. Each component should have someone triaging it, though.

Yeah but the owners are often finer grained than the monorail components.  Eg. all of input-dev uses `Blink>Input` but all features have a couple eng owners who bugs should be routed to.  They'll get to the right engineers 0-7 days sooner (given input-dev weekly triage) if we cc the feature owners.

**Comment by clelland** [comment]
> Wait a second - maybe asking people to supply the component is silly - we should already have it from the components assigned to the launch bug!

Interesting... that would be good for newer features, I think. Do existing platform features have reliable data in the launch bugs (or launch bug links in the first place?)

I'll take a look at their API to see how easy that will be to read out.

For brand new features, should be using data from chromestatus.com to *fill out* the launch bug?

> They'll get to the right engineers 0-7 days sooner (given input-dev weekly triage) if we cc the feature owners.

Good point. I'll make sure to add them to the CC list for bugs.

**Comment by ebidel** [comment]
@RByers just to be clear, we'd still store the user's choice in our db? We're just talking about prepopulating th component names vs. freeform entry?

**Comment by clelland** [comment]
Yes, I think that we should allow owners to fix or adjust these items after pre-populating. If features/components get reorganized in monorail, we shouldn't have to back to change the original launch bug just to get the right component assigned here.

Then we can do a one-time import for existing features, and let new features get populated from the launch bug, if that is entered.

**Comment by RByers** [comment]
Why store it in our DB at all?  The component for any newly filed bug should ALWAYS be the same as whatever the components currently are for the launch bug.  If we have some way of reading the components on the launch bug anyway, then trying to also store a component in our DB seems to just add opportunity for things to get confusing / out of sync.

**Comment by ebidel** [comment]
I'm worried about perf reading live data from Monorail.

**Comment by RByers** [comment]
> I'm worried about perf reading live data from Monorail.

If we do this only when you click on the "new bug" link, then it shouldn't be noticeable (worst case makes the link click take twice as long).  We could even just ask the monorail team for some integration - eg. a template argument we can pass that means "copy the components from bug XXX".  I'm guessing that would be trivial for them.

**Comment by RByers** [comment]
[Monorail feature request filed](https://bugs.chromium.org/p/chromium/issues/detail?id=627670).

**Comment by ebidel** [comment]
Ah cool. Makes sense. I wasn't completely sure where the integration point
was for us.

**Comment by RByers** [comment]
For now should we just have a link for filing with just 'Blink' as the component, and worry about how best to add the component as a separate step?

**Comment by ebidel** [comment]
That seems like a reasonable first step.

**Comment by clelland** [comment]
New pull request #328 doesn't include the components field; just the "file bug" button. 'Blink' is auto-filled as the component.

**Comment by clelland** [comment]
It looks like the monorail JSON endpoints are all either admin- or internal-only :(

I suppose we could XHR an issue detail page, and scrape the components with something like `document.evaluate("//div[@id='meta-float']//th[.='Components:']/../td")`, but that's pretty brittle. We should probably put some effort into getting a proper API exposed from crbug instead.

**Comment by RByers** [comment]
Yeah, this is all Chrome team - so if the feature is worth having, then it's worth doing right across monorail and chromedash.  In fact, I'm sure the monorail folks would be happy to accept pull requests if you're interested in looking into it.  jparent@ is probably the main person to talk to.

The file a bug link on /features looks great!  Should we also have a similar link in the /feature/XXX page do you think?

**Comment by clelland** [comment]
We should, yes -- I'll add that (it's generated differently, so I had just tackled them one-at-a-time)

**Comment by RByers** [comment]
Yep, makes sense - thanks!

**Comment by clelland** [comment]
Filed #331 for making all of the icons consistent between the list and detail pages.
