### ISSUE TITLE
Nav links for Chrome 16 + 17 don't work because no data for those versions

### ISSUE THREAD

**Issue by drufball** [GoogleChrome/chromium-dashboard#299]
We should either remove the side nav links for Chrome 16+17, have them jump to Chrome 18, or create dummy headers for those versions so the links can jump to them.

**Comment by jpchase** [comment]
I would rule out creating dummy headers for versions without features, given the discussion in #307 about changing the way features are listed.

I think jumping to an adjacent version is potentially confusing. If the user clicks version X, and ends up on version X+1 (or even X+2), it could seem like a bug. This is more likely when version X+1 has enough features that the header for the earlier version (i.e. X - 2) isn't visible on the screen. For example, try it with version 8, which does not have data.

Removing the side nav links for versions without features might also be confusing, especially if that version is at the top of the list. It seems unlikely with even smaller features having entries, but it's possible that the canary/dev/stable release would not have any features. That would leave an odd gap at the top of the side nav list.

From an implementation perspective, the list of versions is populated independently from the features. That complicates the approach of removing versions (e.g. it could cause flashes in the content).

I see two reasonable options for now:
1) Do nothing. Users click on 16, notice no scroll changes, then click adjacent versions (or scroll the list) and soon figure out that there's no features in 16 
2) Disable/add note for versions without features. This could potentially happen on load, or only when a user actually clicks on the version

Thoughts?

In the meantime, I'll do some more hacking to see if (2) is feasible without too much work.

**Comment by ebidel** [comment]
(2) should be easy to do. When users click a milestone, https://github.com/GoogleChrome/chromium-dashboard/blob/6a7df234a812158c59a0d8ea4da749091082378c/static/elements/chromedash-featurelist.html#L190 knows if there are features for that milestone.

**Comment by ebidel** [comment]
This is fixed now that we're doing filtering when a version is clicked.
