### ISSUE TITLE
Text insertion is shown instead of cursor when hovering over sample type buttons

### ISSUE THREAD

**Issue by drufball** [GoogleChrome/chromium-dashboard#300]
Go to https://www.chromestatus.com/samples and hover over any of the left navigation buttons ('DOM', 'File APIs', etc.). A text insertion cursor is shown instead of the normal cursor that shows over buttons.

**Comment by RByers** [comment]
Can be fixed with a rule like:
```css
paper-item {
  cursor: pointer;
}
```
I'm surprised `paper-menu` doesn't have a cursor by default, maybe a Polymer bug?  This [demo page](https://elements.polymer-project.org/elements/paper-menu?view=demo:demo/index.html&active=paper-menu) has it, but it's not clear to me why our usage here doesn't.

**Comment by ebidel** [comment]
Yea, the demo page defines the custom property:

```
paper-item {
  --paper-item: {
    cursor: pointer;
  };
}
```
