### ISSUE TITLE
Create a script to populate your environment 

### ISSUE THREAD

**Issue by jcscottiii** [GoogleChrome/chromium-dashboard#3007]
Taking inspiration from [wpt.fyi](https://github.com/web-platform-tests/wpt.fyi#setting-up-your-environment), it would be nice to have an optional script that will read information from staging to populate your local environment.

wpt.fyi currently has:

- bash [script](https://github.com/web-platform-tests/wpt.fyi/blob/main/util/docker-dev/dev_data.sh), which calls
- a Makefile [target](https://github.com/web-platform-tests/wpt.fyi/blob/main/Makefile#L249) that calls a go program that
- makes public API calls to read data from staging and then populate the local database.

Similarly, we could have:
- npm target that calls
- a python program that makes API calls to staging to read data and populates the local database.

**Comment by jphysicsx17** [comment]
hii assign this to me

**Comment by jyasskin** [comment]
A hint to whoever picks this up: there's a route handler to import some data from JSON at https://github.com/GoogleChrome/chromium-dashboard/blob/fe936c92f6aeb0d4daee4538e4cce12341d620c0/api/dev_api.py#L64-L91, and a commented-out route to call it from the dev server at https://github.com/GoogleChrome/chromium-dashboard/blob/fe936c92f6aeb0d4daee4538e4cce12341d620c0/main.py#L293.

**Comment by jphysicsx17** [comment]
hey I am not getting how to start  can you give me some  more hint
