### ISSUE TITLE
Serious issue with live caption in Chrome, causing significant difficulties for users

### ISSUE THREAD

**Issue by minhaics** [GoogleChrome/chromium-dashboard#3011]
Hi Chrome Dev Team,

I am using the live caption feature and have noticed that it is not working well, unlike the automatic captioning feature on YouTube. In the live caption feature of Chrome, every time a sentence ends or there is a pause in speech, it automatically inserts punctuation marks, causing the text to jump, become disorganized, and constantly flicker. This creates a visually unpleasant experience for users. Please consider adding an option to disable the automatic insertion of punctuation marks and automatic capitalization of the first letter of each sentence.

I hope that Chrome's live caption can function similarly to what YouTube has implemented.

Thank you!

Best regards,

**Comment by minhaics** [comment]
- [ ]

**Comment by jrobbins** [comment]
Thank you for your submission. Unfortunately, this is not where you report Chrome bugs. This is where you report bugs with [Chrome Status](https://chromestatus.com/). To report a Chrome bug go to https://bugs.chromium.org/.
