### ISSUE TITLE
Ability to choose between 'stack rank' and 'timeline' disappears on narrow viewports

### ISSUE THREAD

**Issue by drufball** [GoogleChrome/chromium-dashboard#302]
When the viewport narrows enough, the buttons to switch between timeline view and stack rank for feature popularity disappear and there is no way to change views.

![image](https://cloud.githubusercontent.com/assets/5472050/16741998/b142fe88-475a-11e6-8f9d-97437e42431e.png)

**Comment by drufball** [comment]
wider viewport with buttons:

![image](https://cloud.githubusercontent.com/assets/5472050/16742015/c914b218-475a-11e6-9a08-a2b649947175.png)

We could easily show these in a row across the top.

**Comment by jpmedley** [comment]
@jrobbins This appears to still be true.

**Comment by shivamag00** [comment]
Hi @drufball . I would like to take up and solve this issue as suggested by chromium's GSOC page.

**Comment by Lord-Aman** [comment]
I would like to work on this UI issue and to enhance the  UX  @drufball @jpmedley...

**Comment by shivamag00** [comment]
@jrobbins @jpmedley @drufball, I have tried to fix this issue and raised the following PR. Please review and let me know if any modifications are required
#1202

**Comment by jrobbins** [comment]
I think what is needed instead is a responsive UI approach.   We have conditional CSS based on with width of the viewport, but in the case where the viewport is narrow, we currently hide the side navigation buttons.  The missing part of that implementation is that we should still offer those side-nav elements in a way that does not use up horizontal space on the page.  Two common approaches to that are (1) introducing a hamburger menu to the site or some button that would show the side nav temporarily overlapping other content on the page, or (2) displaying the side-nav items in a a horizontal layout across the top of the main content area.

**Comment by shivamag00** [comment]
@jrobbins Thank you for clarifying the two approaches. I have made a new PR #1220  in which I have followed the second approach.

**Comment by jrobbins** [comment]
The new links show up on the all properties pages, but there are also the animated properties pages and the all features pages.  So, we just need to add them there too.

**Comment by shivamag00** [comment]
Okay @jrobbins. I will add them there too.

**Comment by shivamag00** [comment]
@jrobbins, I have raised CL #1256 which should close this issue.
