### ISSUE TITLE
mathtex displays \mathcal characters as square

### ISSUE THREAD

**Issue by sophial05** [GoogleChrome/chromium-dashboard#3057]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
When I use google chrome to open an HTML page (generated from RMarkdown), any pages with mathtex (colab pages, etc), the mathcal characters appear as squares. 

**To Reproduce**
see https://meta.stackexchange.com/questions/384924/i-think-there-is-a-mathjax-bug-for-mathcal-typesetting-on-some-platforms

**Expected behavior**
mathcal characters are displayed as square. 

**Additional context**
See https://meta.stackexchange.com/questions/384924/i-think-there-is-a-mathjax-bug-for-mathcal-typesetting-on-some-platforms user [Davide Cervone](https://meta.stackexchange.com/users/161253/davide-cervone)'s response: "The HTML-CSS renderer in MathJax v2 tries to detect whether there are local copies of the MathJax or STIX fonts and will use those in place of web-based fonts if they are available (to reduce the amount of information that a user must download over the network). Apple has shipped the STIX1 fonts as part of Mac OS and iOS for a number years, but in Ventura, they have switched to the STIX2 fonts. These are packaged differently (the STIX1 fonts came in 29 separate fonts, but STIX2 combines these into 5, one each for regular, bold, italic, and bold-italic, plus a math font). In order to try to keep things backward compatible, Apple still allows access to the STIX1 fonts by (what appears to be) mapping the original 29 fonts into the new 5 fonts. This is largely effective, but not completely. In particular, the calligraphic characters are not part of the Unicode standard, and so STIX includes them in the Private Use Are (PUA) of their fonts. Unfortunately, the location in the PUA Changed between STIX1 and STIX2, and Apple mapping from the old fonts to the new ones doesn't take that into account.

The upshot is, when MathJax asks the local system whether STIXGeneral-Regular (the old STIX1 font) is available, Ventura says "yes" and MathJax believes that the 29 original fonts are there, and tries to use them in the layout that the original fonts actually have. But in Ventura, the calligraphic characters are not in the same location, so you get the missing character symbol instead.

This issue only affects the HTML-CSS output, since it is the only one that uses local STIX fonts. So if you switch to the CommonHTML or SVG output (using the MathJax contextual menu if you are a user, or changing the configuration file if you manage the website), or configuring MathJax to not look for local STIX fonts, then that should show these characters as they should be. Also, version 3, and the upcoming version 4, doesn't use local STIX fonts, and so updating to a current version of MathJax would also resolve the issue."

This problem has persisted since the Ventura update. Could you please fix it as it is really inconvenient.

**Comment by jrobbins** [comment]
Thanks for the detailed report.  However, that is a problem with the chrome browser rather than chromestatus.com.  You should file the issue at http://crbug.com/new.
