### ISSUE TITLE
Feature names don't match the code

### ISSUE THREAD

**Issue by mfreed7** [GoogleChrome/chromium-dashboard#3059]
See, for example, this use counter:

https://chromestatus.com/metrics/feature/timeline/popularity/4191

That is listed as "ValidPopupAttribute", yet in the Chromium code, [that is called "ValidPopoverAttribute"](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/mojom/use_counter/metrics/web_feature.mojom;l=3515;drc=851b8bd317b3af1a678b72e48dbd791954e373ed). It is similarly listed in tools/metrics/histograms/enums.xml with the same name. Yet Chromestatus I believe cached the old name before it was [renamed](https://chromium-review.googlesource.com/c/chromium/src/+/3991667). I'm guessing there's some restriction on renaming entries, but nothing in web_feature.mojom says that. Is there a way to get the cache reloaded with new names? In particular for this main use counter for the Popover API, which isn't discoverable via a search for "popover"?

**Comment by jrobbins** [comment]
I believe that this is resolved now.  Please take a look.

**Comment by mfreed7** [comment]
> I believe that this is resolved now. Please take a look.

Awesome! Yes, it looks correct now. Thanks! 😄

**Comment by jrobbins** [comment]
Awesome.

Thanks for the detailed report, that really helped me get to the resolution faster.
