### ISSUE TITLE
Stack rank and timeline features show a list bullet in Firefox

### ISSUE THREAD

**Issue by drufball** [GoogleChrome/chromium-dashboard#306]
https://www.chromestatus.com/metrics/css/animated

The buttons to switch between stack rank and timeline have a list bullet shown:

![image](https://cloud.githubusercontent.com/assets/5472050/16742460/a3162ea0-475c-11e6-85c0-ecfa65c22556.png)

**Comment by drufball** [comment]
Firefox only, sorry!

**Comment by RByers** [comment]
Thanks.  Looks like this is due to [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=25291).  But we should probably be explicit about having no list marker, so I'll fix that.
