### ISSUE TITLE
Bring back RSS on chromestatus.com web

### ISSUE THREAD

**Issue by KiritoKunD2** [GoogleChrome/chromium-dashboard#3068]
Google removed the support for rss on chromestatus webpage. I want to stay up-to-date with it's bugs and features over RSS.

Please bring back RSS.

https://chromestatus.com/features.xml

**Comment by past** [comment]
Perhaps a better way to stay up to date with all browser vendors feature changes is by monitoring https://twitter.com/intenttoship

**Comment by jstenback** [comment]
While I understand the desire to keep using our RSS feed there simply isn't enough demand for it to warrant the resources needed to bring back and continue maintaining that code. Given that alternatives exist, we won't be bringing back the old RSS feed.

**Comment by boghyon** [comment]
> Given that alternatives exist, we won't be bringing back the old RSS feed.

What are the metrics to measure the demand for RSS?  
And what are the alternatives? Not everyone is or want to be on Twitter.
