### ISSUE TITLE
Extra whitespace character to the left of 'timeline'

### ISSUE THREAD

**Issue by drufball** [GoogleChrome/chromium-dashboard#308]
https://www.chromestatus.com/metrics/css/popularity

There is an extra whitespace character to the left of the word timeline:

![image](https://cloud.githubusercontent.com/assets/5472050/16742548/f1b815fa-475c-11e6-95e4-1ec89e2cb76f.png)

**Comment by clelland** [comment]
I don't see it (in code or on screen) -- are you just looking at the fact that the labels are centered in the buttons?

**Comment by RByers** [comment]
Yeah that's just the `text-align: center`.  Here's what it looks like if you remove that and replace it with `padding-left: 3em`:

![image](https://cloud.githubusercontent.com/assets/1280419/16746716/9db2bbae-4789-11e6-80a1-a26912266aaf.png)

better?

**Comment by vprusso** [comment]
Is this bug closed? It seems like it's an aesthetic call whether or not to center the "timeline" text or not. Has there been any consensus on preference for this? Thanks!

**Comment by ebidel** [comment]
Think we can close. This is WIA according to the current design.
