### ISSUE TITLE
Eliminate touch scroll blocking

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#310]
Once we have #309 (and so can measure the improvement), convert the main `touchstart` listeners on the features view to be passive to eliminate touch scroll blocking.

**Comment by ebidel** [comment]
This may need a change in Polymer core's gesture stuff. The handlers are defined declaratively: https://github.com/GoogleChrome/chromium-dashboard/blob/6a7df234a812158c59a0d8ea4da749091082378c/static/elements/chromedash-feature.html#L64

We can switch to imperative `listeners` (https://www.polymer-project.org/1.0/docs/devguide/events#event-listeners) for the time being, but it would be nice to upstream this to Polymer somehow.

**Comment by RByers** [comment]
Thanks.  I'll look into what's required to upstream this into Polymer as part of this.
