### ISSUE TITLE
Improve small-screen UX

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#311]
The site has some glitches on a phone.  Eg:

- When in portrait:
 - The feature list scroller can be larger than the screen meaning the scrollbar thumb will eventually move off the screen, and only once you've scrolled to the bottom of the list can you easily scroll the document to get it into view
 - The left nav entries are unavailable
 - The top buttons are split into 2 rows taking up a lot of space (and looking pretty silly with a single full-width "JS/HTML metrics" button.
- When in landscape:
  - With some phone screen sizes (eg. Lumia 950 XL 853x480) the scrollable list is too short to show even a single entry.

Maybe we should redesign this to be more of a full-page scrolling list with appearing header / side-nav as needed?  Maybe using something like [paper-scroll-header-panel](https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=demo:demo/transform-header-6.html&active=paper-scroll-header-panel)?

@mdittmer @ebidel @drufball WDYT?

**Comment by drufball** [comment]
#302 talks about the left nav entries being unavailable on the feature popularity pages as well

**Comment by drufball** [comment]
Also the paper-scroll-header-panel suggestion SGTM. Hamburger menu on the left is perfect for the disappearing nav.

**Comment by ebidel** [comment]
p-s-h-p is a natural fit. We should have moved to it a long time ago. Also https://elements.polymer-project.org/elements/app-layout for a drawer panel.

I can tackle this one unless someone else wants to.

**Comment by RByers** [comment]
Yeah this is a big enough / UX heavy enough change that (at this point) it's probably better for you to take it than one of us newbies.

**Comment by ebidel** [comment]
I've begun migrating the frontend to use Polymer's newer app-* layout elements.

![screen shot 2016-07-14 at 7 52 38 pm](https://cloud.githubusercontent.com/assets/238208/16862199/9a7befb2-49fc-11e6-9d9e-4ca5ec9b87d2.png)
![screen shot 2016-07-14 at 7 52 58 pm](https://cloud.githubusercontent.com/assets/238208/16862200/9a92564e-49fc-11e6-97d4-0bb50006aa9a.png)
![screen shot 2016-07-14 at 7 53 02 pm](https://cloud.githubusercontent.com/assets/238208/16862201/9aa6eab4-49fc-11e6-959b-2712bb813866.png)
