### ISSUE TITLE
Intent marked approved by me when I had not approved it

### ISSUE THREAD

**Issue by dbratell** [GoogleChrome/chromium-dashboard#3154]
According to the tool, https://chromestatus.com/feature/5714791975878656 was marked approved by me and did not show up in my UI after it had two other approvals. The shipping request was made last night and unless I have been sleep walking I don't know how I could have done that. There is no log that tells me when it happened but maybe you have access to some development log.

Is it an approval for some experiment or belonging to some other chrome status event?

(I have now approved it on the mailing list so the world is in sync, at least for this intent)

**Comment by jrobbins** [comment]
It looks like this entry already had an intent-to-ship thread in Sept 2022.
https://groups.google.com/a/chromium.org/g/blink-dev/c/hSnGUOXTXPE/m/Hj1tjvOICAAJ

The votes from that time were captured from that blink-dev and were still in place when the second intent thread was posted in July 2023:
https://groups.google.com/a/chromium.org/g/blink-dev/c/DaKH9F7X3Lc/m/meojkug6AQAJ
