### ISSUE TITLE
Cannot debug parts of the site that rely on UMA

### ISSUE THREAD

**Issue by mdittmer** [GoogleChrome/chromium-dashboard#318]
There currently is no way to trick a local instance into rendering UMA-related pages. This is a problem for debugging these parts of the site. For example, #220 cannot be debugged until this is fixed.

**Comment by ebidel** [comment]
I've put some time into trying to export the prod db and import it to the local dev db. It looks like there are issues with the current SDK. Filed https://code.google.com/p/googleappengine/issues/detail?id=13119

**Comment by ebidel** [comment]
FYI, I've set the site up to pull from the live prod endpoints when you're on localhost. This can be overridden in settings.py by changing `PROD = False`
