### ISSUE TITLE
Use autoprefixer

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#319]
https://github.com/GoogleChrome/chromium-dashboard/blob/master/static/sass/_vars.scss and other .scss files define the vendor prefixes. It would be better to use autoprefixer to generate the .css and only include the appropriate prefixes. Will be good for perf too (smaller files).

Dependent on https://github.com/GoogleChrome/chromium-dashboard/issues/290

**Comment by jpmedley** [comment]
@jrobbins This seems like it's not relevant any more. Can I close it?

**Comment by jrobbins** [comment]
Correct, this is obsolete.
