### ISSUE TITLE
URL Status bar in bottom left corner covers the context menu

### ISSUE THREAD

**Issue by mrfzd** [GoogleChrome/chromium-dashboard#3233]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
When right-clicking (close to the left side of the screen) for any context menu dropdown to pop open on a shrunk window size, the context menu is displayed under the URL status bar.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any website, in this instance, I have tried it on YouTube
2. Shrink the browser window size and make the window size in such a way to sit in the middle of your desktop screen
3. Right-click on the channel picture for the context menu to appear
4. The context menu is now shown behind the URL status bar

**Expected behaviour**
The URL status bar in the bottom left corner should detect the dropdown menu being detected and should hide the status bar to not cover the context menu items.

**Screenshots**
![image](https://github.com/GoogleChrome/chromium-dashboard/assets/7137600/4135b2a7-1549-491a-9e1e-34bc972fe76e)

**Comment by jrobbins** [comment]
Thanks for the bug report, but this is the wrong place to report it.  This issue tracker is only for the chromestatus.com website.  Bugs with the chrome browser should be reported at https://crbug.com/new.
