### ISSUE TITLE
Remove the old metrics note from the timeline

### ISSUE THREAD

**Issue by past** [GoogleChrome/chromium-dashboard#3245]
In the timeline view we always show 2 notes to help viewers better understand the charts ([example](https://chromestatus.com/metrics/feature/timeline/popularity/465)). The first one says:
> Note: on 2017-10-26 the underlying metrics were switched over to a newer collection system which is [more accurate](https://groups.google.com/a/chromium.org/forum/#!msg/blink-api-owners-discuss/IpIkbz0qtrM/HUCfSMv2AQAJ). This is also the reason for the abrupt spike around 2017-10-26.

It's been 6 years since that change and I don't think there is a way to view page loads from that time any more, so the note is no longer useful.

On the contrary, the second note remains useful since the HTTP Archive chart shows data going back far enough.

**Comment by jrobbins** [comment]
The 2017 data is still visible if the user clicks the "Show all historical data:" checkbox near the top of the page.

**Comment by past** [comment]
Ah, I hadn't noticed that. Agreed that ideally we would show the note when the checkbox is ticked.
