### ISSUE TITLE
Metrics meter should truncate the label when it overflows

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#325]
Check out https://www.chromestatus.com/metrics/css/popularity with a narrow viewport:

![image](https://cloud.githubusercontent.com/assets/1280419/16781743/a000d6cc-484a-11e6-9dff-c37c9a5b00ac.png)

This is inside Polymer's `x-meter` element.  We should probably be applying the `overflow: hidden; text-overflow: ellipsis;` rules to it as well (like we do for the label to the left).

**Comment by ebidel** [comment]
We may also want a min-width on those css property names.

**Comment by jpmedley** [comment]
I don't know when we fixed this, but we did.

![image](https://user-images.githubusercontent.com/8204171/109179935-40e00400-773f-11eb-9328-8fd16184e39f.png)
