### ISSUE TITLE
"Missing Prerequisites" dialog doesn't populate

### ISSUE THREAD

**Issue by josepharhar** [GoogleChrome/chromium-dashboard#3262]
**Describe the bug**
When I click "Draft Intent to Ship email" in this chromestatus entry, a dialog that says "Missing Prerequisites" pops up instead of the draft email, but the dialog is empty and a javascript error is thrown.

**To Reproduce**
1. Go to https://chromestatus.com/guide/edit/5126108151808000
2. Click on "Draft Intent to Ship email"

**Expected behavior**
A list of missing prerequisites should appear in the dialog

![Screenshot 2023-08-16 at 1 24 09 PM](https://github.com/GoogleChrome/chromium-dashboard/assets/7681467/7f3c2e75-1a4a-4378-bcc8-4d543ecf2de1)

**Comment by josepharhar** [comment]
I used the DevTools debugger to figure out which field I was missing - it was the "Finch feature name" field

**Comment by jrobbins** [comment]
D'oh.  I will work on a fix now.

As a work-around, and in fact the preferred way to generate an intent email going forward,
follow the instructions here:
https://github.com/GoogleChrome/chromium-dashboard/wiki/Feature-Owner-Tasks#requesting-reviews
