### ISSUE TITLE
I hate it. My notifications are 👎

### ISSUE THREAD

**Issue by Jayboyok** [GoogleChrome/chromium-dashboard#3264]
Use this template to provide feedback on the new Blink launch process and Guide UX for editing features.

**Process Feedback**
Was anything unclear?  Is there something that you need represented in the process? Is it possibility that some phone numbers have been formated incorrectly? I can't call or text certain 470 phone #. 2nd. When I ping or port scan IP, time out is within ms. 

3 My notifications don't popup on device like they use to do conveniently. My public IP address shows no port. Are my text messages and web messages handled by chrome browser now? I'm in Atlanta, Ga. 

**Guide UX Feedback**
Did you encounter any errors?  Was something unclear?  Did the tool prevent you from doing something that you need to do?  Please provide the URL of the page or a screenshot, and indicate the affected part of the page.

**Comment by Jayboyok** [comment]
![Screenshot_20230817-222214](https://github.com/GoogleChrome/chromium-dashboard/assets/142549733/f70daf01-eb7e-4d2d-ac1b-61c8bd871155)

**Comment by Jayboyok** [comment]
So many changes. Please fix

**Comment by jstenback** [comment]
This issue tracker is for the website chromestatus.com, not the Chrome browser. Closing this issue.
