### ISSUE TITLE
Please op my port's. When I adjust chrome flags, I then receive text messages to my device. 

### ISSUE THREAD

**Issue by Jayboyok** [GoogleChrome/chromium-dashboard#3266]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] Why when I adjust chrome flags. I then get text messages? Otherwise, only 1 or 2 individuals are able to reach me. Why is this happening? I want all my port's open for incoming messages. please 

**Describe the solution you'd like**

**Additional context**

**Comment by jrobbins** [comment]
This issue tracker is only for problems with chromestatus.com.
You can report a chrome bug by using the "Report an issue..." menu item under the "Help" menu.
