### ISSUE TITLE
Please fix my network 

### ISSUE THREAD

**Issue by Jayabsts** [GoogleChrome/chromium-dashboard#3289]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**

**To Reproduce**
1. Go to '...'Im not getting any text messages notification. Please tell me if GitHub had closed my server. 
4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen. Secondly, I believe my number format or keyboard may be adding additional symbols to numbers. I'm just bewildered. My public ip address is showing miles away. I'm in Atlanta GA. Please fix

**Additional context**

**Comment by Jayabsts** [comment]
Google play store is accumulating over 400 gb of data. Is there a path to where my text messages are going

**Comment by Jayabsts** [comment]
When I check local connection. I see timeout. What is aws. Why do I see them on my network

**Comment by jrobbins** [comment]
This issue tracker is only for problems with chromestatus.com.   I don't know anything about problems with android or play store.
