### ISSUE TITLE
Add a SW for offline/LoFi support?

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#329]
The data seems easily cachable, but there's some server-side templating right?  Does it make sense to try to have some sort of offline (or more important lofi) experience?  @ebidel @drufball WDYT?

If we do this, then we might as well also add a manifest to make it a PWA (not many would add it to their homescreen, but I would!).

**Comment by RByers** [comment]
If we wanted a great offline experience, perhaps we could rewrite the server-side templating to be client side?

**Comment by ebidel** [comment]
+1 on making a PWA. Always meant to, just never had the time.

I don't think anything will change regarding the SSR of templates. The app basically falls under the app shell approach atm and it's not a SPA. That's prime for service worker caching.

**Comment by ebidel** [comment]
Fixed
