### ISSUE TITLE
Get off 

### ISSUE THREAD

**Issue by Tasteofteal** [GoogleChrome/chromium-dashboard#3297]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**

**To Reproduce**
4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behavior**

**Additional context**

**Comment by Jayol1234** [comment]
When I ping ip addyy. The time out is to fast. You need to slow down the browser. My device is 4g, and I'm not receiving calls and text messages. My carrier mnc is 240 not 260. Has the string in java strip been changed? I'm unable to receive any messages from people in my Google contact list. My phone number is 4045127737

**Comment by Jayol1234** [comment]
![Screenshot_20230905-004844](https://github.com/GoogleChrome/chromium-dashboard/assets/144083560/ed5a39fc-5049-462c-9c09-50a142527ae4)
