### ISSUE TITLE
Feature page should use same icons as feature list

### ISSUE THREAD

**Issue by clelland** [GoogleChrome/chromium-dashboard#331]
Currently the feature page uses the string "edit" in place of the pencil icon that appears on the feature list, and doesn't include the origin trial icon or new bug link.

**Comment by clelland** [comment]
Example after PR #332:
<img width="549" alt="screen shot 2016-07-14 at 11 21 06 am" src="https://cloud.githubusercontent.com/assets/45853/16845251/400b458c-49b6-11e6-915a-8730d1a9d2a8.png">

**Comment by ebidel** [comment]
Fixed.
