### ISSUE TITLE
Use "Origin Trials" naming instead of "experimental framework"

### ISSUE THREAD

**Issue by jpchase** [GoogleChrome/chromium-dashboard#333]
There's basic support for setting feature status to "available as an origin trial". This support was added before the grand renaming of "experimental framework" -> "origin trials".

Need to apply the appropriate renaming throughout the UI. Should also rename in the code to avoid confusion.

**Comment by RByers** [comment]
I was thinking this too - thanks!

**Comment by beaufortfrancois** [comment]
I'll take care of this.
