### ISSUE TITLE
Intent to Ship email template does not include reason for why web-platform-tests are not possible

### ISSUE THREAD

**Issue by davidben** [GoogleChrome/chromium-dashboard#3335]
**Describe the bug**
The Blink process is designed for the web platform, and thus expects web-platform-tests. WPT is not well-suited for testing networking features, which are web-platform-visible, but below most abstractions in the web platform proper. For example, any features that involve TLS cannot be tested with WPT: https://github.com/web-platform-tests/wpt/issues/20159

The form in chromestatus.com tries to account for this by having both a "Web Platform Tests" checkbox and a freeform "Web Platform Tests Description" field. The latter's description says:

> Please link to the [results on wpt.fyi](https://wpt.fyi/results). If any part of the feature is not tested by web-platform-tests, please include links to issues, e.g. a web-platform-tests issue with the "infra" label explaining why a certain thing cannot be tested ([example](https://github.com/w3c/web-platform-tests/issues/3867)), a spec issue for some change that would make it possible to test. ([example](https://github.com/whatwg/fullscreen/issues/70)), or a Chromium issue to upstream some existing tests ([example](https://bugs.chromium.org/p/chromium/issues/detail?id=695486)).

However, the Intent-to-Ship email template ignores this field and only displays:

> Is this feature fully tested by web-platform-tests?
> No

This is confusing to Blink owners, who are now missing important context. The email template should not elide this context.

**To Reproduce**
1. Launch a networking feature
2. Leave WPT checkbox off, follow the instructions to link a bug for why WPT is not possible
3. Send Intent to Ship based on instructions

**Expected behavior**
Blink owners see the WPT test explanation without having to spend an email round-trip asking why.

**Comment by past** [comment]
@jrobbins is there anything more to be done here?

**Comment by jrobbins** [comment]
This fix went live last week.
