### ISSUE TITLE
Add 'Under investigation' vendor status

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#335]
From https://github.com/GoogleChrome/chromium-dashboard/issues/114#issuecomment-231431801 it sounds like @jacobrossi would prefer we not use any of our existing status entries for their "Under consideration - Low Priority" status.  Can we just add a new one that's basically the same as "no public signals" except includes a link showing that it's at least on a list to be evaluated?

@mdittmer @ebidel WDYT?

**Comment by jacobrossi** [comment]
Having slept on it :-), if it's easiest for you, "no public signals" is fine. I cringe a bit because it sounds like Microsoft doesn't know the feature exists, but I suppose it can just mean "hasn't given an indication up/down".

**Comment by RByers** [comment]
Yeah, it certainly doesn't mean there hasn't been any thought.  As long as we include the link to the Edge status dashboard, perhaps that's enough to address your concern?  I'm not opposed to adding more statuses if they convey more information (Eg. we probably need a 'Shipped - prefixed' status since that's not really the same thing as "shipped").

**Comment by jacobrossi** [comment]
The link would probably be sufficient.  For prefixes, I've been inclined more recently to start moving towards anything prefixed/behind-flag/experiment as a single "Experimental" status and perhaps detailing the specific mechanism you can try the API with in the summary:
![image](https://cloud.githubusercontent.com/assets/2118562/16846747/7d103e2e-49a2-11e6-88c6-3641b8a10b1b.png)
![image](https://cloud.githubusercontent.com/assets/2118562/16846788/a343b896-49a2-11e6-8efe-eadaf5534f6d.png)
The idea is to further downplay prefixed stuff as less usable.

**Comment by ebidel** [comment]
Now that there are other dashboards we may want to align with what language others are using.

https://webkit.org/status/: "Under consideration", "Not considering"

https://platform-status.mozilla.org/: "Considering", "No Signals"

IMO, any feature that doesn't have an entry on another dashboard should be: "No signals"

Experimental features in other dashboard map to our "In development"

**Comment by RByers** [comment]
I'm fine with "have dashboard entry but haven't formed much opinion yet"-type status getting reported as "no public signals" with a URL.  @ebidel are you happy with that too?

See #336 discussion of prefixed status.

**Comment by ebidel** [comment]
Yea, less changes :)

**Comment by RByers** [comment]
Great, let's call this closed then.
