### ISSUE TITLE
Proposed Issue Shows 'Desktop Chrome' for the Imp Status of Mobile Only Feature

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#337]
The Implementation Status for [this ticket](https://www.chromestatus.com/feature/5682658461876224) reads:

**Desktop Chrome:** Proposed

Yet the feature in question is one that is only available to mobile devices. For a proposed feature there appears to be no way to change this.

**Comment by jpmedley** [comment]
Also, here's [the related discussion on blink-dev](https://groups.google.com/a/chromium.org/d/topic/blink-dev/7iVcwNcO3xw/discussion) for this entry.

**Comment by ebidel** [comment]
@clelland do you want to take this too?

**Comment by clelland** [comment]
This strikes me as a labeling issue -- we're assuming that desktop chrome exposes the complete set of blink features, when that's definitely not true. Should we just change that string to "Chromium", without reference to platform?

(In that case, it highlights the fact that we call out Android as the only specific platform for alternate versioning, when there are features even in desktop chrome that aren't present everywhere -- smooth scrolling, or web bluetooth)

**Comment by clelland** [comment]
Never mind -- it looks like this was already fixed, in #312. The label "Desktop Chrome" has been removed.

**Comment by ebidel** [comment]
@jpmedley can we close this?

**Comment by jpmedley** [comment]
Yes. Thank you.
