### ISSUE TITLE
Why aren't any of my social network apps working. 

### ISSUE THREAD

**Issue by ghost** [GoogleChrome/chromium-dashboard#3383]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**

**To Reproduce**
1. Go to '...' You guys have blocked my server. Grinder admin states there's no reason why app shouldn't run. Why can't I just have default settings? Why are all theses stipulations added to my device. I barely get text messages, and seems everything is running through browser. 
4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen. You guys have my device showing someplace elsewhere. I'm located in Atlanta, GA. The server isn't allowing my text messages to come through and I can't log into social apps, such as grinder. Messages states check your connection, but everything else is working phone. 

**Additional context**
Add any other context about the problem here. I'm a grown consenting adults. Why are so many restrictions attached to my device. I want all my text messages and apps running as usual. I'm not sure what you guys have done. Please restore my settings to default. Chrome is doing way to much

**Comment by Jayboyok43** [comment]
What is rfc? My browser just has swingle lines. I don't see the lock symbol like usual
![Screenshot_20230930-232353](https://github.com/GoogleChrome/chromium-dashboard/assets/146604630/92feacb8-b301-46a9-8b6d-8c5c8286a369)

**Comment by Jayboyok43** [comment]
![Screenshot_20230930-221842](https://github.com/GoogleChrome/chromium-dashboard/assets/146604630/288fe81f-c0d3-4857-83e8-dac3bdb0f06c)

**Comment by Jayboyok43** [comment]
![Screenshot_20230930-232353](https://github.com/GoogleChrome/chromium-dashboard/assets/146604630/c376aab5-afe7-4a66-bc90-055948e36df6)

**Comment by Jayboyok43** [comment]
![Screenshot_20230930-232403](https://github.com/GoogleChrome/chromium-dashboard/assets/146604630/97cfedb0-49f9-4c90-b8bf-92b0c81a5b7c)

**Comment by Jayboyok43** [comment]
![Screenshot_20230930-215356](https://github.com/GoogleChrome/chromium-dashboard/assets/146604630/bf264e30-bdd7-4dba-9300-769b54327416)

**Comment by Jayboyok43** [comment]
![Screenshot_20230930-232829](https://github.com/GoogleChrome/chromium-dashboard/assets/146604630/b96c0d52-c60f-4be6-8069-ead7632f536e)

**Comment by Jayboyok43** [comment]
Why would you do this. I'm 43 years old. I don't care about data leaks etc. Please restore my server and device settings. Who made these awful discussions? So you need my Driver's licenses
