### ISSUE TITLE
Always show browser-specific citation link in admin UI

### ISSUE THREAD

**Issue by mdittmer** [GoogleChrome/chromium-dashboard#339]
Currently, citation link UI only appears should always when "No public signals" is _not_ selected for the browser vendor in question. It should always be available. For example, the consensus regarding Edge data appears to be that status:"Under consideration", priority:"Low" in the Edge data should map to "No public signals", but provide a citation link.

**Comment by ebidel** [comment]
@mdittmer I think this is fixed right?

**Comment by mdittmer** [comment]
Yes. Fixed by #340.
