### ISSUE TITLE
Email notifications incorrectly say that the feature owner made a change when a reviewer votes

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#3393]
Example of an incorrect email notification:
```
andruud@chromium.org updated this feature:

Relaxed CSS Nesting

Components: Blink>CSS

Implementation status: Proposed

Estimated milestones:

Shipping on desktop	120
Shipping on Android	120
Shipping on WebView	120
Changes:

yoavweiss@chromium.org set review status in https://chromestatus.com/feature/5070369895743488?gate=5158552956305408:
old: no_response
new: approved
```

andruud@chromium.org did nothing to trigger this email, so that line at the top is incorrect.  yoavweiss@chromium.org is correctly cited near the bottom.

**Comment by impact-maker** [comment]
@jrobbins Hi, could you guide on how to reproduce this issue.

**Comment by Tabhi109** [comment]
Hi @jrobbins , Can you please provide a bit more information regarding this issue , I want to solve this and make my first open source contribution.
Looking forward for your reply.

**Comment by obamwonyi** [comment]
I would also love to contribute to this .

**Comment by Rishikesh63** [comment]
@jrobbins & @DanielRyanSmith I would like to work on it.
i can solve this bug using html & javascript or html & python.

**Comment by jrobbins** [comment]
This is still a problem.  See screenshot below.

I started work on this and didn't finish it, so I should be the one to continue on it.  I'll try to get it done this week. 

![image](https://github.com/GoogleChrome/chromium-dashboard/assets/17365/ad6a2e4c-203f-4026-bde9-c0212fd061c8)

**Comment by kshitjj** [comment]
Hey @jrobbins, 

I have made the [PR](#3674)  which I think fixes this issue, would love to get your review :D

**Comment by Rishikesh63** [comment]
@jrobbins  has this solved?
