### ISSUE TITLE
File new bug link 404s

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#341]
Example, clicking the bug link on  https://www.chromestatus.com/feature/5663174342737920 sends me to a 404 page.

**Comment by RByers** [comment]
Strange, works for me

**Comment by RByers** [comment]
Takes me to https://bugs.chromium.org/p/chromium/issues/entry?components=Blink&blocking=625847&cc=nzolghadr@chromium.org which gives me the issue entry.  Monorail flakiness?

**Comment by ebidel** [comment]
How about in an incognito window?

**Comment by clelland** [comment]
In an incognito window, I get a different redirect; to https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fappengine.google.com%2F_ah%2Fconflogin%3Fcontinue%3Dhttps%3A%2F%2Fbugs.chromium.org%2Fp%2Fchromium%2Fissues%2Fentry%253Fcomponents%253DBlink%2526blocking%253D625847%2526cc%253Dnzolghadr%2540chromium.org&service=ah&sacu=1&rip=1#identifier

The 404 you're getting is from www.google.com; I'm not sure what is constructing that link. Possibly monorail itself. Can you try capturing network requests in devtools when you click that link? I'd like to see the chain of redirects that ends up there.

**Comment by ebidel** [comment]
Yea looks like it's Monorail taking you through app engine's sign in flow:
<img width="1211" alt="screen shot 2016-07-14 at 2 57 19 pm" src="https://cloud.githubusercontent.com/assets/238208/16857262/9db31b34-49d3-11e6-8103-19cc0030b039.png">

You get the same thing when you open https://bugs.chromium.org/p/chromium/issues/list in an incognito window and hit "New issue" That handler is requiring auth.

The link it's trying to go to (https://bugs.chromium.org/p/chromium/issues/entry?components=Blink&blocking=625847&cc=nzolghadr@chromium.org) only works for me if I open it in a profile signed into my `@chromium.org` account.

**Comment by clelland** [comment]
https://bugs.chromium.org/p/monorail/issues/detail?id=1563 was filed and fixed today. From a quick glance, I can't tell if that would have created or solved the problem, but I think it fixed it. Can you try again and see if you can reproduce the 404?

**Comment by ebidel** [comment]
Ah! That gets me through but it doesn't look like there are prepopulated fields:
<img width="1182" alt="screen shot 2016-07-14 at 8 16 39 pm" src="https://cloud.githubusercontent.com/assets/238208/16862628/f98cbb3c-49ff-11e6-9589-5410e2aebcee.png">

**Comment by clelland** [comment]
You won't see the prepopulated fields in the form if you don't have permission to change them,  but they'll be added to the issue anyway. I just verified with a couple of bug submissions (since deleted).

**Comment by ebidel** [comment]
Cool. I think we can call this closed then!
