### ISSUE TITLE
Not able to edit Motivation section

### ISSUE THREAD

**Issue by snianu** [GoogleChrome/chromium-dashboard#3450]
Use this template to provide feedback on the new Blink launch process and Guide UX for editing features.

**Process Feedback**
Was anything unclear?  Is there something that you need represented in the process?

**Guide UX Feedback**
Did you encounter any errors?  Was something unclear?  Did the tool prevent you from doing something that you need to do?  Please provide the URL of the page or a screenshot, and indicate the affected part of the page.

For some reason I'm not able to edit the Motivation section in https://chromestatus.com/feature/5176417696612352

**Comment by RByers** [comment]
I think you mean this one, right? https://chromestatus.com/feature/5716132676763648

I also don't see how to change the text under "motivation". In other entries it's under a "start incubating" stage, but I don't see that stage here or any way to add it. Maybe an issue with data migration from the older data format? @jrobbins?

**Comment by snianu** [comment]
> I think you mean this one, right? https://chromestatus.com/feature/5716132676763648

Oops, sorry, you're right.

**Comment by jstenback** [comment]
The motivation field also doesn't appear editable in the "Edit all fields" view.

**Comment by snianu** [comment]
Hi, for some reason, I'm still not able to edit the Motivation field in the ChromeStatus entry page when I click on Edit All Fields:
![image](https://github.com/GoogleChrome/chromium-dashboard/assets/45411397/9169fcf4-ccfc-4470-8413-d209a1136e19)

**Comment by jrobbins** [comment]
I just merged the PR to address this problem.  It will go live as part of our next deployment, which will probably happen on Monday.
