### ISSUE TITLE
Missing approval flags

### ISSUE THREAD

**Issue by ajay-rah** [GoogleChrome/chromium-dashboard#3455]
We are not seeing any approval flags other than API Owners in the Prepare to Ship section. Privacy, Security flags are missing for the following entry.

https://chromestatus.com/feature/5084460341264384

**Comment by jrobbins** [comment]
You created the feature entry using the "web developer facing code change" feature type.
I don't know your feature in detail, but that feature type seems correct.
For that feature type, you don't need the cross-functional approvals unless one of the API Owners asks for them.
https://www.chromium.org/blink/launching-features/#psa-prepare-to-ship


Just make sure that you send an intent email with a subject line starting with "Web-Facing Change PSA:". If you generate the email on chromestatus, it will use that subject line prefix in the preview that you are supposed to copy and paste into the actual email.

If you are sure that you need the cross-functional gates, let me know and I can add them for you.

**Comment by jyasskin** [comment]
This got sent to blink-dev on Oct 27, so I suspect it's resolved.
