### ISSUE TITLE
Click Event Triggering Range Expands on Mobile Devices

### ISSUE THREAD

**Issue by smallCF** [GoogleChrome/chromium-dashboard#3456]
Hello developer：
I have developed a web project, and of course, I have done the adaptation of mobile devices;

I have bound a click event to a certain dom object, and on the web side, I need to click on the corresponding dom object to trigger the event; When I access a mobile device, the trigger event range is doubled
![3f6123141c5dea7a27bf37e8f7723c7](https://github.com/GoogleChrome/chromium-dashboard/assets/50435732/e9ff47b3-b858-4f3e-8862-0b4c5df5fb7d)
The above picture is the dom I wrote. I tested it on both new and old browsers, and it won't have this problem in the old version of the browser
I don't know if it's my problem or if the browser has this bug. I also tested other browsers that use the Google kernel, and the new version will have this problem

**Comment by jstenback** [comment]
For filing issues with Chrome, please use http://crbug.com/new. This issue tracker is only for issues with the website at chromestatus.com. Given you're not sure this is a bug, a discussion on blink-dev@chromium.org might be more appropriate as a starting point.
