### ISSUE TITLE
Typo. error in "Origin trial creation prerequisites" dialog

### ISSUE THREAD

**Issue by LuHuangMSFT** [GoogleChrome/chromium-dashboard#3459]
**Describe the bug**
There are instructions in the UI that appears after clicking on "Request trial creation" button in the Origin Trial section of a feature page. The instructions reference "origin_trials_allows_third_party" but the actual field name is "origin_trial_allows_third_party". 

**To Reproduce**
1. Go to an editable feature page. 
2. Go to the Origin Trial section. 
3. Click on the "Request trial creation" button. 
4. Look at the instructions in the form that appears.

![image](https://github.com/GoogleChrome/chromium-dashboard/assets/53061947/2d0c0b7b-c416-45b0-8513-ef0641f68468)

**Comment by jyasskin** [comment]
Is this related to https://chromium-review.googlesource.com/c/website/+/5067756, that only Googlers can request origin trials?

**Comment by LuHuangMSFT** [comment]
It's not related. The UI above shows "origin_trials_allows_third_party" but it should actually show "origin_trial_allows_third_party".
