### ISSUE TITLE
OT required fields are preventing me from editing all fields

### ISSUE THREAD

**Issue by johannhof** [GoogleChrome/chromium-dashboard#3492]
**Describe the bug**
I'd like to be able to "edit all fields" on features that don't have an OT, or that don't specify 

- Chromium trial name
- WebFeature UseCounter name
- Documentation link

most of which feel like they should be optional, even with an OT...

**To Reproduce**
1. Go to any feature (e.g. https://chromestatus.com/feature/5133113939722240)
2. Click on Edit -> Edit all fields
3. Hit "Submit"
4.

![image](https://github.com/GoogleChrome/chromium-dashboard/assets/2622601/694ed1f4-b41b-4a33-9d5a-a4481d06d120)

**Expected behavior**
Form should submit

**Comment by jrobbins** [comment]
@DanielRyanSmith I'll take a look at this and probably send you a PR.

**Comment by DanielRyanSmith** [comment]
Thanks for bringing this up to us @johannhof! This was a side effect of moving these fields to a separate form, and they should no longer be a part of this page after we land a fixing change.
