### ISSUE TITLE
Why is this happening 

### ISSUE THREAD

**Issue by Hashfixplease** [GoogleChrome/chromium-dashboard#3513]
![Screenshot_20231122-205029](https://github.com/GoogleChrome/chromium-dashboard/assets/151813756/55dd0e1e-ada4-4de5-9a01-5a302f10d5ac)
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
A clear and concise description of what the bug is. Why is the flag on RCS . I'm not receiving any messages. 

**To Reproduce**
4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behavior**

**Additional context**

**Comment by jyasskin** [comment]
This page is for recording bugs on Chrome Status (https://www.chromestatus.com/), not RCS issues.
