### ISSUE TITLE
This isn't working correctly

### ISSUE THREAD

**Issue by jayboy311** [GoogleChrome/chromium-dashboard#3514]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
A clear and concise description of what the bug is. I have to change color every other minute to receive certain text messages. Why was this implemented via chrome. I want all my text messages to come through regardless of color. This is so very depressing

**To Reproduce**
4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behavior**

**Additional context**
Add any other context about the problem here. Chrome have truly made life unpleasant. Please remove or correct this, so anyone can reach me
![Screenshot_20231126-060710](https://github.com/GoogleChrome/chromium-dashboard/assets/152056233/9396bdea-45cd-460b-baa6-b4cd283344c4)

**Comment by jayboy311** [comment]
![Uploading Screenshot_20231126-060120.png…]()

**Comment by jyasskin** [comment]
This page is for recording bugs on Chrome Status (https://www.chromestatus.com/). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new), but this doesn't even appear to be a Chrome bug.
