### ISSUE TITLE
Google Chrome Group Policy for HTTP Authentication - Wild Cards not working 

### ISSUE THREAD

**Issue by pdintusurg** [GoogleChrome/chromium-dashboard#3515]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
This Bug is regarding the Google Chrome Group Policy for HTTP Authentication

**To Reproduce**
Computer Configuration --> Policies -->  Administrative Template --> Google --> Google CHrome --> HTTP Authentication --> List of Origins Allowing all HTTP authentication (Enabled) 

**Expected behavior**

The description says that "Wildcards are allowed for the whole origin or parts of the origin, either the scheme, host, port." but no combination of wild cards don't work 

**Additional context**
We have to mention each and every hostname  to the allow list for the exception to work, as mentioned wild card option does not work 

![Capture](https://github.com/GoogleChrome/chromium-dashboard/assets/151694182/87383559-9f20-45fe-a830-fdcb0b31ef05)

**Comment by jrobbins** [comment]
Thanks for the report, but you reported it in the wrong place.  This issue tracker is only for the chromestatus.com website.  To report bugs in chrome, please use https://crbug.com/new
