### ISSUE TITLE
Channels API returns invalid JSON

### ISSUE THREAD

**Issue by Elchi3** [GoogleChrome/chromium-dashboard#3522]
**Describe the bug**

The channels API returns invalid JSON. The first 4 characters are erroneous.

**To Reproduce**
1. Go to https://chromestatus.com/api/v0/channels
2. See `)]}'`

**Expected behavior**

https://chromestatus.com/api/v0/channels returns valid JSON.

**Additional context**

We're currently stripping the first 4 chars as a workaround.

**Comment by jrobbins** [comment]
That's working as intended.   It prevents the JSON from being interpreted as executable JS.  Normally JSON should be safe to interpret as executable JS, but hackers might find a way to insert some code.
