### ISSUE TITLE
Once a milestone range is set, it cannot be cleared

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#3525]
**Describe the bug**
I tried to remove the OT milestones for a feature entry and found that it complained that the end needed to be after the start.

**To Reproduce**
1. Go to a feature entry that has start and end OT milestones set
2. Clear out both fields
3. Submit
4. See field error on both fields, preventing submission.

**Expected behavior**
It should be allowed to have one of both fields empty, even if they were previously set.

**Comment by dlaliberte** [comment]
The problem appears to be that, once the field value has been entered, deleting it leaves its value as 0.  This behavior may affect other fields and other processing of field values beyond the semantic checks.
