### ISSUE TITLE
Mozilla's File System Access position is harmful, not positive

### ISSUE THREAD

**Issue by ShivanKaul** [GoogleChrome/chromium-dashboard#3546]
The link to Firefox's standards position on https://chromestatus.com/feature/6284708426022912 marks the API as `harmful`, not `positive` as noted on Chrome Status.

**Comment by jrobbins** [comment]
I reached out to the feature owner for clarification.

**Comment by ShivanKaul** [comment]
fwiw I think Mozilla supports Origin Private File System (it's all confusingly named)
