### ISSUE TITLE
Missing edit icon on new features page for features I own

### ISSUE THREAD

**Issue by GabriellaMSanchez** [GoogleChrome/chromium-dashboard#3569]
**Describe the bug**
On the new features page, the edit icon is missing even though I am signed in and I own this feature. I am able to click into this feature and edit it on the feature detail page. This bug occurs whether I am logged into my personal email or the example@chromium.org email log in.

**To Reproduce**
1. Be logged into your account or the example@chromium.org account.
2. Click on "All Features" on the side bar.
3. Click on "Try out our new features page".
4. See error [screenshot below]

<img width="1421" alt="Screen Shot 2024-01-03 at 6 43 53 PM" src="https://github.com/GoogleChrome/chromium-dashboard/assets/83431411/972c71ee-2fb3-42de-992f-c83c0bde78e5">

**Comment by DanielRyanSmith** [comment]
I have confirmed that the edit icon does not display here for editable features of users without special site permissions. It seems that the [permissions are being passed down to the table](https://github.com/GoogleChrome/chromium-dashboard/blob/8ecb3c92f6b5588c9202370abf6c635568a86bf8/client-src/elements/chromedash-all-features-page.js#L94) checking if the user can is a site editor or admin that can edit every feature. That means that either the edit icon will display for all features to editor-level users, or not at all for normal users, even if that user has access to edit the feature.

**Comment by Ali7040** [comment]
Please assign it to me. I want to work on that.

**Comment by BalrajDhakad** [comment]
Hey, 
This is Balraj,
I am new to open source and I want to contribute to this issue.
@DanielRyanSmith @GabriellaMSanchez can you please elaborate it to me

**Comment by r3yc0n1c** [comment]
@DanielRyanSmith  I have an idea to fix this. If this issue is still open, I would like to work on it.

**Comment by afeedhshaji** [comment]
I might have fixed this issue in https://github.com/GoogleChrome/chromium-dashboard/pull/3734

**Comment by jrobbins** [comment]
We phased out the edit icon and the editing overview page that it linked to.  Instead, please click the feature entry title and then use one of the "Edit" buttons on the appropriate stage, or use "Edit all".
