### ISSUE TITLE
Please stop adding anything that restricts

### ISSUE THREAD

**Issue by jayok1234** [GoogleChrome/chromium-dashboard#3570]
**Is your feature request related to a problem? Please describe.** I keep seeing error messages  404. 
I'm choosing to no longer use chrome as browser.  I'm sick of all the new security features and restrictions that's been implemented. I seem to not get text messages from individuals,  which I've interacted with previously.  I'm not sure if it's a synco or DNS situation, but I'm just simply over it. I use social apps , such as jackd, grinder,  and adam4adam.  Consequently,  my apps and social web pages aren't getting messages.  You've disabled my cookies and I just don't understand how you Guys are so invested in my privacy when I'm not. 
**Describe the solution you'd like**
A clear and concise description of what you want to happen. My device location is off, and showing someplace different.  Can't enable cookies.  I want all messages ports and anything to do with my device text messages or web messages left alone.  Please 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏  stop. My google accounts should be able to combine and share locations info etc. I'm using Samsung browser moving forward.  I'm so very disappointed.  My Javascript in my opinion has been affected  or strings in assuming 

**Additional context**

**Comment by jayok1234** [comment]
![chrome_screenshot_Jan 4, 2024 3_48_24 AM EST](https://github.com/GoogleChrome/chromium-dashboard/assets/155604288/84834684-6c1b-4ccd-ac63-08c5cc07bcea)


Please review these components,  and remove anything causing my internet service not to operate fully on my device

**Comment by jayok1234** [comment]
I'm about to post all over play store and developer my negative grievance.  What is google play services doing restricting Via Droid guards? Just leave me alone.

**Comment by jrobbins** [comment]
This issue tracker is only for issues regarding the chromestatus.com website.
