### ISSUE TITLE
Support animated webpage icon (Animated GIF, SVG with CSS animation, JS animation, SMIL animation)

### ISSUE THREAD

**Issue by Glypse** [GoogleChrome/chromium-dashboard#3595]
I think support for **animated webpage icon** would be a great feature.
By that, I mean that native Chromium should support animated GIF, and SVG with CSS animation, JS animation, and SMIL animation, natively. This would extend the creative possibilities of any website, while being (I suppose) relatively easy to implement.

So far, the only ways I have found to get it working natively was to manually update the icon each frame, using JavaScript.
Examples:
[https://www.geeksforgeeks.org/how-to-use-animation-on-favicon-image/](https://www.geeksforgeeks.org/how-to-use-animation-on-favicon-image/)
[https://css-tricks.com/the-making-of-an-animated-favicon/](https://css-tricks.com/the-making-of-an-animated-favicon/)
[https://stackoverflow.com/questions/1837261/how-to-animate-a-favicon](https://stackoverflow.com/questions/1837261/how-to-animate-a-favicon)

If the implementation of this causes problems, say per example when creating a bookmark of the webpage, or when adding the webpage to Home Screen on mobile devices, the static favicon could, for example, be by default the first frame of the animation ; then, the user could specify (I don't know if this is Chromium's job or W3C's) a frame number to be used a the static icon when needed, and/or another file to be used when the static icon is needed.

This feature (animated favicon) is natively supported in Firefox. I find it annoying, as a beginner web developper, that it is not available in Google Chrome and the Chromium browsers.

Example of the difference between Chrome and Firefox:
[https://animated-svg-favicon.glitch.me/](https://animated-svg-favicon.glitch.me/) (choose one of the three buttons on a Chromium browser, then do the same on the Firefox browser: it works on Firefox, not on Chromium)
See videos below

https://github.com/GoogleChrome/chromium-dashboard/assets/124286664/db338670-5724-4506-829d-8cf422da30e3

https://github.com/GoogleChrome/chromium-dashboard/assets/124286664/83d551eb-aba8-4417-86a5-4636b04b9945

**Comment by jrobbins** [comment]
This site is only for reporting bugs with the chromestatus.com website.  To suggest new features, use https://crbug.com/new
