### ISSUE TITLE
This is ridiculous. I'm sure it's chrome

### ISSUE THREAD

**Issue by Jjjdgkkk** [GoogleChrome/chromium-dashboard#3599]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] Everysince chrome have rolled out these new implementation, I've been having device problems. The JavaScript is defective in my opinion, because individuals I've previously interacted with aren't able to respond. I'm not receiving some messages via web pages. I wish these people who just stop. I want all my messages, and ability to use all social pages. None of my messages viable Google voice are popping up anymore. I've do devastating and upset. All my previous device are connected to play store. One's I don't even use anymore. Chrome keep re logging in my same device, and just making my hole experience awful. I want default settings and understand why people can't reach me. Is it string, JavaScript, or what

**Describe the solutio. ns to play store. Ones you'd like**
A clear and concise description of what you want to happen. No messages from people I've previously received messages from via social pages or text

**Additional context**

**Comment by Jjjdgkkk** [comment]
![Screenshot_20240121-135600](https://github.com/GoogleChrome/chromium-dashboard/assets/157275045/9a433541-e952-4b67-9dbb-2edfee2d48d2)


I'm begging you guys to please remove these sitting. Aren't my calls and text messages working. I can't use any other browser other than chrome. I'm so upset. Can someone please respond. What's changed on my device. I hate this

**Comment by past** [comment]
This GitHub project is not about Chrome, but the chromestatus.com website.
