### ISSUE TITLE
我

### ISSUE THREAD

**Issue by xoxx761206** [GoogleChrome/chromium-dashboard#3604]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**

**To Reproduce**
4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behavior**

**Additional context**

**Comment by jstenback** [comment]
No bug described here. Feel free to reopen and add a description of the issue if that was the intent.
