### ISSUE TITLE
The date of birth is not modified on my page, why?

### ISSUE THREAD

**Issue by ahmedf1993** [GoogleChrome/chromium-dashboard#3624]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**

**To Reproduce**
4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behavior**

**Additional context**

**Comment by jstenback** [comment]
This issue tracker is about the chromestatus.com website. This issue appears to be about something else. If you have more information you can share how this relates to the website chromestatus.com (not the Chrome browser), please reopen this issue and provide said details. Thanks.
