### ISSUE TITLE
Nat

### ISSUE THREAD

**Issue by Nat2537** [GoogleChrome/chromium-dashboard#3629]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**

**To Reproduce**
4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behavior**

**Additional context**

**Comment by jstenback** [comment]
This is lacking a description of a problem. Please reopen if there's a problem with chromestatus.com that you'd like to report, and give details of what the issue is.
