### ISSUE TITLE
edit icon not showing

### ISSUE THREAD

**Issue by AsedAliSekh** [GoogleChrome/chromium-dashboard#3648]
https://github.com/GoogleChrome/chromium-dashboard/blob/8ecb3c92f6b5588c9202370abf6c635568a86bf8/client-src/elements/chromedash-all-features-page.js#L94

**Comment by BalrajDhakad** [comment]
I am willing to work on this issue can you please elaborate it to me

**Comment by BalrajDhakad** [comment]
@AsedAliSekh

**Comment by DanielRyanSmith** [comment]
Duplicate of #3569
