### ISSUE TITLE
password import larger than 150kb 

### ISSUE THREAD

**Issue by samascience** [GoogleChrome/chromium-dashboard#3655]
**Is your feature request related to a problem? Please describe.**

I am always frustated when there is a need for passwords to be syncd and the google password manager is not able to sync with google password manager in chrome and so there is a need for larger sized import for passwords in chrome ! 

**Describe the solution you'd like**

increase the password limit to 300kb 

**Additional context**

**Comment by jrobbins** [comment]
This issue tracker is only for problems with the chromestatus.com website.
To report a problem with the chrome browser, use the menu item "Help" > "Report a problem..." or https://crbug.com/new
