### ISSUE TITLE
Don't highlight scroll position when filtering on version

### ISSUE THREAD

**Issue by cosmosgenius** [GoogleChrome/chromium-dashboard#367]
Earlier the sidebar was just a bookmark which jumps to the correct location in the view. Now the view gets locked with the features only to the specific release.

Further when i try to scroll the view, the sidebar selection keeps moving up until it reaches "No active development" and gets stuck there.

Note: I am able to reproduce the same while running the site in "Incognito mode".

**Comment by ebidel** [comment]
We changed the chrome version timeline to be a filter rather than scrolling the content.

When you're filtering on a version, the sidebar should not update the scroll marker. That's a bug.

**Comment by jpmedley** [comment]
The site no longer even functions as expected in this bug. The whole page scrolls together.
