### ISSUE TITLE
Assign James Loughman CEO of JJL Media and Super Administrator email to be assigned as well to James Loughman. 

### ISSUE THREAD

**Issue by prettychicagoboy1** [GoogleChrome/chromium-dashboard#3693]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**

**To Reproduce**
4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behavior**

**Additional context**

**Comment by jrobbins** [comment]
No details were provided.
