### ISSUE TITLE
Status Item Contains Link to Itself Labeled 'Sample'.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#372]
The link is circled below. It only shows up in the [/features](https://www.chromestatus.com/features/5668635896971264) view. It's not in the [/feature](https://www.chromestatus.com/feature/5668635896971264) view.
![image](https://cloud.githubusercontent.com/assets/8204171/17224598/779a9de4-54b6-11e6-8c0b-1500ba9ad712.png)

**Comment by ebidel** [comment]
Looks like https://github.com/GoogleChrome/chromium-dashboard/blob/master/templates/feature.html#L68-L77 needs to loop over the list of samples.

However, for this example, it looks like Sample 2 is bogus. It links to the feature itself (https://www.chromestatus.com/features/5668635896971264).
