### ISSUE TITLE
Selected Pagination in /newfeatures page

### ISSUE THREAD

**Issue by r3yc0n1c** [GoogleChrome/chromium-dashboard#3727]
**Is your feature request related to a problem? Please describe.**
The /newfeatures page has a default pagination of 100 per page. It would be great if we can provide custom pagination like this:

![image (1)](https://github.com/GoogleChrome/chromium-dashboard/assets/57730879/dd4ee4d8-0bbb-4420-aab2-bb57cb28eaea)

**Describe the solution you'd like**
- Set a default pagination with 25 items or so
- Give users the choice of selecting how many items they want
- Set standard item counts like 10 / 25 / 50 / 100

cc: @DanielRyanSmith @jrobbins 

I'd like to work on this feature. Please assign it to me.

**Comment by jrobbins** [comment]
I did this already.
