### ISSUE TITLE
Error Code 11 in Chrome When Using mat-select Component

### ISSUE THREAD

**Issue by kev-creator** [GoogleChrome/chromium-dashboard#3806]
**Describe the bug**
I am experiencing an issue with Google Chrome when using the mat-select component in my web application. When I try to select an option, the browser shows "error code 11" and nothing appears in the console. However, the same functionality works correctly in other browser without any errors.

**To Reproduce**

1. Open the web application in Google Chrome.
2. Navigate to the page containing the mat-select component.
3. Try to select an option from the dropdown.
4. Observe that the "error code 11" appears in the browser, but no error is shown in the console.

**Expected behavior**
The mat-select should function as intended, allowing the selection of an option without any errors, similar to how it works in other browsers.

**Environment Information**
Chrome Version: [Chromium version 124.0.6367.61 (Official Build) (arm64)]
Operating System: [macOS Sonoma 14.1]

**Comment by jrobbins** [comment]
This issue tracker is only for problems with the chromestatus.com website.

It sounds like you are reporting a problem with chrome and the mat-select component in Angular.   You should report that at https://crbug.com/new and/or https://github.com/angular/components.
