### ISSUE TITLE
Feature Request: Record the last date an item was modified.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#384]
So that we can identify potential stale entries for removal. So:

Review set = Entries that haven't been touched in a while - Entries with a Milestone.

**Comment by ebidel** [comment]
At the bottom of each feature, there's a "Last updated on" date:
https://www.chromestatus.com/feature/5687338902487040

Do you mean on a sorting feature on /features?

**Comment by jpmedley** [comment]
I'm flexible on the implementation. The use case is that I want to look at everything that hasn't been touched in for example 6 months and see if it has a milestine.

**Comment by jpmedley** [comment]
I don't exactly when this was implemented, but change dates have been part of features for several years.

![image](https://user-images.githubusercontent.com/8204171/76434671-33d1d580-6373-11ea-8c03-340952dec6e0.png)
