### ISSUE TITLE
The sidebar in the external reviews page doesn't use the full window height

### ISSUE THREAD

**Issue by past** [GoogleChrome/chromium-dashboard#3852]
The sidebar in the new external reviews page looks like this with a tall window:

![Screenshot 2024-05-06 3 43 26 PM](https://github.com/GoogleChrome/chromium-dashboard/assets/49118/9c670a23-2458-4cc2-91a3-a78c0815c346)

Visiting one of the subpages with enough content shows the full sidebar. Conversely the spec mentors page uses the full height:

![Screenshot 2024-05-06 3 44 20 PM](https://github.com/GoogleChrome/chromium-dashboard/assets/49118/d38ad194-85b9-47d9-8902-5eb8160d15a4)

CC @jyasskin .

**Comment by jyasskin** [comment]
This is true for all short pages, e.g. https://chromestatus.com/myfeatures/starred. https://github.com/GoogleChrome/chromium-dashboard/blob/1c398888722a6f6aba1f82395d2fbb594adf9701/client-src/elements/chromedash-app.js#L45-L49 seems to have the result of giving the sidebar at least 500px regardless of the main page content, but it should really have a height of 100%... Changing that div and [this one](https://github.com/GoogleChrome/chromium-dashboard/blob/1c398888722a6f6aba1f82395d2fbb594adf9701/client-src/elements/chromedash-app.js#L669) to have a `height: 100%` property appears to fix the problem. 

@KyleJu, you [touched](https://github.com/GoogleChrome/chromium-dashboard/pull/3112) this last; do you think that's the right fix, or am I missing a better way to do it?

**Comment by KyleJu** [comment]
> This is true for all short pages, e.g. https://chromestatus.com/myfeatures/starred.
> 
> https://github.com/GoogleChrome/chromium-dashboard/blob/1c398888722a6f6aba1f82395d2fbb594adf9701/client-src/elements/chromedash-app.js#L45-L49
> 
> seems to have the result of giving the sidebar at least 500px regardless of the main page content, but it should really have a height of 100%... Changing that div and [this one](https://github.com/GoogleChrome/chromium-dashboard/blob/1c398888722a6f6aba1f82395d2fbb594adf9701/client-src/elements/chromedash-app.js#L669) to have a `height: 100%` property appears to fix the problem.
> @KyleJu, you [touched](https://github.com/GoogleChrome/chromium-dashboard/pull/3112) this last; do you think that's the right fix, or am I missing a better way to do it?

I think that will fix the issue. 500px might come from the minimum height from the content container, that shows the feature list. It is an issue when the list is empty. 

Thanks for the fix!
