### ISSUE TITLE
chromestatus.com/features is very slow to load

### ISSUE THREAD

**Issue by markafoltz** [GoogleChrome/chromium-dashboard#3860]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
When I navigated to chromestatus.com/features, a spinner appeared for 60-90 seconds and nothing loaded.  Force-reloading the page reproduced the same state.  Eventually after about 90 seconds the page loaded.

**To Reproduce**
1.  Navigate to chromesatus.com
2. Click on "All Features"

4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behavior**
Features load immediately

**Additional context**
If it repros, I can try to grab a screenshot

**Comment by jrobbins** [comment]
Our old version of that page was not very scalable.  We replaced it with a simpler feature list that loads much faster.
