### ISSUE TITLE
Deprecation trial creation requests should not require providing a WebFeature UseCounter value

### ISSUE THREAD

**Issue by mfoltzgoogle** [GoogleChrome/chromium-dashboard#3863]
**Describe the bug**
The  origin trial request form is failing to validate my input and I don't know how to fix it.

**To Reproduce**
1. Go to https://chromestatus.com/ot_creation_request/5100528783851520/5082955723833344
2. Click on "Chromium Trial Name" field
3. Enter MediaPreviewsOptOut which exists in runtime_enabled_features.json5
4. Click on "WebFeature UseCounter Name" field
5. Enter kNumberOfFeatures [*]
6. Click Submit
7. Spinner appears for a while and it says the trial name and the use counter are not valid

**Expected behavior**
Form is submitted

**Additional context**

[*] This OT is for browser behavior and is not exposed to Blink.  Therefore I did not add a use counter to web_feature.mojom because it would be unused.

**Comment by jstenback** [comment]
@DanielRyanSmith or @past, any insight into what might be getting in the way here?

**Comment by DanielRyanSmith** [comment]
I'll look into this and report back ASAP. Thanks for bringing this up. 🙂

**Comment by DanielRyanSmith** [comment]
As for the "Chromium Trial Name" field, the value that needs to be provided is from the `origin_trial_feature_name` property, which is ["MediaPreviewsOptOutPersistent" in this case](https://chromium.googlesource.com/chromium/src/+/main/third_party/blink/renderer/platform/runtime_enabled_features.json5#2398).

@mfoltzgoogle Is this a deprecation trial? If so, then we have a bug in the form that needs to be fixed, as it should not require a usecounter value for deprecation trials. In this scenario, I would advise the workaround of providing an existing usecounter with a numeric value (e.g. "kOBSOLETE_PageDestruction"), and we will handle your request disregarding that value.

However, if this is not a deprecation trial, we have a separate problem in which we have no way to track usage of the feature. @past might have further opinions on moving forward if that is the case.

**Comment by mfoltzgoogle** [comment]
Thank you for the prompt response, those workarounds allowed the form to be submitted :grin: 

> As for the "Chromium Trial Name" field, the value that needs to be provided is from the origin_trial_feature_name

I was using the value from the `name` field instead; maybe the form could be specific to refer to the `origin_trial_feature_name` field to avoid future confusion

> @mfoltzgoogle Is this a deprecation trial?   

Yes, I set this up as a deprecation trial, because it's allowing sites to opt into existing behavior.  Once I checked the "deprecation trial" checkbox it allowed me to submit the form with the dummy usecounter.

I'ts a good point that there is not a way to track usage of this trial yet.  I can add a custom UMA for that.

**Comment by DanielRyanSmith** [comment]
We can see your creation request submission on our side, so the problem has been mitigated. 🙂

Our validation checks on values in Chromium files is a recently-added feature, so your feedback in this situation has been valuable. We'll take steps to make this less confusing in the future.

**Comment by past** [comment]
Sorry for these bumps as we improve these checks Mark and thanks for your patience, much appreciated! 

Note that the Intent to Experiment field should also be mandatory (we'll fix that), so you need to request approval from API Owners before we can proceed with the trial.

**Comment by mfoltzgoogle** [comment]
The intent to experiement was LGTMed.

https://groups.google.com/a/chromium.org/g/blink-dev/c/f_x-iPGZSPg/m/QB6nATbuBAAJ

**Comment by mfoltzgoogle** [comment]
Let me know if there are other steps required.

**Comment by past** [comment]
Thanks for that pointer, I;ll follow up in the OT ticket. Let's use this issue for tracking the Chromestatus bug fixing work.

**Comment by DanielRyanSmith** [comment]
Deprecation trials are no longer required to provide a usecounter value in the OT creation request form.
