### ISSUE TITLE
Chrome Status Entry sends a lot of emails when an edit is submitted to the feature.

### ISSUE THREAD

**Issue by issackjohn** [GoogleChrome/chromium-dashboard#3883]
**Describe the bug**
When I make a draft edit to a field in the chrome status entry feature, I am spammed with 10+ emails about a single change.

**To Reproduce**
1. Go to a feature you are an owner of editor for.
2. Click on 'Edit fields' in any of the Development stages.
3. Save the edit.
4. See lots of emails sent to you.

**Expected behavior**
One email which details the change is sent.

**Additional context**
![image](https://github.com/GoogleChrome/chromium-dashboard/assets/117320405/44b2e525-ec20-4f63-a064-bd2ce0d71893)

**Comment by jrobbins** [comment]
Sorry about that.   We actually had an error-retry loop that would have (slowly) sent you an infinite number of the same message, but I deleted the task from our task queue.  I am looking for the root cause now.

**Comment by jrobbins** [comment]
This should be resolved now.  I deployed a couple of fixes and I don't see any new email tasks accumulating in the past few hours.

**Comment by issackjohn** [comment]
Thank you!
