### ISSUE TITLE
Remove the scroll bars from the timeline view

### ISSUE THREAD

**Issue by phistuck** [GoogleChrome/chromium-dashboard#390]
I have plenty of screen real estate, yet I see awkward scroll bars.
![image](https://cloud.githubusercontent.com/assets/184400/17844373/5e8433c6-6841-11e6-9c52-5bd799b8c2d2.png)

**Comment by phistuck** [comment]
After a few minutes of superficial debugging, I see that `<div class="data-panel">` has a narrow `max-width` value which explains the (inner) horizontal scroll bar. I currently cannot explain the (inner) vertical scroll bar, though.


To be clear, I am not referring at all to the scroll bar of the page (even though it is also unnecessary).

**Comment by ebidel** [comment]
What platform and browser?

**Comment by phistuck** [comment]
Oops, sorry. Stable Chrome 52, Windows 7.

**Comment by phistuck** [comment]
Still happening on Chrome 53 as well.
Also, another scroll bar issue (less severe, just looks unpolished) is when you click on the Usage Metrics link at the top and click on JS/HTML, it suddenly adds a scroll bar. On `mousedown` (active?), there are two scroll bars (horizontal and vertical) and on `mouseup` there is only one (vertical) scroll bar.

![image](https://cloud.githubusercontent.com/assets/184400/18489519/84b9f310-7a06-11e6-8f1d-78cc90a4d6f6.png)
(I resized the window, but it is not necessary)

Perhaps my resolution matters - 1366x768.

**Comment by ebidel** [comment]
For the nav examples, do scrollbars appear on  https://elements.polymer-project.org/elements/paper-menu-button?view=demo:demo/index.html&active=paper-menu-button if you click around some of those demos?

Sorry for all inquiries. I don't have a Windows machine handy.

**Comment by phistuck** [comment]
The "Alternate Button" example shows (in addition to the expected vertical scroll bar) a horizontal scroll bar on `mousedown`.

(That is pretty disappointing... :( Googlers should really check things on Windows)

**Comment by ebidel** [comment]
Googlers are lazy developers too :p

**Comment by phistuck** [comment]
@ebidel - you might be able to leverage BrowserStack (consult with @RByers) instead of getting a real Windows machine. It is good for the lazy. ;)

**Comment by phistuck** [comment]
Filed https://github.com/PolymerElements/paper-menu-button/issues/124 for the paper-menu-button scroll bar.
