### ISSUE TITLE
"OT Contacts" argument needs to be added to OT creation Chromestatus request

### ISSUE THREAD

**Issue by DanielRyanSmith** [GoogleChrome/chromium-dashboard#3902]
[The OT Creation request code](https://github.com/GoogleChrome/chromium-dashboard/blob/main/framework/origin_trials_client.py#L105-L154) in Chromestatus should send over the "OT Contacts” argument.
OT Contacts are the combined values of ot_owner_email (one email) and ot_emails (multiple emails) fields.
The ot_emails field should be filtered to remove any non-google.com emails, as they cannot be added to internal groups and ganpati groups. This is how we handle the manual process as well.

**Comment by KyleJu** [comment]
Leaving a note here: we also have to differentiate between Google groups and Googler email addresses, but probably on the backend
