### ISSUE TITLE
U suggest chrome stop blocking and restricting my dns and server

### ISSUE THREAD

**Issue by jayok1234** [GoogleChrome/chromium-dashboard#3927]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**
My WiFi connection show's excellent. After changing components in chrome such as this 1,3 downgrade and up protection, I then get some messages and txt to my Google number. Please!!! How can I change chrome version

**Comment by jrobbins** [comment]
This issue tracker is only for problems with the chromestatus.com website.  So, I will close this issue.

I'll just note that Chrome is normally always on the latest version.  You can check if a newer version is available by choosing "..." > "Help" > "About Google Chrome".  Or, type "chrome://settings/help" in the address bar.
