### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by jayok1234** [GoogleChrome/chromium-dashboard#3928]
I want to also ensure none of my information is going to cloud. I want all messages via app, text , and so on coming directly to my device. I feel like something is restricting my apps, such as jackd, and any other adult content. My pages should be loaded freely. I dont want any preload

**Comment by jayok1234** [comment]
Hello. Please respond. Seems I'm not receiving all messages to my google voice and other apps. I'm noticing that chrome controls most system features and fetch, which I don't like. I want all my notifications to pop up on my device like normal 
![Screenshot_20240616-065818](https://github.com/GoogleChrome/chromium-dashboard/assets/155604288/cb58b263-abe4-4a4d-8c85-1025d237c2bf)

**Comment by jstenback** [comment]
As I mentioned in issue 3977, this issue tracker is only for issues with the website chromestatus.com. The issues you're describing sounds like either Google Voice or a broader Android issue, which the folks working in this repository know little, if anything, about.
