### ISSUE TITLE
Outbound emails failures when to=[]

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#3969]
Today I noticed a couple of outbound email tasks that have been failing 84 times:

`{"to": [], "cc": ["origin-trials-support@google.com", "origin-trials-timeline-updates@google.com"], "subject": "DisableThirdPartyStoragePartitioning2 origin trial is branching", "reply_to": null, "html": "According to go/chrome-schedule, Chrome 127 branch is\nMonday, June 10, 2024. This release will contain your feature as an origin trial.\n<br /><br />\nYou should aim to post a blog post on https://developer.chrome.com/blog/ as\nsoon as possible so you can begin to get origin trials sign ups early\n(which means you get feedback earlier!). If you are already working with\nsomeone from Chrome Web Developer Relations they can help you with this.\nOtherwise, reach out to chrome-devrel-content@google.com for help.\n<br /><br />P.S. This email was generated automatically (for\ndetails, see <a href='http://go/running-an-origin-trial'>go/running-an-origin-trial</a>).\nPlease contact origin-trials-support@google.com if this email is incorrect or not useful."}`

and

`{"to": [], "cc": ["origin-trials-support@google.com", "origin-trials-timeline-updates@google.com"], "subject": "WebAssembly JS String Builtins origin trial has branched for its last release", "reply_to": null, "html": "According to go/chrome-schedule, Chrome 127 is branching\nMonday, June 10, 2024. This release will be the final one to include your feature as\nan origin trial.\n<br /><br />Code you land from here on will land in the first\nrelease after the origin trial is over.\n<br /><br />P.S. This email was generated automatically (for\ndetails, see <a href='http://go/running-an-origin-trial'>go/running-an-origin-trial</a>).\nPlease contact origin-trials-support@google.com if this email is incorrect or not useful."}`

I deleted them to clear up the task queue.  In the logs, I see that each request returns a 400 response, but nothing is logged other than the task parameters.

According to this page, the `to` field must have **one** or more email addresses.
https://cloud.google.com/appengine/docs/standard/python3/reference/services/bundled/google/appengine/api/mail/SendMail

So, I am thinking that instead of using the `to` and `cc` fields, it might be better to just put all the addresses in the `to` field.  Just be careful to verify that any concatenation is done on arrays rather than mixing arrays and strings.

**Comment by DanielRyanSmith** [comment]
This might be fixed by https://github.com/GoogleChrome/chromium-dashboard/pull/3916 since we'll no longer try and send the email without any recipients, but it may also be worth notifying OT support if we don't have any OT contacts on record for a given trial.

**Comment by jrobbins** [comment]
I believe that Daniel's change did fix this issue.
