### ISSUE TITLE
Search hash needs escaping (eg. spaces)

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#398]
Type a search term that includes a space, eg. "Event Listeners".  It works, but you get a URL like `https://www.chromestatus.com/features#Event Listeners` which I think isn't valid (it works but most things don't expect spaces in URLs - will replace with %20 which then doesn't work).  Eg. see #397

**Comment by ebidel** [comment]
@mdittmer would you be interested in this as part of your search updates? We'll need to escape it for the URL but also unescape it for the input when users deep link.
