### ISSUE TITLE
"Intent to Implement" email template: make formatting/style easier to use in email

### ISSUE THREAD

**Issue by ddorwin** [GoogleChrome/chromium-dashboard#402]
The "Intent to Implement" email template generated for new entries has a formatting style that is difficult to modify to complete the email.

Examples:
- Use of faded colors.
  - Any default formatting/style in the email app will not match this.
  - New links added will not be the same color blue.
- Font size is non-standard.
  - It appears to be between Gmail's Normal and Large sizes, making it difficult to format text to match.
- Some sections do not have only documentation text and no normally-formatted text.
  - This makes filling in these sections difficult because the style doesn't match the other sections, especially because of the issues above.
  - Simply adding `<Insert here>` in the same style as the text in other sections would make this easier.

**Comment by ebidel** [comment]
I don't think we've ever intended for the email template's styling to match the email sent to blink-dev. Folks should be pasting as text and not formatted text.

Do you think a textbox would be better?

**Comment by ddorwin** [comment]
It would be nice to not have to format all the section headers, but okay.

A textbox would make this clearer, but I think there is some value in seeing how it should look and what text is simply directions.

**Comment by jpmedley** [comment]
The resolution of this is some weird hybrid of 'Addressed'/'Won't fix'/'Duplicate'. 

Regardless, this issue will soon be moot because of #764
