### ISSUE TITLE
Block pages from locking and preventing browser from closing

### ISSUE THREAD

**Issue by StoneSage** [GoogleChrome/chromium-dashboard#4078]
**Is your feature request related to a problem? Please describe.**
Why after all this time with the Remote tech support scammers is the browser still allowing advertisements to open pages that cannot be closed without using tasking manager to close the browser? It would save a lot of people from the scammers if the page just allowed them to close it.

**Describe the solution you'd like**
If the feature of going full screen or locking the page is required for some functionality, could we at least add an authorization promp when a page request to do so? A simple hey do you want to allow this page to go full screen or the like would at least allow the common person to get out of the pop up.

**Additional context**

**Comment by jrobbins** [comment]
Thanks for the bug report, but this is the wrong place to report it. This issue tracker is only for the chromestatus.com website. Bugs with the chrome browser should be reported at https://crbug.com/new.

**Comment by StoneSage** [comment]
Thanks
