### ISSUE TITLE
Border radius issue in the Extension badge UI

### ISSUE THREAD

**Issue by iplanwebsites** [GoogleChrome/chromium-dashboard#4079]
On the action buttons of extensions, there's a border around the coloured badges. The corner radius doesn't match.

Example image showing [Adblock](https://chromewebstore.google.com/detail/adblock-%E2%80%94-block-ads-acros/gighmmpiobklfepjocnamgkkbiglidom), [Honey](https://chromewebstore.google.com/detail/paypal-honey-automatic-co/bmnlcjabgnpnenekpadlanbbkooimhnj) and [Invitation app Extensions](https://chromewebstore.google.com/detail/invitation-%E2%86%90-referral-cou/kmeijfochmidimcngicjabokhkeifmmj)
 
<img width="126" alt="image" src="https://github.com/GoogleChrome/chromium-dashboard/assets/787729/d38e9c69-1f34-40d1-af92-44d144077142">

**Comment by jstenback** [comment]
This issue tracker is unfortunately only for tracking issues with the website at https://chromestatus.com. Please raise this issue with the individual projects you linked at where it has a much greater chance of getting the attention it deserves. Thank you.
