### ISSUE TITLE
Milestone filtering picks up numbers in any field

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/chromium-dashboard#409]
Clicking on "54 beta" in the current sidebar does a search for `=54`. `=54`, when used as a search term, should only pick up features with a Milestone of 54. But it looks like the filtering is being applied to all fields, so instances of 54 in any property cause the feature to be included.

Also, when you expand the feature that's been included in the list, the "No active development" version is highlighted, rather than either the version corresponding to the actual feature (51, in this case) or the version corresponding to the search (54).

![image](https://cloud.githubusercontent.com/assets/1749548/18529534/7bcba6b4-7a9b-11e6-8915-0b7278db9aa8.png)

**Comment by mdittmer** [comment]
Milestone filtering quietly changed with #394. I was careful to update the example queries:

![image](https://cloud.githubusercontent.com/assets/1775176/18530217/73ce7704-7a9e-11e6-9cee-b2ce49ffe5dc.png)

I believe your query is being interpreted as `"=" OR "54"`, `"=54" OR ""54"`, or possibly even just `"54"`.

Is special-casing one-sided expressions to bring back the old behaviour really important to you?

**Comment by jeffposnick** [comment]
Gotcha.

Clicking on the version numbers in the left-hand nav automatically trigger searches along the lines of `=MILESTONE`. It sounds like the left-hand nav click handlers need to be updated to trigger `shipped_milestone=MILESTONE` instead.

**Comment by mdittmer** [comment]
Thanks for catching this! I'll fix it.
