### ISSUE TITLE
Switch to new Blink.UseCounter metrics

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#414]
The usage data is based on WebCore.FeatureObserver UMA data.  I'm [in the process](https://bugs.chromium.org/p/chromium/issues/detail?id=597963) of replacing this with a new UMA (Blink.UseCounter) which fixes a number of known issues with the data.  Once that's available and confirmed to have high quality data, we need to switch chromestatus over to this new data source.

**Comment by RByers** [comment]
One problem here is that the semantics of the animated CSS properties histogram has changed completely.  Previously it was the fraction of all property animations that animated the given property.  We found this to not be that useful and so it was re-worked to be the fraction of page loads in which the given property was animated (directly analogous to the normal CSS Properties histogram).

As a result I don't think the new data is at all comparable to the old data.  This data is relatively niche, I think we should just dump the historical data from chromestatus (Googler's can get it internally if need be) rather than try to represent both on the animated property timeline.

For the other timelines I imagine we'll just want to draw a dot or something on the date we switch over and link to something with the details of how the semantics have changed.  In general the values are roughly comparable still, so having the history is more value than noise.

**Comment by ebidel** [comment]
Yea. Sgtm on just showing the new stuff for these.

**Comment by RByers** [comment]
Server side is done.  Possible remaining work for the client:

- [ ] Dump the historical animated CSS properties data
- [ ] Add some indicator at the change point to the two other timelines with a label saying the semantics changed, perhaps link to [this thread](https://groups.google.com/a/chromium.org/d/msg/blink-api-owners-discuss/IpIkbz0qtrM/HUCfSMv2AQAJ)

**Comment by ebidel** [comment]
+1. On it.

**Comment by RByers** [comment]
Looks like this is all done now, right?

Oh, one more thing:
[ ] Update description on [animated css stack rank page](https://www.chromestatus.com/metrics/css/animated).  Eg. "the amount of times (as the fraction of all animated properties) each property is used in a Transition or Animation" -> "the fraction of Chrome page loads that animates the corresponding CSS property (in a transition or animation) at least once".

**Comment by RByers** [comment]
We could backfill some of the timeline data back to when the new counters first hit stable (Chrome 57, early March).  I think it's probably not worth it (Googlers can check the internal dashboard if the differences matter, and it could cause more confusion by retroactively changing the data used in deprecation discussions).  But others might disagree, or even argue it would be worth the effort to show both lines from March to October.

**Comment by ebidel** [comment]
Marking this as fixed. We can decide if it's worth backfilling data from May later on.
