### ISSUE TITLE
touch-action sample is 404ing

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#416]
@jeffposnick the demo from https://www.chromestatus.com/samples#touch-action is missing. It's pointing to https://rawgit.com/jeffposnick/touch-action-sample/master/app/index.html. Is there a better demo we should add instead?

**Comment by jeffposnick** [comment]
Yeah, that was some unofficial stuff from way back in the day, before we were populating the GoogleChrome/samples repo. I don't know that it ever worked as well as the various samples that @RByers had put together anyway, so I'll just change the link to point to http://rbyers.github.io/touch-action.html

**Comment by ebidel** [comment]
Thanks dude
