### ISSUE TITLE
Pagination start does not reset to 0 when the user does a new search

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#4217]
**Describe the bug**
Pagination does not reset when doing a new search, which can give the user the message that there are no results when there are < 100.

**To Reproduce**
1. Go to the new search page
2. Navigate to a higher pagination page
3. Do a query for something that has < 100 results.
4. See "No results" because the user has start=100 or more.

**Expected behavior**
1. `start` parameter should reset to 0 on a new search.
2. there should be a better error message when there are N results but start > N.

**Additional context**

**Comment by ProElecttro** [comment]
please assign this issue to me, i want to work on this.
