### ISSUE TITLE
Many (most?) "intent thread" links are broken

### ISSUE THREAD

**Issue by domenic** [GoogleChrome/chromium-dashboard#4244]
Looking at https://chromestatus.com/myfeatures/review as an API owner, the following features all have broken "intent thread" links:

- https://chromestatus.com/feature/5201116810182656 (link goes to ChromeStatus instead of blink-dev)
- https://chromestatus.com/feature/6612726584180736
- https://chromestatus.com/feature/4993824284475392
- https://chromestatus.com/feature/5193021205774336
- https://chromestatus.com/feature/5183881532932096
- https://chromestatus.com/feature/6398297361088512

This makes reviewing quite difficult.

**Comment by jrobbins** [comment]
The fix in #4300 went live last week and I made a pass over the database to find and fix all the broken links that I could.  The examples you listed are all working now.
