### ISSUE TITLE
Add gate descriptions that clarify their purpose

### ISSUE THREAD

**Issue by past** [GoogleChrome/chromium-dashboard#4246]
One consistent feedback we received in the recent survey is that people aren't sure why there are all these approval gates slowing down their launches. It would be helpful to at least add some explanation of the value of the gate (if not the context of its original addition) in a description field. I imagine a short intro right after the panel header would work here.

**Comment by jrobbins** [comment]
We are drafting the text in an internal doc:
https://docs.google.com/document/u/0/d/17mZl9Ml3MyEes7oW585YUj39mz_Wk6xSB2Khh7ux-fc/edit
