### ISSUE TITLE
How to report typos, broken links, etc. in content?

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/chromium-dashboard#426]
E.g. https://www.chromestatus.com/feature/6232200047493120; the fragment in the “Editor’s draft” URL is broken, it should be `#white-space-processing` instead.

I occasionally spot broken links and other issues in the content, and would be happy to report them but don’t know how.

**Comment by ebidel** [comment]
Thanks. I've taken care of this one. https://www.chromestatus.com/feature/6232200047493120

Filing bugs is the best way to report content issues! :)
