### ISSUE TITLE
Order by "Milestone of most recent update"

### ISSUE THREAD

**Issue by maxh** [GoogleChrome/chromium-dashboard#43]
Currently, features are sorted by desktop launch milestones.  They should instead be sorted by "most recent milestone on any platform."

For example, datalist support was added to Chrome for Android in M33: http://www.chromestatus.com/features/6090950820495360

The "datalist" feature should appear in the list of features for M33, not M20.

WDYT?

**Comment by jpmedley** [comment]
I can't of a pithy way to title this. Basically if a feature shipped in different versions on different platforms, it doesn't show up in the list for both versions.

**Comment by jrobbins** [comment]
I think that this issue has not gotten enough interest over the years to justify doing it.   People seem to be going along with a desktop-centric view.  If folks disagree, let's open a new issue.
