### ISSUE TITLE
new histogram for Web Bluetooth

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/chromium-dashboard#430]
Hey @ebidel,

Can we please update histograms and push it live as there is a new Counter for Web Bluetooth? 
See https://codereview.chromium.org/2457653004/

Thank you!

**Comment by ebidel** [comment]
Histograms are pulled in nighty from cron. Remember you did that :) it
should show up in 24hrs.

**Comment by beaufortfrancois** [comment]
... and the Alzheimer's oscar goes to @beaufortfrancois.
