### ISSUE TITLE
Intent to ship links are often broken in the API owners dasboard

### ISSUE THREAD

**Issue by chrishtr** [GoogleChrome/chromium-dashboard#4307]
Example:  [this feature](https://chromestatus.com/feature/6398297361088512) shows an I2S link that is [this](https://groups.google.com/a/chromium.org/g/blink-dev/c/82541dfc-0611-4c6c-a1af-6249c9bc0a0an@chromium?e=48417069), which is invalid.

**Comment by jrobbins** [comment]
We just deployed https://github.com/GoogleChrome/chromium-dashboard/pull/4300 which should prevent this in the future.  I will also make a pass over the existing data to find broken links and correct them where I can.

**Comment by jrobbins** [comment]
OK, I made a pass through the DB and verified that everything currently pending review is free from mis-parsed Google Groups links.

I'll close this for now, but let me know if you ever spot another broken intent thread link.
