### ISSUE TITLE
chrome --print-to-pdf command not saving pdf begining on 128 version

### ISSUE THREAD

**Issue by Slywear** [GoogleChrome/chromium-dashboard#4322]
**Describe the bug**
After chrome update to 128.* version,the command --print-to-pdf stop working

**To Reproduce**
open RUN on windows 11 paste the command bellow

CHROME.EXE --headless --disable-gpu --print-to-pdf="c:\temp\teste.pdf" "https:/www.terra.com.br"
or
CHROME.EXE --print-to-pdf="c:\temp\teste.pdf" "https:/www.terra.com.br"

 Remember to update the destination dir to one existing in your machine.

This command does not print any screen error
or register on windows event viewer

**Expected behavior**
create a PDF file on the directory specified

**Additional context**
Last time it worked whas on version  127.0.6533.72

**Comment by jrobbins** [comment]
Thanks for this report, however this issue tracker is only for problems with the chromestatus.com website.  Please file chrome browser bugs at https://crbug.com/new.
