### ISSUE TITLE
Please allow deletion / deduplicate CSS Text Decorations

### ISSUE THREAD

**Issue by drott** [GoogleChrome/chromium-dashboard#434]
I had login issues when filing the CSS Text decorations entries and thought the previous entry had been lost, but now it occurs there are two entries for CSS Text decorations - could someone with database access delete the second one, which is status "in development" (5695146909761536) and only keep the one that says, behind a flag, (5766823203045376) slated for release in M57?

Thanks.

**Comment by ebidel** [comment]
Removed. It may take a bit to actually be removed from the list due to caching.

**Comment by drott** [comment]
:+1: Thank you.
