### ISSUE TITLE
I'm so very upset and disappointed 

### ISSUE THREAD

**Issue by Jayokqwr** [GoogleChrome/chromium-dashboard#4347]
Thank you for letting us know that something needs to be fixed. This page is for recording bugs on Chrome Status (https://www.chromestatus.com). If you need to report a problem with Chrome or Chromium, please use crbug (http://crbug.com/new). Thank you.

**Describe the bug**
A clear and concise description of what the bug is. I continue to see page insecure in chrome browser. None of my background apps are giving notifications. My Google voice, Grindr, and jackd accounts aren't working. I want to disable chrome and use another browser. This is ridiculous. I do not use audio speaking now or never, but accessibility keeps offering and mandating I use. My device isn't able to show it's located in apps, and the Chrome browser is blocking or restricting my network. How dare you guys do this to me. My device phone number and network aren't able to run other than in Google sponsorsed apps. I'm located in Atlanta, GA 30311
**To Reproduce**
4. See error.  If applicable, add screenshots to help explain your problem.

**Expected behavior**

**Additional context**

**Comment by jrobbins** [comment]
This issue tracker is only for reporting problems with chromestatus.com.
