### ISSUE TITLE
Move the action in escalation emails closer to the top

### ISSUE THREAD

**Issue by past** [GoogleChrome/chromium-dashboard#4355]
**Is your feature request related to a problem? Please describe.**
Feedback suggests that people sometimes scan the escalation emails and if the information looks correct assume there is nothing for them to do. 

**Describe the solution you'd like**
Perhaps moving the action button towards the top, before the explanation of the current status (like a tl;dr) would anchor their mind towards acting.

**Additional context**
Further confusion arises when clicking the button takes you to a page with much more information than the email, which increases the mental overhead of confirming the data. Maybe we should make the button click take you to a simple interstitial or just a "success" message?

**Comment by KyleJu** [comment]
@jrobbins I will make progress on this issue this week since it is a part of my KR

**Comment by Varryme** [comment]
I found the wiki feed that deprecated I took care it

**Comment by KyleJu** [comment]
A few ideas in the email:
1. Title can be changed to: `[Action requested] Verify your webstatus feature before launch - Insecure form warnings on iOS`. Emails rarely use the format of `[webstatus] ESCALATED: [Action requested]` in email subjects.
2. Move the `verify feature accuracy` to the top, and replace the position of the `Insecure form warnings on iOS` link
3. Show the `accurate_as_of date` in the email to highlight when the last update was
4. Highlight it is scheduled to ship **soon** in the first sentence
5. Merge the 4 boxes of texts into two, with one being action items on top and another one for brief explanations. It might reduce the mental overhead to read the email and prompt more actions

![Screenshot 2024-10-31 3 29 07 PM](https://github.com/user-attachments/assets/50e1d6d1-e32a-4176-986f-a2cb3aca28ec)


In the feature accuracy page
1. Move the `confirm accuracy` to the top of the page. Authors can avoid reading through the page and verify the accuracy right away if they are confident about the information.

![Screenshot 2024-10-31 3 38 15 PM](https://github.com/user-attachments/assets/c39114b8-4a68-4b0b-836e-b0e348bf1afc)

**Comment by KyleJu** [comment]
This is complete
