### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by Jayokqwr** [GoogleChrome/chromium-dashboard#4360]
Why aren't I receiving and able to send web messages from various individuals I've texted with prior days ago. It something you guys are doing that's changing the strip strings or whatever else it could be. I have no idea. All I know is I want basic dns enable with capabilities to receive all calls text and notifications to my phone. I do not appreciate these changes taking place. Why aren't I able t have consistent dialogue via text. Only Google sponsored apps are running.why aren't my background apps running constantly freely 
[bugreport-T434D-UP1A.231005.007-2024-09-13-14-41-02-dumpstate_log-12762.txt](https://github.com/user-attachments/files/16998197/bugreport-T434D-UP1A.231005.007-2024-09-13-14-41-02-dumpstate_log-12762.txt)
[dumpstate-stats.txt](https://github.com/user-attachments/files/16998198/dumpstate-stats.txt)
[Uploading bugreport-T434D-UP1A.231005.007-2024-09-13-14-41-02.zip…]()

**Comment by jrobbins** [comment]
This issue tracked is only for the chromestatus.com website.

**Comment by Jayokqwr** [comment]
Why is chrome connected to c2d messaging. I want all incoming text and calls to my Google voice account like normal. Please do not allow chrome to middle man my service. I'm not receiving any foreground messages in my third party apps

**Comment by Jayokqwr** [comment]
![Uploading Screenshot_20240917-161303.png…]()
