### ISSUE TITLE
Feature - Blocking of any geo-locations  / any feature by hacking / hackers

### ISSUE THREAD

**Issue by crazyart1213** [GoogleChrome/chromium-dashboard#4362]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] - working on youtube channel, someone blocked many features of the program.......... 

**Describe the solution you'd like**
A clear and concise description of what you want to happen. - 

1)I believe to be informed (owner), when changes are made. Informing date, time, location. (this also should have pin system

2)U can have an option (changes made by owner / editor / visitor / agency.

3)If these changes are made an email info maybe send to primary and alternative email

4)the primary email should have more security options - On my account it should be hidden. or a code or pin system be available

**Additional context**
Text - You tube should be more under strong security features.
           Even if someone enters - a pin or cross checking feature should be available.

**Comment by jrobbins** [comment]
This issue tracker is only for problems with chromestatus.com.
