### ISSUE TITLE
Remove the red highlighting for usage <0.03%

### ISSUE THREAD

**Issue by foolip** [GoogleChrome/chromium-dashboard#439]
0.03% isn't mentioned in http://www.chromium.org/blink and it's not a rule that things with higher usage can't be removed. Since we have to judge the usage differently depending on what kind of thing it is (attribute, method, code path in parser, etc.) it's just as well to not make 0.03% special on chromestatus.com.

FYI @chrishtr @dglazkov @jeisinger @RByers @tkent-google

**Comment by RByers** [comment]
Yeah I agree having a special "cut-off" value has caused more harm than good (0.03% of page views is still a LOT of page views, yet people tend to assume that it's fine to break anything below that without further consideration / mitigations.

/cc @mdittmer
