### ISSUE TITLE
Include released date and estimated release date for milestones

### ISSUE THREAD

**Issue by robbecker-wf** [GoogleChrome/chromium-dashboard#440]
I would love to use chromestatus.com to see when versions of chrome were released and when new versions will advance to the next stage.

**Comment by ebidel** [comment]
We would love to put release date information up, but my understanding is that Chrome's release team purposefully does not publish estimated dates so people don't rely on the information (dates slip, plans change, etc.) We have internal pages that show the schedule but nothing public. 

That said, it would be cool to put up the historical information on when a milestone shipped to stable.

cc @RByers

**Comment by robbecker-wf** [comment]
I understand not wanting to publish future dates, so I'll settle for released dates for Chrome stable.

**Comment by RByers** [comment]
ebidel@ something quietly changed around that policy awhile back - see [this public page](https://www.chromium.org/developers/calendar).

**Comment by ebidel** [comment]
Oh woot! Maybe we can just make that page more accessible and link off to it?

**Comment by jpmedley** [comment]
This is covered now by the [Roadmap](https://chromestatus.com/roadmap) view.
