### ISSUE TITLE
Update development status for intersection observer

### ISSUE THREAD

**Issue by NoNameProvided** [GoogleChrome/chromium-dashboard#441]
According to the [WebKit Status page](https://webkit.org/status/#specification-intersection-observer) the _Intersection Observer_ is in development in Safari. The [Chromium Dashboard feature page](https://www.chromestatus.com/features/5695342691483648) says no public signal from Safari. This info is pulled for for the [Microsoft Edge Platform Status](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/intersectionobserver/) as well so it's needs to be fixed here first to be fixed there. 

I couldn't find a way to edit this status information, but if anyone guide me how to do so I will happily open a PR for this one and any other findings.

**Comment by mdittmer** [comment]
Fixed. FYI, issues are edited by logging in to chromestatus.com via your chromium.org account.
