### ISSUE TITLE
Safari supports Content-Security-Policy Level 2

### ISSUE THREAD

**Issue by vcsjones** [GoogleChrome/chromium-dashboard#442]
Safari as of 9.3 in iOS and macOS support Content-Security-Policy Level 2, in full.

WebKit blog: https://webkit.org/blog/6830/a-refined-content-security-policy/
caniuse: http://caniuse.com/#feat=contentsecuritypolicy2

**Comment by ebidel** [comment]
Which feature is this referring to? I don't see a general CSP2 feature on https://www.chromestatus.com/features#csp.

**Comment by vcsjones** [comment]
@ebidel https://www.chromestatus.com/feature/4957003285790720

**Comment by ebidel** [comment]
Of course! I should have broadened my search :)

Updated the data. Thanks for the reporr.

**Comment by wr0ngway3** [comment]
look any further communication you recieve from this user DONOTREPLY HACKER
WARNING
