### ISSUE TITLE
Incorrect tool tip on "Web developers" in the "Consensus & Standardization" section

### ISSUE THREAD

**Issue by gsathya** [GoogleChrome/chromium-dashboard#444]
Hovering over the web developers icon says "Web developers: In development" instead of "Web developers: Positive signals".

Screenshot --

![bug](https://cloud.githubusercontent.com/assets/565765/22122141/a2fc1c88-de3b-11e6-92c8-f98d3bb5d201.png)

Although this seems to work fine for "Mixed public signals" value.

**Comment by beaufortfrancois** [comment]
Thanks for reporting this issue @gsathya!
@ebidel Can you have a look at https://github.com/GoogleChrome/chromium-dashboard/pull/446?
