### ISSUE TITLE
Replace chrome://flags with about://flags for feature flag question

### ISSUE THREAD

**Issue by SamFort-MSFT** [GoogleChrome/chromium-dashboard#4500]
Consider replacing chrome://flags with about://flags given multiple embedders support the same page and methodology for a developer to change the flag and experiment with a web platform feature.

**Comment by jstenback** [comment]
It appears both work in Chrome already. I agree that we should do this.

**Comment by jrobbins** [comment]
Just to clarify, I believe that this issue is about changing the field-level help-text to use a more browser-neutral term.

**Comment by jstenback** [comment]
I won't speak for Sam, but that was my interpretation as well.

**Comment by SamFort-MSFT** [comment]
Apologies that I wasn't as clear as I could have been originally. There were two places I was thinking of:

1. field-level help-text: i.e. this string: Name of the flag on chrome://flags that allows a web developer to enable this feature in their own browser to try it out. E.g., "storage-buckets". These are defined in [about_flags.cc](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/about_flags.cc).
2. The Intents emails that are generated. Right now, those emails use "Flag name on chrome://flags" to represent this field value.
