### ISSUE TITLE
Update CSS Box Alignment

### ISSUE THREAD

**Issue by scheinercc** [GoogleChrome/chromium-dashboard#455]
https://www.chromestatus.com/feature/6173208034148352 seems to be outdated:
- Firefox ~ in Development
https://bugzilla.mozilla.org/show_bug.cgi?id=1105571
https://platform-status.mozilla.org/#css-box-alignment-block
- Edge ~ Under Consideration
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/boxalignment/

**Comment by ebidel** [comment]
Update the database. Thanks for reporting!
