### ISSUE TITLE
MSEdge does not support the latest CSS Grid spec 

### ISSUE THREAD

**Issue by SaschaNaz** [GoogleChrome/chromium-dashboard#456]
[Chrome status page](https://www.chromestatus.com/features/4589636412243968) incorrectly says MSEdge supports it. Microsoft did [started working on it](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/gridupdate/?q=grid) but the work is not released yet.

**Comment by ebidel** [comment]
It looks like they shipped a prefixed version and are working on updates. Is that your read too?

**Comment by SaschaNaz** [comment]
Yes. Related PR on Firefox side: https://github.com/mozilla/platform-status/pull/466

**Comment by ebidel** [comment]
Fixed in the db to point to the new update.
