### ISSUE TITLE
Duplicate feature entries

### ISSUE THREAD

**Issue by rmahdav** [GoogleChrome/chromium-dashboard#4563]
I have just noticed that when I created an entry for my feature, two entries were created [this](https://chromestatus.com/feature/5087324181102592) and [this](https://chromestatus.com/feature/5173800596144128). Since the time stamp of their creation time have 1 second difference, I suspect that this is a bug.

**Comment by rmahdav** [comment]
![image](https://github.com/user-attachments/assets/59470bdf-db11-442b-8882-2479cbdfd42c)
 and 
![image](https://github.com/user-attachments/assets/5a609d7e-a714-4411-a6a5-43ff45a3207c)

**Comment by jrobbins** [comment]
It seems that the second one has been marked as deleted now.

I was able to repro this by focusing on the feature creation page `Submit` button and pressing Return multiple times.  I thought that we had some debouncing code, but apparently that is not the case.

**Comment by rmahdav** [comment]
Yeah, I deleted the duplicate one. Thanks for looking into this! I did not know how that happened.
