### ISSUE TITLE
Increase metrics precision from 4 to 6 decimal places

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#458]
The [usage stats](https://www.chromestatus.com/metrics/feature/popularity) are [truncated](https://github.com/GoogleChrome/chromium-dashboard/blob/ab8c0a70389db44bdb0b4798a8619ecfe54d2155/common.py#L61) to 4 decimal places of percentage.  Based on API owner [experience](https://docs.google.com/document/d/1RC-pBBvsazYfCNNUSkPqAVpSpNJ96U8trhNkfV0v9fk/edit#), we now believe this isn't enough for good decision making.  Seriously breaking even 1 in a million page views is often not something we can do without careful consideration.  I think adding just one more decimal place would probably be enough though (see [discussion](https://docs.google.com/document/d/1RC-pBBvsazYfCNNUSkPqAVpSpNJ96U8trhNkfV0v9fk/edit?disco=AAAABBfmAVI)).  Can we do that?

**Comment by mikewest** [comment]
I wonder if metrics folks could tell us how much noise there is in the data. That is, it's a public API endpoint, I have to imagine that it's being spammed. There might be a reasonably situated floor below which everything is error bars anyway.

**Comment by RByers** [comment]
Anecdotally, looking at timelines internally there seems to be a reasonable signal at the 5-decimal-point level (eg. see go/mwrbusecounter).

**Comment by mikewest** [comment]
> Anecdotally, looking at timelines internally there seems to be a reasonable signal at the 6-decimal-point level

I guess my question is whether that's "reasonable signal" or "noise". I'm happy to believe that it's the former, though. :) I'm all for more precision.

**Comment by RByers** [comment]
> I guess my question is whether that's "reasonable signal" or "noise".

If the level is roughly consistent over time and there's a clear and consistent discrimination between different buckets then that seems like it can't be "noise" to me.  Also a pattern that repeats on a 7-day cycle seems more likely to be legitimate than noise (since we know aggregate browsing behavior is different on weekends than weekdays).

I.e. the difference between these three lines is statistically significant and meaningful (note the troughs are all on Saturday):

![image](https://cloud.githubusercontent.com/assets/1280419/25707238/eda280ac-30b0-11e7-8b58-c101f92a187f.png)

While the difference between these are not:

![image](https://cloud.githubusercontent.com/assets/1280419/25707378/59a5d3b2-30b1-11e7-8ecd-6dd7f06d385f.png)

**Comment by mikewest** [comment]
SGTM. :)

**Comment by RByers** [comment]
Sounds like we're fine making this change.  @ebidel mind landing it?

**Comment by ebidel** [comment]
Will do tomorrow!

**Comment by ebidel** [comment]
The chromestatus side of this is done. I've increased the metrics to 6 decimals in https://github.com/GoogleChrome/chromium-dashboard/commit/31079159006d0f61c17cf1059ae6d737ab693624 and deployed those changes. We're still waiting on the internal UMA cl to land so we begin collecting higher precision metrics. Once that lands, we should automatically show more decimals.

I'll leave this open until chromestatus shows the updates.

**Comment by ebidel** [comment]
This should be fixed. https://www.chromestatus.com/metrics/feature/popularity

**Comment by ebidel** [comment]
<img width="592" alt="screen shot 2017-06-05 at 5 53 43 pm" src="https://cloud.githubusercontent.com/assets/238208/26809219/ee1ae7ce-4a17-11e7-8d46-afa16a8bd848.png">
