### ISSUE TITLE
Deleted entry still showing in ChromeStatus database

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/chromium-dashboard#4587]
**Describe the bug**
https://chromestatus.com/feature/5169880146640896 was deleted but still shows in the database. The new entry is https://chromestatus.com/feature/5134341540413440

**Expected behavior**
The deleted entry should not show up in the database?

**Additional context**
This is tripping up our privacy reviewer bot.

**Comment by jrobbins** [comment]
This change is live now.
