### ISSUE TITLE
Move the use counter field to an earlier stage

### ISSUE THREAD

**Issue by past** [GoogleChrome/chromium-dashboard#4606]
**Is your feature request related to a problem? Please describe.**
We already require use counters for features in OT, but often features have counters that don't go through a trial stage. 

**Describe the solution you'd like**
We should surface the use counter field in an earlier stage (probably DevTrial)  so that every feature can be connected to a use counter.

**Additional context**
This is a small part of the broader project in our backlog to display use counter data in the feature details page.

**Comment by Saleemfarheen** [comment]
> **Is your feature request related to a problem? Please describe.**
> We already require use counters for features in OT, but often features have counters that don't go through a trial stage. 
> 
> **Describe the solution you'd like**
> We should surface the use counter field in an earlier stage (probably DevTrial)  so that every feature can be connected to a use counter.
> 
> **Additional context**
> This is a small part of the broader project in our backlog to display use counter data in the feature details page.
>
