### ISSUE TITLE
Chrome Windows msi 131.0.6778.109 don't install BUG

### ISSUE THREAD

**Issue by steom** [GoogleChrome/chromium-dashboard#4608]
![image](https://github.com/user-attachments/assets/4c5644af-cffe-4340-bc56-ca7d58fa5b71)

both as update or clean install

maybe caused by WiX Toolset (5.0.1.0) instead of the usual Windows Installer XML Toolset (3.8.1128.0)

**Comment by jrobbins** [comment]
Thanks for filing this report! Unfortunately this is the wrong tracker for the Chrome browser (this tracker is for the website chromestatus.com). Please file the Chrome issue at https://crbug.com/new
