### ISSUE TITLE
Add a vendor status "public interest" (in between mixed and pub support)

### ISSUE THREAD

**Issue by mgiuca** [GoogleChrome/chromium-dashboard#461]
I currently have to choose between "mixed public signals" and "public support" for a third-party vendor status. I want something in between that (and I suspect it's a fairly common case) for when a vendor has expressed interest (e.g., filing a bug on their own tracker) but does not officially support the proposal. "Mixed" is too weak; it implies there are dissenting opinions. "Support" is too strong; it implies they will come to bat for us.

I suggest "public interest" or "publicly under consideration" or something to that effect.

Case study: [Web Share](https://www.chromestatus.com/features/5668769141620736). Both Apple and Mozilla have a public bug ([WebKit](https://bugs.webkit.org/show_bug.cgi?id=171100), [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1312422)) tracking it, which publicly shows interest in the API. Nobody has dissented from either vendor. The [WebKit Feature Status](https://webkit.org/status/) dashboard lists it as "Under Consideration". I think "public support" is a bit too strong for describing their position.

**Comment by yoichio** [comment]
+1 to support more subtle circumstances.

One example is [Intent to Implement: fetch() upload streaming](https://groups.google.com/a/chromium.org/g/blink-dev/c/hqzIf3gdahs) thread:
 > For Mozilla, I believe that counts as "positive signals", but not "public support".

 but the feature dushboard has only "Shipped", "In development", "Public support", "Mixed public signals", "No public signals", "Public skepticism" and "Opposed" items.

**Comment by jyasskin** [comment]
I think we can close this, now that Firefox and Safari have dedicated positions repositories with clear mappings to our states. https://bit.ly/blink-signals
