### ISSUE TITLE
Dashboard Entry Contains Link to Itself

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#465]
[This ticket](https://www.chromestatus.com/features/6680566019653632) contains a link to itself next to 'Documentation/Samples'. I clicked edit to remove it and couldn't find the link in any of the fields.

**Comment by jpmedley** [comment]
This doesn't appear to be a caching problem.

**Comment by jpmedley** [comment]
Here's another one with the same problem. https://www.chromestatus.com/features/5629582019395584

**Comment by ebidel** [comment]
It looks like this happens when people include a newline in the samples section of the form.

I just removed the extra line from https://www.chromestatus.com/features/5629582019395584 that seemed to do the trick.

**Comment by jpmedley** [comment]
For now, I'll keep my eye out and remove them when I find them. Any chance you can run a trim() function on the field during submit?

**Comment by ebidel** [comment]
Fixed. If you run into any, please fix em up. New entries should be g2g.
