### ISSUE TITLE
Blink: update Intent to Implement email template

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#469]
https://github.com/GoogleChrome/chromium-dashboard/blob/ab8c0a70389db44bdb0b4798a8619ecfe54d2155/templates/blink/intent_to_implement.html has diverged from the Intent Email templates I'm seeing get sent to blink-dev. We're missing lines like "Is this feature fully tested by web-platform-tests?"

Need to track down the master template or get folks using chromestatus's template.

cc @RByers

**Comment by henceproved** [comment]
[Intent email templates](https://docs.google.com/document/d/1vlTlsQKThwaX0-lj_iZbVTzyqY7LioqERU8DK3u3XjI/edit)

This help?

**Comment by RByers** [comment]
Yeah it's annoying to have this duplicated.  The [official instructions](https://www.chromium.org/blink/launching-features) have links to that master doc.  IIRC we talked about trying to unify the two copies somehow but it seems non-trivial.  /cc @foolip

**Comment by ebidel** [comment]
I'm cool with whatever is easiest for the Chrome team. 
 
But I'd love not to remove chromestatus's version and not maintain an outdated version if the doc is going to be the source of truth.

I do think it's convenient that there's a copy-n-paste email at the end of creating a new feature, with all the values filled in. We'd just have to 1.) encourage folks to use it, 2.) put in other links to regenerate email templates for intent to impl, intent to ship, etc.

Thoughts?

**Comment by RByers** [comment]
Product team ownership of issues like this is probably [blocked on me here](https://bugs.chromium.org/p/chromium/issues/detail?id=806680).

**Comment by phistuck** [comment]
We sometimes get intents with this outdated template... How about making chromestatus.com be the source of truth instead? Maybe store it in a database like the rest of the content of the site and so any @chromiim.org could edit it.

**Comment by yoavweiss** [comment]
At a recent thread, this [seemed like](https://groups.google.com/a/chromium.org/d/msg/blink-dev/jx2joIL5SbU/iCtVg2bOEAAJ) the origin of another outdated template.

Is it possible to update the templates manually until a full-fledged syncing solution will be in place?

FWIW, @phistuck's suggestion to make this repo be the source of truth instead of the doc seems simple enough to get done. Is there any reason to stick with the document instead?

**Comment by foolip** [comment]
If this is the source of truth, will there be a page that can be copy-pasted with formatting? A template alone isn't that, so maybe we can render it somewhere?

**Comment by yoavweiss** [comment]
I guess we can create a JS rendered page which takes https://github.com/GoogleChrome/chromium-dashboard/blob/master/templates/blink/intent_to_implement.html as input and makes it copy-pastable

**Comment by phistuck** [comment]
@ebidel - I believe this is the latest -
https://docs.google.com/document/d/1vlTlsQKThwaX0-lj_iZbVTzyqY7LioqERU8DK3u3XjI/edit#heading=h.6pbzrinh7kv4
Though it seems to have been hacked a bit (how?! I do not have access to the version history).

**Comment by clelland** [comment]
@phistuck, I think what you're seeing are "suggestions", which are unfortunately visible by default in this case. If you switch to "Viewing" mode, you should see that the original document is still there under the suggested edits.

**Comment by phistuck** [comment]
@clelland - thank you, that was such a rookie mistake. ;)
As nice as this picture seems, someone should really reject those suggestions, though...

**Comment by foolip** [comment]
I've rejected the edits and changed the sharing settings to just view :/

**Comment by ojanvafai** [comment]
I think we should get rid of the template docs entirely. Let's generate the intent to * emails from chromestatus itself. That will make it easier to write intents, create less duplicate work, and ensure that they template *can't* get out of sync with chromestatus.

**Comment by domenic** [comment]
Right now there are three ways people create intents:

1. Using the doc template
2. Using the Chrome Status results
3. Copying an old email sent to blink-dev and filling in values

This thread is about unifying 1 and 2, but anecdotal evidence indicates the true problem is 3; most out of sync intents come from that. It'd be nice to address 3 somehow.

My tentative suggestion is to put some text like

> WHEN CREATING YOUR OWN INTENT, DO NOT COPY AND MODIFY THIS EMAIL. INSTEAD GENERATE A NEW ONE VIA $URL.

and then making sure that actually gets sent out with every intent email. Probably there are better ways though.

**Comment by jpmedley** [comment]
Since Chrome Status is not supposed to be used in stead of whatever Google Docs templates are hanging around, I'm closing this.
