### ISSUE TITLE
Update Logical Properties support

### ISSUE THREAD

**Issue by jonathantneal** [GoogleChrome/chromium-dashboard#471]
Hello. I noticed [CSS Logical Properties](http://caniuse.com/css-logical-props) is far more evolved than [Microsoft’s Platform Status](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/csslogicalpropertieslevel1/) suggested, so [I filed a pull request to fix this](https://github.com/MicrosoftEdge/Status/pull/530), and [I was redirected](https://github.com/MicrosoftEdge/Status/pull/530#issuecomment-309921608) to ask here about it.

I hope I’ve done this right.

**Comment by ebidel** [comment]
Updated the entry: https://www.chromestatus.com/feature/6325742262550528

That look ok?
