### ISSUE TITLE
Duplicate entries created

### ISSUE THREAD

**Issue by pwnall** [GoogleChrome/chromium-dashboard#479]
I've somehow managed to create two entries for the same feature:

https://www.chromestatus.com/feature/5669618848890880
https://www.chromestatus.com/feature/5740723861192704 (duplicate)

Can you please remove the duplicate? Many thanks!

**Comment by jpmedley** [comment]
And here's another one:

https://www.chromestatus.com/features/5703688089763840
https://www.chromestatus.com/features/5713301031878656 (duplicate)
