### ISSUE TITLE
Turn urls into clickable links

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChrome/chromium-dashboard#482]
For example on https://www.chromestatus.com/feature/4964279606312960 a url is posted. It would be nice if that url would be clickable (with the url as text), so mobile users dont need to copy-paste.

**Comment by ebidel** [comment]
This was removed in https://github.com/GoogleChrome/chromium-dashboard/commit/730b46adde5ec9aa3bffe34c318c02a613c56228, but we should probably bring it back. I'd have to look at perf again to see how much overhead the extra stuff was adding.

**Comment by OscarF95** [comment]
Hi, I'd like to fix this issue but I'm having some trouble trying to run the application and actually test it.
