### ISSUE TITLE
Use official chrome logos for the releases page

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/chromium-dashboard#484]
Let's use official chrome logos for the releases page:
https://www.gstatic.com/images/icons/material/product/2x/chrome_512dp.png
https://www.gstatic.com/images/icons/material/product/2x/chrome_beta_512dp.png
https://www.gstatic.com/images/icons/material/product/2x/chrome_dev_512dp.png

Feel free to play with image URLs to find the appropriate size.

**Comment by ebidel** [comment]
PR?
