### ISSUE TITLE
Fix "stats" button top alignment

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/chromium-dashboard#485]
See screenshots below
![screenshot 2017-07-28 at 10 19 20 am](https://user-images.githubusercontent.com/634478/28708912-48343e10-737e-11e7-857e-49eb7bdba54d.png)
![screenshot 2017-07-28 at 10 19 03 am](https://user-images.githubusercontent.com/634478/28708915-485cc4fc-737e-11e7-9ca0-0d9e65742efb.png)

**Comment by ebidel** [comment]
what device and browser version is this? Can't repo on nexus 5x or a pixel.

**Comment by beaufortfrancois** [comment]
I can reproduce on Chromebook and Chrome for Mac now.

```
Google Chrome	62.0.3195.0 (Official Build) canary (64-bit)
Revision	0
Platform	9874.0.0 (Official Build) canary-channel samus
```
```
Version 60.0.3112.101 (Official Build) (64-bit)
```
