### ISSUE TITLE
"Blink>Media>Video" is missing

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/chromium-dashboard#496]
https://www.chromestatus.com/feature/5682169347309568 tells me "Blink>Media>Video" is not a valid choice while it was clearly one at some point.

Any idea what happened?

For now, I've updated it to "Blink>Media" but it would be nice to have it fixed.

**Comment by ebidel** [comment]
Some used it on the https://bugs.chromium.org/p/chromium/issues/detail?id=310450. We pull the first tag from the bug if you save the feature with the generic "Blink" component when it's first created.

Blink>Media>Video might be new or non-standard. It's not listed in blinkcomponents-b48b5.firebaseapp.com/blinkcomponents, which is where that list comes from.

LMK if you run into others like this. I'm making a list for the TPMs :)

**Comment by beaufortfrancois** [comment]
Thanks @ebidel.
Where is the source code for blinkcomponents-b48b5.firebaseapp.com/blinkcomponents and where I can contribute?

**Comment by beaufortfrancois** [comment]
I can see "Blink>Media>Video" in component drop list at https://bugs.chromium.org/p/chromium/issues/list

**Comment by beaufortfrancois** [comment]
@ebidel I'm still running in the same issue with `Blink>Media` and now `Blink>Media>PictureInPicture`.
Let me know where I can update https://blinkcomponents-b48b5.firebaseapp.com/blinkcomponents if possible.

Thank you!

**Comment by ebidel** [comment]
You should ask the owners to add them to https://storage.googleapis.com/chromium-owners/component_map.json.

**Comment by jpmedley** [comment]
@jrobbins These still seem to be issues.

**Comment by jpmedley** [comment]
Not sure when this was fixed (#1466?).
