### ISSUE TITLE
HTML/JS features name does not in sync with latest source

### ISSUE THREAD

**Issue by TakayoshiKochi** [GoogleChrome/chromium-dashboard#501]
I noticed that some of the feature names are old ones, not the latest one.

https://www.chromestatus.com/metrics/feature/timeline/popularity/1123 EventDeepPath
https://www.chromestatus.com/metrics/feature/timeline/popularity/1140 EventScoped

EventDeepPath should be EventComposedPath, EventScoped should be EventComposed.
They were renamed due to API renaming, but reused the same number.

I did not exhaustively tested, so there may be other renamed names.

**Comment by ebidel** [comment]
Whenever things are renamed in UMA that really messes things up :(

I bet that explains the doubt entries:
<img width="645" alt="screen shot 2017-09-08 at 10 45 01 am" src="https://user-images.githubusercontent.com/238208/30224243-d1c38b02-9482-11e7-9051-278dc4191254.png">

**Comment by TakayoshiKochi** [comment]
Aha, yes, EventDeepPath entry is also duplicated.

I looked at the chromium-dashboard source but it seems the entries seem stored in appengine's
memcache, and I could not dig further.  What can I do for helping to get this fixed?

**Comment by ebidel** [comment]
I can go through and update the database later today.

**Comment by TakayoshiKochi** [comment]
Ping?   I still see duplicate entries.

**Comment by ebidel** [comment]
Sorry, was on vacation. I'll try and get to this next week.

**Comment by ebidel** [comment]
update: Planning to look at this and other issues next week. After CDS :)

**Comment by TakayoshiKochi** [comment]
Thanks!

**Comment by ebidel** [comment]
Both of these should be fixed now. Give the stank rank list 24hrs to update, but the individual graphs are looking good.

https://www.chromestatus.com/metrics/feature/timeline/popularity/1140
https://www.chromestatus.com/metrics/feature/timeline/popularity/1123
