### ISSUE TITLE
WebShare: restrict to android

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#508]
Pretty silly that the feature detect returns positive on desktop. We should hide the icon on desktop since it's only supported on Chrome Android.

**Comment by PaulKinlan** [comment]
It shouldn't run on desktop unless you have the flag there, the API is not supposed to be exposed.

There was supposed to be canShare() on navigator object.

**Comment by beaufortfrancois** [comment]
@PaulKinlan is right. `navigator.share` is available on Desktop if you've enabled `chrome://flags/#enable-experimental-web-platform-features`. That's all.

**Comment by ebidel** [comment]
It's present, but a noop :\ If it's behind a flag, probably not a big deal. Most users won't run into this issue.
