### ISSUE TITLE
Remove shipped status for Battery Status API support from Firefox

### ISSUE THREAD

**Issue by makotokato** [GoogleChrome/chromium-dashboard#511]
https://www.chromestatus.com/features/4537134732017664

This page says that Firefox is shipped, but Mozilla don't ship this API from version 52 [*1] [*2].  So this page should not mark as Shipped for Firefox.

*1 https://groups.google.com/d/msg/mozilla.dev.platform/5U8NHoUY-1k/9ybyzQIYCAAJ
*2 https://bugzilla.mozilla.org/show_bug.cgi?id=1313580

**Comment by myakura** [comment]
@makotokato Thanks. Updated with the changes noted below:

1. mark Firefox status as "Public skepticism" as there's no "removed" status :(
2. add the following comment with the link pointing to the dev-platform thread
  > Firefox removed support for the API in Firefox 52 due to privacy concerns. 
  > https://groups.google.com/d/msg/mozilla.dev.platform/5U8NHoUY-1k/9ybyzQIYCAAJ

Let me know if that's okay for you.

**Comment by makotokato** [comment]
> Let me know if that's okay for you.

no problem.
