### ISSUE TITLE
add a vendor status "removed" (or marking as no longer pursuing)

### ISSUE THREAD

**Issue by myakura** [GoogleChrome/chromium-dashboard#512]
There's a content feedback from Mozilla in #511 that they removed support for Battery API.
I just changed their status as "public skepticism" as there's no "removed".

For feature removal in Chrome you can create a new "Remove ***" entry, but that cannot be done for other vendors.
Some features like CSS Regions are being removed from Safari, so we'll need some status noting that vendor removed or is no longer pursuing the feature.

**Comment by ebidel** [comment]
When possible, we're trying to avoid tracking each vendor at this level of granularity. The vendor views are mainly meant as a barometer for developers to know where other vendors sit. Wording is less critical IMO. So reusing something like "Public Skepticism" or "Opposed" would work. That creates a red signal. "Opposed" would be good for this one b/c there is public docs on why it was removed.
