### ISSUE TITLE
Variation Font Support Status Updates

### ISSUE THREAD

**Issue by gregwhitworth** [GoogleChrome/chromium-dashboard#514]
On our Microsoft Edge status page we just flipped variation fonts to "In Development" and realized that chromestatus data that we're pulling in is incorrect. Firefox has it in development, Safari shipped it last month. So if you could please update FF/Edge/Safari to reflect the current state we would greatly appreciate it. Thank you.

**Comment by gregwhitworth** [comment]
cc: @RByers

**Comment by ebidel** [comment]
Do you have reference links for those statues? We like to link to resources.

@patrickkettner has been helping update Edge information and has access to edit data. Please reach out to him if you see any other discrepancies.

**Comment by ebidel** [comment]
Also is this https://www.chromestatus.com/features/4708676673732608?

**Comment by patrickkettner** [comment]
updated edge and safari data, trying to find firefox info (don't think jdaggett is on github/twitter?)

**Comment by ebidel** [comment]
Thanks Pat. Closing this one out.
