### ISSUE TITLE
JS metrics page throwing 500

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#519]
https://www.chromestatus.com/metrics/feature/popularity is throwing a 500

Looks like we need to chunk the memcache data just like /features

<img width="868" alt="screen shot 2017-10-17 at 10 49 44 am" src="https://user-images.githubusercontent.com/238208/31680370-f407f2c4-b328-11e7-8d48-40e1451d85a6.png">

**Comment by yoichio** [comment]
TPAC is coming and I want to know this metrics ASAP.

**Comment by ebidel** [comment]
Should be fixed now. Sorry for the troubles.

**Comment by RByers** [comment]
Note that Googlers should prefer using the internal data anyway - [see instructions](https://www.chromium.org/blink/platform-predictability/compat-tools)
