### ISSUE TITLE
Consider showing a special icon for “Behind a flag” entries

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/chromium-dashboard#520]
One common way that web developers use Chrome Status is to click on a browser version in the left sidebar, and then inspect the entries associated with that version. This is especially useful when a new Chrome version ships, and the developer wants to know which new features shipped with it.

An entry can be in one of the following categories:

* Enabled by default
* Behind a flag
* Browser intervention
* Deprecated
* Removed

Notice how the latter three categories also have a special icon that is displayed in the top right corner of the entry. Could we have such an icon for “behind a flag” entries as well?

For a developer, the difference between “enabled by default” and “behind a flag” is very significant, so I think it’s important that “behind a flag” entries are clearly labelled. Something like a purple flag icon could help with that.

**Comment by mathiasbynens** [comment]
The colors on the left represent the status. E.g. green means “enabled by default”.

![](https://user-images.githubusercontent.com/81942/31826875-1cd4a852-b56b-11e7-81e7-aa4e3cf9fad7.png)

**Comment by simevidas** [comment]
It doesn’t look like it. Instead, that color seems to be a mix between all the colors in the “consensus and standardization” section.

For example, go to https://www.chromestatus.com/features#milestone=61, and notice how there are a bunch of “enabled” entries that are orange or yellow.

**Comment by ebidel** [comment]
We have a flag icon when things are behind a flag. It could be a bug if it's not showing up. Do you have an example "behind the flag" feature that it's not showing for?

@simevidas is correct about the side colors. Those represent the overall "consensus" of the vendors.

BTW, to see what features are in a release, https://www.chromestatus.com/features/schedule is a great new view for that :)

**Comment by simevidas** [comment]
@ebidel Yes, open https://www.chromestatus.com/features#milestone=61, and scroll down to WebUSB API.
