### ISSUE TITLE
[Feature Request] Add a link and corresponding that shows all issues currently listed as "Behind a flag".

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#533]

**Comment by ebidel** [comment]
Little hard to discover, but we could put this in the help popup"

https://www.chromestatus.com/features#browsers.chrome.status.val%3D4

**Comment by jpmedley** [comment]
What's the help popup?

**Comment by ebidel** [comment]
<img width="1250" alt="screen shot 2018-02-22 at 4 56 04 pm" src="https://user-images.githubusercontent.com/238208/36572545-4986de18-17f1-11e8-9d74-3934883c8eb2.png">
