### ISSUE TITLE
Output data of visible entries to a CSV file

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#534]
I have multiple use for this. How hard would it be to do?

**Comment by jpmedley** [comment]
Emphasis on **visible entries**.

**Comment by ebidel** [comment]
Rather than building this into the site, I'd recommend consuming the features list (https://www.chromestatus.com/features.json) in a app script and/or google spreadsheet. IRC, I  think there's even an `importJson()` method :)

**Comment by jpmedley** [comment]
Then I have to build my own sorting and searching.

**Comment by ebidel** [comment]
Spreadsheets is pretty good at both :) I don't think CSV output makes sense to support on the site sense we have json and rss already.

What's your use case?
