### ISSUE TITLE
[Proposal] Add a Box Labeled 'Motivation'

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#535]
Here's my arguments:
(1) It would better communicate with the developer community what a change is about. 
(2) It will assist me in writing the beta blob post where I need to communicate the answer to this question.

Incidentally, I can regurgitate API functionality from now until the end of time. As a non-eng, I've always been a bit week on the why.

I open the floor for discussion.

**Comment by ebidel** [comment]
IMO, this is the job of our DA/DPEs. Create content around why developers should care about an API, it's useful cases, how to use it with other features/tools, etc.

**Comment by jpmedley** [comment]
The how about splitting description into two boxes: problem and solution?

**Comment by jpmedley** [comment]
This was partially addressed by #589 which exposed a new 'Motivation' field adopted from the Blink launch process. Currently, this field is internal only. Exposing it to external viewers will finish this proposal.

**Comment by jpmedley** [comment]
Addressed by #603
