### ISSUE TITLE
Remove usage of HTML Imports styling the main document

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#539]
<img width="1272" alt="screen shot 2018-03-23 at 11 03 35 am" src="https://user-images.githubusercontent.com/238208/37846117-da5b4ee8-2e89-11e8-9aeb-7cbce8de6771.png">

https://bugs.chromium.org/p/chromium/issues/detail?id=822135

**Comment by jrobbins** [comment]
This was done
