### ISSUE TITLE
V8SloppyMode is used on 119% of pages

### ISSUE THREAD

**Issue by progers** [GoogleChrome/chromium-dashboard#553]
V8SloppyMode is used on 119% of pages:
https://www.chromestatus.com/metrics/feature/popularity

But it is actually only used on 79% of pages:
https://www.chromestatus.com/metrics/feature/timeline/popularity/1075

I think this is just a problem on the overview feature popularity page.

**Comment by ebidel** [comment]
See https://github.com/GoogleChrome/chromium-dashboard/issues/545. Apparently this is fixing itself in m67 as the metrics were changed/fixed from under us.

cc @loonybear

**Comment by ebidel** [comment]
Closing in favor of #545.
