### ISSUE TITLE
/features/schedule in inconsistent state

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/chromium-dashboard#554]
It's possible for https://www.chromestatus.com/features/schedule to end up in an inconsistent/unexpected state. When I loaded the page just now, I see "Chrome 65" listed as "Stable 76 days ago" and also "Chrome 66" listed as "Stable 34 days ago":

<img width="1364" alt="screen shot 2018-05-21 at 1 52 18 pm" src="https://user-images.githubusercontent.com/51244/40308678-ebd0a67a-5cfe-11e8-82a3-2d5c6a22006e.png">

The expected output is:

<img width="1298" alt="screen shot 2018-05-21 at 1 58 32 pm" src="https://user-images.githubusercontent.com/51244/40308727-10eb2494-5cff-11e8-9dfd-9a404bb1df7a.png">

After discovering this, I did take some screenshots of the state of the cache, but I don't think they'll be very useful since I reloaded the page in another tab (i.e. whatever "bad" state that was lurking in the cache) has probably gone away. But in case it helps:

<img width="908" alt="screen shot 2018-05-21 at 2 03 44 pm" src="https://user-images.githubusercontent.com/51244/40309119-5731c3ee-5d00-11e8-83da-06f004dfca50.png">
<img width="906" alt="screen shot 2018-05-21 at 2 03 36 pm" src="https://user-images.githubusercontent.com/51244/40309120-57489574-5d00-11e8-950d-c4bfcf5d15af.png">
<img width="898" alt="screen shot 2018-05-21 at 2 03 23 pm" src="https://user-images.githubusercontent.com/51244/40309121-575e225e-5d00-11e8-80f8-a1c01aaedc5f.png">

**Comment by ebidel** [comment]
There's a lot of caching on this page. SW caching, server/browser caching, backend memcaching of different JSON endpoints. For the page itself and the json handlers, the sw caching strategy is set to 'fastest` (https://github.com/GoogleChrome/chromium-dashboard/blob/master/gulpfile.babel.js#L190). I suspect you're seeing a stale sw cache from a previous visit. A page refresh should do the trick.
