### ISSUE TITLE
Origin Trial and Behind a Flag Labeling Incomplete.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#555]
A dashboard entry needs a way to indicate that something is both in an origin trial and behind a flag. These two states frequently occur at the same time. Currently, feature owners can only chose one or the other.

**Comment by clelland** [comment]
Origin trial features are a strict subset of those behind a runtime flag. We might want to change the way the information is displayed, but I don't think we need to make feature owners explicitly state both.
