### ISSUE TITLE
Some UseCounter graphs stop at March 22nd

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#556]
@ebidel @loonybear
It looks like a [number](https://www.chromestatus.com/metrics/feature/timeline/popularity/1441) of [graphs](https://www.chromestatus.com/metrics/feature/timeline/popularity/1540) have no data later than Mar 22, while [some do](https://www.chromestatus.com/metrics/feature/timeline/popularity/2195).  What's up?

**Comment by ebidel** [comment]
For those charts, [we filter out outliers](https://github.com/GoogleChrome/chromium-dashboard/blob/master/metrics.py#L53-L54) that don't fall within [0, 1] percentages. I think we should remove that filtering so the charts are consistent with the other bar charts.
