### ISSUE TITLE
Issue in getting TimezoneOffset from a Date object

### ISSUE THREAD

**Issue by vivekmadurai** [GoogleChrome/chromium-dashboard#559]
Developer console return wrong timezone offset after the latest update of the Chrome browser.

In **67.0.3396.79** version returns wrong timezone value,
new Date(1900, 0, 1).getTimezoneOffset() ==> **321**
new Date(1900, 0, 1) ==> Mon Jan 01 1900 00:00:00 GMT+0521 (IST)

Till **66.0.3359.181** version it works correctly,
new Date(1900, 0, 1).getTimezoneOffset() ==> **330**
new Date(1900, 0, 1) ==> Mon Jan 01 1900 00:00:00 GMT+0530 (IST)

I am from IST timezone, it returns 321 instead of 330 for the years before 1970.

**Comment by ebidel** [comment]
This is not the appropriate issue tracker to report issues in Chrome. crbug.com is your ticket :)
