### ISSUE TITLE
SameSite Cookies status in Firefox should be listed as 'shipped'

### ISSUE THREAD

**Issue by Gymnasiast** [GoogleChrome/chromium-dashboard#560]
(I was asked in https://github.com/MicrosoftEdge/Status to report this here.)

Firefox 60 introduced support for Same-Site cookies. Blog post here: https://blog.mozilla.org/security/2018/04/24/same-site-cookies-in-firefox-60/

The release notes of Firefox 60 do not mention the support, but it is implemented. See here for more details: https://bugzilla.mozilla.org/show_bug.cgi?id=795346#c58

**Comment by ebidel** [comment]
Done.
