### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by seal90** [GoogleChrome/chromium-dashboard#562]
I might have found a chrome security problem,But I didn't find a mailbox to feed this information.Can you tell me a mailbox that can feed back questions?thinks

**Comment by mdittmer** [comment]
Thanks for reporting! Please follow the general guidelines outlined here:
https://www.chromium.org/Home/chromium-security/reporting-security-bugs

**Comment by seal90** [comment]
You know I am in China,We have a scientific  Internet, so we are in a large LAN, so I have no access to this web site.So I need a mailbox address.

**Comment by ebidel** [comment]
Please follow the guidelines above if you think you find an issue.

**Comment by mdittmer** [comment]
If you need to initiate the conversation by email feel free to send to security@chromium.org

**Comment by seal90** [comment]
Thank you for your answer, I found the problem at spring. Thinks
