### ISSUE TITLE
Missing component "Blink>ReportingObserver"

### ISSUE THREAD

**Issue by jpchase** [GoogleChrome/chromium-dashboard#565]
The component "Blink>ReportingObserver" is missing from the list when editing a entry.

As in #496, this component is missing from https://blinkcomponents-b48b5.firebaseapp.com/blinkcomponents, and it's underlying source: https://storage.googleapis.com/chromium-owners/component_map.json.

Upon investigation, I see that component_map.json is populated by scraping OWNERS files in the Chromium code base. See https://cs.chromium.org/chromium/src/tools/checkteamtags/extract_components.py.

This is where we run into a problem for "Blink>ReportingObserver". The OWNERS file only supports one assigned Blink component per directory. The ReportingObserver code lives in a shared directory. We can't reasonably change the existing component mapping. In the longer term, it probably makes sense to move the ReportingObserver to a separate directory.

Regardless, it seems like a problem that the list of available Blink components in chromestatus relies on source code organization in Chromium. I would expect that if the components are defined in crbug.com, then they should be made available for selection when editing an entry.

**Comment by aglaforge** [comment]
Do we have any ways to query into Monorail to get a list of components?  The indirection seems to be problematic here.

**Comment by jpchase** [comment]
Yes, it's possible to use the Monorail API to get a list of components. I've been able to get that working in another project.
@jrobbins I can point you at the internal code (although it's in Go, I think there are Python examples around).
