### ISSUE TITLE
Pointer Lock: Wrong "prefixed" flag for Chrome

### ISSUE THREAD

**Issue by tidoust** [GoogleChrome/chromium-dashboard#570]
In [`features.json`](https://www.chromestatus.com/features.json), Pointer Lock is described with a `prefixed` flag set in Chrome. The spec does not require a prefix as far as I can tell, and the [page that describes the feature](https://www.chromestatus.com/feature/6753200417800192) does not mention it in particular.

**Comment by ebidel** [comment]
Thanks, that's an old one. I've the db and it should show up on the site soon.
