### ISSUE TITLE
Firefox Object rest/spread properties support

### ISSUE THREAD

**Issue by inoyakaigor** [GoogleChrome/chromium-dashboard#571]
problem url https://www.chromestatus.com/feature/5657004848709632
Firefox supports rest/spread since 55 version.
[rest on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters)
[spread on MDN](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Spread_syntax)

**Comment by myakura** [comment]
Thanks. Updated.

> [rest on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters)

That's a *rest params* not the rest properties, so I added the following to the document section instead. 

https://developer.mozilla.org/docs/Web/JavaScript/Reference/Operators/Object_initializer#Spread_properties
