### ISSUE TITLE
A Chromestatus entry should have a field to indicate a 'Planned to be implemented' milestone

### ISSUE THREAD

**Issue by natorion** [GoogleChrome/chromium-dashboard#572]
In order to use Chromestatus as a way to communicate a roadmap, it is essential to also indicate a milestone (range) when something should be implemented behind a flag.

Currently this is only loosely possible by designating a future milestone as 'Implemented behind a flag'. The UI does not fit this pattern though.

**Comment by jpmedley** [comment]
Duplicate of #1473. The earlier ticket is usually the preferred, but in this case the later ticket has more information.
