### ISSUE TITLE
Update or remove outdated "About" link in footer

### ISSUE THREAD

**Issue by JamesCatt** [GoogleChrome/chromium-dashboard#573]
The "About" link in the footer leads to a Google Doc that appears obsolete—it provides instructions for updating the spreadsheet (which has been deprecated), and directs people to email meh@chromium.org — which is defunct.

It would be preferable to update this link to new instructions are for contributing (I discovered this while trying to figure out how to get a feature added to the list), but failing that it should at least be removed. If it's just going to be removed, I'm happy to help with a PR.

**Comment by shivamag00** [comment]
UPDATE: The About link has been removed as mentioned in #1152 

@jrobbins @JamesCatt , please close this issue
