### ISSUE TITLE
Intervention: Blocking the load of cross-origin, parser-blocking scripts inserted via document.write for users on 2G

### ISSUE THREAD

**Issue by almoharebh** [GoogleChrome/chromium-dashboard#577]
A parser-blocking, cross site (i.e. different eTLD+1) script, https://www.google.com/uds/api/visualization/1.1/cc5d8333ad9d2dca8ea31ac15ed4e2df/webfontloader,format+en,default+en,ui+en,corechart+en.I.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.

**Comment by ikumargaurav** [comment]
I am getting the same issue. I am pretty sure though this is not a slow network problem for me, I am unable to find any solution to this.
My files are hosted in GCP and I have optical fibre broadband connection.

**Comment by jstenback** [comment]
This issue tracker is for the code behind the site https://www.chromestatus.com. Please file issues with Chrome the browser at https://bugs.chromium.org/p/chromium/issues/list.
