### ISSUE TITLE
Add a link to the Origin Trial dashboard from relevant features

### ISSUE THREAD

**Issue by phistuck** [GoogleChrome/chromium-dashboard#579]
https://developers.chrome.com/origintrials/ is the place for registering for an origin trial, yet I had to search for it for a few minutes and finally found a link in a Chromium blog post.

I think one of the right places to surface this link is in the entry of a feature that has the "Origin Trial" status. Ideally, the origin trial ID could be added to a feature entry and the link will go straight to the origin trial page for that specific trial, for example, https://developers.chrome.com/origintrials/#/view_trial/-1621295865853378559

Either "Want to participate in the origin trial? Go to the [origin trial dashboard](https://developers.chrome.com/origintrials/).", or a simple "([want to activate it on your domain?](https://developers.chrome.com/origintrials/#/view_trial/-1621295865853378559))" and the like, next to the "Origin Trial" status.

**Comment by jpmedley** [comment]
Duplicate of #968.
