### ISSUE TITLE
chrome doesn't start, the version is the newest 71.xxxxxxxxx

### ISSUE THREAD

**Issue by terU3760** [GoogleChrome/chromium-dashboard#580]
On kali linux, I typed the command to start chrome. But it just won't start and reported the following error:

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:255:67: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:264:69: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:272:72: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:310:54: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:476:68: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:489:70: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:501:67: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:512:70: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:523:68: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:533:70: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:544:67: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:554:70: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:574:72: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:584:72: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:597:69: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:657:72: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:667:74: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:678:58: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:688:72: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:747:71: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:757:73: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:768:58: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:778:72: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1287:68: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1296:70: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1305:67: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1314:70: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1525:72: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2142:9: Not using units is deprecated. Assuming 'px'.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2142:9: Expected a string.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2549:72: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2560:74: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2569:71: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2578:74: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2877:55: Using one color stop with linear-gradient() is deprecated.

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3842:8: not a number

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3842:17: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:4079:14: not a number

(chrome:1715): Gtk-WARNING **: Theme parsing error: gtk-contained.css:4079:14: Expected a string.
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(chrome:1715): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.
Gkr-Message: couldn't connect to dbus session bus: Failed to connect to socket /run/user/1000/bus: Permission denied

**Comment by terU3760** [comment]
Dear Eric Bidelman,
        Why do you close this issue?

**Comment by myakura** [comment]
@terU3760 because this repository isn't a help forum for Chrome, nor the development repository. It's the repository for the Chrome Status site (chromestatus.com).

**Comment by terU3760** [comment]
@myakura  Could you please suggest me the right forum for the maintenance or development of chrome that I could put my issue? Thanks in advance!

**Comment by ebidel** [comment]
crbug.com is chromium'snissue tracker
 Please post a more detailed explanation and  repro steps if you file an
issue there.
