### ISSUE TITLE
Painful lag time on iPhone

### ISSUE THREAD

**Issue by robcolburn** [GoogleChrome/chromium-dashboard#59]
Occurs in Safari and Chrome for iOS.

Initial page load is fast: partial page render, iOS no longer displays spinner.  After initial load, Page UI and Browser UI are unresponsive - you can hit home button to escape.  Then the page is ok, until you attempt to search, the on-key-press seems to re-engage the lag.

iPhone 4S / iOS 6.1.3

**Comment by ebidel** [comment]
This issue is really old. Going to close since ios6 was a long time ago :)
