### ISSUE TITLE
Github needs many "Reloads" to open in chrome!

### ISSUE THREAD

**Issue by C-PyLx** [GoogleChrome/chromium-dashboard#590]
Hello, i have google chrome browser on linux kubuntu 18.10
when i search "github.com" in my browser bar, it not open and hang on: "Establishing secure connection...".

I tried all the ways to solve it, but did not. Please help me about this issue.

**Comment by ebidel** [comment]
This issue tracker is for http://chromestatus.com

**Comment by myakura** [comment]
@C-PyLx for suggestions or issues with Chrome browser, please file a bug from https://crbug.com/new
