### ISSUE TITLE
Issue on Chrome 73 Beta - input textbox unresponsive after javascript call 'window.print()'

### ISSUE THREAD

**Issue by achoi0330** [GoogleChrome/chromium-dashboard#592]
### Input Textbox Unresponsive after Javascript Call 'window.print()'

**Simple example reproduce steps:**
1. Search anything on 'google.com', go to the search results page.
(e.g. https://www.google.co.nz/search?rlz=1C1GCEU_enNZ821NZ821&ei=-fh1XPagA5n7rQGu9Zi4DQ&q=window+print+doesn%27t+work&oq=window+print+doesn%27t+work&gs_l=psy-ab.3..33i22i29i30l6.13620.15840..15958...0.0..0.169.3557.0j23......0....1..gws-wiz.......0j0i22i30j0i13i30.GhoLlFkKRz4)

2. Open developer console, run window.print() - which will open a print dialog.

3. Close the print dialog, and click on the search textbox again. 

4. Try to type anything - not responsive.
Try to edit what's already typed in - not responsive.
Backspace works fine.

This applies to **any input textbox** on **any website**. 
Printing using the shortcut (ctrl+P) does not cause the same issue, only happens after running javascript to print.

Please address this issue as soon as possible and let me know. Thanks.

**Comment by jstenback** [comment]
Hello achoi0330. This issue tracker is specifically for the website https://www.chromestatus.com. For issues relating to Chrome the browser, please see http://dev.chromium.org/for-testers/bug-reporting-guidelines for guidance.
