### ISSUE TITLE
Duplicate entries created

### ISSUE THREAD

**Issue by dway123** [GoogleChrome/chromium-dashboard#594]
I accidentally created a duplicate feature entry. Could you please remove my duplicate? 

Also, please feel free to let me know how to delete it myself if relevant. I couldn't find a delete button or other UI to delete the feature.

(Good) https://www.chromestatus.com/feature/5074658793619456
(Duplicate) https://www.chromestatus.com/feature/5120155113750528

**Comment by jstenback** [comment]
https://www.chromestatus.com/feature/5120155113750528 has now been deleted.
