### ISSUE TITLE
Unable to edit existing feature

### ISSUE THREAD

**Issue by dway123** [GoogleChrome/chromium-dashboard#595]
While trying to edit https://www.chromestatus.com/features/5120155113750528, I'm able to enter an edit page, but when clicking submit, I get an internal server error 500 error.

"500 Internal Server Error
The server has either erred or is incapable of performing the requested operation."

**Comment by jstenback** [comment]
This appears to be due to missing multiline=True arguments to some of the new db.StringProperty() calls when creating the containers for a few of the new values. I have a fix coming...

**Comment by jstenback** [comment]
I went ahead and deployed the proposed PR to hopefully unblock people who are trying to edit features.

**Comment by jpmedley** [comment]
I just got an email from Yoav Weiss confirming that he can edit entries now.
