### ISSUE TITLE
https://www.chromestatus.com/features_v2.json returns a 500

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/chromium-dashboard#602]
Requests for `https://www.chromestatus.com/features_v2.json` are currently returning a HTTP 500 server error. (You need to check from an Incognito window if you have a valid copy of it already in your service worker cache, or you won't notice.)

As per the App Engine logs, the underlying error is

```
    d['intent_stage'] = INTENT_STAGES[self.intent_stage]
KeyError: 0L
```

which is comes from line https://github.com/GoogleChrome/chromium-dashboard/blob/4a26c57c8a500ce28a77fbf2deb1558f213628c7/models.py#L438-L439

I.e. there's a value of `0` being used as a key in `INTENT_STAGES`, but there's no corresponding entry for 0 in that dict:

https://github.com/GoogleChrome/chromium-dashboard/blob/4a26c57c8a500ce28a77fbf2deb1558f213628c7/models.py#L76-L83

**Comment by jpmedley** [comment]
It looks like #601 fixes this, but it has not yet been deployed. I'll see if I can expedite.

**Comment by jpmedley** [comment]
Should be fixed now.

**Comment by jstenback** [comment]
Yep, tested locally and this works now.
