### ISSUE TITLE
Unreasonable required fields

### ISSUE THREAD

**Issue by tkent-google** [GoogleChrome/chromium-dashboard#605]
I tried to update an entry for a feature removal.  https://www.chromestatus.com/admin/features/edit/5075579829223424

I wanted to make the following fields blank, however I couldn't submit the form dues to their "required" attribute.
 - Explainer link(s)
 - Intent to Implement link
 - Doc link(s)
 - Spec link

**Comment by jpmedley** [comment]
@tkent-google I just deployed a fix. Give it a try and let us know if you're still having problems.

**Comment by tkent-google** [comment]
It works well now.  Thank you for the quick fix!
