### ISSUE TITLE
Tag Review field is labeled required though it is not.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#607]
Is this supposed to be here?

![image](https://user-images.githubusercontent.com/8204171/53762641-710ca900-3e7d-11e9-8add-5b5b606c50ec.png)

**Comment by jstenback** [comment]
This should be required for Features at the Intent to "Ship" or "Implement and Ship" stages, per the blink process. As the help text says, a link or an explanation why no tag review is needed for this feature is required.

Are you seeing this in some other cases?

**Comment by jpmedley** [comment]
I think I'm seeing it in very case, but it doesn't appear to be blocking me for saving.

**Comment by jpmedley** [comment]
Not relevant in current interface.
