### ISSUE TITLE
Add Motivation section to RSS feed.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#611]
It will soon be visible on the external page. The RSS feed should reflect that.

**Comment by jpmedley** [comment]
@jrobbins Do we still even have an RSS feed?

**Comment by jrobbins** [comment]
There is a handler for `/features.xml`.  There is no link or icon in the page content that goes to that URL, but there is a `<link rel="alternate" type="application/rss+xml" href="/features.xml" title="All features">` element in `<head>`.

I haven't put much thought into RSS feeds, and no users have said anything about them as far as I recall.  So, it seems like something that could be phased out.

**Comment by jpmedley** [comment]
Closing because of #2132
