### ISSUE TITLE
Add "Generated by Chromestatus" to generated intent templates.

### ISSUE THREAD

**Issue by jstenback** [GoogleChrome/chromium-dashboard#616]
Add a note into the generated templates that states this intent was generated by chromestatus to help spread the word that chromestatus now generates real templates and we're encouraging its use.

**Comment by jstenback** [comment]
This was originally suggested by @bfgeek.

**Comment by jpmedley** [comment]
Upgrading to P0. Rick Byers didn't even know we had done this.

**Comment by jstenback** [comment]
This was actually already done as part of https://github.com/GoogleChrome/chromium-dashboard/commit/18b81b4fbcf463959783ef126af9d47d5b3b7578. Closing.
