### ISSUE TITLE
V8 doesn't follow Blink review process making chromestatus unusable

### ISSUE THREAD

**Issue by gsathya** [GoogleChrome/chromium-dashboard#620]
V8 doesn't need the following fields:
- TAG review
- Web platform tests
and maybe more

cc @mathiasbynens @natorion

**Comment by natorion** [comment]
Are those fields required?

**Comment by gsathya** [comment]
Yes. I tried to update an entry on chromestatus but was not able to -- I see the same error as in https://github.com/GoogleChrome/chromium-dashboard/issues/607, but it's blocking me from saving the entry.

See https://bugs.chromium.org/p/chromium/issues/detail?id=941477#c2 for background

**Comment by natorion** [comment]
ok, that is indeed bad. @mathiasbynens or @addyosmani any clue who can make those fields optional and fix this?

**Comment by jpmedley** [comment]
@gsathy which entry are you trying to update?

**Comment by jpmedley** [comment]
@gsathya I also need to know which fields are asking for content that you don't use.

**Comment by gsathya** [comment]
> @gsathy which entry are you trying to update?

> See https://bugs.chromium.org/p/chromium/issues/detail?id=941477#c2 for background

https://www.chromestatus.com/feature/5747878282657792

> @gsathya I also need to know which fields are asking for content that you don't use.


> V8 doesn't need the following fields:
> 
> * TAG review
> * Web platform tests

**Comment by mathiasbynens** [comment]
The code is here: https://github.com/GoogleChrome/chromium-dashboard/blob/4649d60c079edee534fd582bc356c130972685ec/static/js/admin/feature_form.js#L125-L142 Although I get why these are `VISIBLE_REQUIRED` for Chromium/Blink, they should be `VISIBLE_OPTIONAL` for JavaScript features. cc @jstenback

**Comment by jpmedley** [comment]
The way this site is built, I can't test this locally without making an actual Chrome Status entry that will become visible.

I've staged updated code here: https://2019-03-14-test-dot-cr-status.appspot.com/features

Can someone please try this and let me know if it works. By the way, it uses the same data source as the live site. If if succeeds, you'll be done with updating your entry.

**Comment by gsathya** [comment]
> I've staged updated code here: https://2019-03-14-test-dot-cr-status.appspot.com/features

I don't feel comfortable logging into this with my chromium account. If anyone else wants to, then please change the entry to say "enabled by default" instead of "behind a flag".

**Comment by jpmedley** [comment]
@gsathya What specifically is your concern?

**Comment by jpmedley** [comment]
Pinging this thread again. Can someone try this out so we can get this resolved. I don'w want this holding up other projects.

**Comment by jstenback** [comment]
I just submitted pr #623 that adds exceptions to the form filed requirements for features in the JavaScript category. Hoping that would take care of this, and pave the way for other exceptions down the road.
