### ISSUE TITLE
Card editor should be WISYWIG.

### ISSUE THREAD

**Issue by yoichio** [GoogleChrome/chromium-dashboard#621]
It is hard to edit a form to show an appropriate card.

Card:
![card](https://imgur.com/stVPJtr.png)

Editor:
![editor](https://imgur.com/1QCgCl2.png)

**Comment by jrobbins** [comment]
Agreed.  We are redoing the editing experience as a new "Guide" UX.  It will not be WYSIWYG, but it is more logically organized and helps guide users through the feature launch process.  We will also update the read-only feature detail page as part of issue #925.
