### ISSUE TITLE
Make explainer link visible in public dashboard

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#624]

**Comment by jrobbins** [comment]
@jpmedley Remind me, is this issue about the contents at the top of the feature detail page or some other part of the UI?

**Comment by jpmedley** [comment]
I'm not sure this is relevant any more. Spec links are available on both versions of the card.

**Comment by jyasskin** [comment]
https://www.chromestatus.com/feature/5699436254593024 doesn't show an explainer link even though I can see it in https://www.chromestatus.com/guide/editall/5699436254593024. If the feature doesn't have a specification, we need to show the explainer instead.
