### ISSUE TITLE
Migrate away from web component v0

### ISSUE THREAD

**Issue by liyangguang** [GoogleChrome/chromium-dashboard#625]
This site is built using Web Component V0, which is being deprecated (https://www.chromestatus.com/features/5144752345317376).

We should migrate it away from it, possibly using https://lit-element.polymer-project.org/.

**Comment by liyangguang** [comment]
In addition to components, some related topics came up in code review:
- Update all the sass (at least the ones for components). If possible, change them all to native css and move into components.
- Change to Typescript (?)

**Comment by liyangguang** [comment]
Related PRs:
- #640: rollup setup
- #652: Features page

**Comment by liyangguang** [comment]
lit-virtualizer is discussed offline with the team.
Currently blocked for some features.

**Comment by liyangguang** [comment]
#656: Schedule, metric, samples pages.

**Comment by jrobbins** [comment]
This was accomplished last year.  Thanks so much for doing all that work.
