### ISSUE TITLE
SameSite status out of date for other browsers

### ISSUE THREAD

**Issue by lol768** [GoogleChrome/chromium-dashboard#627]
https://www.chromestatus.com/features/4672634709082112 data for browser Edge is outdated by 9 months.

> Updated 6/27/2018: Same-site cookies are now available for Microsoft Edge and Internet Explorer on the Windows 10 Fall Creators Update and later via the June 2018 Windows Update packages. Users on the Windows Insider Preview will need to use Build 17672 or later to test this feature, as outlined below.

Source: https://blogs.windows.com/msedgedev/2018/05/17/samesite-cookies-microsoft-edge-internet-explorer/

For Safari, SameSite support shipped TP 58 and is now in (iOS) 12. Safari bug is at https://bugs.webkit.org/show_bug.cgi?id=159464 and the commit itself was made last April so this has been wrong for approaching a year now.

Relates to #566 (MDN compat-data is correct and up to date https://github.com/mdn/browser-compat-data/blob/06b1b791a8303ecc7e09ea30bd2a5fafb2aaef30/http/headers/set-cookie.json#L218 and https://github.com/mdn/browser-compat-data/blob/06b1b791a8303ecc7e09ea30bd2a5fafb2aaef30/http/headers/set-cookie.json#L239)

--------

Separately, I know there's a disclaimer:

> After a feature ships in Chrome, the values listed here are not guaranteed to be up to date.

But what's the use in displaying these statuses after the feature has shipped in Chrome if they're this outdated? For this same feature, the indicators were wrong [for Firefox](https://github.com/GoogleChrome/chromium-dashboard/issues/560) for a while too.

 It's frustrating stumbling upon a Chrome status page for a web feature (and they usually rank pretty highly) and not being able to trust any of the browser data except for that given for Chromium itself.

**Comment by jpmedley** [comment]
> But what's the use in displaying these statuses after the feature has shipped in Chrome

Yeah, I don't know what we were thinking that day. I've opened #628 to address this. Hold my feet to the fire if I don't do it within a few weeks.
