### ISSUE TITLE
Hotkeys for duplicate tabs ( Ctrl + K )

### ISSUE THREAD

**Issue by DenisSlabokrug** [GoogleChrome/chromium-dashboard#630]
Could you add hotkeys for duplicate tabs. As for example, this is implemented in Internet Explorer, Ctrl + K. This will make it faster and more convenient to manage the working space in the browser for searching information and developing web applications.

**Comment by jpmedley** [comment]
Hi,

Thank you for your feedback. This is not the channel for Chrome feature requests. You can find instructions for doing that on [one of our developer pages](https://developer.chrome.com/apps/faq#faq-fea-02).

Thanks,
Joe
