### ISSUE TITLE
chromestatus.com is down

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#631]
Looks like the ssl certificate might have expired? cc @samthor @PaulKinlan 

The appspot app (https://cr-status.appspot.com/features) is still working.

<img width="1483" alt="Screen Shot 2019-03-30 at 5 38 55 PM" src="https://user-images.githubusercontent.com/238208/55283213-b86a4600-5312-11e9-96a2-5b4eeb1affc9.png">

**Comment by samthor** [comment]
Yeah, we're looking at this. It was only verified by one user who left
Google 🤔

Jokes aside, the cert actually reported it was valid until the 8th, so I
wonder what's going on here. We'll get it fixed.
