### ISSUE TITLE
Resolve www. vs naked domain

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/chromium-dashboard#632]
Follow-on from #420.

We could redirect all users from www. to the naked domain, and serve a pure redirect there, so that folks don't have both SWs installed.

**Comment by robdodson** [comment]
That seems like a good thing to do. If someone already has a sw installed for the www version do you know if that would interfere with things at all?

**Comment by samthor** [comment]
We'd have to serve a blank SW from "www." so we'd force an update, so folks can get the real HTTP response, which'd redirect them.

It sounds like you prefer the naked domain @robdodson?

**Comment by robdodson** [comment]
I personally prefer the naked domain but am very cautious about zombie service workers :D
