### ISSUE TITLE
Chrome Media Sessions API

### ISSUE THREAD

**Issue by muhammad-usman-anwar** [GoogleChrome/chromium-dashboard#633]
There is an issue with the Chrome's Media Session API. On mobile devices, it doesn't keep the background playback on, in default(mobile view) mode. But when switched to desktop site, it works fine.
First I thought I was making some mistake, while working on the site. Then after some researching, I came to know that Youtube works the same way. So natural conclusion is that when viewport is set to mobile the API doesn't keep the playback running but when switched to desktop, it works fine.

**Comment by myakura** [comment]
@muhammad-usman-anwar this is not a Chrome issue tracker, but a one for https://www.chromestatus.com/ . Can you file a bug via https://crbug.com/new ?

**Comment by muhammad-usman-anwar** [comment]
No, I wasn't able to find one. So registered via https://crbug.com/new
