### ISSUE TITLE
Make 'Doc link(s)' field and 'Explainer link(s)' field optional.

### ISSUE THREAD

**Issue by karlhorky** [GoogleChrome/chromium-dashboard#637]
Before I start, I want to mention that I tried submitting this to [the "File a content issue"](https://groups.google.com/a/chromium.org/forum/#!forum/blink-dev) link 3 times, but it didn't work (it said "successfully posted" but then did not show up in the list of topics).

So I'm submitting here.

---

Thanks for this resource, first of all! It's super helpful for looking at the progress of features on the web.

I clicked on the "Link 1" link in the [Support for SVG in favicons section](https://www.chromestatus.com/feature/5180316371124224), but it appears to go to https://www.chromestatus.com/features/No%20design%20doc , which doesn't exist.

<img width="552" alt="Screen Shot 2019-04-10 at 15 00 19" src="https://user-images.githubusercontent.com/1935696/55881532-1ca6c880-5ba3-11e9-9340-9c7226aa21ae.png">

I wanted to open a pull request here on GitHub, but I couldn't find the content that I was supposed to edit there (or even if it was on GitHub at all).

**Comment by karlhorky** [comment]
Ah looks like there was just a huge delay opening it on the `blink-dev` group:

https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/ArW2aAZJOnI

Feel free to close this if GitHub is not the right place.

**Comment by jpmedley** [comment]
@jstenback 'Support for SVG...' project does not have a design doc (or not one that can be externally shared), but the form requires that the box be filled in. So they wrote 'No Design Doc.' I've hacked around this by entering a space in, which removes the errant link. I did the same thing for the explainer field.

Can you please make the 'Doc link(s)' field and the 'Explainer link(s)' field optional?

**Comment by mathiasbynens** [comment]
For posterity, the direct link to the relevant status entry is https://www.chromestatus.com/feature/5180316371124224.

**Comment by karlhorky** [comment]
Good idea, I've added the link to the original description too!

**Comment by jpmedley** [comment]
Fixed, but I don't know when.

**Comment by karlhorky** [comment]
@jpmedley Thanks for circling back around to this one!
