### ISSUE TITLE
500 error when adding a new feature

### ISSUE THREAD

**Issue by mfalken** [GoogleChrome/chromium-dashboard#641]
This happened twice, and I lost all form input in an unrecoverable way :(

I don't know if I did something like use multiple lines as mentioned in issue #106 

I will try adding a skeleton feature then slowly updating sections one-by-one.

**Comment by jpmedley** [comment]
The error logs are reporting: 'ValueError: invalid literal for int() with base 10: ' in admin.py at line 443.

**Comment by jpmedley** [comment]
@mattto Did you get your feature submitted?

**Comment by mattto** [comment]
Yep, just by submitting a skeleton first then filling it out in multiple updates.

**Comment by mugdhalakhani** [comment]
Running into this as well. Who's the best person to assign this to?

**Comment by beverloo** [comment]
@jstenback @addyosmani @PaulKinlan fyi

**Comment by lilles** [comment]
I've tried multiple times to edit and generate an intent-to-ship for prefers-color-scheme today and get 500 every time. Related to this?

**Comment by lilles** [comment]
> I've tried multiple times to edit and generate an intent-to-ship for prefers-color-scheme today and get 500 every time. Related to this?

I got it to work to have single paragraphs everywhere.

**Comment by kevers-google** [comment]
I've hit this issue twice in the past week with intent-to-implement-and-ship for web animation features.  Both times the first submit fails, and second submit succeeds.

**Comment by jstenback** [comment]
I merged PR #644 this morning and deployed the change. I would really appreciate if someone can provide additional information here if this issue still reproduces. I'll keep an eye on the logs etc as well.

**Comment by kevers-google** [comment]
Hit this issue again yesterday. Possible that it is not the same bug.  Needed to reenter all of the data.

**Comment by jstenback** [comment]
Interestingly enough I see zero evidence of that in the logs (not saying it didn't happen, just that I have nothing to go on in trying to understand what happened :( ). Any more detail you have on what happened would be greatly appreciated (time of error, ip address if you're willing to share, what you did differently when it worked the second time, if anything, etc).

**Comment by jpmedley** [comment]
@jstenback I just learned that service workers can return 500 errors. Chrome Status has a service worker. You might look there.

**Comment by jrobbins** [comment]
This was fixed years ago.
