### ISSUE TITLE
Track Flexbox gap

### ISSUE THREAD

**Issue by zxti** [GoogleChrome/chromium-dashboard#642]
The CSS `gap` property has been specified for flexbox—it's now in the W3C spec but not implemented:

https://bugs.chromium.org/p/chromium/issues/detail?id=762679

Would be great to add this to the dashboard!

**Comment by jpmedley** [comment]
There's a defined point in the Chromium development process where items get added to the dashboard. Someone has to be working on it before than can happen. If you want to follow this feature now, you can create a Chromium account and star the ticket.
