### ISSUE TITLE
TAG review field value not included in the Intent to Ship email

### ISSUE THREAD

**Issue by pwnall** [GoogleChrome/chromium-dashboard#643]
Example feature: https://www.chromestatus.com/feature/5375472036741120
Generated email: https://groups.google.com/a/chromium.org/d/topic/blink-dev/_-WBHYZ-rBk/discussion

**Comment by jpmedley** [comment]
@jstenback @RByers I would expect tag review in an intent to implement. Is it supposed to show in the intent to ship. I'd think it would be old news by then.

@pwnall Tag review will not show up on the dashboard card. That information is intended for future users of the feature.

**Comment by pwnall** [comment]
I'm not a Blink API OWNER... but I were, I'd prefer that the Intent to Ship has all the information I need to assess which parts of the relevant process were followed.
