### ISSUE TITLE
Line breaks taken out of "Motivation" section

### ISSUE THREAD

**Issue by chlily1** [GoogleChrome/chromium-dashboard#646]
Is there a reason linebreaks are taken out? This makes it impossible to write a "Motivation" section containing multiple paragraphs.

**Comment by jstenback** [comment]
Fix waiting for review in PR #647

**Comment by jstenback** [comment]
Fix merged.

**Comment by jstenback** [comment]
And deployed too.

**Comment by chlily1** [comment]
Thank you for the speedy fix!
