### ISSUE TITLE
JS metrics page throwing 500

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#653]
https://chromestatus.com/metrics/feature/popularity is not returning data. Looks like the data endpoint (https://chromestatus.com/data/featurepopularity) is returning a 500.

The logs will probably reveal what's going on.

Could be related: https://github.com/GoogleChrome/chromium-dashboard/issues/519

**Comment by jpmedley** [comment]
This appears to be an intermittent error.

**Comment by jrobbins** [comment]
This is a duplicate of #678.
