### ISSUE TITLE
Entry form should clarify audience for the fields

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#660]
The proposals is to break the entry form in to two sections with labels indicating who the intended audience of that content is. Those sections/audiences are:

* Web Developers - Includes only the information that is publicly visible on the rendered entry.
* Chrome implementors - Information that is only relevant to Chromium implementors.

As before, the generated intent email will be a combination of both.

This is probably blocked by #625

**Comment by jrobbins** [comment]
Pretty much everything is public.  We can't be sure that no web developer will make what use of any particular field.
