### ISSUE TITLE
Chrome Crashes if you load a wide image  (27150 x 20950) px

### ISSUE THREAD

**Issue by dota2Pro** [GoogleChrome/chromium-dashboard#661]
The details of this issue can be found in this [stackoverflow post](https://stackoverflow.com/q/57223559/5724889)

```
Browser: Chrome Latest (Desktop)
Hardware: Windows Standard PC with default Intel Graphics card
Ram: 8GB
Processor: i7 @ 3.40 GHz
```

`
**Javascript**
<img src="my27150x20950Image" >`

**Comment by jstenback** [comment]
This issue tracker is for tracking issues in the Chromium Dashboard (www.chromestatus.com). Please file issues on Chrome itself at https://crbug.com/wizard
