### ISSUE TITLE
Not all Monorail components are listed on chromestatus

### ISSUE THREAD

**Issue by jeremyroman** [GoogleChrome/chromium-dashboard#664]
For example, the Blink>HTML>Portal component isn't present in the dropdown list.

**Comment by jstenback** [comment]
Interesting. This appears to be a bug in with https://blinkcomponents-b48b5.firebaseapp.com/blinkcomponents not returning the complete list. Unfortunately I don't know who runs that site...

**Comment by jpchase** [comment]
See #565, where I did some initial investigation.

**Comment by jpmedley** [comment]
We have to update this manually from time to time. If you find a missing feature, please open a new ticket. We aren't automatically notified.
