### ISSUE TITLE
input number up and down is not showing when used with Angular 8

### ISSUE THREAD

**Issue by Richu98** [GoogleChrome/chromium-dashboard#665]
**<input** type ="number" >  in html 5 used with Angular 8 and 6 is not showing up and down arrows even in focus mode but it is working fine in firefox

Chrome Version:76.0.3809.100

**Comment by myakura** [comment]
@Richu98 you might want to file a bug against https://crbug.com/new as this repository is for chromestatus.com and not Chrome/Chromium browser.

**Comment by jpmedley** [comment]
What @Richu98 said is correct. This channel is for bugs in chromestatus.com. Closing the ticket.
