### ISSUE TITLE
Items Marked 'No Longer Pursuing' are also marked "(deprecated)" in feature titles.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#666]
"Deprecated" should no be automatically added to the title of such things. How can something be deprecated if it was never implemented?

![image](https://user-images.githubusercontent.com/8204171/62971061-bedef300-bdc5-11e9-86e2-f9ebb35bc4ba.png)

**Comment by jstenback** [comment]
Agreed. What wording would you suggest we use in stead?

**Comment by jstenback** [comment]
FWIW, this wording appears to come from https://github.com/GoogleChrome/chromium-dashboard/blob/master/templates/feature.html#L31
