### ISSUE TITLE
Remove Eric's Name from Update notifications sent to DevRel

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#670]
This is mostly a reminder to spend more time digging. I did a quick glance recently and didn't find where this is done.

![image](https://user-images.githubusercontent.com/8204171/63057830-ff12a400-be9f-11e9-97f5-35be7b599c9c.png)

**Comment by sojun181744** [comment]
> This is mostly a reminder to spend more time digging. I did a quick glance recently and didn't find where this is done.
> 
> ![image](https://user-images.githubusercontent.com/8204171/63057830-ff12a400-be9f-11e9-97f5-35be7b599c9c.png)
Bug

**Comment by jpmedley** [comment]
Eric's name is no longer in emails.
