### ISSUE TITLE
JS/HTML use counters aren't loading

### ISSUE THREAD

**Issue by tdsmith** [GoogleChrome/chromium-dashboard#678]
https://chromestatus.com/metrics/feature/popularity never populates; the data blob at https://chromestatus.com/data/featurepopularity is returning a 500 error.

**Comment by mozfreddyb** [comment]
Came here to say this. The web site is essentially broken.
Paging @ebidel.

**Comment by robdodson** [comment]
Hey folks, we're meeting tomorrow to allocate some eng resources to fix things up. Hope to get those endpoints working again asap.

**Comment by mrego** [comment]
It loads but just a few features, not the whole list at https://cs.chromium.org/chromium/src/third_party/blink/public/mojom/web_feature/web_feature.mojom

Then if you go into the details of one of them, the select box allows you to see any of them.

**Comment by robdodson** [comment]
I think this should be fixed now. Please let me know if y'all continue to hit issues.

**Comment by robdodson** [comment]
@jpmedley I think you can close this when you have a minute.

**Comment by tdsmith** [comment]
> I think this should be fixed now. Please let me know if y'all continue to hit issues.

Thank you; will do!

**Comment by jrobbins** [comment]
This should be working for everyone as of 2019-10-21.
