### ISSUE TITLE
Delete double entry in Chrome Platform Status

### ISSUE THREAD

**Issue by sahel-sh** [GoogleChrome/chromium-dashboard#680]
I accidentally submitted the entry for shipping and contact delegation twice:
https://chromestatus.com/features#shipping%20address%20and%20contact
I could not find a way to delete one.

**Comment by jstenback** [comment]
Do you have a preference for which one to delete? They look identical to me, but if links to one exists elsewhere then let's delete the other. Thanks.

**Comment by sahel-sh** [comment]
please remove https://chromestatus.com/feature/5637409230290944
Thanks!

**Comment by jpmedley** [comment]
Done.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by jrobbins** [comment]
Closing because previous comment said this was done.
