### ISSUE TITLE
Render bug with the options of a select box inside iframe

### ISSUE THREAD

**Issue by chriscodeweb** [GoogleChrome/chromium-dashboard#681]
For a few month now, there is this bug with the options of a selectbox in a iframe.
A simple example, go to this fiddle: https://jsfiddle.net/j7vLtfmy/58/
The selectbox is inside a iframe and when you open the dropdown you will see that the options
show really big padding and i'ts position is incorrect. 
But when you make a resize of your window, it will render correct again.

**Comment by jstenback** [comment]
This repository is for the chromestatus.com website, not the Chrome browser. Please follow the directions at https://www.chromium.org/for-testers/bug-reporting-guidelines for reporting issues in Chrome/Chromium.

Thanks.
