### ISSUE TITLE
Web Audio API: "prefixed" flag should be false for Chrome

### ISSUE THREAD

**Issue by tidoust** [GoogleChrome/chromium-dashboard#685]
The  [Unprefixed Web Audio API](https://www.chromestatus.com/feature/6261718720184320) asserts that the unprefixed version of the API was shipped in Chrome 34, which seems correct.

However, the corresponding entry in [`features.json`](https://www.chromestatus.com/features.json) has a `prefixed` flag set to `true` for Chrome, which seems wrong.

**Comment by cwilso** [comment]
Fixed.
