### ISSUE TITLE
"Experiment Goals" field is wiped upon editing

### ISSUE THREAD

**Issue by mgiuca** [GoogleChrome/chromium-dashboard#690]
If you have a feature with Intent Stage "Extend Origin Trial" (or possible "Experiment"), the "Experiment Goals" field is mandatory. But if you type something in there, save, then click edit again, the Experiment Goals field is wiped, but still mandatory. So I have to type something into that box every time I want to edit.

Also, the contents of this field, and all the other experiment fields, aren't even displayed on the view page, so whatever I type in that box is lost forever (i.e., I can't even copy and paste what I wrote last time).

Aside: If you're going to ask authors to answer 6 open-ended prose questions, it would be nice if those answers aren't just sucked into a void when I click Submit.

**Comment by dmcardle** [comment]
I'd like to add a data point that I'm seeing this happen now.  I entered data into the "Experiment Goals" box for a new entry, and it disappeared when I hit submit. Same thing when editing. It appears whatever goes into that box gets dropped.

**Comment by dvorak42** [comment]
Looks like https://github.com/GoogleChrome/chromium-dashboard/blob/57c0e44f1e3caf8b554448b2f08e61ce3b9f0ab3/admin.py#L443 should be updated to experiment_goals instead of experiment_goal. (Though its only used in the i2i template).

**Comment by jstenback** [comment]
Thanks @dvorak42, that indeed looks like the actual problem here!

**Comment by jrobbins** [comment]
The fix is live.  Comment here if you encounter any problems.
