### ISSUE TITLE
chromestatus does not load in Chrome 80 canary

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#691]
1. Visit https://chromestatus.com using Chrome 80 canary.  View almost any page.

Browser console shows:
Uncaught TypeError: document.registerElement is not a function
    at metrics-imports.vulcanize.js?_sw-precache=0d21383aebc0899e8013557b89af36b0:2
    at metrics-imports.vulcanize.js?_sw-precache=0d21383aebc0899e8013557b89af36b0:2

Uncaught (in promise) TypeError: featureList.filter is not a function
    at features:730

Surprisingly, command-shift-R allows the page to load without an error, but that is only on the /features page.

**Comment by jrobbins** [comment]
We need to land our lit-element upgrade sooner rather than later.  

Web components v0 will be removed around Feb 2020, but our users tend to use canary and dev channels, so we need to phase out web components v0 now.
https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade

**Comment by jpmedley** [comment]
I feel like I should have seen that coming.

**Comment by mfreed7** [comment]
Feel free to apply for a [reverse origin trial](https://developers.chrome.com/origintrials/#/view_trial/2431943798780067841) to give yourself more time to upgrade to lit-element. Or, perhaps try to use a feature-detecting polyfill? It appears to UA detect Chrome and not load the polyfill there, while correctly loading the polyfill on Safari and Firefox. Correct me if I'm wrong.

**Comment by mfreed7** [comment]
Anything I can do to help get the [origin trial](https://developers.chrome.com/origintrials/#/view_trial/2431943798780067841) running here? People on the I2D have commented that it's embarrassing to have chromestatus not work. I tend to agree. :-)

**Comment by mfreed7** [comment]
This appears to be fixed now - perhaps we can close this bug. Thanks for adding the origin trial.

**Comment by jrobbins** [comment]
I didn't make the new version live, so the reverse origin trial header is not being set.   However, I also see that the site is working for me in Chrome Canary 80.0.3968.0.

I'm thinking that the latest Chrome Canary disabled HTML imports and that makes the polyfill if-statements in base.html work correctly now.   So, I don't think that we actually need the reverse origin trial.  A little testing with the origin trial shows that it also works, but it will eventually expire.  I'll leave revert the PR that added the origin trial token, but we can always add it again if needed.

**Comment by mfreed7** [comment]
Oh! Ok, well I think that’s actually better. Thanks for testing it, I appreciate it.

**Comment by ericlaw1979** [comment]
This page isn't loading in Edge 80 Canary... perhaps HTML imports are not disabled there?

**Comment by mfreed7** [comment]
Hmm, I just tried loading chromestatus.com with Edge Canary 80.0.353.0, and it appears to be working for me. Which version are you using, and which page (specifically) looks broken to you?

(Edge 80.0.353.0 has all three Web Components v0 features re-enabled.)

**Comment by mfreed7** [comment]
I agree - it appears that at least [this page](https://chromestatus.com/metrics/feature/popularity) is broken, due to . I'll reach out to the Edge folks.

**Comment by mfreed7** [comment]
From looking at the site, it appears that there are still no origin-trial tokens being used. I just wanted to verify that this is the case (based on [this comment](https://github.com/GoogleChrome/chromium-dashboard/issues/691#issuecomment-555778215)), as I look at why it is broken in Edge.

**Comment by mfreed7** [comment]
Ok, it appears that this is broken because in the latest Edge Canary, Shadow DOM v0 and Custom Elements v0 are both disabled, while HTML Imports is still enabled. That breaks the feature detection logic in some polyfills, which is likely why the site is broken in Edge. You can also see this from the Console log, which shows deprecation warnings for HTML Imports (indicating they are active) and then an error message for document.registerElement (indicating custom elements v0 is being attempted). I'll forward to the Edge team.

**Comment by BoCupp-Microsoft** [comment]
After Mason's change landed in Edge, some parts of the browser UX that still had a dependency on HTML imports broke.  HTML imports (only) got reenabled to fix those test failures which is what's leading the behavior you're seeing right now.  A fix should be out soon that scopes HTML import support to just the browser UX that needs it.

**Comment by BoCupp-Microsoft** [comment]
HTML Imports are disabled now in Edge and [Chrome Status](https://chromestatus.com) is working correctly in the latest Edge Canary.

**Comment by mfreed7** [comment]
Good news! Thanks for the update.

**Comment by jrobbins** [comment]
We no longer use HTML imports.
