### ISSUE TITLE
Schedule: Find a Better Way to Show Origin Trials

### ISSUE THREAD

**Issue by scheib** [GoogleChrome/chromium-dashboard#695]
https://www.chromestatus.com/features/schedule shows what features are launching.  Would be good to show the features in Origin Trial as well.  Related:  https://developers.chrome.com/origintrials/#/trials/active.

**Comment by jpmedley** [comment]
+1

**Comment by jpmedley** [comment]
It turns out that we already do. We just don't do it well. 

The image below shows how we do it now. If you hover over this icon, an "Origin Trial" label appears. 

![image](https://user-images.githubusercontent.com/8204171/69260345-914bd780-0b74-11ea-8e4f-121e5a503d37.png)

**Comment by jpmedley** [comment]
I hope it goes without saying that the existence of this ticket demonstrates that the current method of showing origin trials stinks.

**Comment by jpmedley** [comment]
The new [roadmap/](https://chromestatus.com/roadmap) page covers this.
