### ISSUE TITLE
"public signals" field does not provide room for subtlety 

### ISSUE THREAD

**Issue by yoavweiss** [GoogleChrome/chromium-dashboard#703]
When filing in "public signals" there are various cases where none of the current options apply. 
A couple of random examples:
* There's no official "public support" position, but various folks from that vendor thought that this is a good idea.
* We haven't gotten official word from other vendors, but they already pass the tests (can be applicable for small API changes)

We should try to capture such common cases in more ready made options (e.g. "positive signals, but no support yet"). We should also enable an escape hatch (e.g. "other") and allow engineers to write down the current state as a note.

**Comment by jyasskin** [comment]
I think we can close this, now that Firefox and Safari have dedicated positions repositories with clear mappings to our states. https://bit.ly/blink-signals
