### ISSUE TITLE
Chrome dev tools. Can't search tree?

### ISSUE THREAD

**Issue by antoniobeltran** [GoogleChrome/chromium-dashboard#706]
Can any of you right click this to show the menu? I used this to search the tree for code.

Seemed to start happening after the dec 10 release

![image](https://user-images.githubusercontent.com/39303412/70754157-7fd59580-1d04-11ea-81ed-5919ac4d3407.png)

**Comment by jstenback** [comment]
This issue tracker is for the site https://chromestatus.com.

Please file Chrome bugs at https://crbug.com/wizard. Thanks.
