### ISSUE TITLE
Intent to Prototype URL should not be required for Intent to Ship

### ISSUE THREAD

**Issue by foolip** [GoogleChrome/chromium-dashboard#716]
@alvestrand had to work around this with https://dev/null in [Intent to Ship: onclosing event on RTCDataChannel](https://groups.google.com/a/chromium.org/d/msg/blink-dev/bYqDvpPTawc/rG2sOEAOCQAJ).

**Comment by alvestrand** [comment]
This is a feature that's small enough that merging the intent-to-ship into intent-to-prototype was a reasonable thing to do.
In this case, I had ticked the "generate intent to ship" template, which meant that the system was offering to generate the mail I was asked to provide the link to.
