### ISSUE TITLE
Hard to find how to add an entry

### ISSUE THREAD

**Issue by maxlgu** [GoogleChrome/chromium-dashboard#729]
I've spent a while on the page but I haven't found anything that can allow/teach me how to add an entry for a new feature. So, two questions:
1. how can I add an entry?
2. can we move the guide or the button to a more prominent place?

**Comment by maxlgu** [comment]
The "Add new feature" button showed up only after I found the small "Login" at the bottom of the page and login. Can we make the "Add new feature" button always displayed on the dashboard and ask users to login after they click the button?

**Comment by jpmedley** [comment]
We moved log in to the top so that it's easier to find. The number of people who should be able to create an entry will remain limited, hence the need to hide the button behind log in. That part will remain the same. 

cc: @cwilso
