### ISSUE TITLE
Typing in search input is very slow

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#733]
Looks like something has changed in mechanics on how searching works. Typing in the input now updates the URL in realtime.

Would be good to add debouncing to the user typing in the input.

**Comment by jpmedley** [comment]
I've noticed this too. The URL updates faster than the input box. Sometimes 3 or 4 characters will show up in the URL before anything appears in the search box. It's a little disconcerting. @jrobbins

**Comment by sangeeth96** [comment]
Experiencing this as well. 😞 Fix this TODO? 🤔 

https://github.com/GoogleChrome/chromium-dashboard/blob/64ea4973a2872fcc38c8034f2b69fd7334116db4/static/js-src/features-page.js#L28-L29

**Comment by jrobbins** [comment]
This fix went live on Friday.
