### ISSUE TITLE
Weird behaviour of chrome when making multiple requests to the same http 1 endpoint 

### ISSUE THREAD

**Issue by also-png** [GoogleChrome/chromium-dashboard#762]
Im making 20 requests on my frontend to my express server and for some reason the way requests are send depends on the time it takes for server  to respond 
1 - delay 0.5 sec
<img width="978" alt="Screenshot 2020-02-20 at 22 09 15" src="https://user-images.githubusercontent.com/60599337/74974780-8da74580-542e-11ea-9dd4-16f797ea0464.png">
2- delay 4.5 sec
<img width="970" alt="Screenshot 2020-02-20 at 22 11 00" src="https://user-images.githubusercontent.com/60599337/74974793-913acc80-542e-11ea-8c0f-665fed978f45.png">
3 - delay 1.5 sec
<img width="1522" alt="Screenshot 2020-02-20 at 22 05 32" src="https://user-images.githubusercontent.com/60599337/74974800-926bf980-542e-11ea-8cfc-f488a547e2f5.png">
my backend code
<img width="639" alt="Screenshot 2020-02-20 at 22 07 26" src="https://user-images.githubusercontent.com/60599337/74974809-96981700-542e-11ea-9f34-79ad4aba37a5.png">
my frontend call
<img width="529" alt="Screenshot 2020-02-20 at 22 08 15" src="https://user-images.githubusercontent.com/60599337/74974811-9730ad80-542e-11ea-849f-dd6f480d8579.png">
btw i could not reproduce it but sometimes behaviour or the browser is different even when code on back/front is unchanged

**Comment by jstenback** [comment]
Thanks for the detailed bug report. This however is the issue tracker for the site https://chromestatus.com. Please use the issue wizzard at https://chromiumbugs.appspot.com/ to file issues with Chrome the browser.
