### ISSUE TITLE
Feature stack rank skips features between 0.343591% and 0.0006%

### ISSUE THREAD

**Issue by jyasskin** [GoogleChrome/chromium-dashboard#768]
If I scroll down in https://chromestatus.com/metrics/feature/popularity, the following two counters are right next to each other, skipping all the features with an intermediate popularity.

```
CSSTypedOMStylePropertyMap         0.343591%
WebAudioDezipperDelayNodeDelayTime 0.0006%
```

I can imagine reasons to do that, but they should be marked in the UI.

**Comment by jrobbins** [comment]
Sorry to not respond on this issue sooner.

I don't know what the cause could have been at the time, but now I see lots of values in the range between 0.34 and 0.0006.  Also, overall the values look to be spread out pretty evenly and sorted correctly.

![image](https://user-images.githubusercontent.com/17365/168158013-d0be74fb-3dda-4474-8937-558d22f9d9ec.png)

Both CSS and JS stack ranks look good now.
