### ISSUE TITLE
Documentation/Developer resources field not visible in edit mode

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#777]
[This item](https://www.chromestatus.com/features/5737051062272000) has a broken link in the Documentation/Developer resources field. (Note that this field has the former name in the `feature/` view and the latter name in the `features/` view.) When I open the edit view, the field is not visible under either name. 

I tried several different 'Status in Chromium' values to see if one of them triggered its visibility. I could not find one that did.

**Note:** I marked this P0 because the feature with the broken link is shipping in beta in about three weeks.

**Comment by jrobbins** [comment]
Are these links gathered from the fields:
 + Explainer links
 + Safari views, Firefox views, Edge, Web / Framework deverloper views

See https://screenshot.googleplex.com/GCUQbnOisP0

**Comment by jpmedley** [comment]
No. They have their own fields. Part of the confusion is that someone has put an explainer in this field instead of or in addition to the explainer field.

**Comment by jrobbins** [comment]
OK, I will investigate a fix today.

**Comment by jrobbins** [comment]
I think that I see the cause here.
https://github.com/GoogleChrome/chromium-dashboard/blob/master/static/js-src/admin/feature_form.js#L122

I am testing a fix now.

**Comment by jrobbins** [comment]
OK, the doc links form field should be there if you reload the page.
Let me know if you hit any problems.

**Comment by jpmedley** [comment]
It seems to work. Thank you.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*
