### ISSUE TITLE
Windows OS - Horizontal scroll using trackpad

### ISSUE THREAD

**Issue by ckr1989** [GoogleChrome/chromium-dashboard#782]
In Windows settings, trackpad scroll is set to "Natural Scrolling".

In Chrome, only vertical scroll works as per this setting, whereas, the horizontal scroll works in opposite direction.

This is not consistent. It should work in any one particular way. Either both vertical and horizontal do a natural scroll or a regular scroll.

This is only with "Two finger" trackpad scroll. Chrome version: 78.0.3904.87 (64 bit).

I want to raise this as a chromium issue, because electron.js apps also have the above bug.

**Comment by jstenback** [comment]
Thanks for reporting this issue. Unfortunately this issue tracker is for the https://chromestatus.com website, not Chrome the browser. Please file issues with Chrome itself at https://chromiumbugs.appspot.com/?token=0
