### ISSUE TITLE
Fix CSS feature usage dashboard

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/chromium-dashboard#784]
Related issue: https://github.com/HTTPArchive/httparchive.org/issues/194

On the CSS feature popularity pages, the dashboards based on HTTP Archive data are not showing any data. For example https://chromestatus.com/metrics/css/timeline/popularity/516.

This is due to a mismatch in the CSS property names used by Chrome Status and the feature names used by HTTP Archive. For example Chrome Status refers to CSS feature number 516 as `font-display` while HTTP Archive and the dashboard recognize it as `CSSPropertyFontDisplay`.

The pattern of prepending `CSSProperty` and converting hyphenated words to title case seems to work for [~80%](https://github.com/HTTPArchive/httparchive.org/issues/194#issuecomment-597901810) of cases, so I'd like to propose a change to the CSS feature popularity pages where we apply a function like `convertToFeatureName` defined below to any CSS feature when constructing the URL to embed the dashboard:

```js
// Capitalizes the first letter of a word.
function capitalize(word) {
  var letters = word.split('');
  letters[0] = letters[0].toUpperCase();
  return letters.join('');
}

// Converts 'background-image' to 'CSSPropertyBackgroundImage'.
function convertToFeatureName(property) {
  return 'CSSProperty' + property.split('-').map(capitalize).join('');
}
```

Here's the code that embeds the dashboard:

https://github.com/GoogleChrome/chromium-dashboard/blob/8f1f18cfa10fcba70b8df5c4f3b7b180fbb5adfb/static/elements/chromedash-timeline.js#L177-L197

I'm not sure how to detect whether it's a CSS feature or not, but the modified code could look something like this:

```js
let featureName = feature[1];
if (isCSSFeature()) {
  featureName = convertToFeatureName(featureName);
}
```

The corrected `featureName` would be applied to `dsEmbedUrl` and also the `bigqueryEl` which includes the query snippet to find the feature in the BigQuery dataset.

**Comment by jrobbins** [comment]
This is is now live.

**Comment by rviscomi** [comment]
Thanks for fixing this!
