### ISSUE TITLE
chromestatus.com SSL cert renewal automation

### ISSUE THREAD

**Issue by SWBennett06** [GoogleChrome/chromium-dashboard#789]
Looks like the TLS certificate on chromestatus.com expired this morning. This isn't the first time this has happened (#631) , so perhaps consider automating the process?

**Comment by jrobbins** [comment]
This is fixed again for now.
We are looking into automating.

**Comment by jrobbins** [comment]
Actually, I'll keep this issue open for the automation part.

**Comment by jrobbins** [comment]
It sounds like this is done.  Thanks!
