### ISSUE TITLE
Address Chrome 82 in navaigation

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#795]
I'm not sure what the best course of action is. Options
* Remove 82 completely.
* Change the 82 label to say something like "82 (Skipped)" or "82 (Abandoned)"
* Leave 82 but redirect to a notice about it being skipped.

![image](https://user-images.githubusercontent.com/8204171/77554569-7b785700-6e73-11ea-843d-4f875e957cef.png)

**Comment by jpmedley** [comment]
We should probably discuss this. I've put it on tomorrow's agenda.

**Comment by jpmedley** [comment]
Per the Web Status weekly meeting: Chrome 82 will remain in navigation, but will show a brief message that it was skipped and link to the beta release post.

**Comment by jrobbins** [comment]
I noticed that the nav for 82 is gone now.  I did not make a code change for that, I think that it happens as a natural consequence of there being no features targeting 82.  So, I am reluctant to add a special case to add a nav item for it.  Let me know if you feel strongly about still implementing this.
