### ISSUE TITLE
Blink components out of date

### ISSUE THREAD

**Issue by cmumford** [GoogleChrome/chromium-dashboard#800]
The Blink components are not in sync with Monorail. 

Currently there are these components:

```
UI>Browser>WebAppInstalls
UI>Browser>WebAppInstalls(Android)
UI>Browser>WebAppinstalls
UI>Browser>WebAppinstalls(Windows)
```

Note the second pair has a lowercase 'i'. Monorail has this fixed as well as different subcomponents. Requesting these be synchronized with Monorail.

**Comment by cmumford** [comment]
The cause of this CL may be a typo in two Chromium OWNES files. A fix is up at https://crrev.com/c/2139434. Once landed I will check the components list and close if corrected.

**Comment by jrobbins** [comment]
I think your fix worked.  I see the capital "I" for those components now on the live site.  Thanks!
