### ISSUE TITLE
Highlight Text Changes in Update Emails

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#801]
I often review textual changes to Chrome Status entries to ensure clear communication and absence of typos and obvious mistakes. 

It would be nice if the email notifying me of an update could highlight the differences between the old and new versions of text.

![image](https://user-images.githubusercontent.com/8204171/77945492-96810780-7275-11ea-85c3-bc952fca3139.png)

**Comment by jrobbins** [comment]
I think Joe's PR resolved this.  That change was deployed yesterday.

**Comment by jpmedley** [comment]
@jrobbins Ask me about this in person.

**Comment by jpmedley** [comment]
Duplicate of #1303
