### ISSUE TITLE
Comments box is escaping markup

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#806]
Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/8204171/78694200-2ac01f80-78b1-11ea-85cc-aa088f42ccc7.png)
 
Here's what's in the editing view:

![image](https://user-images.githubusercontent.com/8204171/78694260-3dd2ef80-78b1-11ea-9626-9633971d00b6.png)

**Comment by mustaqahmed** [comment]
Thanks for flagging this.  Done clarifying the comment, copied the decisive comment from the bug.
