### ISSUE TITLE
Multiple issues with file downloads

### ISSUE THREAD

**Issue by gitcnd** [GoogleChrome/chromium-dashboard#811]
*. File download toolbar does not show the name of the file (truncates it with a bunch of .... even if there is plenty of space in the bar to show the full name).

*. file download info ^ option does not show the file name either

*. file download info ^ option does not show where the file is coming from (e.g. what website it is downloading from, nor what website triggered the download)

*. browser history tab shows downloaded files as "file://" with no indication of where they came from.

Come on guys - it is malware WWIII out there, you really need to do a LOT better to help us avoid falling into evil traps.

**Comment by jstenback** [comment]
Thanks for reporting this issue. Unfortunately this issue tracker is for the https://chromestatus.com website, not Chrome the browser. Please file issues with Chrome itself at https://chromiumbugs.appspot.com/?token=0
