### ISSUE TITLE
Encountered a picture bomb on Chrome 81

### ISSUE THREAD

**Issue by joseph-cheung** [GoogleChrome/chromium-dashboard#813]
Please open it with chrome browser when the memory is greater than 2G:

http://www.shundehr.com/WebPerson/JobDetail?jid=255062

(Not necessarily reproducible), my computer occupies a maximum of 2.1G of memory, full of single-core.

I think there should be a performance problem when scaling this image: http://www.shundehr.com/Images/EnterpriseLogo/202004141610345532.jpg

This picture is 5.9MB in size, but the size is 23310x12672, opened with irfanview, it takes up 880MB of memory ...

**Comment by jrobbins** [comment]
Thanks for the report, but please report this issue at https://crbug.com/new.
This GitHub project is only for the chromestatus.com website.
