### ISSUE TITLE
Enable creation of features w/o publishing them

### ISSUE THREAD

**Issue by jstenback** [GoogleChrome/chromium-dashboard#815]
I've heard several requests to make it possible to create an issue w/o publishing it so that an feature entry can be created and get reviewed by an engineering team, say. And once there's agreement that the entry is ready to go they can check the published checkbox (or whatever we'd call it) on the entry and move on. I would recommend we treat this as a feature that is intentionally just to keep things somewhat hidden until they're ready rather than trying to actually promise that a feature in this state is actually unfindable or anything like that, given that we really don't make any guarantees about visibility or lack thereof for any of the data behind chromestatus at this stage.

**Comment by jpmedley** [comment]
Not just engineering. I often request changes to the summary, which is the first chance feature owners have to communicate to a broader web developer audience. I also use the summaries, and sometimes the motivation as the basis for the beta release post.
