### ISSUE TITLE
Chrome does not load font referenced from inside shadow element.

### ISSUE THREAD

**Issue by repinvv** [GoogleChrome/chromium-dashboard#824]
Gist URL:  https://gist.github.com/repinvv/b9d98547e0c4b7999829764c02576143

To reproduce the defect:
1)save gist files locally
2)open index.html with chrome
3)look at "network" debug information in developer console

Expected result: Two requests for fonts, icons.woff and pics.woff (files are not actually included in gist)
Actual result: Only icons font is requested, pics font is not requested

**Comment by jstenback** [comment]
Thanks for reporting this issue. Unfortunately this issue tracker is for the https://chromestatus.com website, not Chrome the browser. Please file issues with Chrome itself at https://chromiumbugs.appspot.com/?token=0
