### ISSUE TITLE
Allow editting a feature from its view

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/chromium-dashboard#836]
I'm looking to edit the EventTiming feature entry, so I went to https://www.chromestatus.com/feature/5167290693713920. However, I don't see any way to edit the page from here. Am I missing something? I had to go to https://www.chromestatus.com/features#event%20timing and click on the edit button to edit it.

**Comment by jstenback** [comment]
As long as I'm logged in (bottom of the page), I see an edit button in https://www.chromestatus.com/feature/5167290693713920. Are you saying that's not the case for you?

@jrobbins What do you see on the given links above?

**Comment by jstenback** [comment]
Very odd, not only is the edit button missing for you, but so are the email notification and bug filing buttons. Both of those are conditional on the app knowing about the user, which I don't understand how that can be true given that the site tells you that you are in fact logged in. @jrobbins do you have any ideas on what might be happening here? Nothing around this stuff has changed in months, if not years, IIRC.

**Comment by npm1** [comment]
Ping. I'm trying to update entries, and this is a problem.

**Comment by jrobbins** [comment]
I'll look into this today.

**Comment by jrobbins** [comment]
I looked into the code for this and I tested it locally.  The logic that decides permission to edit checks for both "@chromium.org" and "@google.com".  If I test on my local instance using an account with the same email address shown in the screenshot, I see the editing icon as expected.

But, then I noticed that you are missing all the icons.  The star icon, the file-a-bug icon, and a share icon should show up even if you don't have editing permission.  So, it might be a problem with icons not showing up even though you have permission.

Try a hard reload of the page.   Also, check the browser console for any error messages.

If you still don't see an icon, you can jump directly to the editing page, and I bet that you will have permission to make and save edits.  You might try making a small edit and saving it first just to avoid the risk that you get an error on submission.
https://chromestatus.com/admin/features/edit/5167290693713920

**Comment by npm1** [comment]
Ohh I figured it out, it's caused by an extension! Sorry for the noise, I filed https://github.com/GoogleChrome/web-vitals-extension/issues/72.
