### ISSUE TITLE
Prepare to ship email template does not include implementer signals

### ISSUE THREAD

**Issue by reillyeon** [GoogleChrome/chromium-dashboard#864]
**Describe the bug**
The email generated for a feature in the "Prepare to ship" state does not include the signals from other implementers.

**To Reproduce**
1. Go to https://chromestatus.com/feature/5180688812736512.
2. Click on "edit" icon.
3. Check "Generate "Intent to Prepare to ship" email on next page."
4. Click "Submit" button.
5. See the email template filled in without implementer signals.

**Expected behavior**
The generated email should include implementer signals as shown on the feature page.

**Additional context**
The [nearly-deprecated intent email templates](https://docs.google.com/document/d/1vlTlsQKThwaX0-lj_iZbVTzyqY7LioqERU8DK3u3XjI/edit) still include implementer signals for "Intent to Ship" emails.

**Comment by jpmedley** [comment]
@cwilso Is this a genuine omission or a change in procedure?

**Comment by jstenback** [comment]
This feels like an omission to me. Thanks for reporting this @reillyeon!

**Comment by jrobbins** [comment]
I think this was due to renaming the intent stages.  It was temporarily resolved by PR #881.
And that was deployed.  A better fix is in review now in PR #887, and that is also tracked in issue #880.
