### ISSUE TITLE
Version Number Boxes Need to Appear with "Status in Chromium" Field

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#868]
**Describe the bug**
In the new design, the version number box are in separate subforms. This is fine in most instances. Some status require that version numbers must be entered. 

**To Reproduce**
Edit a feature and open "Prepare to ship".
![image](https://user-images.githubusercontent.com/8204171/85612460-c1c58980-b60d-11ea-9999-7d7999816ad4.png)

**Expected behavior**
The version number boxes need to appear for the following statuses:
* Behind a flag
* Enabled by default
* Deprecated
* Removed
* Origin trial

**Additional context**
Leaving the new interface as is will lead to an increase in status entries being advanced to one of the above status without version numbers being added. This will:
* Provide incomplete information to web developers.
* Require me to write more emails asking developers to fill in this information.

**Comment by jpmedley** [comment]
Here's an illustration from an update that come through recently. Notice that the intent stage has been advanced to "Prepare to ship". DevRel needs to know whether this is in 85 or later, but the form doesn't prompt him to fill that in.

![image](https://user-images.githubusercontent.com/8204171/85743916-4e795180-b6b9-11ea-911c-55e934eb8bf9.png)

**Comment by jpmedley** [comment]
I got this back from the feature owner. 
![image](https://user-images.githubusercontent.com/8204171/85776856-f1d85f80-b6d5-11ea-8559-790e657806ae.png)

**Comment by jpmedley** [comment]
@jrobbins Is there any chance you can prioritize this soon?

**Comment by jrobbins** [comment]
I'll look into it today.

**Comment by jrobbins** [comment]
This is being addressed in PR #1011.

**Comment by jrobbins** [comment]
This was deployed.

**Comment by jpmedley** [comment]
Yeah!
