### ISSUE TITLE
Visually align submit button to the form controls

### ISSUE THREAD

**Issue by hwikyounglee** [GoogleChrome/chromium-dashboard#872]
**Describe the bug**
Just a button alignment suggestion

**To Reproduce**
https://chromestatus.com/guide/new  with New UI

**Expected behavior**
![image](https://user-images.githubusercontent.com/7561395/85776039-2dbef500-b6d5-11ea-9e30-970b1e988001.png)

**Additional context**
It just a visual preference, so if you disagree, no need to change.

**Comment by hwikyounglee** [comment]
oops -- sorry for not using the bug template for "Process and Guide UX Feedback"!

**Comment by jpmedley** [comment]
Closed by #883
