### ISSUE TITLE
Add focus indicators on form controls

### ISSUE THREAD

**Issue by hwikyounglee** [GoogleChrome/chromium-dashboard#873]
**Guide UX Feedback**

https://chromestatus.com/guide/new
Use 'Tab' key to navigate the controls, and observe the focus indicator

Currently only the <select> controls show the focus indicator. 
Recommending we add focus indicators for other controls to help form-filling using keyboard. 

Thanks for looking into this!

**Comment by jrobbins** [comment]
To clarify, the checkbox and radio buttons on that form are missing the indication of focus.

After investigating, I found that the normal browser focus indication had been set to "none" throughout the site.

**Comment by jpmedley** [comment]
@jrobbins I was tempted to close this. We should probably wait for deployment and verification when closing bugs.
