### ISSUE TITLE
DevTools > Elements > search no longer highlighting for first element found

### ISSUE THREAD

**Issue by terts** [GoogleChrome/chromium-dashboard#886]
If you search for an element in the Inspector where only one exists, in version 83 it highlighted in yellow, but in version 84 it no longer does that.
![image](https://user-images.githubusercontent.com/2946153/87809990-48930e00-c82a-11ea-9ab4-57a58f75bc03.png)

But if you search for one that has multiple, it does still highlight but only elements after the first one.
![image](https://user-images.githubusercontent.com/2946153/87810249-afb0c280-c82a-11ea-9d94-4132ad5abc97.png)
![image](https://user-images.githubusercontent.com/2946153/87810294-c1926580-c82a-11ea-81bb-f1ea3d892960.png)

And to be clear, even if you use the arrows on multiple results, when you are on the last result and hit the down arrow to go to the first result, it doesn't move you to that element's location in the DOM.  In the above pictures, the only reason it has the grey highlighting is because I had just right-clicked and chosen Inspect.  See the following two images:
![image](https://user-images.githubusercontent.com/2946153/87812760-ade8fe00-c82e-11ea-87ed-68407cdccf24.png)
![image](https://user-images.githubusercontent.com/2946153/87812792-bd684700-c82e-11ea-97eb-5d8e8573ab80.png)

This happens on all platforms.

**Comment by terts** [comment]
also logged the bug here https://bugs.chromium.org/p/chromium/issues/detail?id=1106822 as I really wasn't sure if it should be logged there or here.

**Comment by jstenback** [comment]
https://bugs.chromium.org/ is the right place for an issue like this. This issue tracker only tracks issues with the website chromestatus.com. Thanks.
