### ISSUE TITLE
Backfill intent_stage for existing issue

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#933]
The Guide UX does not make a good impression when used to view existing features that have made progress through the launch process and yet still have intent stage None.   We should set the intent_stage field for all existing features.

For features that have shipped, I think that we can unilaterally set the intent_stage to INTENT_SHIPPED.  We might also be able to make some heuristic rules for other states as well.  And, we might need some human review to cover some more features and/or double check.

**Comment by carolrivero** [comment]
pending user feedback if this request is valid.
