### ISSUE TITLE
Unable to leave "Doc Link(s)", "Intent to Prototype" link, etc fields empty when editing old chromestatus entries

### ISSUE THREAD

**Issue by dway123** [GoogleChrome/chromium-dashboard#938]
**Describe the bug**
When editing old chromestatus entries to add some information, like shipped milestones, we're unable to leave some fields empty. This means folks may simply not add this new information, since they may not have all the other information readily available (or this information may not exist at all).

**To Reproduce**
1. Go to https://www.chromestatus.com/admin/features/edit/5767075295395840 or some other status entry you own, that doesn't have all the new fields filled in
2. Click on edit
3. Click submit
4. See error.
![image](https://user-images.githubusercontent.com/10102114/88849110-42901c00-d19e-11ea-81f7-5313c6b121c5.png)

**Expected behavior**
For existing entries being edited, folks shouldn't have to add links that may not be available, and these links should be optional. Also, for new entries, some of these links should be optional as well. For example, I've heard recommendations to file chromestatus entries for small changes that might not need blink-dev/TAG review, just as a heads up to developers following chromestatus. After recent ChromeStatus updates, these entries are more difficult to make, due to blocking error messages.

**Comment by jpmedley** [comment]
Thank you for filling this out. We are working that. In the meantime, the firm accepts a space as an entered value.
