### ISSUE TITLE
textarea new line not visible at the top after scrollbar appears

### ISSUE THREAD

**Issue by pulkitgulati** [GoogleChrome/chromium-dashboard#950]
**Describe the bug**
We received the issue for one of our Applications in the textarea where you keep entering new lines until scrollbar is active. Use the keyboard Arrow keys to go back to the top position and press enter. You'll think that nothing has happened, as new line is added but not in View until you scroll up with mouse or Arrow key.

Chrome Version 81.0.4044.113 (Official Build) (64-bit)

**To Reproduce**
1. Go to https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea2
2. Enter text with new lines until scroll bar appears.
3. Use up Arrow key to move back to top position and press enter, you'll observe nothing happens but new line added is not in view. You can see it if you scroll up.
4. screen-shot:
![image](https://user-images.githubusercontent.com/5213029/89392019-95ca1780-d726-11ea-97e3-47eaa379a0ec.png)

![image](https://user-images.githubusercontent.com/5213029/89392418-2274d580-d727-11ea-9607-22048186cc35.png)

**Expected behavior**
New line added should be visible.

**Additional context**
It is not reproducible if you scroll up with mouse and click at the top position. The new line added remains in view.

**Comment by jpmedley** [comment]
Paul,

Thank you opening this. Unfortunately, this site is for bugs related to [Chrome Status](https://www.chromestatus.com/), not for bugs related to Chrome. Can you please open a bug a https://bugs.chromium.org/p/chromium/issues/list.

Thanks
