### ISSUE TITLE
Login status should be more prominent

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/chromium-dashboard#955]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to more easily tell if/when I'm logged in. In addition, when I login I think I'm sometimes having to refresh the page so that the login-only content (like adding a new feature) shows up.

**Describe the solution you'd like**
The login button should be 1. larger 2. at the top of the page instead of the bottom 3. in a more contrasting color/background so that it's more easily detectable.

**Comment by jrobbins** [comment]
Yep, this all matches up with work I am doing on a new page layout and color scheme.

**Comment by jrobbins** [comment]
The Login status is now in the far upper right.

**Comment by jstenback** [comment]
Sweet, been wanting to see this happen for a while! 👍
