### ISSUE TITLE
New UI pre-populated wrong "Contact emails"

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/chromium-dashboard#956]
**Describe the bug**
I clicked to add new feature, clicked to try new UI. I see that the "Contact emails" part is pre-populated, but it shows "kbr@chromium.org". That seems like a bug? It should either be blank or be pre-populated for me with "npm@chromium.org".

**Comment by jpmedley** [comment]
I'm unable to duplicate this. Can you try refreshing the cache and see if it still happens?

![image](https://user-images.githubusercontent.com/8204171/89682746-1b2b0480-d8ac-11ea-9e93-a6ad0db3b124.png)

**Comment by npm1** [comment]
I tried this flow again and didn't see the Contact emails populated at all, weird.

I still have to reload the page after logging in in order to see the "add feature" button. Do I file a separate bug for that?

**Comment by jpmedley** [comment]
Please.
