### ISSUE TITLE
Login requires refresh to see 'Add feature' button

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/chromium-dashboard#957]
**Describe the bug**
After logging in, I should see the buttons like adding a new feature. Currently I don't and require a refresh of the page.

**To Reproduce**
1. Go to chromestatus.com without being logged in.
2. Login and notice that the button to add feature is not present.
3. Refresh, and notice the button appearing.

**Comment by jrobbins** [comment]
Are you still seeing this?

I believe this was due to a bug that we had in our use of service worker, however we have completely removed service worker.   I am no longer able to reproduce this.

**Comment by npm1** [comment]
Tried just now, works fine! Closing
