### ISSUE TITLE
Application stuck on splash screen

### ISSUE THREAD

**Issue by araafat3** [GoogleChrome/chromium-dashboard#962]
Bug Report
Problem
What is expected to happen?
go to screen after splash screen

What does actually happen?
Stuck in splash screen

Information
run app on tecno C8 then app stuck on splash screen
This problem is coming randomly not all the timee

Command or Code
Stacktrace:

08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors

Environment, Platform, Device
Android

Version information
Mobile: tecno C8
Android Version: 5.0.2
Cordova Version:8.0.0
Android platform version:8.1.0
Node version:10.16.3

**Comment by jrobbins** [comment]
This issue tracker is only for the chromestatus.com website.   You might want to report your issue to the owners of the app that you had the problem with.
