### ISSUE TITLE
Lookalike feature in release 84 kills website access

### ISSUE THREAD

**Issue by mhgschmidt** [GoogleChrome/chromium-dashboard#967]
Hi,

we are running 2 domains:
- exabyte.systems
- exabyte-systems.com (this one does a rewrite to exabyte.systems)

Since a few days (since release 84 ?) we are getting the message "did you mean ... ?" in case somebody accesses our domain "exabyte-systems.com".

**Steps to reproduce the behavior:**
1. Go to 'https://www.exabyte-systems.com/test.html'

2. See error.  (screenshot attached)
![lookalike-exabyte](https://user-images.githubusercontent.com/68081688/90310490-07a61c00-def2-11ea-99a8-03fae81e84e5.png)

3. Test with "wget":
wget https://www.exabyte-systems.com/test.html
--2020-08-15 12:18:05--  https://www.exabyte-systems.com/test.html
Resolving www.exabyte-systems.com... 88.99.138.194
Connecting to www.exabyte-systems.com|88.99.138.194|:443... connected.
HTTP request sent, awaiting response... 200 OK

**Expected behavior**
Browser *should* show: "Hello World ! [ exabyte-systems.com ]"
I expect chrome to NOT show this message because 'exabyte-systems.com' is a valid domain. We own this domain.

**Additional context**
This worked for years without problems (also with Chrome). Since a few days (Release 84). Chrome killed access to our second domain!

best regards,
Michael

**Comment by jstenback** [comment]
Thanks for reporting this issue. Unfortunately this issue tracker is for the https://chromestatus.com website, not Chrome the browser. Please file issues with Chrome itself at https://crbug.com/new
