### ISSUE TITLE
Summary and other text fields should show variable-width fonts during editing.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#969]
**Describe the bug**
The use of a fixed-width font in free-form text fields leads some users to think they have press enter every time their cursor approaches the right edge of the input box. I've already edited two summaries to remove the errant crlf characters.

**Comment by jrobbins** [comment]
This might have been fixed by other changes.  I don't see fixed-width fonts being used now.

Is there any field where you still see fixed-width fonts?

**Comment by jpmedley** [comment]
I'm still seeing this:

![image](https://user-images.githubusercontent.com/8204171/93783425-858bd000-fbe0-11ea-82ba-4596a591062d.png)

**Comment by jrobbins** [comment]
I must have been looking in the wrong place when I wrote that.
I see the fixed-width fonts during editing now.
I will make this change now.
