### ISSUE TITLE
Comments field is incorrectly escaped

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#999]
**Describe the bug**
In this feature 
https://chromestatus.com/features/5078049450098688
the comments include a link that is shown with visible markup.

The user only typed the bare URL.  Our UI component converted it to an <a> tag, but then rendered that as plain text.

**Expected behavior**
If we urlize text, we should keep track of the fact that it is markup and not let it be escaped afterwards.

The defect seems to be in chromedash-feature.js which calls urlize() but then renders the result as a regular string rather than as an html-string.  Probably the function _getCommentHtml() should construct and return a lit-html object.

**Comment by jpmedley** [comment]
It seems like this should apply to any free-form entry field, summary and motivation specifically.
